### PR TITLE
feat(GlobalHeader): optionally render new items under pro pricing

### PR DESCRIPTION
**Pull request by xendke**
### Overview

Optionally render new items under pricing dropdown in the GlobalHeader

header on
header off

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [GRW-32](https://codecademy.atlassian.net/browse/GRW-32?atlOrigin=eyJpIjoiMTE5OGJmMmI5MmY4NGZkYTk4ZGFlZjU3OWFjYWU1Y2QiLCJwIjoiaiJ9)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.12-alpha.727800.0<br/>@codecademy/gamut-labs@28.1.0-alpha.727800.0<br/>@codecademy/styleguide@50.1.9-alpha.727800.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618ad691a9a0871181fb87ec--gamut-preview.netlify.app>https://618ad691a9a0871181fb87ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618ad691a9a0871181fb87ec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.12-alpha.d27cb6.0<br/>@codecademy/gamut-labs@28.1.0-alpha.d27cb6.0<br/>@codecademy/styleguide@50.1.9-alpha.d27cb6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618adebca9a08720b1fb84e5--gamut-preview.netlify.app>https://618adebca9a08720b1fb84e5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618adebca9a08720b1fb84e5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.12-alpha.b911fe.0<br/>@codecademy/gamut-labs@28.1.0-alpha.b911fe.0<br/>@codecademy/styleguide@50.1.9-alpha.b911fe.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619afa4f54e7260cffa6884d--gamut-preview.netlify.app>https://619afa4f54e7260cffa6884d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619afa4f54e7260cffa6884d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.12-alpha.e51b06.0<br/>@codecademy/gamut-labs@28.1.0-alpha.e51b06.0<br/>@codecademy/styleguide@50.1.9-alpha.e51b06.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619bb086f9db38241ffa5358--gamut-preview.netlify.app>https://619bb086f9db38241ffa5358--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619bb086f9db38241ffa5358>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.12-alpha.468a38.0<br/>@codecademy/gamut-labs@28.1.0-alpha.468a38.0<br/>@codecademy/styleguide@50.1.9-alpha.468a38.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619bb34abfdc6b2600a71922--gamut-preview.netlify.app>https://619bb34abfdc6b2600a71922--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619bb34abfdc6b2600a71922>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.9d2ecf.0<br/>@codecademy/gamut-labs@28.1.0-alpha.9d2ecf.0<br/>@codecademy/styleguide@50.2.7-alpha.9d2ecf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619bc91a30bbe840647efc8a--gamut-preview.netlify.app>https://619bc91a30bbe840647efc8a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619bc91a30bbe840647efc8a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.20-alpha.61a8c1.0<br/>@codecademy/gamut-labs@28.1.0-alpha.61a8c1.0<br/>@codecademy/styleguide@50.3.2-alpha.61a8c1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619cf7b97fd04b0ab5e7e1a3--gamut-preview.netlify.app>https://619cf7b97fd04b0ab5e7e1a3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619cf7b97fd04b0ab5e7e1a3>Deploy Logs</a></p>

**Review by sylvanasantos — APPROVED** [review]
Makes sense to me!

**Review by ahmed-abdallah — APPROVED** [review]
:shipit: Would eventually be nice to have this in all header dropdowns but a solid initial pattern!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619d14f67fd04b2a71e7e112--gamut-preview.netlify.app>https://619d14f67fd04b2a71e7e112--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619d14f67fd04b2a71e7e112>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.00cc11.0<br/>@codecademy/gamut-labs@28.5.0-alpha.00cc11.0<br/>@codecademy/styleguide@52.2.3-alpha.00cc11.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61ba28b52e2fdd5490598e19--gamut-preview.netlify.app>https://61ba28b52e2fdd5490598e19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61ba28b52e2fdd5490598e19>Deploy Logs</a></p>

**Pull request closed without merging**
