### PR TITLE
refactor(GlobalHeader): pricing dropdown updates

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

[DISC-643](https://codecademy.atlassian.net/browse/DISC-643): 
Change "Pro pricing" in the top navigation to be "Pricing". This includes the dropdown and the link that also says "Pro Pricing" for users in India. 

[DISC-644](https://codecademy.atlassian.net/browse/DISC-644): 
Add "For Teams" to the pricing dropdown. Acceptance criteria:
- Link should be placed last, after “individuals” and “students”
- Section should link to: https://www.codecademy.com/business#section-pricing-table
- Tracking = `topnav_pricing_business`
- Change existing "For Business" next to "Pricing" to be "Business Solutions" (in footer as well).

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DISC-463 and DISC-644
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/30975)  | [Monolith Env](https://pr-30975-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/portal-app/pull/2061)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2061)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.132-alpha.24f246.0<br/>@codecademy/gamut-labs@31.14.2-alpha.24f246.0<br/>@codecademy/styleguide@57.6.2-alpha.24f246.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6297af4639d98a00b38332f2--gamut-preview.netlify.app>https://6297af4639d98a00b38332f2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6297af4639d98a00b38332f2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6297c7f926aa3402c6c656e6--gamut-preview.netlify.app>https://6297c7f926aa3402c6c656e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6297c7f926aa3402c6c656e6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.133-alpha.ce28ed.0<br/>@codecademy/gamut-labs@31.15.1-alpha.ce28ed.0<br/>@codecademy/styleguide@57.7.1-alpha.ce28ed.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6297de55b143fd277ce663eb--gamut-preview.netlify.app>https://6297de55b143fd277ce663eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6297de55b143fd277ce663eb>Deploy Logs</a></p>

**Review by j10sanders — APPROVED** [review]
lgtm

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
