### PR TITLE
chore: bumped our ESLint config to 7.0.2

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## Overview
Brings in https://github.com/Codecademy/client-modules/pull/10 to resolve our `eslint-plugin-react-hooks`.

### PR Checklist
- [x] Related to JIRA ticket: WEB-1713
- [x] I have run this code to verify it works
- ~[ ] This PR includes [client](https://www.notion.so/codecademy/Frontend-Unit-Tests-1cbf4e078a6647559b4583dfb6d3cb18), [server](https://www.notion.so/codecademy/Ruby-Unit-Tests-6f0353926a034df4909142e4fe686bf7), and/or [end to end](https://www.notion.so/codecademy/Frontend-Acceptance-Tests-cb1125a99a6c4d478a85979aa46cad03) tests for the code change~

### Testing Instructions
See that CI passes!

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a80a3297200e165a9fe5d0--gamut-preview.netlify.app>https://61a80a3297200e165a9fe5d0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a80a3297200e165a9fe5d0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61af7e6924becbf02a966da8--gamut-preview.netlify.app>https://61af7e6924becbf02a966da8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61af7e6924becbf02a966da8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0eafb2bf45d5b7ce1571f--gamut-preview.netlify.app>https://61c0eafb2bf45d5b7ce1571f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0eafb2bf45d5b7ce1571f>Deploy Logs</a></p>

**Review by MattSchiller — APPROVED** [review]
Screen Shot 2021-12-20 at 4 13 12 PM

**Comment by JoshuaKGoldberg** [comment]
rip

**Pull request closed without merging**
