### PR TITLE
chore(NotificationList): move to NotificationsList to Brand

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Moves the NotificationList and its related types to Brand

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Head to the monolith or monorepo PRs and check out the notifcationlists ✨ 

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/37164)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Monorepo       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/5112)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.2-alpha.17805f.0<br/>@codecademy/gamut-kit@0.6.383-alpha.17805f.0<br/>@codecademy/styleguide@66.12.1-alpha.17805f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.3-alpha.23faea.0<br/>@codecademy/gamut-kit@0.6.384-alpha.23faea.0<br/>@codecademy/styleguide@66.12.2-alpha.23faea.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65dced35e814421e49a4affc--gamut-preview.netlify.app>https://65dced35e814421e49a4affc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65dced35e814421e49a4affc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.3-alpha.7ac4d7.0<br/>@codecademy/gamut-kit@0.6.384-alpha.7ac4d7.0<br/>@codecademy/styleguide@66.12.2-alpha.7ac4d7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65de1cdc3d60681451ba4822--gamut-preview.netlify.app>https://65de1cdc3d60681451ba4822--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65de1cdc3d60681451ba4822>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
lgtm. seems like there is a formatting issue on an unrelated button file though

**Review by aresnik11 — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.3-alpha.b23f17.0<br/>@codecademy/gamut-icons@9.18.1-alpha.b23f17.0<br/>@codecademy/gamut-illustrations@0.42.1-alpha.b23f17.0<br/>@codecademy/gamut-kit@0.6.384-alpha.b23f17.0<br/>@codecademy/gamut-patterns@0.9.12-alpha.b23f17.0<br/>@codecademy/gamut-styles@16.2.1-alpha.b23f17.0<br/>@codecademy/gamut-tests@5.0.10-alpha.b23f17.0<br/>@codecademy/styleguide@66.12.2-alpha.b23f17.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65df809d4234454b3c47e49a--gamut-preview.netlify.app>https://65df809d4234454b3c47e49a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65df809d4234454b3c47e49a>Deploy Logs</a></p>

**Review by BandanaKM — APPROVED** [review]
looks great, cass 💯

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65e09e34652c8c0b50d21550--gamut-preview.netlify.app>https://65e09e34652c8c0b50d21550--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65e09e34652c8c0b50d21550>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.3-alpha.2b039e.0<br/>@codecademy/gamut-kit@0.6.384-alpha.2b039e.0<br/>@codecademy/styleguide@66.12.2-alpha.2b039e.0<br/></pre>

**Pull request merged**
