### PR TITLE
fix(SocialMediaSharing): fix partially undefined id

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Only prepends `sectionId-` to the svg title id if there is a `sectionId`. Previously, when a section id was not passed the title ids would look like `undefined-facebook`. Also adds in `displayName` prop in the `SOCIAL_SHARING_PLATFORMS` array of objects to be used for the dropdown variant in portal.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2235]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

See testing instructions in monolith/portal PRs

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33918)  | [Monolith Env](https://pr-33918-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/860)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-860)   |

[WEB-2235]: https://codecademy.atlassian.net/browse/WEB-2235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.253-alpha.124bee.0<br/>@codecademy/gamut-labs@33.11.3-alpha.124bee.0<br/>@codecademy/styleguide@62.6.10-alpha.124bee.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6397940bc9328446f9c34408--gamut-preview.netlify.app>https://6397940bc9328446f9c34408--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6397940bc9328446f9c34408>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.254-alpha.a6e939.0<br/>@codecademy/gamut-labs@34.0.1-alpha.a6e939.0<br/>@codecademy/styleguide@62.6.11-alpha.a6e939.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398d1e4ba39bc083c14bf9c--gamut-preview.netlify.app>https://6398d1e4ba39bc083c14bf9c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398d1e4ba39bc083c14bf9c>Deploy Logs</a></p>

**Review by BandanaKM — APPROVED** [review]
nice!

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.261-alpha.ea523b.0<br/>@codecademy/gamut-labs@34.0.8-alpha.ea523b.0<br/>@codecademy/styleguide@62.8.2-alpha.ea523b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63b87d4717cef838b16615d0--gamut-preview.netlify.app>https://63b87d4717cef838b16615d0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63b87d4717cef838b16615d0>Deploy Logs</a></p>

**Pull request merged**
