### PR TITLE
fix: Resolve sass division warnings

### PR DESCRIPTION
**Pull request by jrood**
### Overview

Resolve warnings by explicitly using `calc()` or `math.div()` where `/` was used for division.

Since sass uses `/` for division in some contexts and as a separator in other contexts, it now gives a warning when a `/` is used for division without `calc()` or `math.div()`.

see also: https://sass-lang.com/documentation/breaking-changes/slash-div

### PR Checklist

- [ ] ~Related to designs:~
- [ ] ~Related to JIRA ticket: [ABC-123]~
- [x] I have run this code to verify it works
- [ ] ~This PR includes unit tests for the code change~
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

`yarn start` and verify that sass division warnings are gone

#### PR Links and Envs

| Repository   | PR Link                                                  |
| :----------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35330)  |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1574)  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@8.1.2-alpha.9aca67.0<br/>@codecademy/gamut-illustrations@0.34.1-alpha.9aca67.0<br/>@codecademy/gamut-kit@0.6.294-alpha.9aca67.0<br/>@codecademy/gamut-labs@35.8.1-alpha.9aca67.0<br/>@codecademy/gamut-patterns@0.9.3-alpha.9aca67.0<br/>@codecademy/gamut-styles@15.1.1-alpha.9aca67.0<br/>@codecademy/gamut-tests@5.0.2-alpha.9aca67.0<br/>@codecademy/gamut@52.2.1-alpha.9aca67.0<br/>@codecademy/markdown-overrides@0.10.2-alpha.9aca67.0<br/>@codecademy/monaco@0.7.13-alpha.9aca67.0<br/>@codecademy/styleguide@63.7.1-alpha.9aca67.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64138172960d6809e532ad72--gamut-preview.netlify.app>https://64138172960d6809e532ad72--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64138172960d6809e532ad72>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.0.1-alpha.f972f5.0<br/>@codecademy/gamut-illustrations@0.35.1-alpha.f972f5.0<br/>@codecademy/gamut-kit@0.6.304-alpha.f972f5.0<br/>@codecademy/gamut-labs@35.11.2-alpha.f972f5.0<br/>@codecademy/gamut-patterns@0.9.4-alpha.f972f5.0<br/>@codecademy/gamut-styles@16.0.1-alpha.f972f5.0<br/>@codecademy/gamut-tests@5.0.3-alpha.f972f5.0<br/>@codecademy/gamut@53.0.3-alpha.f972f5.0<br/>@codecademy/markdown-overrides@0.10.3-alpha.f972f5.0<br/>@codecademy/monaco@0.7.17-alpha.f972f5.0<br/>@codecademy/styleguide@64.2.1-alpha.f972f5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642f011c8c322917264e39b9--gamut-preview.netlify.app>https://642f011c8c322917264e39b9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642f011c8c322917264e39b9>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
Lgtm! The fact that sass kinda overloads `calc` feels weird... but if it always returns the right thing I can't really complain :)

**Pull request merged**
