### PR TITLE
feat(DropdownList): Allow for dropdown item to open in new tab

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Add optional target prop to DropdownList to allow a dropdown list item link to open in a new tab.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-2770](https://codecademy.atlassian.net/browse/EGG-2770)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

We will be using this new `target` prop in portal-app right away, but not the monolith. Please follow the testing instructions in the portal-app PR using this behavior, and check the monolith PR to ensure tests are passing.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32522)  | [Monolith Env](https://pr-32522-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2562)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2562)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6321f037ffc1c20e331e2f8c--gamut-preview.netlify.app>https://6321f037ffc1c20e331e2f8c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6321f037ffc1c20e331e2f8c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6321f60f6f7e671540e043da--gamut-preview.netlify.app>https://6321f60f6f7e671540e043da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6321f60f6f7e671540e043da>Deploy Logs</a></p>

**Review by sooinc — APPROVED** [review]
LGTM!

**Review by saghdaey — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.203-alpha.a60999.0<br/>@codecademy/gamut-labs@33.4.1-alpha.a60999.0<br/>@codecademy/styleguide@61.5.10-alpha.a60999.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6323304ff5f3e04ba3ea9ce0--gamut-preview.netlify.app>https://6323304ff5f3e04ba3ea9ce0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6323304ff5f3e04ba3ea9ce0>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
