### PR TITLE
staging font test

### PR DESCRIPTION
**Pull request by jrood**
### Overview

This is not meant to be merged. It is only to generate a preview version so that we can test a cors policy in staging.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.1-alpha.f8c838.0<br/>@codecademy/gamut-icons@9.30.2-alpha.f8c838.0<br/>@codecademy/gamut-illustrations@0.47.2-alpha.f8c838.0<br/>@codecademy/gamut-kit@0.6.440-alpha.f8c838.0<br/>@codecademy/gamut-patterns@0.9.15-alpha.f8c838.0<br/>@codecademy/gamut-styles@17.0.1-alpha.f8c838.0<br/>@codecademy/gamut-tests@5.1.2-alpha.f8c838.0<br/>@codecademy/styleguide@68.0.1-alpha.f8c838.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66d758c5d6f7df9dcc3d8bc4--gamut-preview.netlify.app>https://66d758c5d6f7df9dcc3d8bc4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66d758c5d6f7df9dcc3d8bc4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.1-alpha.737099.0<br/>@codecademy/gamut-icons@9.30.2-alpha.737099.0<br/>@codecademy/gamut-illustrations@0.47.2-alpha.737099.0<br/>@codecademy/gamut-kit@0.6.440-alpha.737099.0<br/>@codecademy/gamut-patterns@0.9.15-alpha.737099.0<br/>@codecademy/gamut-styles@17.0.1-alpha.737099.0<br/>@codecademy/gamut-tests@5.1.2-alpha.737099.0<br/>@codecademy/styleguide@68.0.1-alpha.737099.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66d76ec9064dadb97bd733de--gamut-preview.netlify.app>https://66d76ec9064dadb97bd733de--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66d76ec9064dadb97bd733de>Deploy Logs</a></p>

**Comment by jrood** [comment]
closing since we have completed the s3 cors change that we were testing here

**Pull request closed without merging**
