### PR TITLE
fix(ScoreSummary): Use List role for subjects in ScoreSummary

### PR DESCRIPTION
**Pull request by mstykmshy**
### Overview

- Refactor ScoreSummary to add a list role to subject scores

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-3032]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Test in the ScoreSummary page on storybook, and/or in the PR environments in the monolith and portal. In the monolith, you can find the ScoreSummary component on the completion screen after finishing a cumulative assessment ([example assessment](https://pr-34399-monolith.dev-eks.codecademy.com/cumulative-assessment/journeys/full-stack-engineer/paths/fscj-22-building-interactive-websites/parts/1) - as an admin you can skip to the end of the assessment by using the "Jump to last question" option in the settings menu in the header), and in portal you can find it in the [career journey curriculum page](https://tengu.codecademy.com/career-journey/full-stack-engineer?PR_ENV=portal-app-pr-1106), in the expanded exam section below a path for any completed exam.

Navigate through the ScoreSummary component using VoiceOver and ensure that the subjects are announced as a list, including both tested and untested subjects.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34399)  | [Monolith Env](https://pr-34399-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1106)  | [Portal Env](https://pr-34399-monolith.dev-eks.codecademy.com/)   |

[EGG-3032]: https://codecademy.atlassian.net/browse/EGG-3032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.265-alpha.3f08a7.0<br/>@codecademy/gamut-labs@34.0.12-alpha.3f08a7.0<br/>@codecademy/styleguide@62.8.6-alpha.3f08a7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63c7f625c384652ddf9d0151--gamut-preview.netlify.app>https://63c7f625c384652ddf9d0151--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63c7f625c384652ddf9d0151>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63ceb78148d4a05e4e5a0d3c--gamut-preview.netlify.app>https://63ceb78148d4a05e4e5a0d3c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63ceb78148d4a05e4e5a0d3c>Deploy Logs</a></p>

**Comment by dreamwasp** [comment]
can you add this alpha package to portal + the monolith so we can test it out there?

also happy to review this but jsyk since this is a `gamut-labs` change it doesn't require a web-plat engineer to review (just any review!)

**Comment by mstykmshy** [comment]
> can you add this alpha package to portal + the monolith so we can test it out there?
> 
> also happy to review this but jsyk since this is a `gamut-labs` change it doesn't require a web-plat engineer to review (just any review!)

Added! And that's very good to know about gamut labs ty :)

**Review by dreamwasp — APPROVED** [review]
lgtm + VO sounds perfect ✨

**Comment by mstykmshy** [comment]
> Nice! Any reason not to use `<ul>` + `<li>` elements instead?

That was the first approach I tried, but refactoring without messing up the styling ended up being more complicated than expected. Definitely could be done and is probably a better solution overall but just a little higher lift :)

**Pull request merged**
