### PR TITLE
fix: Markdown Updates

### PR DESCRIPTION
**Pull request by jakemhiller**
This fixes a couple issues related to markdown anchors. 

Anchors with in-page links referencing header ids automatically get the `target="_blank"` attribute, which breaks their ability to link to headings.

The `headerIds` prop was added a while ago to insert generated ids on headings. This works, but teams have not utilized this in cases where we need it like articles. Making it the default should fix that, and we can disable it if we end up with id conflicts in cases where we don't need it. To get a conflict, we'd need two headings with the exact same text on the same page, so it should be pretty rare.

This also includes these changes:

* Prevent opening a new tab on in-page links [WEB-1922](https://codecademy.atlassian.net/browse/WEB-1922)
* Makes the `target` prop overridable on `<a>` tags
* Enable header id generation by default [CET-617](https://codecademy.atlassian.net/browse/CET-617)
* Remove `whitespace: no-wrap` from tables [WEB-1923](https://codecademy.atlassian.net/browse/WEB-1923)

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.70-alpha.e468b4.0<br/>@codecademy/gamut-labs@30.0.2-alpha.e468b4.0<br/>@codecademy/gamut@45.0.1-alpha.e468b4.0<br/>@codecademy/monaco@0.6.19-alpha.e468b4.0<br/>@codecademy/styleguide@55.0.2-alpha.e468b4.0<br/></pre>

**Review by dreamwasp — COMMENTED** [review]
can you add a monolith PR with the alpha? looks ✨  but wanna check there 🙏

**Comment by jakemhiller** [comment]
@dreamwasp soon 👀 https://github.com/codecademy-engineering/Codecademy/pull/29843

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.75-alpha.d7cd33.0<br/>@codecademy/gamut-labs@30.2.1-alpha.d7cd33.0<br/>@codecademy/gamut@45.1.0-alpha.d7cd33.0<br/>@codecademy/monaco@0.6.21-alpha.d7cd33.0<br/>@codecademy/styleguide@55.1.1-alpha.d7cd33.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622a0accf6f3003fa9f37e2c--gamut-preview.netlify.app>https://622a0accf6f3003fa9f37e2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622a0accf6f3003fa9f37e2c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.76-alpha.032830.0<br/>@codecademy/gamut-labs@30.2.2-alpha.032830.0<br/>@codecademy/gamut@45.1.1-alpha.032830.0<br/>@codecademy/monaco@0.6.22-alpha.032830.0<br/>@codecademy/styleguide@55.1.2-alpha.032830.0<br/></pre>

**Pull request merged**
