### PR TITLE
feat(MobilePhone): add mobile phone illustration~

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Illustration for LX team, code from pairing w/ @irenerobb72 ✨ 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6239ef8827c6df2361f152bd--gamut-preview.netlify.app>https://6239ef8827c6df2361f152bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6239ef8827c6df2361f152bd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.24.1-alpha.74b24f.0<br/>@codecademy/gamut-kit@0.6.86-alpha.74b24f.0<br/>@codecademy/gamut-labs@30.5.1-alpha.74b24f.0<br/>@codecademy/gamut@45.3.1-alpha.74b24f.0<br/>@codecademy/monaco@0.6.28-alpha.74b24f.0<br/>@codecademy/styleguide@55.4.1-alpha.74b24f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623b548f8a1f5300ac3dd219--gamut-preview.netlify.app>https://623b548f8a1f5300ac3dd219--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623b548f8a1f5300ac3dd219>Deploy Logs</a></p>

**Review by irenerobb72 — APPROVED** [review]
🎈

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.24.1-alpha.4a473c.0<br/>@codecademy/gamut-kit@0.6.89-alpha.4a473c.0<br/>@codecademy/gamut-labs@31.0.1-alpha.4a473c.0<br/>@codecademy/gamut@46.0.1-alpha.4a473c.0<br/>@codecademy/monaco@0.6.30-alpha.4a473c.0<br/>@codecademy/styleguide@56.0.1-alpha.4a473c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623e130a8c8ebe1739c58365--gamut-preview.netlify.app>https://623e130a8c8ebe1739c58365--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623e130a8c8ebe1739c58365>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
