### PR TITLE
feat(List): add overflowHidden prop to List

### PR DESCRIPTION
**Pull request by sooinc**
### Overview

- Adds `overflowHidden` prop to List to conditionally set overflow to 'hidden' if this prop is true

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.343c5e.0<br/>@codecademy/gamut-labs@30.4.1-alpha.343c5e.0<br/>@codecademy/gamut@45.2.2-alpha.343c5e.0<br/>@codecademy/monaco@0.6.27-alpha.343c5e.0<br/>@codecademy/styleguide@55.2.3-alpha.343c5e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623a2269a3ddca0ae8a9b703--gamut-preview.netlify.app>https://623a2269a3ddca0ae8a9b703--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623a2269a3ddca0ae8a9b703>Deploy Logs</a></p>

**Comment by sooinc** [comment]
Before and after adding `overflowHidden` prop to List blocks:
https://user-images.githubusercontent.com/58445391/159560674-ba9de421-3d7b-476b-b823-bbbebd2f214f.mp4

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.86-alpha.0df4f6.0<br/>@codecademy/gamut-labs@30.5.1-alpha.0df4f6.0<br/>@codecademy/gamut@45.3.1-alpha.0df4f6.0<br/>@codecademy/monaco@0.6.28-alpha.0df4f6.0<br/>@codecademy/styleguide@55.4.1-alpha.0df4f6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623ccb3bf1d31b33e6c44836--gamut-preview.netlify.app>https://623ccb3bf1d31b33e6c44836--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623ccb3bf1d31b33e6c44836>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.87-alpha.8e88a8.0<br/>@codecademy/gamut-labs@30.6.1-alpha.8e88a8.0<br/>@codecademy/gamut@45.3.1-alpha.8e88a8.0<br/>@codecademy/monaco@0.6.28-alpha.8e88a8.0<br/>@codecademy/styleguide@55.4.2-alpha.8e88a8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623cd3448335db3d2ff3448a--gamut-preview.netlify.app>https://623cd3448335db3d2ff3448a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623cd3448335db3d2ff3448a>Deploy Logs</a></p>

**Pull request merged**
