### PR TITLE
feat(Icons): Add ClubsSealIcon

### PR DESCRIPTION
**Pull request by mstykmshy**
### Overview

Adds ClubsSealIcon

### PR Checklist

- [x] Related to designs: https://www.figma.com/design/4qWg8upPUluB23zoKbmcSE/%E2%99%A3%EF%B8%8F-Cycle-F-Clubs-Onboarding?node-id=357-45178&node-type=frame&m=dev
- [x] Related to JIRA ticket: [LEGO-4158]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

To see in Storybook, visit https://67531630c4c4826ed1ffd7ca--gamut-preview.netlify.app/?path=/docs/atoms-icons-regular--editable-icons

To see in use in the dashboard, run the `sk-LEGO-4158-dashboard-feature-card-update` monorepo branch locally and scroll down to the "Discover More Features' section at `/learn`

Screenshot 2024-12-06 at 10 53 28 AM

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/8665)  | Icon isn't in the preview env as it's for a contentful change that isn't published yet, see instructions above to view locally  |

[LEGO-4158]: https://skillsoftdev.atlassian.net/browse/LEGO-4158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67531630c4c4826ed1ffd7ca--gamut-preview.netlify.app>https://67531630c4c4826ed1ffd7ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67531630c4c4826ed1ffd7ca>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.5.3-alpha.958c12.0<br/>@codecademy/gamut-icons@9.34.2-alpha.958c12.0<br/>@codecademy/gamut-kit@0.6.456-alpha.958c12.0<br/>@codecademy/styleguide@68.2.8-alpha.958c12.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://675324d66570a59f3b3a2633--gamut-preview.netlify.app>https://675324d66570a59f3b3a2633--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/675324d66570a59f3b3a2633>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
lgtm ! you can run `yarn format --fix` to resolve the lint issues (we're fixing this in our upcoming storybook change)

**Comment by mstykmshy** [comment]
> lgtm ! you can run `yarn format --fix` to resolve the lint issues (we're fixing this in our upcoming storybook change)

ahh tysm @dreamwasp ! 🙏

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://675c7ca328119a6401771018--gamut-preview.netlify.app>https://675c7ca328119a6401771018--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/675c7ca328119a6401771018>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.6.1-alpha.5213c3.0<br/>@codecademy/gamut-icons@9.35.1-alpha.5213c3.0<br/>@codecademy/gamut-kit@0.6.457-alpha.5213c3.0<br/></pre>

**Pull request merged**
