### PR TITLE
feat(Illustration): added new stackedPagesIllustration

### PR DESCRIPTION
**Pull request by so-haa**
### Overview

Added a new illustration : **StackedPages**, that needs to be used in Teams Trial Modal

image (1)

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [[IN-1167](https://skillsoftdev.atlassian.net/browse/IN-1167)]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Storybook Illustrations preview => path=/docs/atoms-illustrations--editable-illustration
2. Search for StackedPages

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[IN-1167]: https://skillsoftdev.atlassian.net/browse/IN-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.1-alpha.34119d.0<br/>@codecademy/gamut-illustrations@0.48.0-alpha.34119d.0<br/>@codecademy/gamut-kit@0.6.442-alpha.34119d.0<br/>@codecademy/styleguide@68.0.3-alpha.34119d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66f0db0090f66d59b7805ef3--gamut-preview.netlify.app>https://66f0db0090f66d59b7805ef3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66f0db0090f66d59b7805ef3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.2-alpha.ffcd64.0<br/>@codecademy/gamut-illustrations@0.48.0-alpha.ffcd64.0<br/>@codecademy/gamut-kit@0.6.443-alpha.ffcd64.0<br/>@codecademy/styleguide@68.0.4-alpha.ffcd64.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66f187a5a568a7318b024887--gamut-preview.netlify.app>https://66f187a5a568a7318b024887--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66f187a5a568a7318b024887>Deploy Logs</a></p>

**Pull request merged**
