### PR TITLE
feat(Icons): add SendIcon

### PR DESCRIPTION
**Pull request by akshaydmc**
### Overview

Add SendIcon, For now we are using this icon for prompt engineering component as we are building a chat based UI. It will be used for button for sending prompts. 

Screenshot 2023-10-27 at 12 20 52 AM

### PR Checklist

- [x] Related to designs: [figma](https://www.figma.com/file/5OyhwYY2wNSdAXQDZ4r5ak/%F0%9F%8D%AE-LLM-enabled-learning?type=design&node-id=65-3794&mode=design&t=iYDhWAgMoPyVKebw-0)
- [x] Related to JIRA ticket: [LABS-61]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[LABS-61]: https://codecademy.atlassian.net/browse/LABS-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.3-alpha.0e3a48.0<br/>@codecademy/gamut-icons@9.4.4-alpha.0e3a48.0<br/>@codecademy/gamut-kit@0.6.358-alpha.0e3a48.0<br/>@codecademy/styleguide@66.5.10-alpha.0e3a48.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://653fd2d27c3dc7463e2e45d5--gamut-preview.netlify.app>https://653fd2d27c3dc7463e2e45d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/653fd2d27c3dc7463e2e45d5>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.4-alpha.05e5cd.0<br/>@codecademy/gamut-icons@9.5.1-alpha.05e5cd.0<br/>@codecademy/gamut-kit@0.6.359-alpha.05e5cd.0<br/>@codecademy/styleguide@66.5.11-alpha.05e5cd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://653fe299ee4ef40dfa95d641--gamut-preview.netlify.app>https://653fe299ee4ef40dfa95d641--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/653fe299ee4ef40dfa95d641>Deploy Logs</a></p>

**Pull request merged**
