### PR TITLE
feat(RatingsBar): create RatingsBar gamut-labs component

### PR DESCRIPTION
**Pull request by bndiep**
### Overview

Adds a RatingsBar component to gamut-labs.

To be used for the ratings distribution summary on the revamped course landing page.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/mAzeq3F7H9Ior4wCIL0oZl/Experiments---Ratings-and-Reviews?node-id=640%3A74455&t=pYyeJGq6C3ypdZIj-0
- [x] Related to JIRA ticket: [REACH-2240](https://codecademy.atlassian.net/browse/REACH-2240)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Visit `/?path=/docs/brand-labs-atoms-ratingsbar--ratings-bar`.
2. Confirm there is a story for the `RatingsBar` and that it shows an example of one (which looks similar to the progress bar with a yellow bar on a white background).
Screen Shot 2022-11-16 at 12 33 29 PM
3. Turn on VoiceOver. Tab into the example of the ratings bar. Confirm the screenreader announces the ratings bar as "75% of ratings".

#### PR Links and Envs
NOTE: This component is to be used in portal-app for the revamped  course landing page.

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/585)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-594)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.229-alpha.3037dd.0<br/>@codecademy/gamut-labs@33.7.1-alpha.3037dd.0<br/>@codecademy/gamut@51.4.0-alpha.3037dd.0<br/>@codecademy/monaco@0.6.104-alpha.3037dd.0<br/>@codecademy/styleguide@62.4.0-alpha.3037dd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6372b9bb3fb2bd17ac085657--gamut-preview.netlify.app>https://6372b9bb3fb2bd17ac085657--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6372b9bb3fb2bd17ac085657>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.230-alpha.3bc082.0<br/>@codecademy/gamut-labs@33.7.2-alpha.3bc082.0<br/>@codecademy/gamut@51.4.1-alpha.3bc082.0<br/>@codecademy/monaco@0.6.105-alpha.3bc082.0<br/>@codecademy/styleguide@62.4.1-alpha.3bc082.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6372be0e3fb2bd1bac08565e--gamut-preview.netlify.app>https://6372be0e3fb2bd1bac08565e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6372be0e3fb2bd1bac08565e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.230-alpha.bed857.0<br/>@codecademy/gamut-labs@33.7.2-alpha.bed857.0<br/>@codecademy/gamut@51.4.1-alpha.bed857.0<br/>@codecademy/monaco@0.6.105-alpha.bed857.0<br/>@codecademy/styleguide@62.4.1-alpha.bed857.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6372c1c9cee60a281cd06008--gamut-preview.netlify.app>https://6372c1c9cee60a281cd06008--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6372c1c9cee60a281cd06008>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.231-alpha.5a25fa.0<br/>@codecademy/gamut-labs@33.7.3-alpha.5a25fa.0<br/>@codecademy/gamut@51.4.2-alpha.5a25fa.0<br/>@codecademy/monaco@0.6.106-alpha.5a25fa.0<br/>@codecademy/styleguide@62.4.2-alpha.5a25fa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6373ec6ef9a609078aff0406--gamut-preview.netlify.app>https://6373ec6ef9a609078aff0406--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6373ec6ef9a609078aff0406>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6374073312e31e2a6ace321c--gamut-preview.netlify.app>https://6374073312e31e2a6ace321c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6374073312e31e2a6ace321c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.231-alpha.2dfe3b.0<br/>@codecademy/gamut-labs@33.7.3-alpha.2dfe3b.0<br/>@codecademy/gamut@51.4.2-alpha.2dfe3b.0<br/>@codecademy/monaco@0.6.106-alpha.2dfe3b.0<br/>@codecademy/styleguide@62.4.2-alpha.2dfe3b.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.231-alpha.f9d116.0<br/>@codecademy/gamut-labs@33.7.3-alpha.f9d116.0<br/>@codecademy/styleguide@62.4.2-alpha.f9d116.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63754b1694bfde50a482240e--gamut-preview.netlify.app>https://63754b1694bfde50a482240e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63754b1694bfde50a482240e>Deploy Logs</a></p>

**Review by awgraves — APPROVED** [review]
Looks great!  Thank you for also thinking about a11y right off the bat. 👍

**Review by aresnik11 — APPROVED** [review]
Approving to unblock - gamut labs doesn't need gamut team review

**Pull request merged**
