### PR TITLE
feat(Footer): remove shop link from footer

### PR DESCRIPTION
**Pull request by borisonr**
### Overview

Remove link to shop from footer

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [DISC-817](https://codecademy.atlassian.net/browse/DISC-817)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories (there are unrelated flaky tests in monolith that ill figure out)

#### Testing Instructions

Verify that the shop link does not appear in the footer

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32257)  | [Monolith Env](https://pr-32257-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/portal-app/pull/2490)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2490)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.191-alpha.504404.0<br/>@codecademy/gamut-labs@33.1.12-alpha.504404.0<br/>@codecademy/styleguide@61.3.5-alpha.504404.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.191-alpha.dd9400.0<br/>@codecademy/gamut-labs@33.1.12-alpha.dd9400.0<br/>@codecademy/gamut@50.5.4-alpha.dd9400.0<br/>@codecademy/monaco@0.6.81-alpha.dd9400.0<br/>@codecademy/styleguide@61.3.5-alpha.dd9400.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630cd3da94f02848ab0aa267--gamut-preview.netlify.app>https://630cd3da94f02848ab0aa267--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630cd3da94f02848ab0aa267>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
🚀

**Pull request merged**
