### PR TITLE
Fix: Determine Card boxShadow based on colorMode

### PR DESCRIPTION
**Pull request by j10sanders**
### Overview

Cards on top of dark backgrounds with a boxShadow were not displaying well on dark backgrounds, because the shadow was always dark. This fixes that.

https://github.com/Codecademy/gamut/assets/11084414/d30c7619-eebc-43cd-a728-34967eb86374

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DOT-102
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Will have to do QA on various cards throughout :(

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.7-alpha.fedcb2.0<br/>@codecademy/gamut-kit@0.6.388-alpha.fedcb2.0<br/>@codecademy/styleguide@66.13.1-alpha.fedcb2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f48ee2a4d56511346a2c79--gamut-preview.netlify.app>https://65f48ee2a4d56511346a2c79--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f48ee2a4d56511346a2c79>Deploy Logs</a></p>

**Comment by dreamwasp** [comment]
there's alot of unintended changes on this branch - not sure why the compiled types are being picked up by git. i'm looking into it now

**Review by dreamwasp — CHANGES_REQUESTED** [review]
blocking this for now while i figure out the unintended changes

**Comment by j10sanders** [comment]
> blocking this for now while i figure out the unintended changes

woah! I don't think the vscode setting.json would do it but I'll remove that change just in case

**Comment by j10sanders** [comment]
It added these three directories:

	packages/gamut-labs/
	packages/markdown-overrides/
	packages/monaco/

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.1-alpha.8d37c4.0<br/>@codecademy/gamut-kit@0.6.389-alpha.8d37c4.0<br/>@codecademy/styleguide@66.14.1-alpha.8d37c4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f4c07c846e7c33bea4210c--gamut-preview.netlify.app>https://65f4c07c846e7c33bea4210c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f4c07c846e7c33bea4210c>Deploy Logs</a></p>

**Comment by j10sanders** [comment]
@dreamwasp trying again here https://github.com/Codecademy/gamut/pull/2846

**Pull request closed without merging**
