### PR TITLE
fix(AvatarChooser): update to proper rhf v7 syntax

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Refactors AvataChooser's props to updated react-hook-form v7 syntax and correct fallback props for if register is undefined.

monolith: [here](https://github.com/codecademy-engineering/Codecademy/pull/29757)
portal: [here](https://github.com/codecademy-engineering/portal-app/pull/1545)
### PR Checklist:

- [x] Related to designs:
- [x] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.69-alpha.1185cd.0<br/>@codecademy/gamut-labs@30.0.1-alpha.1185cd.0<br/>@codecademy/styleguide@55.0.1-alpha.1185cd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62227e02495b940bb3d092c1--gamut-preview.netlify.app>https://62227e02495b940bb3d092c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62227e02495b940bb3d092c1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.69-alpha.dd6510.0<br/>@codecademy/gamut-labs@30.0.1-alpha.dd6510.0<br/>@codecademy/styleguide@55.0.1-alpha.dd6510.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62228304443fd711bdeacbba--gamut-preview.netlify.app>https://62228304443fd711bdeacbba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62228304443fd711bdeacbba>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.69-alpha.4869fc.0<br/>@codecademy/gamut-labs@30.0.1-alpha.4869fc.0<br/>@codecademy/styleguide@55.0.1-alpha.4869fc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62228d2caebe93216960e8a9--gamut-preview.netlify.app>https://62228d2caebe93216960e8a9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62228d2caebe93216960e8a9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.69-alpha.1857c4.0<br/>@codecademy/gamut-labs@30.0.1-alpha.1857c4.0<br/>@codecademy/styleguide@55.0.1-alpha.1857c4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622293b669915a25ce875440--gamut-preview.netlify.app>https://622293b669915a25ce875440--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622293b669915a25ce875440>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.69-alpha.103edf.0<br/>@codecademy/gamut-labs@30.0.1-alpha.103edf.0<br/>@codecademy/styleguide@55.0.1-alpha.103edf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622620ffe95cf2007d9263f6--gamut-preview.netlify.app>https://622620ffe95cf2007d9263f6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622620ffe95cf2007d9263f6>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
word

**Pull request merged**
