### PR TITLE
fix(Alert): height and alignment

### PR DESCRIPTION
**Pull request by LinKCoding**
### Overview
Two Issues:
1. The Alert's alignments were off (not centered and stretched out):
The alignment Alert wasn't rendering properly because the alert was stretched vertically.
Upon investigation, it was the X button that had a large height, despite the button seemingly set to "small"

Looking into IconButton, seems like the size prop wasn't used, adding this prop back in seemed to fix the issue.
--- 
2. The border radius of both inline and general alerts should be 3px. 

### PR Checklist

- [ ] Related to designs: https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=30186-40358&m=dev 
- [ ] Related to JIRA ticket: [ABC-123]
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Go to `/docs/molecules-alert--usage-guidelines#alert-types` 
2. Check that the height alignment matches [figma](https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=30186-40358&m=dev)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6915)  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6683121e7dfbc294076f52bc--gamut-preview.netlify.app>https://6683121e7dfbc294076f52bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6683121e7dfbc294076f52bc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.2-alpha.cb5685.0<br/>@codecademy/gamut-kit@0.6.423-alpha.cb5685.0<br/>@codecademy/styleguide@66.29.3-alpha.cb5685.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.2-alpha.e04885.0<br/>@codecademy/gamut-kit@0.6.423-alpha.e04885.0<br/>@codecademy/styleguide@66.29.3-alpha.e04885.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6683180efef90d97995d7099--gamut-preview.netlify.app>https://6683180efef90d97995d7099--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6683180efef90d97995d7099>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.3-alpha.466a36.0<br/>@codecademy/gamut-kit@0.6.424-alpha.466a36.0<br/>@codecademy/styleguide@66.29.4-alpha.466a36.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://668c48fbb43fe1b048e8c9e0--gamut-preview.netlify.app>https://668c48fbb43fe1b048e8c9e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/668c48fbb43fe1b048e8c9e0>Deploy Logs</a></p>

**Pull request merged**
