### PR TITLE
fix(Popover): Fix Popover story

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Popover story broke, this should fix it.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a752d63ff88d10dd5f1dec--gamut-preview.netlify.app>https://62a752d63ff88d10dd5f1dec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a752d63ff88d10dd5f1dec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a758d7350ed2051d15394b--gamut-preview.netlify.app>https://62a758d7350ed2051d15394b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a758d7350ed2051d15394b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@58.0.3-alpha.2c4065.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@58.0.3-alpha.9c2f06.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.140-alpha.39e50f.0<br/>@codecademy/gamut-labs@32.0.3-alpha.39e50f.0<br/>@codecademy/styleguide@58.0.3-alpha.39e50f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a76573f59b2906eacb41f0--gamut-preview.netlify.app>https://62a76573f59b2906eacb41f0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a76573f59b2906eacb41f0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.140-alpha.e95eda.0<br/>@codecademy/gamut-labs@32.0.3-alpha.e95eda.0<br/>@codecademy/styleguide@58.0.3-alpha.e95eda.0<br/></pre>

**Review by reedlaverack — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a7afcf5be609044dcdb147--gamut-preview.netlify.app>https://62a7afcf5be609044dcdb147--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a7afcf5be609044dcdb147>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
Confirmed popovers work in the preview!

**Pull request merged**
