### PR TITLE
Cass sb 8 fix connectformtypes

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Makes a couple changes to ConnectedForm - I think some of the pakacge bumps require stricter type safety 

#### Testing Instructions

All tests + builds are now passing locally, the remaining test failures are due to the other act errors. See *all* tests passing in the [monorepo PR ](https://github.com/codecademy-engineering/mono/pull/8329)

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67227b042944272e07602a39--gamut-preview.netlify.app>https://67227b042944272e07602a39--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67227b042944272e07602a39>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.469d91.0<br/>@codecademy/gamut@57.4.4-alpha.469d91.0<br/>@codecademy/gamut-icons@9.32.1-alpha.469d91.0<br/>@codecademy/gamut-illustrations@0.49.1-alpha.469d91.0<br/>@codecademy/gamut-kit@0.6.452-alpha.469d91.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.469d91.0<br/>@codecademy/gamut-styles@17.1.1-alpha.469d91.0<br/>@codecademy/gamut-tests@5.1.3-alpha.469d91.0<br/>@codecademy/macros@3.0.5-alpha.469d91.0<br/>@codecademy/styleguide@68.1.4-alpha.469d91.0<br/>@codecademy/variance@0.21.4-alpha.469d91.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67227d8a790ff12dc885089a--gamut-preview.netlify.app>https://67227d8a790ff12dc885089a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67227d8a790ff12dc885089a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.edf7c7.0<br/>@codecademy/gamut@57.4.4-alpha.edf7c7.0<br/>@codecademy/gamut-icons@9.32.1-alpha.edf7c7.0<br/>@codecademy/gamut-illustrations@0.49.1-alpha.edf7c7.0<br/>@codecademy/gamut-kit@0.6.452-alpha.edf7c7.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.edf7c7.0<br/>@codecademy/gamut-styles@17.1.1-alpha.edf7c7.0<br/>@codecademy/gamut-tests@5.1.3-alpha.edf7c7.0<br/>@codecademy/macros@3.0.5-alpha.edf7c7.0<br/>@codecademy/styleguide@68.1.4-alpha.edf7c7.0<br/>@codecademy/variance@0.21.4-alpha.edf7c7.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.de6161.0<br/>@codecademy/gamut@57.4.4-alpha.de6161.0<br/>@codecademy/gamut-icons@9.32.1-alpha.de6161.0<br/>@codecademy/gamut-illustrations@0.49.1-alpha.de6161.0<br/>@codecademy/gamut-kit@0.6.452-alpha.de6161.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.de6161.0<br/>@codecademy/gamut-styles@17.1.1-alpha.de6161.0<br/>@codecademy/gamut-tests@5.1.3-alpha.de6161.0<br/>@codecademy/macros@3.0.5-alpha.de6161.0<br/>@codecademy/styleguide@68.1.4-alpha.de6161.0<br/>@codecademy/variance@0.21.4-alpha.de6161.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67228663a5240439e28b2622--gamut-preview.netlify.app>https://67228663a5240439e28b2622--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67228663a5240439e28b2622>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6723d47e111bbc18c3a366b5--gamut-preview.netlify.app>https://6723d47e111bbc18c3a366b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6723d47e111bbc18c3a366b5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.24602f.0<br/>@codecademy/gamut@57.4.4-alpha.24602f.0<br/>@codecademy/gamut-icons@9.32.1-alpha.24602f.0<br/>@codecademy/gamut-illustrations@0.49.1-alpha.24602f.0<br/>@codecademy/gamut-kit@0.6.452-alpha.24602f.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.24602f.0<br/>@codecademy/gamut-styles@17.1.1-alpha.24602f.0<br/>@codecademy/gamut-tests@5.1.3-alpha.24602f.0<br/>@codecademy/macros@3.0.5-alpha.24602f.0<br/>@codecademy/styleguide@68.1.4-alpha.24602f.0<br/>@codecademy/variance@0.21.4-alpha.24602f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6723e04bd0918e29e36cba76--gamut-preview.netlify.app>https://6723e04bd0918e29e36cba76--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6723e04bd0918e29e36cba76>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.94acef.0<br/>@codecademy/gamut@57.4.4-alpha.94acef.0<br/>@codecademy/gamut-icons@9.32.1-alpha.94acef.0<br/>@codecademy/gamut-illustrations@0.49.1-alpha.94acef.0<br/>@codecademy/gamut-kit@0.6.452-alpha.94acef.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.94acef.0<br/>@codecademy/gamut-styles@17.1.1-alpha.94acef.0<br/>@codecademy/gamut-tests@5.1.3-alpha.94acef.0<br/>@codecademy/macros@3.0.5-alpha.94acef.0<br/>@codecademy/styleguide@68.1.4-alpha.94acef.0<br/>@codecademy/variance@0.21.4-alpha.94acef.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Pull request merged**
