### PR TITLE
refactor(header): add videos in header and footer resource list

### PR DESCRIPTION
**Pull request by aionate0812**
### Overview

Add videos library to resources list in header and footer

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [Reach-1261](https://codecademy.atlassian.net/browse/REACH-1261)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.17-alpha.90c2d0.0<br/>@codecademy/gamut-labs@28.0.12-alpha.90c2d0.0<br/>@codecademy/styleguide@50.2.4-alpha.90c2d0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6195499139ef4a607e3d5e13--gamut-preview.netlify.app>https://6195499139ef4a607e3d5e13--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6195499139ef4a607e3d5e13>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.18-alpha.f29203.0<br/>@codecademy/gamut-labs@28.0.13-alpha.f29203.0<br/>@codecademy/styleguide@50.2.5-alpha.f29203.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61956aba822e2f006df3ff35--gamut-preview.netlify.app>https://61956aba822e2f006df3ff35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61956aba822e2f006df3ff35>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
