### PR TITLE
fix(GridForm): properly align gridform infotips

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Fixes misaligned Infotips - this happened because the screenreader text was a sibling to the Tip container, it is now a child of the Tip container

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* Go to GridForm story
* See the InfoTips properly aligned
* Turn on VO
* Hear them properly announced
* Double check the InfoTip story for floating and regular InfoTip, include cmd + opt text nav

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/38101)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/7088)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@56.0.3-alpha.628c7f.0<br/>@codecademy/gamut-kit@0.6.428-alpha.628c7f.0<br/>@codecademy/styleguide@67.0.3-alpha.628c7f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66a1146da0c8b04128aa8c82--gamut-preview.netlify.app>https://66a1146da0c8b04128aa8c82--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66a1146da0c8b04128aa8c82>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@56.0.3-alpha.4fe369.0<br/>@codecademy/gamut-kit@0.6.428-alpha.4fe369.0<br/>@codecademy/styleguide@67.0.3-alpha.4fe369.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66a12b502091465b7b4b7168--gamut-preview.netlify.app>https://66a12b502091465b7b4b7168--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66a12b502091465b7b4b7168>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@56.0.3-alpha.630ca0.0<br/>@codecademy/gamut-kit@0.6.428-alpha.630ca0.0<br/>@codecademy/styleguide@67.0.3-alpha.630ca0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66a131ff57ee2e0091bd7536--gamut-preview.netlify.app>https://66a131ff57ee2e0091bd7536--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66a131ff57ee2e0091bd7536>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM!

**Review by villdev — APPROVED** [review]
LGTM :shipit:

**Review by LinKCoding — COMMENTED** [review]
LGTM! 

curious why {text} was changed to be included into <Tip> but works well!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@56.0.3-alpha.c89945.0<br/>@codecademy/gamut-kit@0.6.428-alpha.c89945.0<br/>@codecademy/styleguide@67.0.3-alpha.c89945.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66a1362d27d684049062f715--gamut-preview.netlify.app>https://66a1362d27d684049062f715--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66a1362d27d684049062f715>Deploy Logs</a></p>

**Pull request merged**
