### PR TITLE
fix(Anchor): dedupe ids on menus for axe tests + forward role to Anchors

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Fixes useLayoutEffect, dupe id axe failures, and a bug with Anchor where it was not properly forwarding its 'role' props.

Testing on @thedoomshine's  header integration branches:  monolith PR [here](https://github.com/codecademy-engineering/Codecademy/pull/28365), portal app PR [here](https://github.com/codecademy-engineering/portal-app/pull/1083)

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.37-alpha.64d470.0<br/>@codecademy/gamut-labs@28.5.2-alpha.64d470.0<br/>@codecademy/gamut@42.2.2-alpha.64d470.0<br/>@codecademy/monaco@0.5.28-alpha.64d470.0<br/>@codecademy/styleguide@52.3.2-alpha.64d470.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0db6c08ade244d13875b8--gamut-preview.netlify.app>https://61c0db6c08ade244d13875b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0db6c08ade244d13875b8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.37-alpha.703a19.0<br/>@codecademy/gamut-labs@28.5.2-alpha.703a19.0<br/>@codecademy/gamut@42.2.2-alpha.703a19.0<br/>@codecademy/monaco@0.5.28-alpha.703a19.0<br/>@codecademy/styleguide@52.3.2-alpha.703a19.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0df1d22ba4d457ea623ec--gamut-preview.netlify.app>https://61c0df1d22ba4d457ea623ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0df1d22ba4d457ea623ec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0e548d832f950490ebae1--gamut-preview.netlify.app>https://61c0e548d832f950490ebae1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0e548d832f950490ebae1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.37-alpha.ecd61b.0<br/>@codecademy/gamut-labs@28.5.2-alpha.ecd61b.0<br/>@codecademy/gamut@42.2.2-alpha.ecd61b.0<br/>@codecademy/monaco@0.5.28-alpha.ecd61b.0<br/>@codecademy/styleguide@52.3.2-alpha.ecd61b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0ecacbdd83161f7f610f8--gamut-preview.netlify.app>https://61c0ecacbdd83161f7f610f8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0ecacbdd83161f7f610f8>Deploy Logs</a></p>

**Review by thedoomshine — APPROVED** [review]
at some point a bunch of my changes got blown away and i have no idea when

thank you for fixing this!!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.162677.0<br/>@codecademy/gamut-labs@28.6.1-alpha.162677.0<br/>@codecademy/gamut@42.2.2-alpha.162677.0<br/>@codecademy/monaco@0.5.28-alpha.162677.0<br/>@codecademy/styleguide@52.4.1-alpha.162677.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0f24d8794a55ff04e2a0f--gamut-preview.netlify.app>https://61c0f24d8794a55ff04e2a0f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0f24d8794a55ff04e2a0f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.3e3565.0<br/>@codecademy/gamut-labs@28.6.1-alpha.3e3565.0<br/>@codecademy/gamut@42.2.2-alpha.3e3565.0<br/>@codecademy/monaco@0.5.28-alpha.3e3565.0<br/>@codecademy/styleguide@52.4.1-alpha.3e3565.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0fb5dbcbea3696c1d334e--gamut-preview.netlify.app>https://61c0fb5dbcbea3696c1d334e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0fb5dbcbea3696c1d334e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.746b36.0<br/>@codecademy/gamut-labs@28.6.1-alpha.746b36.0<br/>@codecademy/gamut@42.2.2-alpha.746b36.0<br/>@codecademy/monaco@0.5.28-alpha.746b36.0<br/>@codecademy/styleguide@52.4.1-alpha.746b36.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c1000782ada06c93d376a0--gamut-preview.netlify.app>https://61c1000782ada06c93d376a0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c1000782ada06c93d376a0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.ad1c46.0<br/>@codecademy/gamut-labs@28.6.1-alpha.ad1c46.0<br/>@codecademy/gamut@42.2.2-alpha.ad1c46.0<br/>@codecademy/monaco@0.5.28-alpha.ad1c46.0<br/>@codecademy/styleguide@52.4.1-alpha.ad1c46.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c123a3631e569306200c74--gamut-preview.netlify.app>https://61c123a3631e569306200c74--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c123a3631e569306200c74>Deploy Logs</a></p>

**Pull request closed without merging**
