### PR TITLE
update-react-imports + change appropriate TS configs

### PR DESCRIPTION
**Pull request by dreamwasp**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.2a2889.0<br/>@codecademy/gamut-illustrations@0.32.3-alpha.2a2889.0<br/>@codecademy/gamut-kit@0.6.217-alpha.2a2889.0<br/>@codecademy/gamut-labs@33.6.8-alpha.2a2889.0<br/>@codecademy/gamut-patterns@0.8.16-alpha.2a2889.0<br/>@codecademy/gamut-styles@14.1.2-alpha.2a2889.0<br/>@codecademy/gamut-tests@4.0.15-alpha.2a2889.0<br/>@codecademy/gamut@51.0.1-alpha.2a2889.0<br/>@codecademy/markdown-overrides@0.9.13-alpha.2a2889.0<br/>@codecademy/monaco@0.6.96-alpha.2a2889.0<br/>@codecademy/styleguide@62.0.1-alpha.2a2889.0<br/>@codecademy/variance@0.20.4-alpha.2a2889.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.61dd4b.0<br/>@codecademy/gamut-illustrations@0.32.3-alpha.61dd4b.0<br/>@codecademy/gamut-kit@0.6.217-alpha.61dd4b.0<br/>@codecademy/gamut-labs@33.6.8-alpha.61dd4b.0<br/>@codecademy/gamut-patterns@0.8.16-alpha.61dd4b.0<br/>@codecademy/gamut-styles@14.1.2-alpha.61dd4b.0<br/>@codecademy/gamut-tests@4.0.15-alpha.61dd4b.0<br/>@codecademy/gamut@51.0.1-alpha.61dd4b.0<br/>@codecademy/markdown-overrides@0.9.13-alpha.61dd4b.0<br/>@codecademy/monaco@0.6.96-alpha.61dd4b.0<br/>@codecademy/styleguide@62.0.1-alpha.61dd4b.0<br/>@codecademy/variance@0.20.4-alpha.61dd4b.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.718461.0<br/>@codecademy/gamut-illustrations@0.32.3-alpha.718461.0<br/>@codecademy/gamut-kit@0.6.218-alpha.718461.0<br/>@codecademy/gamut-labs@33.6.9-alpha.718461.0<br/>@codecademy/gamut-patterns@0.8.16-alpha.718461.0<br/>@codecademy/gamut-styles@14.1.2-alpha.718461.0<br/>@codecademy/gamut-tests@4.0.15-alpha.718461.0<br/>@codecademy/gamut@51.0.1-alpha.718461.0<br/>@codecademy/markdown-overrides@0.9.13-alpha.718461.0<br/>@codecademy/monaco@0.6.96-alpha.718461.0<br/>@codecademy/styleguide@62.0.3-alpha.718461.0<br/>@codecademy/variance@0.20.4-alpha.718461.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6352d55776907f39a08e73ed--gamut-preview.netlify.app>https://6352d55776907f39a08e73ed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6352d55776907f39a08e73ed>Deploy Logs</a></p>

**Comment by jakemhiller** [comment]
@dreamwasp i think at this point it would be easier to just recreate this so i'm going to close this PR and base a new one off of the TS config changes

**Pull request closed without merging**
