### PR TITLE
feat: (SelectDropdown multi select) Allow value to override internal state

### PR DESCRIPTION
**Pull request by MattSchiller**
### Overview

We were having an issue where the caller of the dropdown component was changing the value, and the component itself was saying "nah fam, we only accept an INITIAL value. Once this ride starts, there's no cutting back in. All gas, no breaks, let's GOOOOO!"

Which was, of course, unacceptably uncooperative.

So now we listen for the `value` changing, and if it does, we comply.

There's a minor edgecase, where if the options change, we might want to consider updating the value, but I'm betting:
- The underlying library handles that for us
- We have no use-cases of that yet
- We're gonna return to this component in a later Gamut ticket and refactor all of this later, so YAGNIIIII

Now, when the `value` prop is passed for multi-select, it will update the component's state, too

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [INT-86](https://codecademy.atlassian.net/browse/INT-86)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.6e3344.0<br/>@codecademy/gamut-labs@28.6.1-alpha.6e3344.0<br/>@codecademy/gamut@42.2.2-alpha.6e3344.0<br/>@codecademy/monaco@0.5.28-alpha.6e3344.0<br/>@codecademy/styleguide@52.4.1-alpha.6e3344.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d7568586f2ed0065f683a8--gamut-preview.netlify.app>https://61d7568586f2ed0065f683a8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d7568586f2ed0065f683a8>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
makes sense!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.39-alpha.b1d2b3.0<br/>@codecademy/gamut-labs@28.6.2-alpha.b1d2b3.0<br/>@codecademy/gamut@42.3.1-alpha.b1d2b3.0<br/>@codecademy/monaco@0.5.29-alpha.b1d2b3.0<br/>@codecademy/styleguide@52.5.1-alpha.b1d2b3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d8bcdfb3490658475e392b--gamut-preview.netlify.app>https://61d8bcdfb3490658475e392b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d8bcdfb3490658475e392b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.40-alpha.77ecdd.0<br/>@codecademy/gamut-labs@28.6.3-alpha.77ecdd.0<br/>@codecademy/gamut@42.3.1-alpha.77ecdd.0<br/>@codecademy/monaco@0.5.29-alpha.77ecdd.0<br/>@codecademy/styleguide@52.5.2-alpha.77ecdd.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.41-alpha.072cc4.0<br/>@codecademy/gamut-labs@28.6.4-alpha.072cc4.0<br/>@codecademy/gamut@43.0.1-alpha.072cc4.0<br/>@codecademy/monaco@0.5.30-alpha.072cc4.0<br/>@codecademy/styleguide@53.0.1-alpha.072cc4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e193920bf13a1b9805a8d7--gamut-preview.netlify.app>https://61e193920bf13a1b9805a8d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e193920bf13a1b9805a8d7>Deploy Logs</a></p>

**Pull request merged**
