### PR TITLE
feat(Modal): adding aria-live as a prop to ModalContainer

### PR DESCRIPTION
**Pull request by amabarr**
### Overview

As a part of this a11y ticket I was asked to turn off a modal's aria-live: [A11Y-579](https://codecademy.atlassian.net/browse/A11Y-579), but I couldn't because it was hardcoded to "polite" in gamut. Here, I'm adding the ability to change the aria-live but also keeping "polite" as a default

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [A11Y-579](https://codecademy.atlassian.net/browse/A11Y-579)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. go to the preview LE below
2. View a solution diff modal, see that it's aria-live is off in the help text
3. Go anywhere else where there is a modal and see that it still has aria-live="polite"

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36196)  | [Monolith Env]( ) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/2883)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2883)   |
| LE link | [Same as Portal link above, but LE](https://github.com/codecademy-engineering/mono/pull/2883) | [LE Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2883)  |

[A11Y-579]: https://codecademy.atlassian.net/browse/A11Y-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A11Y-579]: https://codecademy.atlassian.net/browse/A11Y-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.336-alpha.315ad5.0<br/>@codecademy/gamut-labs@35.15.9-alpha.315ad5.0<br/>@codecademy/gamut@55.1.14-alpha.315ad5.0<br/>@codecademy/styleguide@66.1.19-alpha.315ad5.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.337-alpha.ba7286.0<br/>@codecademy/gamut-labs@35.15.10-alpha.ba7286.0<br/>@codecademy/gamut@55.1.15-alpha.ba7286.0<br/>@codecademy/styleguide@66.1.20-alpha.ba7286.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64c7bc45073d9900b2ec7e1d--gamut-preview.netlify.app>https://64c7bc45073d9900b2ec7e1d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64c7bc45073d9900b2ec7e1d>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
*chef's kiss* perfect

**Pull request merged**
