### PR TITLE
fix(Markdown): nested ordered and unordered list fix

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Fixes a bug with Markdown where ordered list items  that were nested in an unordered list were still getting a bullet point

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: web-1983
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* Navigate to the Markdown component
* Observe no visual bugs on the nested ordered/unordered lists
 
#### PR Links and Envs

**_Note_**: I am using these same PR envs as the [Markdown Checkbox PR](https://github.com/Codecademy/gamut/pull/2460) -- the alpha packages are this PR's (which branches off of Markdown Checkbox)

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31680)  | [Monolith Env](https://pr-31680-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2279)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2279)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.165-alpha.6b5064.0<br/>@codecademy/gamut-labs@33.0.1-alpha.6b5064.0<br/>@codecademy/gamut@48.3.1-alpha.6b5064.0<br/>@codecademy/monaco@0.6.60-alpha.6b5064.0<br/>@codecademy/styleguide@59.0.1-alpha.6b5064.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62d9ba3eda5ea31639f166d9--gamut-preview.netlify.app>https://62d9ba3eda5ea31639f166d9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62d9ba3eda5ea31639f166d9>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.169-alpha.315079.0<br/>@codecademy/gamut-labs@33.0.5-alpha.315079.0<br/>@codecademy/gamut@49.1.1-alpha.315079.0<br/>@codecademy/monaco@0.6.64-alpha.315079.0<br/>@codecademy/styleguide@60.1.1-alpha.315079.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e7eac6767c7565e6545d75--gamut-preview.netlify.app>https://62e7eac6767c7565e6545d75--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e7eac6767c7565e6545d75>Deploy Logs</a></p>

**Pull request merged**
