### PR TITLE
fix(GlobalHeader): Pass user to all anon header items

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

We need to pass `user` to `anonDefaultHeaderItems` and `anonSignupHeaderItems`. We also need to pass `user` to all `anon` `getAppHeaderItems` cases. This is so we can grab the `useNewCatalogDropdown` value for the anon `GlobalHeader` states. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.94-alpha.89a36d.0<br/>@codecademy/gamut-labs@31.2.1-alpha.89a36d.0<br/>@codecademy/styleguide@56.1.2-alpha.89a36d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6247544bc474550b977f142a--gamut-preview.netlify.app>https://6247544bc474550b977f142a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6247544bc474550b977f142a>Deploy Logs</a></p>

**Review by borisonr — APPROVED** [review]
oh whoops, sorry i missed these!

**Comment by zippyzow** [comment]
> oh whoops, sorry i missed these!

no prob, i missed it too lol!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.94-alpha.4eefab.0<br/>@codecademy/gamut-labs@31.2.1-alpha.4eefab.0<br/>@codecademy/styleguide@56.1.2-alpha.4eefab.0<br/></pre>

**Pull request merged**
