### PR TITLE
fix(Pagination): fix totalPages

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

adds total pages to the dependency array so that page numbers correctly populate when totalPages change

Added a totalPageChanger example to test [here](https://625ecf390440b2210016bddb--gamut-preview.netlify.app/?path=/docs/molecules-pagination--pagination#controlled-pagination)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: disc-598
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://625ecf390440b2210016bddb--gamut-preview.netlify.app>https://625ecf390440b2210016bddb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/625ecf390440b2210016bddb>Deploy Logs</a></p>

**Review by j10sanders — APPROVED** [review]
works perfectly in my branch!

Edit: I am noticing a warning when I click a page number:
Screen Shot 2022-04-21 at 3 23 06 PM

This also shows up in my jest tests 

Edit again: this might just be from the way I'm controlling the component and not this change!  I'll let you know

It appears to happen whenever I set pageNumber.  I'll look into it and possibly write a separate bug ticket

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://626827892d50176519c007ce--gamut-preview.netlify.app>https://626827892d50176519c007ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/626827892d50176519c007ce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.115-alpha.4e98b7.0<br/>@codecademy/gamut-labs@31.11.4-alpha.4e98b7.0<br/>@codecademy/gamut@47.0.1-alpha.4e98b7.0<br/>@codecademy/monaco@0.6.38-alpha.4e98b7.0<br/>@codecademy/styleguide@57.0.1-alpha.4e98b7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62685f103ea49700bd1822d7--gamut-preview.netlify.app>https://62685f103ea49700bd1822d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62685f103ea49700bd1822d7>Deploy Logs</a></p>

**Pull request merged**
