### PR TITLE
feat(SelectDropdown): make multi value look like tag

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Updates the `SelectDropdown` multi value options to look like our new `Tag` component! `SelectDropdown` uses react select so we are doing this by overriding the styles for multivalue, multivalue label, and multi value remove by passing in styles that are shared with `Tag`. Multivalue select dropdowns do not appear to be currently used anywhere (looked in monolith, portal app, BAM, author) so this change can be easily made across the board.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2125]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Visit https://63486a28d5f8d9006abcae64--gamut-preview.netlify.app/?path=/docs/atoms-forminputs-selectdropdown--select-dropdown
2. Change the "multiple" prop to true in the prop table
3. Select multiple options in the dropdown and see the new beautiful colors
Screen Shot 2022-10-14 at 1 46 00 PM
Screen Shot 2022-10-14 at 1 46 20 PM

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33027)  | [Monolith Env](https://pr-33027-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/375)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-375)   |

[WEB-2125]: https://codecademy.atlassian.net/browse/WEB-2125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.212-alpha.f6bec1.0<br/>@codecademy/gamut-labs@33.6.3-alpha.f6bec1.0<br/>@codecademy/gamut@50.8.2-alpha.f6bec1.0<br/>@codecademy/monaco@0.6.93-alpha.f6bec1.0<br/>@codecademy/styleguide@61.7.2-alpha.f6bec1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63486a28d5f8d9006abcae64--gamut-preview.netlify.app>https://63486a28d5f8d9006abcae64--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63486a28d5f8d9006abcae64>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.214-alpha.9d0f92.0<br/>@codecademy/gamut-labs@33.6.5-alpha.9d0f92.0<br/>@codecademy/gamut@50.9.1-alpha.9d0f92.0<br/>@codecademy/monaco@0.6.94-alpha.9d0f92.0<br/>@codecademy/styleguide@61.7.4-alpha.9d0f92.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6349a6eeb25d3c0380028818--gamut-preview.netlify.app>https://6349a6eeb25d3c0380028818--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6349a6eeb25d3c0380028818>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
✨

**Pull request merged**
