### PR TITLE
allow static images in storybook 8

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Add image examples in template + configuration in main.ts

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6733c30706b89f64038096ee--gamut-preview.netlify.app>https://6733c30706b89f64038096ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6733c30706b89f64038096ee>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.f00988.0<br/>@codecademy/gamut@57.4.5-alpha.f00988.0<br/>@codecademy/gamut-icons@9.32.2-alpha.f00988.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.f00988.0<br/>@codecademy/gamut-kit@0.6.453-alpha.f00988.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.f00988.0<br/>@codecademy/gamut-styles@17.1.2-alpha.f00988.0<br/>@codecademy/gamut-tests@5.1.4-alpha.f00988.0<br/>@codecademy/macros@3.0.5-alpha.f00988.0<br/>@codecademy/styleguide@68.1.4-alpha.f00988.0<br/>@codecademy/variance@0.21.5-alpha.f00988.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6733d0ad22ad4465a8eae087--gamut-preview.netlify.app>https://6733d0ad22ad4465a8eae087--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6733d0ad22ad4465a8eae087>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.7d3ac9.0<br/>@codecademy/gamut@57.4.5-alpha.7d3ac9.0<br/>@codecademy/gamut-icons@9.32.2-alpha.7d3ac9.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.7d3ac9.0<br/>@codecademy/gamut-kit@0.6.453-alpha.7d3ac9.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.7d3ac9.0<br/>@codecademy/gamut-styles@17.1.2-alpha.7d3ac9.0<br/>@codecademy/gamut-tests@5.1.4-alpha.7d3ac9.0<br/>@codecademy/macros@3.0.5-alpha.7d3ac9.0<br/>@codecademy/styleguide@68.1.4-alpha.7d3ac9.0<br/>@codecademy/variance@0.21.5-alpha.7d3ac9.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.dc2fa5.0<br/>@codecademy/gamut@57.4.5-alpha.dc2fa5.0<br/>@codecademy/gamut-icons@9.32.2-alpha.dc2fa5.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.dc2fa5.0<br/>@codecademy/gamut-kit@0.6.453-alpha.dc2fa5.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.dc2fa5.0<br/>@codecademy/gamut-styles@17.1.2-alpha.dc2fa5.0<br/>@codecademy/gamut-tests@5.1.4-alpha.dc2fa5.0<br/>@codecademy/macros@3.0.5-alpha.dc2fa5.0<br/>@codecademy/styleguide@68.1.4-alpha.dc2fa5.0<br/>@codecademy/variance@0.21.5-alpha.dc2fa5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6733d48f1aef107b5118f8e1--gamut-preview.netlify.app>https://6733d48f1aef107b5118f8e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6733d48f1aef107b5118f8e1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.44732b.0<br/>@codecademy/gamut@57.4.5-alpha.44732b.0<br/>@codecademy/gamut-icons@9.32.2-alpha.44732b.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.44732b.0<br/>@codecademy/gamut-kit@0.6.453-alpha.44732b.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.44732b.0<br/>@codecademy/gamut-styles@17.1.2-alpha.44732b.0<br/>@codecademy/gamut-tests@5.1.4-alpha.44732b.0<br/>@codecademy/macros@3.0.5-alpha.44732b.0<br/>@codecademy/styleguide@68.1.4-alpha.44732b.0<br/>@codecademy/variance@0.21.5-alpha.44732b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6733d7451aa39700f168d861--gamut-preview.netlify.app>https://6733d7451aa39700f168d861--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6733d7451aa39700f168d861>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.895781.0<br/>@codecademy/gamut@57.4.5-alpha.895781.0<br/>@codecademy/gamut-icons@9.32.2-alpha.895781.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.895781.0<br/>@codecademy/gamut-kit@0.6.453-alpha.895781.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.895781.0<br/>@codecademy/gamut-styles@17.1.2-alpha.895781.0<br/>@codecademy/gamut-tests@5.1.4-alpha.895781.0<br/>@codecademy/macros@3.0.5-alpha.895781.0<br/>@codecademy/styleguide@68.1.4-alpha.895781.0<br/>@codecademy/variance@0.21.5-alpha.895781.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6733d929a6a935009ef04c0a--gamut-preview.netlify.app>https://6733d929a6a935009ef04c0a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6733d929a6a935009ef04c0a>Deploy Logs</a></p>

**Review by LinKCoding — APPROVED** [review]
LGTM!

**Pull request merged**
