### PR TITLE
fix(Icons): remove default title

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Removes the default title from icons (per this accessibility ticket). Also adds a discriminated union type that ensures icons with aria-labels are not hidden

### PR Checklist

- [x] Related to JIRA ticket: [gm-594]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* check out Icons story - they should not have default titles
* run the branch locally - check out the new type errors when using an Icon with an aria-label without disabling aria-hidden

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Mono Link](https://github.com/codecademy-engineering/Codecademy/pull/37552)  |TBD |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/5889)  | [Portal Env] TBD  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661ea1807b10263d7d002759--gamut-preview.netlify.app>https://661ea1807b10263d7d002759--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661ea1807b10263d7d002759>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.3-alpha.5b0493.0<br/>@codecademy/gamut-icons@9.21.1-alpha.5b0493.0<br/>@codecademy/gamut-kit@0.6.400-alpha.5b0493.0<br/>@codecademy/styleguide@66.17.4-alpha.5b0493.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.3-alpha.8de98c.0<br/>@codecademy/gamut-icons@9.21.1-alpha.8de98c.0<br/>@codecademy/gamut-kit@0.6.400-alpha.8de98c.0<br/>@codecademy/styleguide@66.17.4-alpha.8de98c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661fd6b78ce25d381b561c7f--gamut-preview.netlify.app>https://661fd6b78ce25d381b561c7f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661fd6b78ce25d381b561c7f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.4-alpha.744169.0<br/>@codecademy/gamut-icons@9.22.1-alpha.744169.0<br/>@codecademy/gamut-kit@0.6.401-alpha.744169.0<br/>@codecademy/styleguide@66.17.5-alpha.744169.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66218374f92695258a21d323--gamut-preview.netlify.app>https://66218374f92695258a21d323--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66218374f92695258a21d323>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.5-alpha.9b821b.0<br/>@codecademy/gamut-icons@9.23.1-alpha.9b821b.0<br/>@codecademy/gamut-kit@0.6.402-alpha.9b821b.0<br/>@codecademy/styleguide@66.17.6-alpha.9b821b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6622da72e5de073b8731c1f7--gamut-preview.netlify.app>https://6622da72e5de073b8731c1f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6622da72e5de073b8731c1f7>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
i just noticed those came back at some point, lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.5-alpha.4d6f5d.0<br/>@codecademy/gamut-icons@9.23.1-alpha.4d6f5d.0<br/>@codecademy/gamut-kit@0.6.402-alpha.4d6f5d.0<br/>@codecademy/styleguide@66.17.6-alpha.4d6f5d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66280f4735fa230464601a77--gamut-preview.netlify.app>https://66280f4735fa230464601a77--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66280f4735fa230464601a77>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.6-alpha.8f9907.0<br/>@codecademy/gamut-icons@9.24.1-alpha.8f9907.0<br/>@codecademy/gamut-kit@0.6.403-alpha.8f9907.0<br/>@codecademy/styleguide@66.18.1-alpha.8f9907.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://662a6b2e5f42becc47f67ae9--gamut-preview.netlify.app>https://662a6b2e5f42becc47f67ae9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/662a6b2e5f42becc47f67ae9>Deploy Logs</a></p>

**Pull request merged**
