### PR TITLE
feat: add new Skills icons

### PR DESCRIPTION
**Pull request by sylvanasantos**
### Overview

- Added new icons for languages and subjects that we teach
- Organized these icons into a new Skills section in storybook

Note: there were a few icons that were already in gamut but just needed to be moved into the Skills section and the RubyIcon needed to be updated and moved. All details are in the [Figma](https://www.figma.com/design/h5Opgw8Inv1KSSsek0aawR/%F0%9F%8C%A0-Skill-XP?node-id=389-14536&t=p2rIbAzaLaBjzFSM-0). 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Visit the storybook preview and navigate to the Regular Icons section.
2. Ensure that you see a new Skills section at the bottom and that all the icons are there and look good.
3. You can also checkout the mono repo PR to see it used in the new skills section on the dashboard. 

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6535)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-6535)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.3-alpha.138737.0<br/>@codecademy/gamut-icons@9.26.1-alpha.138737.0<br/>@codecademy/gamut-kit@0.6.412-alpha.138737.0<br/>@codecademy/styleguide@66.22.1-alpha.138737.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://666230fc651d5871f90e05d8--gamut-preview.netlify.app>https://666230fc651d5871f90e05d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/666230fc651d5871f90e05d8>Deploy Logs</a></p>

**Review by aionate0812 — APPROVED** [review]
Changes look good! - some icons like the `DevopsIcon` is under the interface section instead of skills, even though the icon is in the skills array 🤔

**Review by dreamwasp — APPROVED** [review]
these all look great!

**Comment by sylvanasantos** [comment]
@aionate0812 that's so weird! that wasn't happening locally! I'll dig into it and try to fix before merging, thanks for calling it out!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.3-alpha.da8067.0<br/>@codecademy/gamut-icons@9.26.1-alpha.da8067.0<br/>@codecademy/gamut-kit@0.6.412-alpha.da8067.0<br/>@codecademy/styleguide@66.22.1-alpha.da8067.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6667107796ef835781bf3a5d--gamut-preview.netlify.app>https://6667107796ef835781bf3a5d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6667107796ef835781bf3a5d>Deploy Logs</a></p>

**Pull request merged**
