### PR TITLE
feat(Icons): add UnlockIcon

### PR DESCRIPTION
**Pull request by xendke**
### Overview

Adds UnlockIcon

### PR Checklist

- [x] Related to designs: [FIGMA](https://www.figma.com/design/h8zkWfeYI5IQcTIrX6GSB2/Execution---Opening-first-module-of-paid-courses?node-id=270-104967&node-type=frame&m=dev)
- [x] Related to JIRA ticket: [JIRA](https://skillsoftdev.atlassian.net/browse/FLOW-924?atlOrigin=eyJpIjoiY2JjM2YzYjY1MGFlNDVhYmJmMmRmYjM5M2JjYmRmOTEiLCJwIjoiaiJ9)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [PR Link](https://github.com/codecademy-engineering/mono/pull/8011 'PR link')  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-8011 'Portal Env')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.3-alpha.7cf0ca.0<br/>@codecademy/gamut-icons@9.31.2-alpha.7cf0ca.0<br/>@codecademy/gamut-kit@0.6.447-alpha.7cf0ca.0<br/>@codecademy/styleguide@68.1.3-alpha.7cf0ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67058950caadfb35c8153167--gamut-preview.netlify.app>https://67058950caadfb35c8153167--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67058950caadfb35c8153167>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
maybe rename to UnlockIcon to match UnlockHeavyIcon? i don't feel strongly about it though

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.3-alpha.dad732.0<br/>@codecademy/gamut-icons@9.31.2-alpha.dad732.0<br/>@codecademy/gamut-kit@0.6.447-alpha.dad732.0<br/>@codecademy/styleguide@68.1.3-alpha.dad732.0<br/></pre>

**Pull request merged**
