### PR TITLE
fix(focusVisible): enable always for both native and polyfill

### PR DESCRIPTION
**Pull request by jrood**
### Overview

In [this commit](https://github.com/Codecademy/gamut/commit/ccfd943be6dd1a73aff2a4e021fbaf4e15d75c7a), Aaron Robb fixed an issue so that instead of replacing `:focus-visible` with `[data-focus-visible-added]` (used for polyfills) we use both. However, this fix was only enabled when `process.env.NODE_ENV === 'dev'`. This was exposed when we found the the LE was missing some `:focus-visible` gamut styles because it did not use said polyfill. (the outline on links did not match the hyper blue color)  We should always enable this fix so that we can continue using the polyfill but not be dependent on it.

As a bonus, this will make it easier to debug `:focus-visible` styles in chrome dev tools, since it will allow the `:hov -> :focus-visible` toggle to work properly. (the current behavior is deceiving, since checking focus-visible can seem like it's working because it will in some cases enable outlines states, but on closer inspection, those styles often come from the user-agent-styles and not from Gamut)
Screenshot 2023-06-07 at 10 57 27 AM

### PR Checklist

- [ ] ~Related to designs:~
- [x] Related to JIRA ticket: [REACH-2713]
- [x] I have run this code to verify it works
- [ ] ~This PR includes unit tests for the code change~
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Go to the storybook preview page for Anchor https://6480dcb2c17e9e334b0449f1--gamut-preview.netlify.app/?path=/docs/typography-anchor--anchor
2. Scroll down to "Code Playground" and inspect the anchor element with text "I am a cool link"
3. In chrome dev tools, click the `:hov -> :focus-visible` checkbox
4. Verify that the outline is the correct hyper-blue, and not the browser native sky-blue color.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35794)  | [Monolith Preview Env](https://pr-35794-monolith.dev-eks.codecademy.com/) |
| Portal       | [Monorepo PR](https://github.com/codecademy-engineering/mono/pull/2274)  | [Portal Preview Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2274)   |
|   | | [LE Preview Env](https://tayra.codecademy.com/workspaces/new?PR_ENV=le-pr-2274) 

[REACH-2713]: https://codecademy.atlassian.net/browse/REACH-2713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.3-alpha.c2f3a1.0<br/>@codecademy/gamut-illustrations@0.38.1-alpha.c2f3a1.0<br/>@codecademy/gamut-kit@0.6.328-alpha.c2f3a1.0<br/>@codecademy/gamut-labs@35.15.2-alpha.c2f3a1.0<br/>@codecademy/gamut-patterns@0.9.7-alpha.c2f3a1.0<br/>@codecademy/gamut-styles@16.1.2-alpha.c2f3a1.0<br/>@codecademy/gamut-tests@5.0.6-alpha.c2f3a1.0<br/>@codecademy/gamut@55.1.7-alpha.c2f3a1.0<br/>@codecademy/markdown-overrides@0.10.6-alpha.c2f3a1.0<br/>@codecademy/monaco@0.7.33-alpha.c2f3a1.0<br/>@codecademy/styleguide@66.1.10-alpha.c2f3a1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6480dcb2c17e9e334b0449f1--gamut-preview.netlify.app>https://6480dcb2c17e9e334b0449f1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6480dcb2c17e9e334b0449f1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.4-alpha.c4ff54.0<br/>@codecademy/gamut-illustrations@0.38.1-alpha.c4ff54.0<br/>@codecademy/gamut-kit@0.6.330-alpha.c4ff54.0<br/>@codecademy/gamut-labs@35.15.3-alpha.c4ff54.0<br/>@codecademy/gamut-patterns@0.9.7-alpha.c4ff54.0<br/>@codecademy/gamut-styles@16.1.2-alpha.c4ff54.0<br/>@codecademy/gamut-tests@5.0.6-alpha.c4ff54.0<br/>@codecademy/gamut@55.1.8-alpha.c4ff54.0<br/>@codecademy/markdown-overrides@0.10.6-alpha.c4ff54.0<br/>@codecademy/monaco@0.7.34-alpha.c4ff54.0<br/>@codecademy/styleguide@66.1.12-alpha.c4ff54.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64961a7dceef0907a71e00d6--gamut-preview.netlify.app>https://64961a7dceef0907a71e00d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64961a7dceef0907a71e00d6>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
i think this was originally implemented this way before `focus-visible` was widely supported. it seems to be now so should be safe to 🚢

**Review by jakemhiller — APPROVED** [review]
Lgtm, we're so close to not needing this at all

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.4-alpha.caa36f.0<br/>@codecademy/gamut-illustrations@0.38.1-alpha.caa36f.0<br/>@codecademy/gamut-kit@0.6.330-alpha.caa36f.0<br/>@codecademy/gamut-labs@35.15.3-alpha.caa36f.0<br/>@codecademy/gamut-patterns@0.9.7-alpha.caa36f.0<br/>@codecademy/gamut-styles@16.1.2-alpha.caa36f.0<br/>@codecademy/gamut-tests@5.0.6-alpha.caa36f.0<br/>@codecademy/gamut@55.1.8-alpha.caa36f.0<br/>@codecademy/markdown-overrides@0.10.6-alpha.caa36f.0<br/>@codecademy/monaco@0.7.34-alpha.caa36f.0<br/>@codecademy/styleguide@66.1.12-alpha.caa36f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64a5c1612e6717206a890cb9--gamut-preview.netlify.app>https://64a5c1612e6717206a890cb9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64a5c1612e6717206a890cb9>Deploy Logs</a></p>

**Pull request merged**
