### PR TITLE
chore(gamut-labs): move stories to new Brand Labs category

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Moves all relevant stories to the new Brand Labs category (re-org chart [here](https://www.notion.so/codecademy/gamut-labs-audit-d08a310c532b4ec880819ea1eb342e7d))

Note these are only storybook changes, I still need to audit if all of these are in the 'gamut-labs' package and move them accordingly. 

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: web-1879
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

^ not relevant, storybook-only change ^

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.6-alpha.de5d0a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://626ffc28276ce25ffc2cfaeb--gamut-preview.netlify.app>https://626ffc28276ce25ffc2cfaeb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/626ffc28276ce25ffc2cfaeb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62700294a152cf5d10375da6--gamut-preview.netlify.app>https://62700294a152cf5d10375da6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62700294a152cf5d10375da6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.7-alpha.973e4a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://627017b1909d1e049767f57e--gamut-preview.netlify.app>https://627017b1909d1e049767f57e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/627017b1909d1e049767f57e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.7-alpha.ccccd1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62701f683d03b01069290931--gamut-preview.netlify.app>https://62701f683d03b01069290931--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62701f683d03b01069290931>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.7-alpha.2218fb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6270273afc831615b4b8f722--gamut-preview.netlify.app>https://6270273afc831615b4b8f722--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6270273afc831615b4b8f722>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
🌟 🚀

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.7-alpha.4f2f8d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://627134b59cb58e02e7e2a7ce--gamut-preview.netlify.app>https://627134b59cb58e02e7e2a7ce--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/627134b59cb58e02e7e2a7ce>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.7-alpha.9d7cbe.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6271724a5da6d70714733f2e--gamut-preview.netlify.app>https://6271724a5da6d70714733f2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6271724a5da6d70714733f2e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.8-alpha.92be1c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6271987f565c13069784a91e--gamut-preview.netlify.app>https://6271987f565c13069784a91e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6271987f565c13069784a91e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@57.0.9-alpha.8a57a6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6271ba6a63ba4304b9b78600--gamut-preview.netlify.app>https://6271ba6a63ba4304b9b78600--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6271ba6a63ba4304b9b78600>Deploy Logs</a></p>

**Pull request merged**
