### PR TITLE
fix(Button): button typing issues

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Correct Button types to not be overly permissive

### PR Checklist

- [x] Related to designs: no
- [x] Related to JIRA ticket: [GM-TBA]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Check that buttons still look the same in Storybook preview
2. Check out this branch locally
3. Uncomment the test code and see that the correct errors are reported by TS
4. Profit ✨ 

#### PR Links and Envs

* [Monorepo PR](https://github.com/codecademy-engineering/mono/pull/4445) (in progress)
* Monolith TBD

I will not be shipping this until the above are also reviewed + ready to ship

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.10.9-alpha.ba1140.0<br/>@codecademy/gamut-kit@0.6.373-alpha.ba1140.0<br/>@codecademy/styleguide@66.8.9-alpha.ba1140.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65970885ebd0962a56b14377--gamut-preview.netlify.app>https://65970885ebd0962a56b14377--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65970885ebd0962a56b14377>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.10.12-alpha.e59023.0<br/>@codecademy/gamut-kit@0.6.376-alpha.e59023.0<br/>@codecademy/styleguide@66.9.2-alpha.e59023.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65a82b12271d200a9dd6e51c--gamut-preview.netlify.app>https://65a82b12271d200a9dd6e51c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65a82b12271d200a9dd6e51c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.3d7956.0<br/>@codecademy/gamut-kit@0.6.378-alpha.3d7956.0<br/>@codecademy/styleguide@66.10.1-alpha.3d7956.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65b7e9af5ced50309d788419--gamut-preview.netlify.app>https://65b7e9af5ced50309d788419--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65b7e9af5ced50309d788419>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65b7f37b1e675b36cd7ef392--gamut-preview.netlify.app>https://65b7f37b1e675b36cd7ef392--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65b7f37b1e675b36cd7ef392>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.77a6d7.0<br/>@codecademy/gamut-kit@0.6.378-alpha.77a6d7.0<br/>@codecademy/styleguide@66.10.1-alpha.77a6d7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65b81739d71030522cfe2184--gamut-preview.netlify.app>https://65b81739d71030522cfe2184--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65b81739d71030522cfe2184>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.af84c8.0<br/>@codecademy/gamut-kit@0.6.378-alpha.af84c8.0<br/>@codecademy/styleguide@66.10.1-alpha.af84c8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65b81f99c6c2f85597bb129e--gamut-preview.netlify.app>https://65b81f99c6c2f85597bb129e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65b81f99c6c2f85597bb129e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.1e4237.0<br/>@codecademy/gamut-kit@0.6.378-alpha.1e4237.0<br/>@codecademy/styleguide@66.10.1-alpha.1e4237.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65bac6842ceb552f05aa5eb1--gamut-preview.netlify.app>https://65bac6842ceb552f05aa5eb1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65bac6842ceb552f05aa5eb1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65bacdb1016b2e32a52e85db--gamut-preview.netlify.app>https://65bacdb1016b2e32a52e85db--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65bacdb1016b2e32a52e85db>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.8ebd73.0<br/>@codecademy/gamut-kit@0.6.378-alpha.8ebd73.0<br/>@codecademy/styleguide@66.10.1-alpha.8ebd73.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65bbcc8b2a670300731ecc42--gamut-preview.netlify.app>https://65bbcc8b2a670300731ecc42--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65bbcc8b2a670300731ecc42>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.91edb9.0<br/>@codecademy/gamut-kit@0.6.378-alpha.91edb9.0<br/>@codecademy/styleguide@66.10.1-alpha.91edb9.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
the changes look good! based on testing it out & the implementation PR this is a huge improvement in type safety! 🎊

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.1-alpha.a9073e.0<br/>@codecademy/gamut-kit@0.6.378-alpha.a9073e.0<br/>@codecademy/styleguide@66.10.1-alpha.a9073e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65bd11ced87cef0a84236d02--gamut-preview.netlify.app>https://65bd11ced87cef0a84236d02--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65bd11ced87cef0a84236d02>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.12.2-alpha.919fbd.0<br/>@codecademy/gamut-kit@0.6.379-alpha.919fbd.0<br/>@codecademy/styleguide@66.10.2-alpha.919fbd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65c3ec7cdf04a61df28cea48--gamut-preview.netlify.app>https://65c3ec7cdf04a61df28cea48--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65c3ec7cdf04a61df28cea48>Deploy Logs</a></p>

**Pull request merged**
