### PR TITLE
fix(SelectDropdown): fix remove + remove all  buttons + medium sizing change bug for `multiple` variant

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
Fixes accessibility issues:

* [[ 2.1.1] X buttons cannot be focused and not operated by the Keyboard.](https://codecademy.atlassian.net/browse/WEB-2153?atlOrigin=eyJpIjoiMzE1MTZkZWExZWUzNDg0Yjk2MTY1NDU0ZDZiNzM1NDMiLCJwIjoiaiJ9)
* [ [A] [4.1.2] Remove button is announced with [Object Object] button instead of selected member/group name.](https://codecademy.atlassian.net/browse/WEB-2154?atlOrigin=eyJpIjoiYTI5ODQwMGNlYWM0NDdjNWJlZmE1OWI1NDBmNzc1OGQiLCJwIjoiaiJ9)

Also fixes a sizing change bug on the `medium` SelectDropdown variant

### PR Checklist

- [x] Related to JIRA ticket: [WEB-2153, WEB-2154]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Navigate to SelectDropdown -> multi variant
2. Select a bunch of options
3. You should be able to navigate through the Remove X Buttons on all selected options and the Remove All X using the arrow keys, and remove them using the `Enter` button 
4. You should be able to do the same on VoiceOver (cmd + f5)
5. When items are selected + tabbing through selected items with CONTROL + OPTION + ARROW KEY, the proper "Remove OPTION" test should be read by VoiceOver

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33284)  | [Monolith Env](https://pr-33284-monolith.dev-eks.codecademy.com/) |
| Mono       | [Monorepo PR](https://github.com/codecademy-engineering/mono/pull/510)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-510)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.220-alpha.967041.0<br/>@codecademy/gamut-labs@33.6.11-alpha.967041.0<br/>@codecademy/gamut@51.1.1-alpha.967041.0<br/>@codecademy/monaco@0.6.98-alpha.967041.0<br/>@codecademy/styleguide@62.0.5-alpha.967041.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6359aa33c99b3335f1d0cbaf--gamut-preview.netlify.app>https://6359aa33c99b3335f1d0cbaf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6359aa33c99b3335f1d0cbaf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.220-alpha.743799.0<br/>@codecademy/gamut-labs@33.6.11-alpha.743799.0<br/>@codecademy/gamut@51.1.1-alpha.743799.0<br/>@codecademy/monaco@0.6.98-alpha.743799.0<br/>@codecademy/styleguide@62.0.5-alpha.743799.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://636011709481441108c034ab--gamut-preview.netlify.app>https://636011709481441108c034ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/636011709481441108c034ab>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.221-alpha.cd92bc.0<br/>@codecademy/gamut-labs@33.6.12-alpha.cd92bc.0<br/>@codecademy/gamut@51.1.2-alpha.cd92bc.0<br/>@codecademy/monaco@0.6.99-alpha.cd92bc.0<br/>@codecademy/styleguide@62.0.6-alpha.cd92bc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63601eb90ccda21e0a46bc35--gamut-preview.netlify.app>https://63601eb90ccda21e0a46bc35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63601eb90ccda21e0a46bc35>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.1-alpha.8ca95e.0<br/>@codecademy/gamut-illustrations@0.32.3-alpha.8ca95e.0<br/>@codecademy/gamut-kit@0.6.221-alpha.8ca95e.0<br/>@codecademy/gamut-labs@33.6.12-alpha.8ca95e.0<br/>@codecademy/gamut-patterns@0.8.16-alpha.8ca95e.0<br/>@codecademy/gamut-styles@14.1.2-alpha.8ca95e.0<br/>@codecademy/gamut-tests@4.0.15-alpha.8ca95e.0<br/>@codecademy/gamut@51.1.2-alpha.8ca95e.0<br/>@codecademy/markdown-overrides@0.9.13-alpha.8ca95e.0<br/>@codecademy/monaco@0.6.99-alpha.8ca95e.0<br/>@codecademy/styleguide@62.0.6-alpha.8ca95e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://636025b014a48b25262e9e25--gamut-preview.netlify.app>https://636025b014a48b25262e9e25--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/636025b014a48b25262e9e25>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.222-alpha.9e5bc9.0<br/>@codecademy/gamut-labs@33.6.13-alpha.9e5bc9.0<br/>@codecademy/gamut@51.1.3-alpha.9e5bc9.0<br/>@codecademy/monaco@0.6.100-alpha.9e5bc9.0<br/>@codecademy/styleguide@62.0.7-alpha.9e5bc9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6360331aa81e9f30ee87eeae--gamut-preview.netlify.app>https://6360331aa81e9f30ee87eeae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6360331aa81e9f30ee87eeae>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.223-alpha.570fc7.0<br/>@codecademy/gamut-labs@33.6.14-alpha.570fc7.0<br/>@codecademy/gamut@51.2.1-alpha.570fc7.0<br/>@codecademy/monaco@0.6.101-alpha.570fc7.0<br/>@codecademy/styleguide@62.1.1-alpha.570fc7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63615c1ebe50ef27bedf5549--gamut-preview.netlify.app>https://63615c1ebe50ef27bedf5549--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63615c1ebe50ef27bedf5549>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.224-alpha.881951.0<br/>@codecademy/gamut-labs@33.6.15-alpha.881951.0<br/>@codecademy/gamut@51.2.2-alpha.881951.0<br/>@codecademy/monaco@0.6.102-alpha.881951.0<br/>@codecademy/styleguide@62.1.2-alpha.881951.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63616b8c8e0a6035b16cea0c--gamut-preview.netlify.app>https://63616b8c8e0a6035b16cea0c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63616b8c8e0a6035b16cea0c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.224-alpha.22b67c.0<br/>@codecademy/gamut-labs@33.6.15-alpha.22b67c.0<br/>@codecademy/gamut@51.2.2-alpha.22b67c.0<br/>@codecademy/monaco@0.6.102-alpha.22b67c.0<br/>@codecademy/styleguide@62.1.2-alpha.22b67c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6361710b6c5ec0368ae7abb8--gamut-preview.netlify.app>https://6361710b6c5ec0368ae7abb8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6361710b6c5ec0368ae7abb8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.224-alpha.7ecda4.0<br/>@codecademy/gamut-labs@33.6.15-alpha.7ecda4.0<br/>@codecademy/gamut@51.2.2-alpha.7ecda4.0<br/>@codecademy/monaco@0.6.102-alpha.7ecda4.0<br/>@codecademy/styleguide@62.1.2-alpha.7ecda4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6361817a7e1cfc4937687c38--gamut-preview.netlify.app>https://6361817a7e1cfc4937687c38--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6361817a7e1cfc4937687c38>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.ed6a95.0<br/>@codecademy/gamut-labs@33.6.17-alpha.ed6a95.0<br/>@codecademy/gamut@51.3.2-alpha.ed6a95.0<br/>@codecademy/monaco@0.6.104-alpha.ed6a95.0<br/>@codecademy/styleguide@62.2.2-alpha.ed6a95.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.1af10a.0<br/>@codecademy/gamut-labs@33.6.17-alpha.1af10a.0<br/>@codecademy/gamut@51.3.2-alpha.1af10a.0<br/>@codecademy/monaco@0.6.104-alpha.1af10a.0<br/>@codecademy/styleguide@62.2.2-alpha.1af10a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://636400797eb25c17531e95ad--gamut-preview.netlify.app>https://636400797eb25c17531e95ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/636400797eb25c17531e95ad>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.0b91ab.0<br/>@codecademy/gamut-labs@33.6.17-alpha.0b91ab.0<br/>@codecademy/gamut@51.3.2-alpha.0b91ab.0<br/>@codecademy/monaco@0.6.104-alpha.0b91ab.0<br/>@codecademy/styleguide@62.2.2-alpha.0b91ab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6364096de2391800b2ec918e--gamut-preview.netlify.app>https://6364096de2391800b2ec918e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6364096de2391800b2ec918e>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM! Nice work

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.236-alpha.f0a276.0<br/>@codecademy/gamut-labs@33.8.5-alpha.f0a276.0<br/>@codecademy/gamut@51.4.4-alpha.f0a276.0<br/>@codecademy/monaco@0.6.108-alpha.f0a276.0<br/>@codecademy/styleguide@62.5.5-alpha.f0a276.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://637ba60d6be9ca759cc82b3f--gamut-preview.netlify.app>https://637ba60d6be9ca759cc82b3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/637ba60d6be9ca759cc82b3f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.237-alpha.25b395.0<br/>@codecademy/gamut-labs@33.8.6-alpha.25b395.0<br/>@codecademy/gamut@51.4.5-alpha.25b395.0<br/>@codecademy/monaco@0.6.109-alpha.25b395.0<br/>@codecademy/styleguide@62.5.6-alpha.25b395.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63861e9da6c7661fc3510243--gamut-preview.netlify.app>https://63861e9da6c7661fc3510243--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63861e9da6c7661fc3510243>Deploy Logs</a></p>

**Pull request merged**
