### PR TITLE
feat(Illustration): add block illustration

### PR DESCRIPTION
**Pull request by sooinc**
### Overview

- add Block illustration

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: Egg-2217
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.22.3-alpha.6ea344.0<br/>@codecademy/gamut-kit@0.6.68-alpha.6ea344.0<br/>@codecademy/gamut-labs@29.3.9-alpha.6ea344.0<br/>@codecademy/gamut@44.7.2-alpha.6ea344.0<br/>@codecademy/monaco@0.6.18-alpha.6ea344.0<br/>@codecademy/styleguide@54.3.9-alpha.6ea344.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://621e4e245b5681539f9bfa60--gamut-preview.netlify.app>https://621e4e245b5681539f9bfa60--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/621e4e245b5681539f9bfa60>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.22.3-alpha.db0969.0<br/>@codecademy/gamut-kit@0.6.68-alpha.db0969.0<br/>@codecademy/gamut-labs@29.3.9-alpha.db0969.0<br/>@codecademy/gamut@44.7.2-alpha.db0969.0<br/>@codecademy/monaco@0.6.18-alpha.db0969.0<br/>@codecademy/styleguide@54.3.9-alpha.db0969.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://621e7aa17b73100c6a0f2257--gamut-preview.netlify.app>https://621e7aa17b73100c6a0f2257--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/621e7aa17b73100c6a0f2257>Deploy Logs</a></p>

**Comment by sooinc** [comment]
Here is the accompanying monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/29695

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6226428fff2f041b25a59ffb--gamut-preview.netlify.app>https://6226428fff2f041b25a59ffb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6226428fff2f041b25a59ffb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.23.1-alpha.a1a508.0<br/>@codecademy/gamut-kit@0.6.72-alpha.a1a508.0<br/>@codecademy/gamut-labs@30.1.1-alpha.a1a508.0<br/>@codecademy/gamut@45.0.2-alpha.a1a508.0<br/>@codecademy/monaco@0.6.20-alpha.a1a508.0<br/>@codecademy/styleguide@55.0.4-alpha.a1a508.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6227c34e6a75c00c0e20f59d--gamut-preview.netlify.app>https://6227c34e6a75c00c0e20f59d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6227c34e6a75c00c0e20f59d>Deploy Logs</a></p>

**Pull request merged**
