### PR TITLE
fix(AppHeaderCatalogSection): hot fix for CI failures

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

This is purely meant as a hot-fix for CI failures -- this catalog dropdown will be fully navigable by keyboard with an upcoming disco ticket 

monolith [here](https://github.com/codecademy-engineering/Codecademy/pull/30373)
portal [here](https://github.com/codecademy-engineering/portal-app/pull/1847)
### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: disc-545
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.100-alpha.71200d.0<br/>@codecademy/gamut-labs@31.5.0-alpha.71200d.0<br/>@codecademy/styleguide@56.3.0-alpha.71200d.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.100-alpha.b641b3.0<br/>@codecademy/gamut-labs@31.5.0-alpha.b641b3.0<br/>@codecademy/styleguide@56.3.0-alpha.b641b3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62573ad400b700205eb29c30--gamut-preview.netlify.app>https://62573ad400b700205eb29c30--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62573ad400b700205eb29c30>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.100-alpha.d78294.0<br/>@codecademy/gamut-labs@31.5.0-alpha.d78294.0<br/>@codecademy/styleguide@56.3.0-alpha.d78294.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6257420cf0387024e86e5c13--gamut-preview.netlify.app>https://6257420cf0387024e86e5c13--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6257420cf0387024e86e5c13>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.100-alpha.cf1b30.0<br/>@codecademy/gamut-labs@31.5.0-alpha.cf1b30.0<br/>@codecademy/styleguide@56.3.0-alpha.cf1b30.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6258581b70117e16b827e05a--gamut-preview.netlify.app>https://6258581b70117e16b827e05a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6258581b70117e16b827e05a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.100-alpha.2a98f9.0<br/>@codecademy/gamut-labs@31.5.0-alpha.2a98f9.0<br/>@codecademy/styleguide@56.3.0-alpha.2a98f9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6258711bdb5b6b008a0dd963--gamut-preview.netlify.app>https://6258711bdb5b6b008a0dd963--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6258711bdb5b6b008a0dd963>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.102-alpha.a4683c.0<br/>@codecademy/gamut-labs@31.6.1-alpha.a4683c.0<br/>@codecademy/styleguide@56.4.1-alpha.a4683c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://625881ee9df03311345b7ae3--gamut-preview.netlify.app>https://625881ee9df03311345b7ae3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/625881ee9df03311345b7ae3>Deploy Logs</a></p>

**Review by zippyzow — APPROVED** [review]

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
