### PR TITLE
fix: update PasuableImage button to announce it's label change

### PR DESCRIPTION
**Pull request by vonbarown**
### Overview

Fixing a A11y bug that appeared if a user using voiceover toggle the image using the ``space bar`` or the ``enter`` key.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EN-1747](https://codecademy.atlassian.net/browse/EN-1747)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31093)  | [Monolith Env](https://pr-31093-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2102)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2102)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.139-alpha.f7726b.0<br/>@codecademy/gamut-labs@32.0.2-alpha.f7726b.0<br/>@codecademy/styleguide@58.0.2-alpha.f7726b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a270c66f74432066e7c229--gamut-preview.netlify.app>https://62a270c66f74432066e7c229--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a270c66f74432066e7c229>Deploy Logs</a></p>

**Comment by vonbarown** [comment]
> Pagination

This makes a lot of sense and easier to follow, will make the updates

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.139-alpha.d62d46.0<br/>@codecademy/gamut-labs@32.0.2-alpha.d62d46.0<br/>@codecademy/styleguide@58.0.2-alpha.d62d46.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.140-alpha.024013.0<br/>@codecademy/gamut-labs@32.0.3-alpha.024013.0<br/>@codecademy/styleguide@58.0.3-alpha.024013.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a75f5226477600a4695f2c--gamut-preview.netlify.app>https://62a75f5226477600a4695f2c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a75f5226477600a4695f2c>Deploy Logs</a></p>

**Pull request merged**
