### PR TITLE
fix(Alert): Update alert to be based on component width

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Updates alert to be based on component width not screen size, so the button stacks when the alert is xs or smaller

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [GM-868]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. View the Alert story here https://6706b76391cf1c0f2ee9213f--gamut-preview.netlify.app/?path=/docs/molecules-alert--usage-guidelines#small-widths
2. Confirm the alert still looks as expected, but the button stacks when the component width is xs or smaller

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/38632)  | [Monolith Env](https://pr-38632-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/8085)  | [Portal Env](https://tengu.codecademy.com/admin?PR_ENV=admin-pr-8085)   |

[GM-868]: https://skillsoftdev.atlassian.net/browse/GM-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.1-alpha.4c9010.0<br/>@codecademy/gamut-kit@0.6.442-alpha.4c9010.0<br/>@codecademy/styleguide@68.0.3-alpha.4c9010.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66fda0b5f914aa7be672ebc8--gamut-preview.netlify.app>https://66fda0b5f914aa7be672ebc8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66fda0b5f914aa7be672ebc8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66fdb46a537e8d8fe7f92cad--gamut-preview.netlify.app>https://66fdb46a537e8d8fe7f92cad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66fdb46a537e8d8fe7f92cad>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.1-alpha.f89e39.0<br/>@codecademy/gamut-kit@0.6.442-alpha.f89e39.0<br/>@codecademy/styleguide@68.0.3-alpha.f89e39.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66feba3305f377bbb1f5d081--gamut-preview.netlify.app>https://66feba3305f377bbb1f5d081--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66feba3305f377bbb1f5d081>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.1-alpha.1e3d65.0<br/>@codecademy/gamut-kit@0.6.445-alpha.1e3d65.0<br/>@codecademy/styleguide@68.1.1-alpha.1e3d65.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66feed3990c7d9115d52f825--gamut-preview.netlify.app>https://66feed3990c7d9115d52f825--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66feed3990c7d9115d52f825>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.1-alpha.1e3d65.0<br/>@codecademy/gamut-kit@0.6.445-alpha.1e3d65.0<br/>@codecademy/styleguide@68.1.1-alpha.1e3d65.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.1-alpha.f89e39.0<br/>@codecademy/gamut-kit@0.6.442-alpha.f89e39.0<br/>@codecademy/styleguide@68.0.3-alpha.f89e39.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.1-alpha.1e3d65.0<br/>@codecademy/gamut-kit@0.6.445-alpha.1e3d65.0<br/>@codecademy/styleguide@68.1.1-alpha.1e3d65.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.3-alpha.268834.0<br/>@codecademy/gamut-kit@0.6.447-alpha.268834.0<br/>@codecademy/styleguide@68.1.3-alpha.268834.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67069c45729dff82f1103ac4--gamut-preview.netlify.app>https://67069c45729dff82f1103ac4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67069c45729dff82f1103ac4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.3-alpha.d0ad66.0<br/>@codecademy/gamut-kit@0.6.447-alpha.d0ad66.0<br/>@codecademy/styleguide@68.1.3-alpha.d0ad66.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6706b76391cf1c0f2ee9213f--gamut-preview.netlify.app>https://6706b76391cf1c0f2ee9213f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6706b76391cf1c0f2ee9213f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://670834c16345d06d6445a3c6--gamut-preview.netlify.app>https://670834c16345d06d6445a3c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/670834c16345d06d6445a3c6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.3-alpha.33b159.0<br/>@codecademy/gamut-kit@0.6.447-alpha.33b159.0<br/>@codecademy/styleguide@68.1.3-alpha.33b159.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
image

this is a preexisting bug, but do the alerts have a max width somewhere that stop them at this width or is it a storybook thing?

either way, looks awesome!!!! 🔥

**Comment by aresnik11** [comment]
> image
> 
> this is a preexisting bug, but do the alerts have a max width somewhere that stop them at this width or is it a storybook thing?
> 
> either way, looks awesome!!!! 🔥

@dreamwasp this has come up before and is preexisting so lets handle it separately

**Pull request merged**
