### PR TITLE
fix: DataGrid respects `emptyMessage` props now

### PR DESCRIPTION
**Pull request by MattSchiller**
### Overview

I wanted to use `DataGrid`, but I didn't care for its defautl empty view. So tada, now we just marshall it down.

DataGrid will marshal the `emptyMessage` prop instead of ignoring it now.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.57-alpha.19f3ac.0<br/>@codecademy/gamut-labs@29.2.8-alpha.19f3ac.0<br/>@codecademy/gamut@44.3.3-alpha.19f3ac.0<br/>@codecademy/monaco@0.6.10-alpha.19f3ac.0<br/>@codecademy/styleguide@54.1.3-alpha.19f3ac.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fd7b0f93100811428bf93b--gamut-preview.netlify.app>https://61fd7b0f93100811428bf93b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fd7b0f93100811428bf93b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.58-alpha.1d6ead.0<br/>@codecademy/gamut-labs@29.2.9-alpha.1d6ead.0<br/>@codecademy/gamut@44.5.0-alpha.1d6ead.0<br/>@codecademy/monaco@0.6.11-alpha.1d6ead.0<br/>@codecademy/styleguide@54.2.1-alpha.1d6ead.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fd9a3139dfd3009f666359--gamut-preview.netlify.app>https://61fd9a3139dfd3009f666359--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fd9a3139dfd3009f666359>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.60-alpha.494368.0<br/>@codecademy/gamut-labs@29.3.1-alpha.494368.0<br/>@codecademy/gamut@44.5.2-alpha.494368.0<br/>@codecademy/monaco@0.6.13-alpha.494368.0<br/>@codecademy/styleguide@54.3.1-alpha.494368.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6202c7eca4cb4a515cd6603b--gamut-preview.netlify.app>https://6202c7eca4cb4a515cd6603b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6202c7eca4cb4a515cd6603b>Deploy Logs</a></p>

**Pull request merged**
