### PR TITLE
fix(AppHeader/SearchPane):  Axe - Popular Searches link are identified as button

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

Test io Link: http://codecademy.test.io/products/9763/test_cycles/68776/bugs/1434395

1. With VoiceOver, go to https://www.codecademy.com/catalog
2. Tab to search press Enter
3. Tab to "Data science"
4. The "popular searches" should now be read as links and not buttons. 

_Initially I thought to do this with an `Anchor` but that altered the styling and messed with the `onClick` logic. Using `role` seems like the best solution for this._

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DISC-578
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31040)  | [Monolith Env](https://pr-31040-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2085)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2085)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629fa3cfd8ea5009c2ca88e6--gamut-preview.netlify.app>https://629fa3cfd8ea5009c2ca88e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629fa3cfd8ea5009c2ca88e6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.a40946.0<br/>@codecademy/gamut-labs@31.15.5-alpha.a40946.0<br/>@codecademy/styleguide@57.7.5-alpha.a40946.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629fc0234ae5b621fae27b82--gamut-preview.netlify.app>https://629fc0234ae5b621fae27b82--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629fc0234ae5b621fae27b82>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.f37248.0<br/>@codecademy/gamut-labs@31.15.5-alpha.f37248.0<br/>@codecademy/styleguide@57.7.5-alpha.f37248.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a09784326fe20e1eb691f4--gamut-preview.netlify.app>https://62a09784326fe20e1eb691f4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a09784326fe20e1eb691f4>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
Makes sense to me and confirmed voice over reads as a link instead of a button

**Pull request merged**
