### PR TITLE
feat(Modal): change overlay shroud opacity and make modals use dark by default 

### PR DESCRIPTION
**Pull request by BandanaKM**
### Overview

Screen Shot 2022-08-10 at 1 31 50 PM

This change:

- Modifies the Overlay's shroud prop to have color `shadow-black-heavy` as specified in the mocks (shown in the pic above)
- Stephen mentioned that we want all overlays to have this opacity

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=2449%3A3770
- [x] Related to JIRA ticket: [WEB-2060](https://codecademy.atlassian.net/browse/WEB-2060)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.174-alpha.e0ebde.0<br/>@codecademy/gamut-labs@33.0.10-alpha.e0ebde.0<br/>@codecademy/gamut@50.1.2-alpha.e0ebde.0<br/>@codecademy/monaco@0.6.68-alpha.e0ebde.0<br/>@codecademy/styleguide@61.1.4-alpha.e0ebde.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62f3ecec738336198078428c--gamut-preview.netlify.app>https://62f3ecec738336198078428c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62f3ecec738336198078428c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.174-alpha.5d09f7.0<br/>@codecademy/gamut-labs@33.0.10-alpha.5d09f7.0<br/>@codecademy/gamut@50.1.2-alpha.5d09f7.0<br/>@codecademy/monaco@0.6.68-alpha.5d09f7.0<br/>@codecademy/styleguide@61.1.4-alpha.5d09f7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62f4231f17e12823adfad6c1--gamut-preview.netlify.app>https://62f4231f17e12823adfad6c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62f4231f17e12823adfad6c1>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
this all looks good to me! could you add the alpha pkg to a monolith  PR just so i can double check behavior there?

**Comment by BandanaKM** [comment]
> this all looks good to me! could you add the alpha pkg to a monolith PR just so i can double check behavior there?

yes!

**Review by dreamwasp — APPROVED** [review]
perfect!

**Review by aresnik11 — COMMENTED** [review]
asked @songstephen in slack about if we should update the pattern backgrounds to be lighter since they're not super visible on the dark shroud and they agreed that they should be white. slack here: https://codecademy.slack.com/archives/C02CPQFEFGV/p1660757282185779 also tagging @dreamwasp since bana is out next week (as am i)

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.e376eb.0<br/>@codecademy/gamut-icons@7.8.0-alpha.e376eb.0<br/>@codecademy/gamut-illustrations@0.32.0-alpha.e376eb.0<br/>@codecademy/gamut-kit@0.6.192-alpha.e376eb.0<br/>@codecademy/gamut-labs@33.2.0-alpha.e376eb.0<br/>@codecademy/gamut-patterns@0.8.14-alpha.e376eb.0<br/>@codecademy/gamut-styles@14.0.5-alpha.e376eb.0<br/>@codecademy/gamut-tests@4.0.13-alpha.e376eb.0<br/>@codecademy/gamut@50.6.0-alpha.e376eb.0<br/>@codecademy/macros@3.0.3-alpha.e376eb.0<br/>@codecademy/markdown-overrides@0.9.11-alpha.e376eb.0<br/>@codecademy/monaco@0.6.82-alpha.e376eb.0<br/>@codecademy/styleguide@61.4.0-alpha.e376eb.0<br/>@codecademy/variance@0.20.4-alpha.e376eb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630cda1394f0284db30aa540--gamut-preview.netlify.app>https://630cda1394f0284db30aa540--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630cda1394f0284db30aa540>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630d207be7486b21817607b8--gamut-preview.netlify.app>https://630d207be7486b21817607b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630d207be7486b21817607b8>Deploy Logs</a></p>

**Pull request merged**
