### PR TITLE
feat!: bumped React to 17

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Bumps React and related core packages to React 17 / latest.

I ran `npx yarn-deduplicate` too. Helped getting `@types/react` & co. down to one version each.

Downstream PRs:

* https://github.com/codecademy-engineering/author/pull/1805
* https://github.com/codecademy-engineering/Codecademy/pull/28741
* https://github.com/codecademy-engineering/portal-app/pull/1231

### Notes

I had to add the `as` casts to the `icon-template.js` files that we supply as the templates for svgr. You can see in the [earlier compile failures](https://app.circleci.com/pipelines/github/codecademy-engineering/portal-app/7360/workflows/d25c20e9-e59e-4812-9f34-fd30095a51f9/jobs/74541) that `fr` is marked as required. Bizarre. [[Vaguely related SO link](https://stackoverflow.com/questions/69973452/iconify-react-with-eva-icons-showing-typescript-error)] 

```
src/components/ViewAllButton/ViewAllButton.tsx:33:10 - error TS2741: Property 'fr' is missing in type '{ "aria-hidden": true; }' but required in type 'Pick<GamutIconProps, "string" | "id" | "onError" | "title" | "type" | "key" | "path" | "target" | "href" | "version" | "name" | "p" | "style" | "clipPath" | "filter" | ... 538 more ... | "titleId">'.

33         <MiniArrowRightIcon aria-hidden />
            ~~~~~~~~~~~~~~~~~~
```

I'd wanted to use a `:` type annotation like a normal TypeScripter but: https://github.com/gregberge/svgr/issues/658

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: WEB-1226
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.618f3b.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.618f3b.0<br/>@codecademy/gamut-kit@0.6.37-alpha.618f3b.0<br/>@codecademy/gamut-labs@29.0.0-alpha.618f3b.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.618f3b.0<br/>@codecademy/gamut-styles@13.0.0-alpha.618f3b.0<br/>@codecademy/gamut-tests@4.0.0-alpha.618f3b.0<br/>@codecademy/gamut@43.0.0-alpha.618f3b.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.618f3b.0<br/>@codecademy/monaco@1.0.0-alpha.618f3b.0<br/>@codecademy/styleguide@53.0.0-alpha.618f3b.0<br/>@codecademy/variance@1.0.0-alpha.618f3b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0c675cc864e2d67876b4c--gamut-preview.netlify.app>https://61c0c675cc864e2d67876b4c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0c675cc864e2d67876b4c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.5ff03c.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.5ff03c.0<br/>@codecademy/gamut-kit@0.6.37-alpha.5ff03c.0<br/>@codecademy/gamut-labs@29.0.0-alpha.5ff03c.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.5ff03c.0<br/>@codecademy/gamut-styles@13.0.0-alpha.5ff03c.0<br/>@codecademy/gamut-tests@4.0.0-alpha.5ff03c.0<br/>@codecademy/gamut@43.0.0-alpha.5ff03c.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.5ff03c.0<br/>@codecademy/monaco@1.0.0-alpha.5ff03c.0<br/>@codecademy/styleguide@53.0.0-alpha.5ff03c.0<br/>@codecademy/variance@1.0.0-alpha.5ff03c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0d7ba22ba4d3c86a6227c--gamut-preview.netlify.app>https://61c0d7ba22ba4d3c86a6227c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0d7ba22ba4d3c86a6227c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.97744b.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.97744b.0<br/>@codecademy/gamut-kit@0.6.38-alpha.97744b.0<br/>@codecademy/gamut-labs@29.0.0-alpha.97744b.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.97744b.0<br/>@codecademy/gamut-styles@13.0.0-alpha.97744b.0<br/>@codecademy/gamut-tests@4.0.0-alpha.97744b.0<br/>@codecademy/gamut@43.0.0-alpha.97744b.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.97744b.0<br/>@codecademy/monaco@1.0.0-alpha.97744b.0<br/>@codecademy/styleguide@53.0.0-alpha.97744b.0<br/>@codecademy/variance@1.0.0-alpha.97744b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c204d046859730c2feca6d--gamut-preview.netlify.app>https://61c204d046859730c2feca6d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c204d046859730c2feca6d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.0f9d49.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.0f9d49.0<br/>@codecademy/gamut-kit@0.6.38-alpha.0f9d49.0<br/>@codecademy/gamut-labs@29.0.0-alpha.0f9d49.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.0f9d49.0<br/>@codecademy/gamut-styles@13.0.0-alpha.0f9d49.0<br/>@codecademy/gamut-tests@4.0.0-alpha.0f9d49.0<br/>@codecademy/gamut@43.0.0-alpha.0f9d49.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.0f9d49.0<br/>@codecademy/monaco@1.0.0-alpha.0f9d49.0<br/>@codecademy/styleguide@53.0.0-alpha.0f9d49.0<br/>@codecademy/variance@1.0.0-alpha.0f9d49.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c20735b6d7c82cbd337bdb--gamut-preview.netlify.app>https://61c20735b6d7c82cbd337bdb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c20735b6d7c82cbd337bdb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.d04966.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.d04966.0<br/>@codecademy/gamut-kit@0.6.38-alpha.d04966.0<br/>@codecademy/gamut-labs@29.0.0-alpha.d04966.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.d04966.0<br/>@codecademy/gamut-styles@13.0.0-alpha.d04966.0<br/>@codecademy/gamut-tests@4.0.0-alpha.d04966.0<br/>@codecademy/gamut@43.0.0-alpha.d04966.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.d04966.0<br/>@codecademy/monaco@1.0.0-alpha.d04966.0<br/>@codecademy/styleguide@53.0.0-alpha.d04966.0<br/>@codecademy/variance@1.0.0-alpha.d04966.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c2381b2288bf6e432140d7--gamut-preview.netlify.app>https://61c2381b2288bf6e432140d7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c2381b2288bf6e432140d7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.760be3.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.760be3.0<br/>@codecademy/gamut-kit@0.6.38-alpha.760be3.0<br/>@codecademy/gamut-labs@29.0.0-alpha.760be3.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.760be3.0<br/>@codecademy/gamut-styles@13.0.0-alpha.760be3.0<br/>@codecademy/gamut-tests@4.0.0-alpha.760be3.0<br/>@codecademy/gamut@43.0.0-alpha.760be3.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.760be3.0<br/>@codecademy/monaco@1.0.0-alpha.760be3.0<br/>@codecademy/styleguide@53.0.0-alpha.760be3.0<br/>@codecademy/variance@1.0.0-alpha.760be3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c23d1641a71f71ba2c719a--gamut-preview.netlify.app>https://61c23d1641a71f71ba2c719a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c23d1641a71f71ba2c719a>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.f6cb5a.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.f6cb5a.0<br/>@codecademy/gamut-kit@0.6.42-alpha.f6cb5a.0<br/>@codecademy/gamut-labs@29.0.0-alpha.f6cb5a.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.f6cb5a.0<br/>@codecademy/gamut-styles@13.0.0-alpha.f6cb5a.0<br/>@codecademy/gamut-tests@4.0.0-alpha.f6cb5a.0<br/>@codecademy/gamut@44.0.0-alpha.f6cb5a.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.f6cb5a.0<br/>@codecademy/monaco@1.0.0-alpha.f6cb5a.0<br/>@codecademy/styleguide@54.0.0-alpha.f6cb5a.0<br/>@codecademy/variance@1.0.0-alpha.f6cb5a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e8453d2966d644a43d8409--gamut-preview.netlify.app>https://61e8453d2966d644a43d8409--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e8453d2966d644a43d8409>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.025bb0.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.025bb0.0<br/>@codecademy/gamut-kit@0.6.42-alpha.025bb0.0<br/>@codecademy/gamut-labs@29.0.0-alpha.025bb0.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.025bb0.0<br/>@codecademy/gamut-styles@13.0.0-alpha.025bb0.0<br/>@codecademy/gamut-tests@4.0.0-alpha.025bb0.0<br/>@codecademy/gamut@44.0.0-alpha.025bb0.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.025bb0.0<br/>@codecademy/monaco@1.0.0-alpha.025bb0.0<br/>@codecademy/styleguide@54.0.0-alpha.025bb0.0<br/>@codecademy/variance@1.0.0-alpha.025bb0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e85ac637b18460eed354c7--gamut-preview.netlify.app>https://61e85ac637b18460eed354c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e85ac637b18460eed354c7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.0.0-alpha.31b187.0<br/>@codecademy/gamut-illustrations@1.0.0-alpha.31b187.0<br/>@codecademy/gamut-kit@0.6.45-alpha.31b187.0<br/>@codecademy/gamut-labs@29.0.0-alpha.31b187.0<br/>@codecademy/gamut-patterns@1.0.0-alpha.31b187.0<br/>@codecademy/gamut-styles@13.0.0-alpha.31b187.0<br/>@codecademy/gamut-tests@4.0.0-alpha.31b187.0<br/>@codecademy/gamut@44.0.0-alpha.31b187.0<br/>@codecademy/markdown-overrides@1.0.0-alpha.31b187.0<br/>@codecademy/monaco@1.0.0-alpha.31b187.0<br/>@codecademy/styleguide@54.0.0-alpha.31b187.0<br/>@codecademy/variance@1.0.0-alpha.31b187.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61ef1587998e710914429d28--gamut-preview.netlify.app>https://61ef1587998e710914429d28--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61ef1587998e710914429d28>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
double-checked the usual suspects for breakage and all looks good to me !

**Pull request merged**
