### PR TITLE
feat(DataGrid): default empty loading state

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
adds a loading state for when the DataGrid has no rows[] (yet)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: gm-453
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.8-alpha.1caa62.0<br/>@codecademy/gamut-labs@28.0.3-alpha.1caa62.0<br/>@codecademy/gamut@40.0.1-alpha.1caa62.0<br/>@codecademy/monaco@0.5.6-alpha.1caa62.0<br/>@codecademy/styleguide@50.1.5-alpha.1caa62.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61843b02667c6a4e7b8f99c7--gamut-preview.netlify.app>https://61843b02667c6a4e7b8f99c7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61843b02667c6a4e7b8f99c7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.8-alpha.ab24f1.0<br/>@codecademy/gamut-labs@28.0.3-alpha.ab24f1.0<br/>@codecademy/gamut@40.0.1-alpha.ab24f1.0<br/>@codecademy/monaco@0.5.6-alpha.ab24f1.0<br/>@codecademy/styleguide@50.1.5-alpha.ab24f1.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.8-alpha.4baea5.0<br/>@codecademy/gamut-labs@28.0.3-alpha.4baea5.0<br/>@codecademy/gamut@40.0.1-alpha.4baea5.0<br/>@codecademy/monaco@0.5.6-alpha.4baea5.0<br/>@codecademy/styleguide@50.1.5-alpha.4baea5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61853f0e796baf0093fa0eff--gamut-preview.netlify.app>https://61853f0e796baf0093fa0eff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61853f0e796baf0093fa0eff>Deploy Logs</a></p>

**Review by CharlieBliss — APPROVED** [review]

**Pull request merged**
