### PR TITLE
feat(Flyout): Added optional background prop

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview
Allow gamut Flyout component to have changeable background color. 

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/Km8Nrk054HnZpjHsaSopLp/Filters?node-id=200%3A6307&t=zWVOWjn0zfKnn4RW-0
- [x] Related to JIRA ticket: [DISC-1007]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Open storybook link
2. Navigate to Flyout section 
3. Scroll down to list of props and see new `bg` prop 
4. Change that value to some color 
5. Click "Tell me more" above and see this color in the flyout 

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33936)  | [Monolith Env](https://pr-33936-monolith.dev-eks.codecademy.com/) |
| Monorepo       | [Portal PR](https://github.com/codecademy-engineering/mono/pull/843)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-843)   |

[DISC-1007]: https://codecademy.atlassian.net/browse/DISC-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.253-alpha.98aa31.0<br/>@codecademy/gamut-labs@33.11.3-alpha.98aa31.0<br/>@codecademy/gamut@51.5.3-alpha.98aa31.0<br/>@codecademy/monaco@0.6.114-alpha.98aa31.0<br/>@codecademy/styleguide@62.6.10-alpha.98aa31.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63979c69a6be334f15a12663--gamut-preview.netlify.app>https://63979c69a6be334f15a12663--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63979c69a6be334f15a12663>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6397a48a6898cc5816666b6c--gamut-preview.netlify.app>https://6397a48a6898cc5816666b6c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6397a48a6898cc5816666b6c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6397a7676611305f7e2d2975--gamut-preview.netlify.app>https://6397a7676611305f7e2d2975--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6397a7676611305f7e2d2975>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398a34a2bd382621094fe9c--gamut-preview.netlify.app>https://6398a34a2bd382621094fe9c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398a34a2bd382621094fe9c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.253-alpha.a6f7d4.0<br/>@codecademy/gamut-labs@33.11.3-alpha.a6f7d4.0<br/>@codecademy/gamut@51.5.3-alpha.a6f7d4.0<br/>@codecademy/monaco@0.6.114-alpha.a6f7d4.0<br/>@codecademy/styleguide@62.6.10-alpha.a6f7d4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398b12e8095c55a1b74e8d1--gamut-preview.netlify.app>https://6398b12e8095c55a1b74e8d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398b12e8095c55a1b74e8d1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.254-alpha.02d4ce.0<br/>@codecademy/gamut-labs@34.0.1-alpha.02d4ce.0<br/>@codecademy/gamut@51.5.3-alpha.02d4ce.0<br/>@codecademy/monaco@0.6.114-alpha.02d4ce.0<br/>@codecademy/styleguide@62.6.11-alpha.02d4ce.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398e5dcd96ee51e60e7e3ad--gamut-preview.netlify.app>https://6398e5dcd96ee51e60e7e3ad--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398e5dcd96ee51e60e7e3ad>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.254-alpha.af3e7c.0<br/>@codecademy/gamut-labs@34.0.1-alpha.af3e7c.0<br/>@codecademy/gamut@51.5.3-alpha.af3e7c.0<br/>@codecademy/monaco@0.6.114-alpha.af3e7c.0<br/>@codecademy/styleguide@62.6.11-alpha.af3e7c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398ef5d8c2dca23ff1e2980--gamut-preview.netlify.app>https://6398ef5d8c2dca23ff1e2980--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398ef5d8c2dca23ff1e2980>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.254-alpha.fd0275.0<br/>@codecademy/gamut-labs@34.0.1-alpha.fd0275.0<br/>@codecademy/gamut@51.5.3-alpha.fd0275.0<br/>@codecademy/monaco@0.6.114-alpha.fd0275.0<br/>@codecademy/styleguide@62.6.11-alpha.fd0275.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398f8a4ba39bc2e6f14bd54--gamut-preview.netlify.app>https://6398f8a4ba39bc2e6f14bd54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398f8a4ba39bc2e6f14bd54>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.254-alpha.2006b9.0<br/>@codecademy/gamut-labs@34.0.1-alpha.2006b9.0<br/>@codecademy/gamut@51.5.3-alpha.2006b9.0<br/>@codecademy/monaco@0.6.114-alpha.2006b9.0<br/>@codecademy/styleguide@62.6.11-alpha.2006b9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63990b7974ad243cf234e972--gamut-preview.netlify.app>https://63990b7974ad243cf234e972--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63990b7974ad243cf234e972>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.255-alpha.b8a43e.0<br/>@codecademy/gamut-labs@34.0.2-alpha.b8a43e.0<br/>@codecademy/gamut@51.5.3-alpha.b8a43e.0<br/>@codecademy/monaco@0.6.114-alpha.b8a43e.0<br/>@codecademy/styleguide@62.6.12-alpha.b8a43e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://639a48b4d4946a60593747ea--gamut-preview.netlify.app>https://639a48b4d4946a60593747ea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/639a48b4d4946a60593747ea>Deploy Logs</a></p>

**Review by saghdaey — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]
🔥

**Pull request merged**
