### PR TITLE
chore(CloseSquareIcon and FullscreenSquareIcon): add new icons

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview
We need the close button icon and expand icons in Gamut for our new dashboard widget. They are transparent and will be passed a color. 

Here is what the `CloseSquareIcon` looks like next to the existing  `MinimizeBarIcon ` in the monolith (with beige color)
Screenshot 2023-06-09 at 6 00 53 PM

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/TjBVb65kukF5TZRqYUn4Se/onboarding?node-id=306-11550
- [x] Related to JIRA ticket: [DISC-1212]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions
Open up the [storybook preview](https://648b4b8a969c0c2c5a0dc4f0--gamut-preview.netlify.app/?path=/docs/atoms-icons-regular--editable-icon) and see the CloseSquareIcon and FullscreenSquareIcon.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[DISC-1212]: https://codecademy.atlassian.net/browse/DISC-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64836c3f01c9a1008c1b4c5b--gamut-preview.netlify.app>https://64836c3f01c9a1008c1b4c5b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64836c3f01c9a1008c1b4c5b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64838e78d4758c1208e334e2--gamut-preview.netlify.app>https://64838e78d4758c1208e334e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64838e78d4758c1208e334e2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.3-alpha.895388.0<br/>@codecademy/gamut-kit@0.6.328-alpha.895388.0<br/>@codecademy/gamut-labs@35.15.2-alpha.895388.0<br/>@codecademy/gamut@55.1.7-alpha.895388.0<br/>@codecademy/monaco@0.7.33-alpha.895388.0<br/>@codecademy/styleguide@66.1.10-alpha.895388.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.3-alpha.fecfac.0<br/>@codecademy/gamut-kit@0.6.329-alpha.fecfac.0<br/>@codecademy/gamut-labs@35.15.2-alpha.fecfac.0<br/>@codecademy/gamut@55.1.7-alpha.fecfac.0<br/>@codecademy/monaco@0.7.33-alpha.fecfac.0<br/>@codecademy/styleguide@66.1.11-alpha.fecfac.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://648b4b8a969c0c2c5a0dc4f0--gamut-preview.netlify.app>https://648b4b8a969c0c2c5a0dc4f0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/648b4b8a969c0c2c5a0dc4f0>Deploy Logs</a></p>

**Review by saghdaey — APPROVED** [review]

**Review by medhatnar — APPROVED** [review]

**Pull request merged**
