### PR TITLE
feat: remove unused brandColors and deprecatedColors variables

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Finishes removing `brandColors` and `deprecatedColors` from TypeScript code.

Pending https://github.com/codecademy-engineering/author/pull/1787 these will no longer be used anywhere. Yay!

_"kill it with fire"_ - Cass Spain, 2021

### PR Checklist

- ~[ ] Related to designs:~
- [x] Related to JIRA ticket: WEB-1701
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.0.1-alpha.60d2a0.0<br/>@codecademy/gamut-illustrations@0.20.1-alpha.60d2a0.0<br/>@codecademy/gamut-kit@0.6.14-alpha.60d2a0.0<br/>@codecademy/gamut-labs@28.1.0-alpha.60d2a0.0<br/>@codecademy/gamut-patterns@0.7.2-alpha.60d2a0.0<br/>@codecademy/gamut-styles@12.1.0-alpha.60d2a0.0<br/>@codecademy/gamut-tests@3.0.1-alpha.60d2a0.0<br/>@codecademy/gamut@40.3.1-alpha.60d2a0.0<br/>@codecademy/markdown-overrides@0.7.1-alpha.60d2a0.0<br/>@codecademy/monaco@0.5.11-alpha.60d2a0.0<br/>@codecademy/styleguide@50.3.0-alpha.60d2a0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618c1eab3689531aa6c47aed--gamut-preview.netlify.app>https://618c1eab3689531aa6c47aed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618c1eab3689531aa6c47aed>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.0.1-alpha.7124b6.0<br/>@codecademy/gamut-illustrations@0.20.2-alpha.7124b6.0<br/>@codecademy/gamut-kit@0.6.19-alpha.7124b6.0<br/>@codecademy/gamut-labs@28.1.0-alpha.7124b6.0<br/>@codecademy/gamut-patterns@0.7.2-alpha.7124b6.0<br/>@codecademy/gamut-styles@12.1.0-alpha.7124b6.0<br/>@codecademy/gamut-tests@3.0.1-alpha.7124b6.0<br/>@codecademy/gamut@40.3.4-alpha.7124b6.0<br/>@codecademy/markdown-overrides@0.7.1-alpha.7124b6.0<br/>@codecademy/monaco@0.5.14-alpha.7124b6.0<br/>@codecademy/styleguide@50.3.0-alpha.7124b6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619666e20e78893793a8ca73--gamut-preview.netlify.app>https://619666e20e78893793a8ca73--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619666e20e78893793a8ca73>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.0.1-alpha.38a753.0<br/>@codecademy/gamut-illustrations@0.20.2-alpha.38a753.0<br/>@codecademy/gamut-kit@0.6.19-alpha.38a753.0<br/>@codecademy/gamut-labs@28.1.0-alpha.38a753.0<br/>@codecademy/gamut-patterns@0.7.2-alpha.38a753.0<br/>@codecademy/gamut-styles@12.1.0-alpha.38a753.0<br/>@codecademy/gamut-tests@3.0.1-alpha.38a753.0<br/>@codecademy/gamut@40.3.4-alpha.38a753.0<br/>@codecademy/markdown-overrides@0.7.1-alpha.38a753.0<br/>@codecademy/monaco@0.5.14-alpha.38a753.0<br/>@codecademy/styleguide@50.3.0-alpha.38a753.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619bca7af9db3843a8fa7c27--gamut-preview.netlify.app>https://619bca7af9db3843a8fa7c27--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619bca7af9db3843a8fa7c27>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
yes

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.0.1-alpha.aa3b41.0<br/>@codecademy/gamut-illustrations@0.20.2-alpha.aa3b41.0<br/>@codecademy/gamut-kit@0.6.20-alpha.aa3b41.0<br/>@codecademy/gamut-labs@28.1.0-alpha.aa3b41.0<br/>@codecademy/gamut-patterns@0.7.2-alpha.aa3b41.0<br/>@codecademy/gamut-styles@12.1.0-alpha.aa3b41.0<br/>@codecademy/gamut-tests@3.0.1-alpha.aa3b41.0<br/>@codecademy/gamut@40.4.1-alpha.aa3b41.0<br/>@codecademy/markdown-overrides@0.7.1-alpha.aa3b41.0<br/>@codecademy/monaco@0.5.15-alpha.aa3b41.0<br/>@codecademy/styleguide@50.4.0-alpha.aa3b41.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619cfb600cb829158365df35--gamut-preview.netlify.app>https://619cfb600cb829158365df35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619cfb600cb829158365df35>Deploy Logs</a></p>

**Pull request merged**
