### PR TITLE
fix(Pagination): aria-hidden added for hidden buttons

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Adds aria-hidden to `hidden` pagination buttons

Fixes axe failures on disco PR [here](https://github.com/codecademy-engineering/Codecademy/pull/29639), ty @j10sanders for catching this! 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.65-alpha.04f4e0.0<br/>@codecademy/gamut-labs@29.3.6-alpha.04f4e0.0<br/>@codecademy/gamut@44.6.2-alpha.04f4e0.0<br/>@codecademy/monaco@0.6.16-alpha.04f4e0.0<br/>@codecademy/styleguide@54.3.6-alpha.04f4e0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62193517f280a4164a1fb1d6--gamut-preview.netlify.app>https://62193517f280a4164a1fb1d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62193517f280a4164a1fb1d6>Deploy Logs</a></p>

**Review by j10sanders — APPROVED** [review]
Works perfectly

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.66-alpha.81f8c3.0<br/>@codecademy/gamut-labs@29.3.7-alpha.81f8c3.0<br/>@codecademy/gamut@44.7.1-alpha.81f8c3.0<br/>@codecademy/monaco@0.6.17-alpha.81f8c3.0<br/>@codecademy/styleguide@54.3.7-alpha.81f8c3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://621ce6be2c2abf9bb9bd34eb--gamut-preview.netlify.app>https://621ce6be2c2abf9bb9bd34eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/621ce6be2c2abf9bb9bd34eb>Deploy Logs</a></p>

**Review by reedlaverack — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.67-alpha.115004.0<br/>@codecademy/gamut-labs@29.3.8-alpha.115004.0<br/>@codecademy/gamut@44.7.1-alpha.115004.0<br/>@codecademy/monaco@0.6.17-alpha.115004.0<br/>@codecademy/styleguide@54.3.8-alpha.115004.0<br/></pre>

**Pull request merged**
