### PR TITLE
chore(Truncate)!: Remove `Truncate`

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Removes deprecated `Truncate` component.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-1848]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Visit the alert story and ensure the general (non inline) alert gets truncated with the option to expand. Confirm that clicking the arrow expands the alert and un-truncates the text. Confirm the general inline alert does not get truncated. Confirm that no other alerts show the expand button.
See monolith and portal PRs for testing instructions.

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31746)  | [Monolith Env](https://pr-31746-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2281)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2281)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62d9716f7de82700a16443c8--gamut-preview.netlify.app>https://62d9716f7de82700a16443c8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62d9716f7de82700a16443c8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.165-alpha.c14b20.0<br/>@codecademy/gamut-labs@33.0.1-alpha.c14b20.0<br/>@codecademy/gamut@48.3.1-alpha.c14b20.0<br/>@codecademy/monaco@0.6.60-alpha.c14b20.0<br/>@codecademy/styleguide@59.0.1-alpha.c14b20.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62d98d802a683f1483780bcf--gamut-preview.netlify.app>https://62d98d802a683f1483780bcf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62d98d802a683f1483780bcf>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
perfection

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.169-alpha.e44bdf.0<br/>@codecademy/gamut-labs@33.0.5-alpha.e44bdf.0<br/>@codecademy/gamut@49.1.1-alpha.e44bdf.0<br/>@codecademy/monaco@0.6.64-alpha.e44bdf.0<br/>@codecademy/styleguide@60.1.1-alpha.e44bdf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e7ec5d07f3246aef84a91a--gamut-preview.netlify.app>https://62e7ec5d07f3246aef84a91a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e7ec5d07f3246aef84a91a>Deploy Logs</a></p>

**Pull request merged**
