### PR TITLE
fix(DataGrid/Table): DataGrid/Table fixes

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

- headers and content should use the base paragraph styles - 16px, not 14px. 
- First column font should not be bolded. 
- 1st column padding-left and last column pdding-right should be .5rem, not 1rem
- text not truncating on overflow
- scroll fix on ff

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: gm-447
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.8-alpha.0101c1.0<br/>@codecademy/gamut-labs@28.0.3-alpha.0101c1.0<br/>@codecademy/gamut@40.0.1-alpha.0101c1.0<br/>@codecademy/monaco@0.5.6-alpha.0101c1.0<br/>@codecademy/styleguide@50.1.5-alpha.0101c1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618557132c0bd70da4f7d287--gamut-preview.netlify.app>https://618557132c0bd70da4f7d287--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618557132c0bd70da4f7d287>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.8-alpha.e9fb5f.0<br/>@codecademy/gamut-labs@28.0.3-alpha.e9fb5f.0<br/>@codecademy/gamut@40.0.1-alpha.e9fb5f.0<br/>@codecademy/monaco@0.5.6-alpha.e9fb5f.0<br/>@codecademy/styleguide@50.1.5-alpha.e9fb5f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61855d3fa606b011040ad5ec--gamut-preview.netlify.app>https://61855d3fa606b011040ad5ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61855d3fa606b011040ad5ec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.8-alpha.9ab4f8.0<br/>@codecademy/gamut-labs@28.0.3-alpha.9ab4f8.0<br/>@codecademy/gamut@40.0.1-alpha.9ab4f8.0<br/>@codecademy/monaco@0.5.6-alpha.9ab4f8.0<br/>@codecademy/styleguide@50.1.5-alpha.9ab4f8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61856bd0ea993508ff8fccaf--gamut-preview.netlify.app>https://61856bd0ea993508ff8fccaf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61856bd0ea993508ff8fccaf>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.9-alpha.02ec87.0<br/>@codecademy/gamut-labs@28.0.4-alpha.02ec87.0<br/>@codecademy/gamut@40.1.1-alpha.02ec87.0<br/>@codecademy/monaco@0.5.7-alpha.02ec87.0<br/>@codecademy/styleguide@50.1.6-alpha.02ec87.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618588ebb56bb0236919965a--gamut-preview.netlify.app>https://618588ebb56bb0236919965a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618588ebb56bb0236919965a>Deploy Logs</a></p>

**Review by CharlieBliss — APPROVED** [review]

**Pull request merged**
