### PR TITLE
chore(MinimizeBarIcon): add new minimize bar icon

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Add new minimize bar icon 

### PR Checklist

- [x] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Checkout the new minimize bar icon in the storybook preview

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.2-alpha.0eb544.0<br/>@codecademy/gamut-kit@0.6.324-alpha.0eb544.0<br/>@codecademy/gamut-labs@35.14.13-alpha.0eb544.0<br/>@codecademy/gamut@55.1.5-alpha.0eb544.0<br/>@codecademy/monaco@0.7.31-alpha.0eb544.0<br/>@codecademy/styleguide@66.1.6-alpha.0eb544.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6477a0059ecc23051f81ab56--gamut-preview.netlify.app>https://6477a0059ecc23051f81ab56--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6477a0059ecc23051f81ab56>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]

**Review by zippyzow — APPROVED** [review]
LGTM

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6477b6ca67c66b16acca4c04--gamut-preview.netlify.app>https://6477b6ca67c66b16acca4c04--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6477b6ca67c66b16acca4c04>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.2-alpha.aa25a2.0<br/>@codecademy/gamut-kit@0.6.325-alpha.aa25a2.0<br/>@codecademy/gamut-labs@35.14.14-alpha.aa25a2.0<br/>@codecademy/gamut@55.1.6-alpha.aa25a2.0<br/>@codecademy/monaco@0.7.32-alpha.aa25a2.0<br/>@codecademy/styleguide@66.1.7-alpha.aa25a2.0<br/></pre>

**Pull request merged**
