### PR TITLE
fix: Use child selector for li in markdown

### PR DESCRIPTION
**Pull request by jrood**
### Overview

Use child instead of descendant selector for li in markdown

When a chatbot responds with bulleted lists inside of numbered categories, we were displaying the bullets as numbers also.
|before|after|
|-|-|
||Screenshot 2024-06-17 at 11 12 40 AM|

```html
<ol>
  <li> - ordered list styles should apply here
    <ul>
      <li> - but not here
```

### PR Checklist

- [ ] ~Related to designs:~
- [ ] ~Related to JIRA ticket: [ABC-123]~
- [x] I have run this code to verify it works
- [ ] ~This PR includes unit tests for the code change~
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

[Mono PR](https://github.com/codecademy-engineering/mono/pull/6671)
[LE Preview](https://tayra.codecademy.com/workspaces/new?PR_ENV=le-pr-6671)
[Portal App Preview](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-6671)

### CODE REVIEW

**Review by dreamwasp — COMMENTED** [review]
makes sense to me! would just like to test this in the LE to check some edge cases (+ this may fix some other li related bugs we haven't gotten to yet )

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.4-alpha.73f0d4.0<br/>@codecademy/gamut-kit@0.6.416-alpha.73f0d4.0<br/>@codecademy/styleguide@66.25.1-alpha.73f0d4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://666ca7c39e4f4c5d7161f300--gamut-preview.netlify.app>https://666ca7c39e4f4c5d7161f300--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/666ca7c39e4f4c5d7161f300>Deploy Logs</a></p>

**Comment by jrood** [comment]
Thanks @dreamwasp ! I've added links to portal-app and le preview envs.

**Review by BandanaKM — APPROVED** [review]

**Comment by jrood** [comment]
Mentioned to `#curriculum` in Slack [here](https://codecademy.slack.com/archives/C036WB3FE/p1718652572326469)

**Pull request merged**
