### PR TITLE
fix(Toggle): add border to dark mode circle

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Adds border to dark mode Toggles

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?type=design&node-id=30067-40001&mode=design&t=Uhb6YQV4EmVyfz58-0
- [x] Related to JIRA ticket: [web-2250]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Go to Toggle in the SB testing env
2. Toggle to Dark Mode (using the ColorMode switcher in the top toolbar
3. Toggle should now be on light mode + dark mode

#### PR Links and Envs

The Tools Menu in Lessons is the main place this component is used in Dark Mode. 

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Mono / LE       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/3744)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.5.1-alpha.2de7f5.0<br/>@codecademy/gamut-kit@0.6.346-alpha.2de7f5.0<br/>@codecademy/styleguide@66.3.1-alpha.2de7f5.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.7.2-alpha.5ee505.0<br/>@codecademy/gamut-kit@0.6.351-alpha.5ee505.0<br/>@codecademy/styleguide@66.5.2-alpha.5ee505.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://651b1fc7889cfd0762bc4d88--gamut-preview.netlify.app>https://651b1fc7889cfd0762bc4d88--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/651b1fc7889cfd0762bc4d88>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM! Confirmed in storybook and in LE tools menu

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.7.2-alpha.8cfd7f.0<br/>@codecademy/gamut-kit@0.6.351-alpha.8cfd7f.0<br/>@codecademy/styleguide@66.5.3-alpha.8cfd7f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://651c84a14d4a382d101bc23d--gamut-preview.netlify.app>https://651c84a14d4a382d101bc23d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/651c84a14d4a382d101bc23d>Deploy Logs</a></p>

**Pull request merged**
