### PR TITLE
feat(Icons): add ProductsBriefcaseIcon, SmileyHappyIcon, SmileySadIcon, SmileyIndifferentIcon, and SmileyStarEyesIcon

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

add ProductsBriefcaseIcon, SmileyHappyIcon, SmileySadIcon, SmileyIndifferentIcon, and SmileyStarEyesIcon

Screenshot 2023-11-21 at 3 53 14 PM
<br/>
Screenshot 2023-11-21 at 3 53 11 PM
Screenshot 2023-11-21 at 3 53 07 PM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [LEGO-3551]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[LEGO-3551]: https://codecademy.atlassian.net/browse/LEGO-3551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.10.3-alpha.2e1df3.0<br/>@codecademy/gamut-icons@9.10.1-alpha.2e1df3.0<br/>@codecademy/gamut-kit@0.6.367-alpha.2e1df3.0<br/>@codecademy/styleguide@66.8.3-alpha.2e1df3.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.10.3-alpha.073010.0<br/>@codecademy/gamut-icons@9.10.1-alpha.073010.0<br/>@codecademy/gamut-kit@0.6.367-alpha.073010.0<br/>@codecademy/styleguide@66.8.3-alpha.073010.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://655d1ede6e85230cc441e9fa--gamut-preview.netlify.app>https://655d1ede6e85230cc441e9fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/655d1ede6e85230cc441e9fa>Deploy Logs</a></p>

**Review by katiezutter — APPROVED** [review]
lgtm!

**Review by aresnik11 — APPROVED** [review]

**Pull request merged**
