### PR TITLE
fix: React 18 react-player compatibility

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

React player causes hydration errors in React 18. It barely actually server-rendered anything before, so our solution is to prevent it from rendering server-side. Because of how we do the styles, the spaces where the videos will go still has the correct width/height, so this doesn't cause any unnecessary layout shifts. 

Prevent react-player from rendering server-side for React 18 compatibility

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Open the Portal PR preview, go to https://tengu.codecademy.com/pages/pro?PR_ENV=portal-app-pr-1224
2. Note that there are no warnings in the console for unminified react errors

(for now you may need to test this locally by pulling down the [portal branch](https://github.com/codecademy-engineering/mono/pull/1224))

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/mono/pull/1224)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1224)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.a58adb.0<br/>@codecademy/gamut-labs@35.5.4-alpha.a58adb.0<br/>@codecademy/gamut@52.0.3-alpha.a58adb.0<br/>@codecademy/monaco@0.7.3-alpha.a58adb.0<br/>@codecademy/styleguide@63.5.2-alpha.a58adb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e3d3f03c047003edac143c--gamut-preview.netlify.app>https://63e3d3f03c047003edac143c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e3d3f03c047003edac143c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.299871.0<br/>@codecademy/gamut-labs@35.5.4-alpha.299871.0<br/>@codecademy/gamut@52.0.3-alpha.299871.0<br/>@codecademy/monaco@0.7.3-alpha.299871.0<br/>@codecademy/styleguide@63.5.2-alpha.299871.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e3e56cd9bcba0522e8b8f8--gamut-preview.netlify.app>https://63e3e56cd9bcba0522e8b8f8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e3e56cd9bcba0522e8b8f8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.279-alpha.d7de5e.0<br/>@codecademy/gamut-labs@35.5.5-alpha.d7de5e.0<br/>@codecademy/gamut@52.0.3-alpha.d7de5e.0<br/>@codecademy/monaco@0.7.3-alpha.d7de5e.0<br/>@codecademy/styleguide@63.5.3-alpha.d7de5e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e51972c7205c0050eb3b2e--gamut-preview.netlify.app>https://63e51972c7205c0050eb3b2e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e51972c7205c0050eb3b2e>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM!

**Pull request merged**
