### PR TITLE
chore(CardShell): Delete CardDeprecated + References

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Removes CardDeprecated + all references from Gamut 

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-1888]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32564)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| MonoRepo       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/156)  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[WEB-1888]: https://codecademy.atlassian.net/browse/WEB-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.205-alpha.cac242.0<br/>@codecademy/gamut-labs@33.5.1-alpha.cac242.0<br/>@codecademy/gamut@50.6.6-alpha.cac242.0<br/>@codecademy/monaco@0.6.88-alpha.cac242.0<br/>@codecademy/styleguide@61.5.12-alpha.cac242.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63287c70e16b513c6c8c14cd--gamut-preview.netlify.app>https://63287c70e16b513c6c8c14cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63287c70e16b513c6c8c14cd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.205-alpha.5968fe.0<br/>@codecademy/gamut-labs@33.5.1-alpha.5968fe.0<br/>@codecademy/gamut@50.6.6-alpha.5968fe.0<br/>@codecademy/monaco@0.6.88-alpha.5968fe.0<br/>@codecademy/styleguide@61.5.12-alpha.5968fe.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63287fddf7532446468e3bae--gamut-preview.netlify.app>https://63287fddf7532446468e3bae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63287fddf7532446468e3bae>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Review by aresnik11 — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.205-alpha.7591c2.0<br/>@codecademy/gamut-labs@33.5.1-alpha.7591c2.0<br/>@codecademy/gamut@50.6.6-alpha.7591c2.0<br/>@codecademy/monaco@0.6.88-alpha.7591c2.0<br/>@codecademy/styleguide@61.5.12-alpha.7591c2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://632c72b0d825fd4002bc97af--gamut-preview.netlify.app>https://632c72b0d825fd4002bc97af--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/632c72b0d825fd4002bc97af>Deploy Logs</a></p>

**Pull request merged**
