### PR TITLE
fix(SelectDropDown): fix option voice over announcement bug

### PR DESCRIPTION
**Pull request by vonbarown**
### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EN-2091](https://codecademy.atlassian.net/browse/EN-2091)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Visit https://caiman.codecademy.com//admin and impersonate user: ``test-tracking-admin@testerv.com`` 
2. Visit https://caiman.codecademy.com/learn/learn-python-3 and click on the CTA ``Assign Course``
3. Enable voice over and Tab navigate to the select drop down input box
4. use to the up and down arrows keys to navigate
5. Ensure that when you land on the disabled user you hear the ``Already Assigned`` message

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34100)  | [Monolith Env](https://caiman.codecademy.com/learn/learn-python-3) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/959)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-959')   |

[EN-2091]: https://codecademy.atlassian.net/browse/EN-2091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.6a7def.0<br/>@codecademy/gamut-labs@34.0.6-alpha.6a7def.0<br/>@codecademy/gamut@51.6.3-alpha.6a7def.0<br/>@codecademy/monaco@0.6.117-alpha.6a7def.0<br/>@codecademy/styleguide@62.7.4-alpha.6a7def.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a1fc249544030051e5561e--gamut-preview.netlify.app>https://63a1fc249544030051e5561e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a1fc249544030051e5561e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.23238b.0<br/>@codecademy/gamut-labs@34.0.6-alpha.23238b.0<br/>@codecademy/gamut@51.6.3-alpha.23238b.0<br/>@codecademy/monaco@0.6.117-alpha.23238b.0<br/>@codecademy/styleguide@62.7.4-alpha.23238b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a2113b5ebc4f0fac6c6403--gamut-preview.netlify.app>https://63a2113b5ebc4f0fac6c6403--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a2113b5ebc4f0fac6c6403>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.54e7ad.0<br/>@codecademy/gamut-labs@34.0.6-alpha.54e7ad.0<br/>@codecademy/gamut@51.6.3-alpha.54e7ad.0<br/>@codecademy/monaco@0.6.117-alpha.54e7ad.0<br/>@codecademy/styleguide@62.7.4-alpha.54e7ad.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a21ebb01944c231b21c6bd--gamut-preview.netlify.app>https://63a21ebb01944c231b21c6bd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a21ebb01944c231b21c6bd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a223bda8bb9b1f553ed306--gamut-preview.netlify.app>https://63a223bda8bb9b1f553ed306--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a223bda8bb9b1f553ed306>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.e3399f.0<br/>@codecademy/gamut-labs@34.0.6-alpha.e3399f.0<br/>@codecademy/gamut@51.6.3-alpha.e3399f.0<br/>@codecademy/monaco@0.6.117-alpha.e3399f.0<br/>@codecademy/styleguide@62.7.4-alpha.e3399f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.5144cb.0<br/>@codecademy/gamut-labs@34.0.6-alpha.5144cb.0<br/>@codecademy/gamut@51.6.3-alpha.5144cb.0<br/>@codecademy/monaco@0.6.117-alpha.5144cb.0<br/>@codecademy/styleguide@62.7.4-alpha.5144cb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a34a6651a71e49dc9d9b40--gamut-preview.netlify.app>https://63a34a6651a71e49dc9d9b40--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a34a6651a71e49dc9d9b40>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.f60974.0<br/>@codecademy/gamut-labs@34.0.6-alpha.f60974.0<br/>@codecademy/gamut@51.6.3-alpha.f60974.0<br/>@codecademy/monaco@0.6.117-alpha.f60974.0<br/>@codecademy/styleguide@62.7.4-alpha.f60974.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a36096fb6de85d0e09c655--gamut-preview.netlify.app>https://63a36096fb6de85d0e09c655--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a36096fb6de85d0e09c655>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.d0e2bb.0<br/>@codecademy/gamut-labs@34.0.6-alpha.d0e2bb.0<br/>@codecademy/gamut@51.6.3-alpha.d0e2bb.0<br/>@codecademy/monaco@0.6.117-alpha.d0e2bb.0<br/>@codecademy/styleguide@62.7.4-alpha.d0e2bb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a388c51ff61f7d6c9617fe--gamut-preview.netlify.app>https://63a388c51ff61f7d6c9617fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a388c51ff61f7d6c9617fe>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.259-alpha.ae6e78.0<br/>@codecademy/gamut-labs@34.0.6-alpha.ae6e78.0<br/>@codecademy/gamut@51.6.3-alpha.ae6e78.0<br/>@codecademy/monaco@0.6.117-alpha.ae6e78.0<br/>@codecademy/styleguide@62.7.4-alpha.ae6e78.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63a46e28c1cc6930121667d4--gamut-preview.netlify.app>https://63a46e28c1cc6930121667d4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63a46e28c1cc6930121667d4>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
thanks for taking this on -- works like a charm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.260-alpha.2dcf77.0<br/>@codecademy/gamut-labs@34.0.7-alpha.2dcf77.0<br/>@codecademy/gamut@51.7.1-alpha.2dcf77.0<br/>@codecademy/monaco@0.6.118-alpha.2dcf77.0<br/>@codecademy/styleguide@62.8.1-alpha.2dcf77.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63b84a1eaa21c71441570774--gamut-preview.netlify.app>https://63b84a1eaa21c71441570774--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63b84a1eaa21c71441570774>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.262-alpha.7f89e1.0<br/>@codecademy/gamut-labs@34.0.9-alpha.7f89e1.0<br/>@codecademy/gamut@51.7.2-alpha.7f89e1.0<br/>@codecademy/monaco@0.6.119-alpha.7f89e1.0<br/>@codecademy/styleguide@62.8.3-alpha.7f89e1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63bc65ec9fad360669659e7c--gamut-preview.netlify.app>https://63bc65ec9fad360669659e7c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63bc65ec9fad360669659e7c>Deploy Logs</a></p>

**Pull request merged**
