### PR TITLE
style(BookAndNotepad): Replace current svg with new cropped svg

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

The current illustration for the BookAndNotepad has extra space on the right side making it hard to center (see pics). Once we have the updated illustration, replace the current BookAndNotepad svg in [gamut illustrations](https://gamut.codecademy.com/?path=/docs/atoms-illustrations--editable-illustration) and then bump the monolith package so it gets the corrected illustration.

**Before** (note the extra space on the right)
Screenshot 2023-07-12 at 12 34 20 PM

**After**
Screenshot 2023-07-12 at 12 33 59 PM

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/TjBVb65kukF5TZRqYUn4Se/onboarding?node-id=306-11550
- [x] Related to JIRA ticket: [DISC-1226]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Check out the BookAndNotepad under Illustrations in Storybook. You can see its more centered than the one in production which has extra space on the right. 
2. You can also go on the monolith PR env link, go to the dashboard as a user in the `onboarding_getting_started` experiment `variant`, and see the new illustration in action

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36035)  | [Monolith Env](https://pr-36035-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/2697)  |     |

[DISC-1226]: https://codecademy.atlassian.net/browse/DISC-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.38.2-alpha.0e00e4.0<br/>@codecademy/gamut-kit@0.6.331-alpha.0e00e4.0<br/>@codecademy/gamut-labs@35.15.4-alpha.0e00e4.0<br/>@codecademy/gamut@55.1.9-alpha.0e00e4.0<br/>@codecademy/monaco@0.7.35-alpha.0e00e4.0<br/>@codecademy/styleguide@66.1.13-alpha.0e00e4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64adbe59ee424e419f3aa718--gamut-preview.netlify.app>https://64adbe59ee424e419f3aa718--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64adbe59ee424e419f3aa718>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.38.2-alpha.97abb4.0<br/>@codecademy/gamut-kit@0.6.331-alpha.97abb4.0<br/>@codecademy/gamut-labs@35.15.4-alpha.97abb4.0<br/>@codecademy/gamut@55.1.9-alpha.97abb4.0<br/>@codecademy/monaco@0.7.35-alpha.97abb4.0<br/>@codecademy/styleguide@66.1.13-alpha.97abb4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64adce370d22f04c0a3c4b4f--gamut-preview.netlify.app>https://64adce370d22f04c0a3c4b4f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64adce370d22f04c0a3c4b4f>Deploy Logs</a></p>

**Review by saghdaey — APPROVED** [review]
LGTM! tested in storybook preview & monolith preview

**Pull request merged**
