### PR TITLE
fix: maintain open state when hovering over 'floating' tooltip content

### PR DESCRIPTION
**Pull request by awgraves**
### Overview

Adds event listeners to mouse overing a floating tooltip so it remains open.
Previously, the floating variant would close whenever mousing over the tooltip content.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [DOT-79]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. visit the [prod storybook page](https://gamut.codecademy.com/?path=/docs/atoms-tooltip--tool-tip) for the tooltip.  Go to the first example and set the `placement` as `floating`.  Note that mousing over the tooltip example causes it to close (most of the time).
Screenshot 2024-02-29 at 4 13 06 PM

2. now visit the [new storybook page](https://65e102132724213c07d8b869--gamut-preview.netlify.app/?path=/docs/atoms-tooltip--tool-tip) and confirm the fix - tooltip should stay open when mousing over the popover content.
new_storybook

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/37212)  | [Monolith Env](https://pr-37212-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/5216)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-5216)   |

[DOT-79]: https://codecademy.atlassian.net/browse/DOT-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dreamwasp** [comment]
we're actually currently working on  an overhaul of tooltips!  in progress branch [here](https://github.com/Codecademy/gamut/pull/2832) + [our accessibility proposal ](https://skillsoft-my.sharepoint.com/:w:/r/personal/cass_spain_skillsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BC7DAC4BF-F899-471B-A65B-2727E300DA76%7D&file=Icons_and_ToolTips_Proposal.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1709219280859&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=fd3da938-259d-4bbd-ad6d-ad1b80623a2f&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=aed29e88-4ef3-4edd-b0e0-548b3d855e92) if you're curious!

**Comment by awgraves** [comment]
> we're actually currently working on an overhaul of tooltips! in progress branch [here](https://github.com/Codecademy/gamut/pull/2832) + [our accessibility proposal ](https://skillsoft-my.sharepoint.com/:w:/r/personal/cass_spain_skillsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BC7DAC4BF-F899-471B-A65B-2727E300DA76%7D&file=Icons_and_ToolTips_Proposal.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1709219280859&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=fd3da938-259d-4bbd-ad6d-ad1b80623a2f&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=aed29e88-4ef3-4edd-b0e0-548b3d855e92) if you're curious!

@dreamwasp nice!  my change is related to a test.io audit for a feature we need to launch by Monday.
Is that WIP branch going in soon, or should we just go with this smaller PR for now?

(btw sorry i should have made this PR draft as im still waiting on alpha build - forgot it auto tagged people when opening a pr!)

**Comment by dreamwasp** [comment]
no worries, just wanted to share for visibility. i'll check out this pr once the pkgs built and all the good stuff, hoping to have new tooltips shipped later next week

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.3-alpha.df4b39.0<br/>@codecademy/gamut-kit@0.6.384-alpha.df4b39.0<br/>@codecademy/styleguide@66.12.2-alpha.df4b39.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65e0a44835f68f164abb0a73--gamut-preview.netlify.app>https://65e0a44835f68f164abb0a73--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65e0a44835f68f164abb0a73>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65e0adc65eac521de4f9b286--gamut-preview.netlify.app>https://65e0adc65eac521de4f9b286--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65e0adc65eac521de4f9b286>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.4-alpha.704176.0<br/>@codecademy/gamut-kit@0.6.385-alpha.704176.0<br/>@codecademy/styleguide@66.12.3-alpha.704176.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65e102132724213c07d8b869--gamut-preview.netlify.app>https://65e102132724213c07d8b869--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65e102132724213c07d8b869>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
love this, i think the only things failing are jest snapshot tests in your integration PRs! i hadn't implement this behavior yet on my in-progress tooltip branch so this is super helpful thank youu!! ✨

**Pull request merged**
