### PR TITLE
feat(ColorMode): add text-secondary + new white weights

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Add `text-secondary` and new white weights

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2224]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Check out the `ColorMode` story + see the new `text-secondary` token + examples for the new white color weights.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[WEB-2224]: https://codecademy.atlassian.net/browse/WEB-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@8.0.1-alpha.258f59.0<br/>@codecademy/gamut-illustrations@0.33.1-alpha.258f59.0<br/>@codecademy/gamut-kit@0.6.274-alpha.258f59.0<br/>@codecademy/gamut-labs@35.4.1-alpha.258f59.0<br/>@codecademy/gamut-patterns@0.9.1-alpha.258f59.0<br/>@codecademy/gamut-styles@15.0.1-alpha.258f59.0<br/>@codecademy/gamut-tests@5.0.1-alpha.258f59.0<br/>@codecademy/gamut@52.0.1-alpha.258f59.0<br/>@codecademy/markdown-overrides@0.10.1-alpha.258f59.0<br/>@codecademy/monaco@0.7.1-alpha.258f59.0<br/>@codecademy/styleguide@63.3.1-alpha.258f59.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63dae825c823843b3a66bdb6--gamut-preview.netlify.app>https://63dae825c823843b3a66bdb6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63dae825c823843b3a66bdb6>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@8.0.1-alpha.5e3dd6.0<br/>@codecademy/gamut-illustrations@0.33.1-alpha.5e3dd6.0<br/>@codecademy/gamut-kit@0.6.274-alpha.5e3dd6.0<br/>@codecademy/gamut-labs@35.4.1-alpha.5e3dd6.0<br/>@codecademy/gamut-patterns@0.9.1-alpha.5e3dd6.0<br/>@codecademy/gamut-styles@15.0.1-alpha.5e3dd6.0<br/>@codecademy/gamut-tests@5.0.1-alpha.5e3dd6.0<br/>@codecademy/gamut@52.0.1-alpha.5e3dd6.0<br/>@codecademy/markdown-overrides@0.10.1-alpha.5e3dd6.0<br/>@codecademy/monaco@0.7.1-alpha.5e3dd6.0<br/>@codecademy/styleguide@63.3.1-alpha.5e3dd6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63dbd311d43abe67a5fc039e--gamut-preview.netlify.app>https://63dbd311d43abe67a5fc039e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63dbd311d43abe67a5fc039e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63dc29119035f440ccbc56d6--gamut-preview.netlify.app>https://63dc29119035f440ccbc56d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63dc29119035f440ccbc56d6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@8.0.1-alpha.0ae620.0<br/>@codecademy/gamut-illustrations@0.33.1-alpha.0ae620.0<br/>@codecademy/gamut-kit@0.6.276-alpha.0ae620.0<br/>@codecademy/gamut-labs@35.5.2-alpha.0ae620.0<br/>@codecademy/gamut-patterns@0.9.1-alpha.0ae620.0<br/>@codecademy/gamut-styles@15.0.1-alpha.0ae620.0<br/>@codecademy/gamut-tests@5.0.1-alpha.0ae620.0<br/>@codecademy/gamut@52.0.2-alpha.0ae620.0<br/>@codecademy/markdown-overrides@0.10.1-alpha.0ae620.0<br/>@codecademy/monaco@0.7.2-alpha.0ae620.0<br/>@codecademy/styleguide@63.4.2-alpha.0ae620.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e10e615ab5c10b8cf6905f--gamut-preview.netlify.app>https://63e10e615ab5c10b8cf6905f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e10e615ab5c10b8cf6905f>Deploy Logs</a></p>

**Pull request merged**
