### PR TITLE
refactor(gamut-patterns): replacing incremental ids with auto-id

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

* refactors incremental ids to use auto-id

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [web-2285]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* go to patterns in the test env
* the patterns should render
* go to a component that uses a `gamut-pattern` like `FloatingCard` 
* they should look identical to the way they do now

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34613)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1232)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.99a1f1.0<br/>@codecademy/gamut-labs@35.5.4-alpha.99a1f1.0<br/>@codecademy/gamut-patterns@0.9.2-alpha.99a1f1.0<br/>@codecademy/gamut@52.0.3-alpha.99a1f1.0<br/>@codecademy/monaco@0.7.3-alpha.99a1f1.0<br/>@codecademy/styleguide@63.5.2-alpha.99a1f1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e3dccdd33dd40ce1b944b1--gamut-preview.netlify.app>https://63e3dccdd33dd40ce1b944b1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e3dccdd33dd40ce1b944b1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.f8ddfc.0<br/>@codecademy/gamut-labs@35.5.4-alpha.f8ddfc.0<br/>@codecademy/gamut-patterns@0.9.2-alpha.f8ddfc.0<br/>@codecademy/gamut@52.0.3-alpha.f8ddfc.0<br/>@codecademy/monaco@0.7.3-alpha.f8ddfc.0<br/>@codecademy/styleguide@63.5.2-alpha.f8ddfc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e4023f721e051bf0e0f96a--gamut-preview.netlify.app>https://63e4023f721e051bf0e0f96a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e4023f721e051bf0e0f96a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.b825ee.0<br/>@codecademy/gamut-labs@35.5.4-alpha.b825ee.0<br/>@codecademy/gamut-patterns@0.9.2-alpha.b825ee.0<br/>@codecademy/gamut@52.0.3-alpha.b825ee.0<br/>@codecademy/monaco@0.7.3-alpha.b825ee.0<br/>@codecademy/styleguide@63.5.2-alpha.b825ee.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.9ef07d.0<br/>@codecademy/gamut-labs@35.5.4-alpha.9ef07d.0<br/>@codecademy/gamut-patterns@0.9.2-alpha.9ef07d.0<br/>@codecademy/gamut@52.0.3-alpha.9ef07d.0<br/>@codecademy/monaco@0.7.3-alpha.9ef07d.0<br/>@codecademy/styleguide@63.5.2-alpha.9ef07d.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.279-alpha.a0c9fc.0<br/>@codecademy/gamut-labs@35.5.5-alpha.a0c9fc.0<br/>@codecademy/gamut-patterns@0.9.2-alpha.a0c9fc.0<br/>@codecademy/gamut@52.0.3-alpha.a0c9fc.0<br/>@codecademy/monaco@0.7.3-alpha.a0c9fc.0<br/>@codecademy/styleguide@63.5.3-alpha.a0c9fc.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.280-alpha.a1604d.0<br/>@codecademy/gamut-labs@35.5.6-alpha.a1604d.0<br/>@codecademy/gamut-patterns@0.9.2-alpha.a1604d.0<br/>@codecademy/gamut@52.0.4-alpha.a1604d.0<br/>@codecademy/monaco@0.7.4-alpha.a1604d.0<br/>@codecademy/styleguide@63.5.4-alpha.a1604d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e534c5da2ab5102cfc3297--gamut-preview.netlify.app>https://63e534c5da2ab5102cfc3297--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e534c5da2ab5102cfc3297>Deploy Logs</a></p>

**Pull request merged**
