### PR TITLE
refactor(ScoreSummary): make trackSlug and tracking optional in ScoreSummary

### PR DESCRIPTION
**Pull request by mstykmshy**
### Overview

- Make `trackSlug` optional and refactor Review Concepts link to only show if `trackSlug` is present
- Make tracking optional in ScoreSummary since it's only used for Review Concepts link which is now optional
- Use `Math.round()` for QuizSummaryscore calculation instead of `Math.floor()`

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-2994]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Test in storybook. Optionally you can also test in [this portal-app preview environment](https://tengu.codecademy.com/career-journey/full-stack-engineer?PR_ENV=portal-app-pr-788) where the changes will be used.

- Test that score rounding is working right in storybook by setting the `totalCorrect` and `totalQuestions` props to something that would have a different result from `Math.floor()` and `Math.round()`. For example,`totalCorrect=2` and `totalQuestions=3` should result in a score of `67`, not `66`.
- Ensure that `trackSlug` is optional and the Review Concepts links are not rendered when no `trackSlug` is given.
- Ensure that `trackingData` and `trackUserClick` are now optional.

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/788)  | [Portal Env](https://tengu.codecademy.com/career-journey/full-stack-engineer?PR_ENV=portal-app-pr-788)   |

[EGG-2994]: https://codecademy.atlassian.net/browse/EGG-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.249-alpha.9b77c5.0<br/>@codecademy/gamut-labs@33.10.1-alpha.9b77c5.0<br/>@codecademy/styleguide@62.6.6-alpha.9b77c5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6390fd38c5a57e0ef23d7cc0--gamut-preview.netlify.app>https://6390fd38c5a57e0ef23d7cc0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6390fd38c5a57e0ef23d7cc0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.249-alpha.97033b.0<br/>@codecademy/gamut-labs@33.10.1-alpha.97033b.0<br/>@codecademy/styleguide@62.6.6-alpha.97033b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63910065c116ae1025b3eb11--gamut-preview.netlify.app>https://63910065c116ae1025b3eb11--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63910065c116ae1025b3eb11>Deploy Logs</a></p>

**Review by sooinc — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
