### PR TITLE
fix(GlobalHeader): a11y fixes for resources & catalog drop downs 

### PR DESCRIPTION
**Pull request by saghdaey**
### Overview

1. hides decorative right arrow icon from screen readers on links (in resources dropdown, the arrow next to 'view all docs' and 'view all topics'; in the catalog dropdown it's next to 'take our quiz')
2. hides decorative box svg from catalog dropdown (next to "dont know where to start" in catalog dropdown)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [DISC-898], [DISC-900]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33088)  | [Monolith Env](https://pr-33088-monolith.dev-eks.codecademy.com/) |

testing in just monolith should be enough
monolith PR has screenshots as well

1. Visit preview env
2. Navigate global header w/ voice over
3. Open the resources menu and confirm that view all docs and view all topics are not read w/ the right arrow symbol
4. Open the catalog menu and confirm that the img next to 'take our quiz' is not read, and neither is the right arrow symbol
5. Approve!

[DISC-898]: https://codecademy.atlassian.net/browse/DISC-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DISC-900]: https://codecademy.atlassian.net/browse/DISC-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://634f592442ffdf2e2fe6f6e1--gamut-preview.netlify.app>https://634f592442ffdf2e2fe6f6e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/634f592442ffdf2e2fe6f6e1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.214-alpha.c3af97.0<br/>@codecademy/gamut-labs@33.6.5-alpha.c3af97.0<br/>@codecademy/styleguide@61.7.4-alpha.c3af97.0<br/></pre>

**Review by zippyzow — APPROVED** [review]

**Review by medhatnar — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.217-alpha.96cf38.0<br/>@codecademy/gamut-labs@33.6.8-alpha.96cf38.0<br/>@codecademy/styleguide@62.0.1-alpha.96cf38.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6352a321f4766908ba0bd961--gamut-preview.netlify.app>https://6352a321f4766908ba0bd961--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6352a321f4766908ba0bd961>Deploy Logs</a></p>

**Pull request merged**
