### PR TITLE
fix(InfoTip): fix DOM ordering + tip not being reread

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Fixes DOM ordering and Infotip not being re-read on retrigger (known issue with aria-live on Chrome)

i've found that properly fixing the floating alignment would require an entire overhaul of the Popover component -- i've caught a larger epic for that [here](https://skillsoftdev.atlassian.net/jira/software/projects/GM/boards/784?assignee=712020:d3cb9076-03cb-43eb-905b-058aa25d1578&selectedIssue=GM-788).

 instead, the user can tab through the **_screenreader_** text for the floating component which does respect DOM order - giving the user the correct information in the correct order even if its not the same HTML element. this is a quick fix, i'm planning for a long-term fix with the adjustments to the Popover component but thats a much larger effort.

### PR Checklist

- [x] Related to JIRA ticket: [gm-788, [ENT-73](https://skillsoftdev.atlassian.net/browse/ENT-73?focusedCommentId=731387)]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Head to InfoTip story
2. Turn on VO 
3. Trigger an InfoTip at least 3x times - you should hear it read each re-trigger
4. Navigate to the alignment section
5. Open a top-aligned infotip
6. You should be able to hear the tip announced, and navigate through the text in correct DOM order using CTRL + OPT
7. Open a bottom-aligned infotip
8. You should be able to hear the tip announced, and navigate through the text in correct DOM order using CTRL + OPT
9. Navigate to the floating section
10. You should be able to hear the tip announced, and navigate through the text in correct DOM order using CTRL + OPT. The tip **will not be highlighted**, though the information should be communicated in the correct order.
11. Navigate to ToolTip page
12. You should only hear tips communicated as the Buttons and not repeated when navigating with CTRL + OPT
13. Profit

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/38063/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6972')  | [Portal Env](http://www.google.fr/ 'Named link title')   |

[ENT-73]: https://skillsoftdev.atlassian.net/browse/ENT-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.4027d2.0<br/>@codecademy/gamut-kit@0.6.425-alpha.4027d2.0<br/>@codecademy/styleguide@66.29.5-alpha.4027d2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://669007e3a724ef08e1186cf1--gamut-preview.netlify.app>https://669007e3a724ef08e1186cf1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/669007e3a724ef08e1186cf1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.a87120.0<br/>@codecademy/gamut-kit@0.6.425-alpha.a87120.0<br/>@codecademy/styleguide@66.29.5-alpha.a87120.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66904857bd7c2045ce422d3f--gamut-preview.netlify.app>https://66904857bd7c2045ce422d3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66904857bd7c2045ce422d3f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.b4fc1b.0<br/>@codecademy/gamut-kit@0.6.425-alpha.b4fc1b.0<br/>@codecademy/styleguide@66.29.5-alpha.b4fc1b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66915b5d33078d008524deac--gamut-preview.netlify.app>https://66915b5d33078d008524deac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66915b5d33078d008524deac>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.eb48ef.0<br/>@codecademy/gamut-kit@0.6.425-alpha.eb48ef.0<br/>@codecademy/styleguide@66.29.5-alpha.eb48ef.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6691977233078d4b6324dd52--gamut-preview.netlify.app>https://6691977233078d4b6324dd52--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6691977233078d4b6324dd52>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.e50bb5.0<br/>@codecademy/gamut-kit@0.6.425-alpha.e50bb5.0<br/>@codecademy/styleguide@66.29.5-alpha.e50bb5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66919bbdfc1cfb6bec2586a7--gamut-preview.netlify.app>https://66919bbdfc1cfb6bec2586a7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66919bbdfc1cfb6bec2586a7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.d83714.0<br/>@codecademy/gamut-kit@0.6.425-alpha.d83714.0<br/>@codecademy/styleguide@66.29.6-alpha.d83714.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6691a1768d894f5580457ac7--gamut-preview.netlify.app>https://6691a1768d894f5580457ac7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6691a1768d894f5580457ac7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6691a50ec9f4c85b4b474af7--gamut-preview.netlify.app>https://6691a50ec9f4c85b4b474af7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6691a50ec9f4c85b4b474af7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.32b328.0<br/>@codecademy/gamut-kit@0.6.425-alpha.32b328.0<br/>@codecademy/styleguide@66.29.6-alpha.32b328.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66952df3d13a7c399c672754--gamut-preview.netlify.app>https://66952df3d13a7c399c672754--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66952df3d13a7c399c672754>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.4-alpha.04617d.0<br/>@codecademy/gamut-kit@0.6.425-alpha.04617d.0<br/>@codecademy/styleguide@66.29.6-alpha.04617d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://669594e7f619af36684dcb39--gamut-preview.netlify.app>https://669594e7f619af36684dcb39--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/669594e7f619af36684dcb39>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@56.0.1-alpha.19ec4c.0<br/>@codecademy/gamut-kit@0.6.426-alpha.19ec4c.0<br/>@codecademy/styleguide@67.0.1-alpha.19ec4c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://669695c1b2875dd579b6de6b--gamut-preview.netlify.app>https://669695c1b2875dd579b6de6b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/669695c1b2875dd579b6de6b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@56.0.1-alpha.f27b64.0<br/>@codecademy/gamut-kit@0.6.426-alpha.f27b64.0<br/>@codecademy/styleguide@67.0.1-alpha.f27b64.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6696b309b4404cfc93855779--gamut-preview.netlify.app>https://6696b309b4404cfc93855779--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6696b309b4404cfc93855779>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
LGTM! Works as expected ✨

**Pull request merged**
