### PR TITLE
fix(HorizontalScrollMenu): polyfill IntersectionObserver

### PR DESCRIPTION
**Pull request by j10sanders**
### Overview

Around 1% of people are using browsers that don't support IntersectionObserver.  It's causing a lot of errors that have surfaced in datadog monitoring.

I tried dynamically loading the polyfill only if window.IntersectionObserver is undefined, but I was running into issues.  I also tried using `react-intersection-observer` with Colin, but since we are using it for multiple entries it was not ideal.  This is the simplest solution and I don't think it adds a lot of overhead, but happy to discuss/pair if there are concerns!

I didn't make a build of this in monolith, but confimed it fixes the homepage crashing if you turn off IntersectionObserver in Safari.  I did make a portal app build that fixes /catalog and any hub page (which all use the HorizontalScrollMenu)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DISC-679
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |

| Portal        | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2087)   |
| Monolith | [Monolith Env](https://pr-31086-monolith.dev-eks.codecademy.com) |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.fd106c.0<br/>@codecademy/gamut-labs@31.15.5-alpha.fd106c.0<br/>@codecademy/styleguide@57.7.5-alpha.fd106c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629f986f221e3a00b78978d3--gamut-preview.netlify.app>https://629f986f221e3a00b78978d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629f986f221e3a00b78978d3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.af29d2.0<br/>@codecademy/gamut-labs@31.15.5-alpha.af29d2.0<br/>@codecademy/styleguide@57.7.5-alpha.af29d2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.282713.0<br/>@codecademy/gamut-labs@31.15.5-alpha.282713.0<br/>@codecademy/styleguide@57.7.5-alpha.282713.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629fb7d97926401bb68d6ffa--gamut-preview.netlify.app>https://629fb7d97926401bb68d6ffa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629fb7d97926401bb68d6ffa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.d58747.0<br/>@codecademy/gamut-labs@31.15.5-alpha.d58747.0<br/>@codecademy/styleguide@57.7.5-alpha.d58747.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629fc51ad466af0058330528--gamut-preview.netlify.app>https://629fc51ad466af0058330528--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629fc51ad466af0058330528>Deploy Logs</a></p>

**Review by borisonr — APPROVED** [review]
seems reasonable to me, but definitely curious to hear what web plat folks think!

**Comment by j10sanders** [comment]
Hi @aresnik11 @thedoomshine can I get a review?  Thanks!

**Review by zippyzow — COMMENTED** [review]
Curious if [you tried importing](https://github.com/w3c/IntersectionObserver/issues/413) if it would work? Also what were you steps to turn off IntersectionObserver in Safari?

**Comment by j10sanders** [comment]
> Curious if [you tried importing](https://github.com/w3c/IntersectionObserver/issues/413) if it would work? Also what were you steps to turn off IntersectionObserver in Safari?

Interesting, I'll give it a shot!

Make sure developer mode is turned on, and then Develop > Experimental Features > IntersectionObserver

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.137-alpha.f9370d.0<br/>@codecademy/gamut-labs@31.15.5-alpha.f9370d.0<br/>@codecademy/styleguide@57.7.5-alpha.f9370d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a22822c84d820427c53e4e--gamut-preview.netlify.app>https://62a22822c84d820427c53e4e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a22822c84d820427c53e4e>Deploy Logs</a></p>

**Comment by j10sanders** [comment]
Can't seem to use the new gamut build since `Module '"@codecademy/gamut"' has no exported member 'Breadcrumbs'.ts` but the import should work based on @zippyzow's comment

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.139-alpha.c41962.0<br/>@codecademy/gamut-labs@32.0.2-alpha.c41962.0<br/>@codecademy/styleguide@58.0.2-alpha.c41962.0<br/></pre>

**Review by dreamwasp — COMMENTED** [review]
i'm still seeing the crash in the PR env with IntersectionObserver turned off 

https://user-images.githubusercontent.com/58054751/172936851-97d9ad80-c2a0-4c6c-8b3c-67006c512cac.mov

**Comment by j10sanders** [comment]
@dreamwasp I didn't push the change to monolith so the homepage will still crash.  But hub pages and catalog page should not crash any longer (that are in experiment).

I'll add to monolith now too...

**Comment by dreamwasp** [comment]
> @dreamwasp I didn't push the change to monolith so the homepage will still crash. But hub pages and catalog page should not crash any longer (that are in experiment).
> 
> I'll add to monolith now too...

ahh that makes sense! sorry i got confused cos your referenced the homepage in your PR. i will check those places now

**Comment by dreamwasp** [comment]
i am still seeing the page crash on those pages too: 

https://user-images.githubusercontent.com/58054751/172940819-d06aee7f-7a28-434a-b5f6-953e9da75247.mov

**Comment by j10sanders** [comment]
@dreamwasp  Here is the monolith PR.  Looking into the portal app...

https://pr-31086-monolith.dev-eks.codecademy.com

**Comment by j10sanders** [comment]
> i am still seeing the page crash on those pages too:
> 
>  iOCrash.mov

@dreamwasp this page is also monolith so should work in https://pr-31086-monolith.dev-eks.codecademy.com/

**Review by dreamwasp — APPROVED** [review]
works for me!

**Review by zippyzow — APPROVED** [review]

**Pull request merged**
