### PR TITLE
feat(Toggle): Set toggle as type button when set as button

### PR DESCRIPTION
**Pull request by jcenglish**
### Overview
We have a toggle button inside of a connected form, which is causing issues because the toggle button submits the form. Setting the toggle as `type='button'` fixes it.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [GRW-303]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[GRW-303]: https://codecademy.atlassian.net/browse/GRW-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6348890b321a7a13c2b15873--gamut-preview.netlify.app>https://6348890b321a7a13c2b15873--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6348890b321a7a13c2b15873>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.213-alpha.6359fd.0<br/>@codecademy/gamut-labs@33.6.4-alpha.6359fd.0<br/>@codecademy/gamut@50.8.2-alpha.6359fd.0<br/>@codecademy/monaco@0.6.93-alpha.6359fd.0<br/>@codecademy/styleguide@61.7.3-alpha.6359fd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63497c8653d49c0b6c064598--gamut-preview.netlify.app>https://63497c8653d49c0b6c064598--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63497c8653d49c0b6c064598>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
love it -- thank you!!!

**Pull request merged**
