### PR TITLE
remove old styleguide files

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Removes of stylesguide files 😄

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://675719a6b6db640761b2e105--gamut-preview.netlify.app>https://675719a6b6db640761b2e105--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/675719a6b6db640761b2e105>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.a5381f.0<br/>@codecademy/gamut@57.5.3-alpha.a5381f.0<br/>@codecademy/gamut-icons@9.34.2-alpha.a5381f.0<br/>@codecademy/gamut-illustrations@0.49.3-alpha.a5381f.0<br/>@codecademy/gamut-kit@0.6.456-alpha.a5381f.0<br/>@codecademy/gamut-patterns@0.9.18-alpha.a5381f.0<br/>@codecademy/gamut-styles@17.1.3-alpha.a5381f.0<br/>@codecademy/gamut-tests@5.1.5-alpha.a5381f.0<br/>@codecademy/macros@3.0.5-alpha.a5381f.0<br/>@codecademy/styleguide@68.1.4-alpha.a5381f.0<br/>@codecademy/variance@0.21.5-alpha.a5381f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67575d31c8ade020f76d6d90--gamut-preview.netlify.app>https://67575d31c8ade020f76d6d90--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67575d31c8ade020f76d6d90>Deploy Logs</a></p>

**Review by LinKCoding — APPROVED** [review]
🪓🪓🪓

**Pull request merged**
