### PR TITLE
refactor(GlobalHeader): Catalog dropdown data and logic 

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

These are changes for the upcoming Catalog dropdown V2 experiment. They are not visible changes for now. 

- Remove Practice tools section from catalogList
- Remove the conditional logic for Resource dropdown that hides Projects and Challenges
- Update data in Top career paths section in catalogList  
- Update title and data in Popular courses section in catalogList
- Update tests where necessary

Data changes should be reflected in this doc: https://docs.google.com/spreadsheets/d/1JpHIxi06SlMvHOwJd5AuKLZBTLGc3cerYtwbg5-Xzvg/edit#gid=1598239929
Tracking should follow this format: 
https://www.notion.so/codecademy/Navigation-catalog-dropdown-V2-55a4c3935c244228aae3db7b5db7fa26#0c68a9bd89e749ff80f1a0cccd3d675e

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DISC-547
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31116)  | [Monolith Env](https://pr-31116-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2109)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2109)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a38f1fd4616f06e677c5b5--gamut-preview.netlify.app>https://62a38f1fd4616f06e677c5b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a38f1fd4616f06e677c5b5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.140-alpha.e450f0.0<br/>@codecademy/gamut-labs@32.0.3-alpha.e450f0.0<br/>@codecademy/styleguide@58.0.3-alpha.e450f0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a656913eb97f2db941699b--gamut-preview.netlify.app>https://62a656913eb97f2db941699b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a656913eb97f2db941699b>Deploy Logs</a></p>

**Review by borisonr — APPROVED** [review]
lgtm!

**Review by dreamwasp — APPROVED** [review]
nice!

**Pull request merged**
