### PR TITLE
fix(HorizontalScrollMenu): fixing multiple root observer query issue

### PR DESCRIPTION
**Pull request by cstatro**
### Overview

Fixes an issue (of my own creation) where if two scroll menus are on the same page only one of them will display contents since we're querying document rather than within our ref. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Review by dreamwasp — COMMENTED** [review]
seems reasonable - any additional context? also would love to test in monolith 🙏

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.116-alpha.924a87.0<br/>@codecademy/gamut-labs@31.11.5-alpha.924a87.0<br/>@codecademy/styleguide@57.0.2-alpha.924a87.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://627021fe3d03b0132429099c--gamut-preview.netlify.app>https://627021fe3d03b0132429099c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/627021fe3d03b0132429099c>Deploy Logs</a></p>

**Review by borisonr — APPROVED** [review]
thanks @cstatro !
@dreamwasp you can see the issue it solved in this [draft pr](https://github.com/codecademy-engineering/portal-app/pull/1896)

without this fix if you had two scroll menus on the same page the second one would render as hidden, and we're adding two of these on the hub pages (to beginner and career sections)

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
