### PR TITLE
feat(Illustration): add AnnouncementIllustration

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

add Announcement illustration

Screen Shot 2022-08-19 at 1 54 51 PM

### PR Checklist

- [ ] Related to designs: [figma](https://www.figma.com/file/79KrWRiCNx933R7kbEG36U/Converting-to-Career-Journey)
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.30.0-alpha.0c6347.0<br/>@codecademy/gamut-kit@0.6.183-alpha.0c6347.0<br/>@codecademy/gamut-labs@33.1.4-alpha.0c6347.0<br/>@codecademy/gamut@50.4.2-alpha.0c6347.0<br/>@codecademy/monaco@0.6.75-alpha.0c6347.0<br/>@codecademy/styleguide@61.2.2-alpha.0c6347.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62ffd0a1139e411be7e521ec--gamut-preview.netlify.app>https://62ffd0a1139e411be7e521ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62ffd0a1139e411be7e521ec>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.30.0-alpha.2e1304.0<br/>@codecademy/gamut-kit@0.6.183-alpha.2e1304.0<br/>@codecademy/gamut-labs@33.1.4-alpha.2e1304.0<br/>@codecademy/gamut@50.4.2-alpha.2e1304.0<br/>@codecademy/monaco@0.6.75-alpha.2e1304.0<br/>@codecademy/styleguide@61.2.2-alpha.2e1304.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62ffd5943a95cb1ec750e5d1--gamut-preview.netlify.app>https://62ffd5943a95cb1ec750e5d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62ffd5943a95cb1ec750e5d1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.30.0-alpha.6644ab.0<br/>@codecademy/gamut-kit@0.6.183-alpha.6644ab.0<br/>@codecademy/gamut-labs@33.1.4-alpha.6644ab.0<br/>@codecademy/gamut@50.4.2-alpha.6644ab.0<br/>@codecademy/monaco@0.6.75-alpha.6644ab.0<br/>@codecademy/styleguide@61.2.2-alpha.6644ab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62ffec0f37e9f830e46daf28--gamut-preview.netlify.app>https://62ffec0f37e9f830e46daf28--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62ffec0f37e9f830e46daf28>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
