### PR TITLE
style(GlobalHeader): Catalog Dropdown V3 updates

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview
**Style**
Switch the course and career sections, so that popular course topics appear first.
Iterate the UI of the “See full catalog” CTA 
Introduce a new section for beginners
Include the user_click event: - Context: global_nav - Target: sorting_quiz

**Copy**
Update section titles and descriptions. 

The subdescription for "popular course topics" and "Docs" sections also need updating. Should be:
Popular course topics --> Explore free or paid courses in topics that interest you.
Docs (in resources menu) --> Find definitions, code syntax, and more -- or contribute your own code documentation.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/40NSFXquATvE19Gm9pnJzI/Catalog-navigation-dropdown?node-id=1740%3A26807
- [x] Related to JIRA ticket: [DISC-785]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions
Interact with the catalog dropdown menu noting the design matches figma (approved by Mark and Tamar) and there is no weird behavior on any screen size. 

The easiest way to test is on [storybook](https://630f8cb720529d38b8236590--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-globalheader--free-user-in-catalog-dropdown-variant#free-user---in-catalog-dropdown-variant). If you want to test on the portal or monolith pr envs, you will need to add your Experimentation ID found in admin user concessions to the [Anon Nav Drodown experiment whitelist](https://app.optimizely.com/v2/projects/21056540090/experiments/21990050105/whitelist) and/or the [Logged In Nav Dropdowns experiment whitelist](https://app.optimizely.com/v2/projects/21056540090/experiments/22003060387/variations). 

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32239)  | [Monolith Env](https://pr-32239-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2477)  | [Portal Env]( https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2477)   |

[DISC-785]: https://codecademy.atlassian.net/browse/DISC-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.708d95.0<br/>@codecademy/gamut-labs@33.2.2-alpha.708d95.0<br/>@codecademy/styleguide@61.4.2-alpha.708d95.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.5d84ea.0<br/>@codecademy/gamut-labs@33.2.2-alpha.5d84ea.0<br/>@codecademy/gamut@50.6.1-alpha.5d84ea.0<br/>@codecademy/monaco@0.6.83-alpha.5d84ea.0<br/>@codecademy/styleguide@61.4.2-alpha.5d84ea.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630f8f92bf2db339d1144d6e--gamut-preview.netlify.app>https://630f8f92bf2db339d1144d6e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630f8f92bf2db339d1144d6e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.195-alpha.90fa75.0<br/>@codecademy/gamut-labs@33.2.3-alpha.90fa75.0<br/>@codecademy/styleguide@61.4.3-alpha.90fa75.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630f98c3d02b9200a6240823--gamut-preview.netlify.app>https://630f98c3d02b9200a6240823--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630f98c3d02b9200a6240823>Deploy Logs</a></p>

**Comment by borisonr** [comment]
i think this looks a little off on tablet?
Screen Shot 2022-08-31 at 1 33 43 PM

**Comment by zippyzow** [comment]
> i think this looks a little off on tablet? Screen Shot 2022-08-31 at 1 33 43 PM

nice catch, will fix

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.195-alpha.e38a67.0<br/>@codecademy/gamut-labs@33.2.3-alpha.e38a67.0<br/>@codecademy/styleguide@61.4.3-alpha.e38a67.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630fad5d7d3cae1c9b56d7da--gamut-preview.netlify.app>https://630fad5d7d3cae1c9b56d7da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630fad5d7d3cae1c9b56d7da>Deploy Logs</a></p>

**Review by borisonr — APPROVED** [review]
looks great!

**Pull request merged**
