### PR TITLE
fix(Flyout): move background color to fix overflow

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Currently, if flyout overflows, the background color only extends to the bottom of the screen and on scroll is transparent. This fixes that.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Look at the new Flyout story for with overflow and confirm the background color stays on scroll

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34039)  | [Monolith Env](https://pr-34039-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/912)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-912)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.258-alpha.2fc5c3.0<br/>@codecademy/gamut-labs@34.0.5-alpha.2fc5c3.0<br/>@codecademy/gamut@51.6.2-alpha.2fc5c3.0<br/>@codecademy/monaco@0.6.116-alpha.2fc5c3.0<br/>@codecademy/styleguide@62.7.3-alpha.2fc5c3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://639cce5fb5d258131fc14453--gamut-preview.netlify.app>https://639cce5fb5d258131fc14453--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/639cce5fb5d258131fc14453>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.258-alpha.692f4b.0<br/>@codecademy/gamut-labs@34.0.5-alpha.692f4b.0<br/>@codecademy/gamut@51.6.2-alpha.692f4b.0<br/>@codecademy/monaco@0.6.116-alpha.692f4b.0<br/>@codecademy/styleguide@62.7.3-alpha.692f4b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://639cd32335081617bc0a8eb4--gamut-preview.netlify.app>https://639cd32335081617bc0a8eb4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/639cd32335081617bc0a8eb4>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
perfection

**Review by medhatnar — APPROVED** [review]
LGTM! thanks for being speedy on this

**Pull request merged**
