### PR TITLE
fix(GlobalHeader): add `business solutions` for Trial / Pro learners

### PR DESCRIPTION
**Pull request by JahazielGuzman**
### Overview

This PR adds the "Business Solutions" header link for Pro and Trial users to the `GlobalHeader`. Prior to this PR the link only appears for free users but not Pro or Trial.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [PX-5849](https://codecademy.atlassian.net/browse/PX-5849)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Follow each step as a Pro, Trial and Free user
2. visit the catalog page on the portal app env, and the dashboard page on the monolith env
3. Notice the "Business Solutions" link in the header.
4. Click it make sure it takes you where it should.
5. ...
6. Profit!

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31487)  | [Monolith Env](https://pr-31487-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2205)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2205)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.152-alpha.261dbd.0<br/>@codecademy/gamut-labs@32.3.1-alpha.261dbd.0<br/>@codecademy/styleguide@58.1.6-alpha.261dbd.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.152-alpha.80b9ad.0<br/>@codecademy/gamut-labs@32.3.1-alpha.80b9ad.0<br/>@codecademy/styleguide@58.1.6-alpha.80b9ad.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62c45ad7abadbf2625b59b01--gamut-preview.netlify.app>https://62c45ad7abadbf2625b59b01--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62c45ad7abadbf2625b59b01>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.152-alpha.2613d2.0<br/>@codecademy/gamut-labs@32.3.1-alpha.2613d2.0<br/>@codecademy/styleguide@58.1.6-alpha.2613d2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.152-alpha.923774.0<br/>@codecademy/gamut-labs@32.3.1-alpha.923774.0<br/>@codecademy/styleguide@58.1.6-alpha.923774.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.152-alpha.8b301a.0<br/>@codecademy/gamut-labs@32.3.1-alpha.8b301a.0<br/>@codecademy/styleguide@58.1.6-alpha.8b301a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62c5e758d315bb05967f2756--gamut-preview.netlify.app>https://62c5e758d315bb05967f2756--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62c5e758d315bb05967f2756>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
looks good to me! waiting to ✅ till  @Codecademy/discovery take a final look

**Comment by JahazielGuzman** [comment]
> As a pro trial user, I see Business Solutions on desktop, but not on the mobile menu. I see Business Solutions for both dekstop and mobile for anon and free users fine. Screen Shot 2022-07-07 at 1 26 08 PM Screen Shot 2022-07-07 at 1 26 22 PM

Oh, I need to update the gamut kit again after a recent commit. Once the environment rebuilds I'll let you know and everything should be good 🙂

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.156-alpha.709a57.0<br/>@codecademy/gamut-labs@32.6.1-alpha.709a57.0<br/>@codecademy/styleguide@58.1.11-alpha.709a57.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62c8869c21017f0065e91fff--gamut-preview.netlify.app>https://62c8869c21017f0065e91fff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62c8869c21017f0065e91fff>Deploy Logs</a></p>

**Comment by JahazielGuzman** [comment]
@zippyzow Both monolith and catalog portal-app page now display `Business Solutions` link in the global header.

**Review by zippyzow — APPROVED** [review]
Looks good!

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
