### PR TITLE
chore(deps): bump tracking from 0.26.0 to 1.0.1

### PR DESCRIPTION
**Pull request by BandanaKM**
### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [WEB-2175](https://codecademy.atlassian.net/browse/WEB-2175)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

Hard to test, but I'm confirming that it's working by:
1. Viewing that it's able to read the type correctly in the Score Summary component, the one component that is using tracking for types. 
2. Testing it out in storybook locally

Screen Shot 2022-11-17 at 11 58 35 AM

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6375c77bb8ee06333966619d--gamut-preview.netlify.app>https://6375c77bb8ee06333966619d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6375c77bb8ee06333966619d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.231-alpha.637d03.0<br/>@codecademy/gamut-labs@33.7.3-alpha.637d03.0<br/>@codecademy/styleguide@62.4.2-alpha.637d03.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6377010720d43f63d103ab1b--gamut-preview.netlify.app>https://6377010720d43f63d103ab1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6377010720d43f63d103ab1b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.234-alpha.20b791.0<br/>@codecademy/gamut-labs@33.8.3-alpha.20b791.0<br/>@codecademy/styleguide@62.5.3-alpha.20b791.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://637708d30c68416abf217247--gamut-preview.netlify.app>https://637708d30c68416abf217247--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/637708d30c68416abf217247>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
