### PR TITLE
chore: gitignore update & node-sass V5

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

* Variance: Update gitignore for variance to prevent issues if `.d.ts` files get added to the src directory
* Styleguide: Downgrade back to `node-sass` to prevent console warnings.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.4.5-alpha.a12b2d.0<br/>@codecademy/gamut-illustrations@0.28.5-alpha.a12b2d.0<br/>@codecademy/gamut-kit@0.6.168-alpha.a12b2d.0<br/>@codecademy/gamut-labs@33.0.4-alpha.a12b2d.0<br/>@codecademy/gamut-patterns@0.8.11-alpha.a12b2d.0<br/>@codecademy/gamut-styles@14.0.2-alpha.a12b2d.0<br/>@codecademy/gamut-tests@4.0.10-alpha.a12b2d.0<br/>@codecademy/gamut@49.0.2-alpha.a12b2d.0<br/>@codecademy/markdown-overrides@0.9.8-alpha.a12b2d.0<br/>@codecademy/monaco@0.6.63-alpha.a12b2d.0<br/>@codecademy/styleguide@60.0.2-alpha.a12b2d.0<br/>@codecademy/variance@0.20.2-alpha.a12b2d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e3fbc2e5c279032aa6cd3b--gamut-preview.netlify.app>https://62e3fbc2e5c279032aa6cd3b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e3fbc2e5c279032aa6cd3b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.4.5-alpha.818cb7.0<br/>@codecademy/gamut-illustrations@0.28.5-alpha.818cb7.0<br/>@codecademy/gamut-kit@0.6.168-alpha.818cb7.0<br/>@codecademy/gamut-labs@33.0.4-alpha.818cb7.0<br/>@codecademy/gamut-patterns@0.8.11-alpha.818cb7.0<br/>@codecademy/gamut-styles@14.0.2-alpha.818cb7.0<br/>@codecademy/gamut-tests@4.0.10-alpha.818cb7.0<br/>@codecademy/gamut@49.0.2-alpha.818cb7.0<br/>@codecademy/markdown-overrides@0.9.8-alpha.818cb7.0<br/>@codecademy/monaco@0.6.63-alpha.818cb7.0<br/>@codecademy/styleguide@60.0.2-alpha.818cb7.0<br/>@codecademy/variance@0.20.2-alpha.818cb7.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
🚢

**Pull request merged**
