### PR TITLE
feat(JiraIcon): Adding it

### PR DESCRIPTION
**Pull request by MattSchiller**
### Overview

Adds the JiraIcon

Just wanted to use this icon, so I figured I should add it to Gamut instead of just my personal repo so I can benefit from all the other icon-y stuff.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [INT-72](https://codecademy.atlassian.net/browse/INT-72)
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by dreamwasp — COMMENTED** [review]
could you add example under the Vendor header ([here](https://gamut.codecademy.com/?path=/docs/atoms-icons-regular--editable-icon))

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.0.3-alpha.8c3afc.0<br/>@codecademy/gamut-kit@0.6.35-alpha.8c3afc.0<br/>@codecademy/gamut-labs@28.4.4-alpha.8c3afc.0<br/>@codecademy/gamut@42.1.3-alpha.8c3afc.0<br/>@codecademy/monaco@0.5.26-alpha.8c3afc.0<br/>@codecademy/styleguide@52.2.4-alpha.8c3afc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61bbaab7b8bb410a53db3aa1--gamut-preview.netlify.app>https://61bbaab7b8bb410a53db3aa1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61bbaab7b8bb410a53db3aa1>Deploy Logs</a></p>

**Review by dreamwasp — CHANGES_REQUESTED** [review]
this also should be added to the `packages/gamut-icons/src/icons/regular/index.tsx` file, then you're good to 🛳

**Comment by MattSchiller** [comment]
> this also should be added to the `packages/gamut-icons/src/icons/regular/index.tsx` file, then you're good to 🛳

@dreamwasp Is there a particular way to add that? It looks like that index is autogenerated/gitignored in my IDE

**Review by dreamwasp — APPROVED** [review]
i'm an idiot, forgot to yarn build before spinning it up locally 🛳

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.0.3-alpha.e97dc7.0<br/>@codecademy/gamut-kit@0.6.38-alpha.e97dc7.0<br/>@codecademy/gamut-labs@28.6.1-alpha.e97dc7.0<br/>@codecademy/gamut@42.2.2-alpha.e97dc7.0<br/>@codecademy/monaco@0.5.28-alpha.e97dc7.0<br/>@codecademy/styleguide@52.4.1-alpha.e97dc7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d31c4087cc532491ec2b73--gamut-preview.netlify.app>https://61d31c4087cc532491ec2b73--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d31c4087cc532491ec2b73>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d47dfb7678e24862ca92a0--gamut-preview.netlify.app>https://61d47dfb7678e24862ca92a0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d47dfb7678e24862ca92a0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d5a931fe1fba571d0629e3--gamut-preview.netlify.app>https://61d5a931fe1fba571d0629e3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d5a931fe1fba571d0629e3>Deploy Logs</a></p>

**Pull request merged**
