### PR TITLE
fix(DropdownList): Make dropdown list items focusable

### PR DESCRIPTION
**Pull request by katiezutter**
Outcome of pairing with @dreamwasp and @mstykmshy.

### Overview

Accessibility fix: add focus to dropdown list items.

This is a stopgap solution until [WEB-1769](https://codecademy.atlassian.net/browse/WEB-1769) is picked up and dropdown interactions from the global header can be split out and shared with `DropdownButton`.

Screen Shot 2022-09-12 at 11 40 14 AM

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2087](https://codecademy.atlassian.net/browse/WEB-2087), [WEBREQ-99](https://codecademy.atlassian.net/browse/WEBREQ-99)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Two PRs have been opened in the monolith and portal-app using the alpha package - please check the testing instructions in both of these PRs to ensure the behavior is correct in the places we are using the dropdown button.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32474)  | [Monolith Env](https://pr-32474-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2548)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2548)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.200-alpha.e06ba3.0<br/>@codecademy/gamut-labs@33.3.4-alpha.e06ba3.0<br/>@codecademy/styleguide@61.5.7-alpha.e06ba3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://631b91b2b9acb80f485ae4e1--gamut-preview.netlify.app>https://631b91b2b9acb80f485ae4e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/631b91b2b9acb80f485ae4e1>Deploy Logs</a></p>

**Review by sylvanasantos — APPROVED** [review]

**Review by dreamwasp — COMMENTED** [review]
lgtm !! could you add the monolith + portal alpha PRs? I want to make sure it doesn't trigger unexpected e2e accessibility failures anywhere else

**Comment by katiezutter** [comment]
> lgtm !! could you add the monolith + portal alpha PRs? I want to make sure it doesn't trigger unexpected e2e accessibility failures anywhere else

@dreamwasp 😄...I mistakenly added the testing instructions into a commented out section...they are uncommented now thanks for catching that!

**Review by dreamwasp — APPROVED** [review]
🙏

**Pull request merged**
