### PR TITLE
fix(ScoreSummary): Use List element for subjects in ScoreSummary

### PR DESCRIPTION
**Pull request by mstykmshy**
### Overview

- Refactors ScoreSummary to use a List component for the individual subject scores

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EGG-3032]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33940)  | [Monolith Env](https://pr-33940-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/844)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-844)   |

[EGG-3032]: https://codecademy.atlassian.net/browse/EGG-3032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.253-alpha.bd1e0b.0<br/>@codecademy/gamut-labs@33.11.3-alpha.bd1e0b.0<br/>@codecademy/styleguide@62.6.10-alpha.bd1e0b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63981e4b1983414ec3a6dbb4--gamut-preview.netlify.app>https://63981e4b1983414ec3a6dbb4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63981e4b1983414ec3a6dbb4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.253-alpha.338482.0<br/>@codecademy/gamut-labs@33.11.3-alpha.338482.0<br/>@codecademy/styleguide@62.6.10-alpha.338482.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6398456e4c878d78945d211b--gamut-preview.netlify.app>https://6398456e4c878d78945d211b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6398456e4c878d78945d211b>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
lgtm! will do a final look + test more once merge conflicts are resolved

**Comment by mstykmshy** [comment]
This issue is fixed in https://github.com/Codecademy/gamut/pull/2650 instead

**Pull request closed without merging**
