### PR TITLE
fix(HorizontalScrollMenu): fixed axe issue with hidden elements receiving focus

### PR DESCRIPTION
**Pull request by cstatro**
### PR Checklist

fixes an accessibility issue where `aria-hidden` elements can't have focusable elements within them. By creating this psuedo selector on attribute we make sure that focus won't go in. 

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.102-alpha.f502c1.0<br/>@codecademy/gamut-labs@31.6.1-alpha.f502c1.0<br/>@codecademy/styleguide@56.4.1-alpha.f502c1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://625743c46761901e10854c6c--gamut-preview.netlify.app>https://625743c46761901e10854c6c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/625743c46761901e10854c6c>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
could you put link yr monolith implementation? i just wanna make sure this passes CI there 🙏

**Comment by cstatro** [comment]
yep got a passing e2e run here https://app.circleci.com/pipelines/github/codecademy-engineering/Codecademy/126531/workflows/d38811b5-4b9b-4009-8a09-4a967c4c38e3/jobs/1875913

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
