### PR TITLE
chore(OpenAiIcon, ThumbDownIcon and ThumbUpIcon): add new icons

### PR DESCRIPTION
**Pull request by JahazielGuzman**
### Overview
Adds Open AI Icon, Thumb down icon and thumb up icon

### PR Checklist

- [ ] Related to designs: https://www.figma.com/file/7YDHHaKnsuzC2KWFq1ZkXK/Career-Services?node-id=643%3A52855&mode=dev
- [ ] Related to JIRA ticket: [LEGO-3360](https://codecademy.atlassian.net/browse/LEGO-3360)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[LEGO-3360]: https://codecademy.atlassian.net/browse/LEGO-3360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.5-alpha.79821d.0<br/>@codecademy/gamut-kit@0.6.335-alpha.79821d.0<br/>@codecademy/gamut-labs@35.15.8-alpha.79821d.0<br/>@codecademy/gamut@55.1.13-alpha.79821d.0<br/>@codecademy/monaco@0.7.39-alpha.79821d.0<br/>@codecademy/styleguide@66.1.17-alpha.79821d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64baef1a7c2b22006f328e5f--gamut-preview.netlify.app>https://64baef1a7c2b22006f328e5f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64baef1a7c2b22006f328e5f>Deploy Logs</a></p>

**Review by j10sanders — APPROVED** [review]

**Comment by j10sanders** [comment]
The thumbs up and thumbs down look strange in storybook 
Screenshot 2023-07-26 at 3 35 39 PM

**Comment by j10sanders** [comment]
I've also installed gamut-kit 0.6.335-alpha.79821d.0 but for some reason don't have access to these icons in portal app.  Any idea why?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.5-alpha.e05d35.0<br/>@codecademy/gamut-kit@0.6.336-alpha.e05d35.0<br/>@codecademy/gamut-labs@35.15.9-alpha.e05d35.0<br/>@codecademy/gamut@55.1.14-alpha.e05d35.0<br/>@codecademy/styleguide@66.1.19-alpha.e05d35.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64c2ba3065a2e505b18a2ba3--gamut-preview.netlify.app>https://64c2ba3065a2e505b18a2ba3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64c2ba3065a2e505b18a2ba3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.5-alpha.93fa59.0<br/>@codecademy/gamut-kit@0.6.336-alpha.93fa59.0<br/>@codecademy/gamut-labs@35.15.9-alpha.93fa59.0<br/>@codecademy/gamut@55.1.14-alpha.93fa59.0<br/>@codecademy/styleguide@66.1.19-alpha.93fa59.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64c2ce32426c2408f977ab1b--gamut-preview.netlify.app>https://64c2ce32426c2408f977ab1b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64c2ce32426c2408f977ab1b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@9.3.5-alpha.868f8b.0<br/>@codecademy/gamut-kit@0.6.336-alpha.868f8b.0<br/>@codecademy/gamut-labs@35.15.9-alpha.868f8b.0<br/>@codecademy/gamut@55.1.14-alpha.868f8b.0<br/>@codecademy/styleguide@66.1.19-alpha.868f8b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64c2ea40d4eb2d007315f5bb--gamut-preview.netlify.app>https://64c2ea40d4eb2d007315f5bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64c2ea40d4eb2d007315f5bb>Deploy Logs</a></p>

**Comment by j10sanders** [comment]
@katiezutter they look great in storybook!

**Pull request merged**
