### PR TITLE
fix(AppHeader): Change title to aria-label

### PR DESCRIPTION
**Pull request by jrood**
### PR Checklist

- [x] Related to JIRA ticket: [REACH-2506]
- [x] I have run this code to verify it works

#### Testing Instructions

In storybook, inspect the AppHeader and see that it has an `aria-label` instead of a `title` attribute.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34774)  |   |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/mono/pull/1321)  |  |

[REACH-2506]: https://codecademy.atlassian.net/browse/REACH-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.284-alpha.6557ec.0<br/>@codecademy/gamut-labs@35.5.10-alpha.6557ec.0<br/>@codecademy/styleguide@63.5.8-alpha.6557ec.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63ee80b037be1d0301059bd2--gamut-preview.netlify.app>https://63ee80b037be1d0301059bd2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63ee80b037be1d0301059bd2>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
could you add the `gamut-kit` alpha packages to portal + the monolith and link them here? it may seem silly for a small change but you'd be surprised when can break e2e tests

**Comment by jrood** [comment]
@dreamwasp for sure, just added and linked in the description!

**Comment by zippyzow** [comment]
@jrood it looks like there is a [test failing on the portal branch](https://github.com/codecademy-engineering/mono/actions/runs/4233833568/jobs/7355368867). Maybe rerun if its just a timeout error to make sure?

**Comment by jrood** [comment]
@zippyzow ah thanks. Yes it was indeed a timeout error. I re-ran the failed check and it has now succeeded.

**Review by dreamwasp — APPROVED** [review]
this all looks good to me - the pr title should be edited to match [this format](https://github.com/Codecademy/gamut#pr-title-format) to get that CI check to pass but after that you can ✅

**Pull request merged**
