### PR TITLE
feat(EditableIcon): Add SparkleIcon, BugIcon, ThumbsUpFilledIcon, ThumbsDownFilledIcon, and OpenAIFullIcon

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Adds SparkleIcon, BugIcon, ThumbsUpFilledIcon, ThumbsDownFilledIcon, and OpenAIFullIcon.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/skDEunydk4AfvXX40kXV6a/Dynamic-Hints?type=design&node-id=1548-2644&mode=design&t=WGSb625wWw3bLVYx-0
- [x] Related to JIRA ticket: [LEGO-3539](https://codecademy.atlassian.net/browse/LEGO-3539)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Ensure that all five icons are appearing in Storybook: https://653fdcd8d5f60200774b7616--gamut-preview.netlify.app/?path=/docs/atoms-icons-regular--editable-icon and check the linked preview environments.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36676)  | [Monolith Env](https://pr-36676-monolith.dev-eks.codecademy.com/learn) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/3942)  | [Portal Env](https://tayra.codecademy.com/projects/practice/honey-production?PR_ENV=le-pr-3942)   |

[LEGO-3539]: https://codecademy.atlassian.net/browse/LEGO-3539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.3-alpha.c26c37.0<br/>@codecademy/gamut-icons@9.4.4-alpha.c26c37.0<br/>@codecademy/gamut-kit@0.6.358-alpha.c26c37.0<br/>@codecademy/styleguide@66.5.10-alpha.c26c37.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://653fca9b8607053acd76c26d--gamut-preview.netlify.app>https://653fca9b8607053acd76c26d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/653fca9b8607053acd76c26d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.3-alpha.f14241.0<br/>@codecademy/gamut-icons@9.4.4-alpha.f14241.0<br/>@codecademy/gamut-kit@0.6.358-alpha.f14241.0<br/>@codecademy/styleguide@66.5.10-alpha.f14241.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://653fdcd8d5f60200774b7616--gamut-preview.netlify.app>https://653fdcd8d5f60200774b7616--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/653fdcd8d5f60200774b7616>Deploy Logs</a></p>

**Review by natalieweesh — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.5-alpha.8d6a64.0<br/>@codecademy/gamut-icons@9.6.1-alpha.8d6a64.0<br/>@codecademy/gamut-kit@0.6.360-alpha.8d6a64.0<br/>@codecademy/styleguide@66.5.12-alpha.8d6a64.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://654116652cf10b0c3ef0b4c1--gamut-preview.netlify.app>https://654116652cf10b0c3ef0b4c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/654116652cf10b0c3ef0b4c1>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]

**Pull request merged**
