### PR TITLE
feat: Allowing overflow in DataTable

### PR DESCRIPTION
**Pull request by MattSchiller**
### Overview

I have a use-case for the <DataTable /> and I wanted to have tooltips that could overflow out of the row they're in.

This seemed like the easiest way to do that.

Adds the ability to allow overflow elements in your data table component

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: INT-158
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.46-alpha.2001a2.0<br/>@codecademy/gamut-labs@29.0.1-alpha.2001a2.0<br/>@codecademy/gamut@44.0.1-alpha.2001a2.0<br/>@codecademy/monaco@0.6.1-alpha.2001a2.0<br/>@codecademy/styleguide@54.0.1-alpha.2001a2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f039c89c21f37bf4604c63--gamut-preview.netlify.app>https://61f039c89c21f37bf4604c63--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f039c89c21f37bf4604c63>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.46-alpha.307ce3.0<br/>@codecademy/gamut-labs@29.0.1-alpha.307ce3.0<br/>@codecademy/gamut@44.0.1-alpha.307ce3.0<br/>@codecademy/monaco@0.6.1-alpha.307ce3.0<br/>@codecademy/styleguide@54.0.1-alpha.307ce3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f05461aad7bf8c556c464e--gamut-preview.netlify.app>https://61f05461aad7bf8c556c464e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f05461aad7bf8c556c464e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.46-alpha.da1053.0<br/>@codecademy/gamut-labs@29.0.1-alpha.da1053.0<br/>@codecademy/gamut@44.0.1-alpha.da1053.0<br/>@codecademy/monaco@0.6.1-alpha.da1053.0<br/>@codecademy/styleguide@54.0.1-alpha.da1053.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f0800652b0d6005c8533cd--gamut-preview.netlify.app>https://61f0800652b0d6005c8533cd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f0800652b0d6005c8533cd>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
nice! could you link the accompanying PR for where you're using this in nexus? just wanna play around with a live example before i ✅ 

alternatively, you could add a brief example to the docs here w/ tooltip

**Comment by MattSchiller** [comment]
> nice! could you link the accompanying PR for where you're using this in nexus? just wanna play around with a live example before i ✅
> 
> alternatively, you could add a brief example to the docs here w/ tooltip

How's this look?
https://github.com/codecademy-engineering/nexus/pull/36

I'm less inclined to update the docs since I think they're a bit out of date anyway when it comes to the various states available in `ColEl`, but I _did_ add a comment about what it's for, so it's a bit more discoverable there. I wish the types were a bit more robust in allowing star-comments to propagate through the `styled` generation. Alas, nice to haves.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.46-alpha.284dda.0<br/>@codecademy/gamut-labs@29.0.1-alpha.284dda.0<br/>@codecademy/gamut@44.0.1-alpha.284dda.0<br/>@codecademy/monaco@0.6.1-alpha.284dda.0<br/>@codecademy/styleguide@54.0.1-alpha.284dda.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f08e5bd735430e2a3de446--gamut-preview.netlify.app>https://61f08e5bd735430e2a3de446--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f08e5bd735430e2a3de446>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
live laugh love it

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f179d54efc61e1dd4b4c3a--gamut-preview.netlify.app>https://61f179d54efc61e1dd4b4c3a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f179d54efc61e1dd4b4c3a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.48-alpha.e531cb.0<br/>@codecademy/gamut-labs@29.1.1-alpha.e531cb.0<br/>@codecademy/gamut@44.0.2-alpha.e531cb.0<br/>@codecademy/monaco@0.6.2-alpha.e531cb.0<br/>@codecademy/styleguide@54.0.3-alpha.e531cb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f2f918732d373459720bf2--gamut-preview.netlify.app>https://61f2f918732d373459720bf2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f2f918732d373459720bf2>Deploy Logs</a></p>

**Pull request merged**
