### PR TITLE
refactor(Footer + FromSkillsoftLogo): clean up + add story

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Cleans up footer feature flag things + adds story for new FromSkillsoftLogo

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.96-alpha.84184e.0<br/>@codecademy/gamut-labs@31.3.1-alpha.84184e.0<br/>@codecademy/styleguide@56.2.1-alpha.84184e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624c3df1318db4471f50fdc1--gamut-preview.netlify.app>https://624c3df1318db4471f50fdc1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624c3df1318db4471f50fdc1>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624c51d4266d7a41c2f55030--gamut-preview.netlify.app>https://624c51d4266d7a41c2f55030--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624c51d4266d7a41c2f55030>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.97-alpha.fbd639.0<br/>@codecademy/gamut-labs@31.3.2-alpha.fbd639.0<br/>@codecademy/styleguide@56.2.2-alpha.fbd639.0<br/></pre>

**Pull request merged**
