### PR TITLE
feat: update packages to support React v18

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Extension of #2557

* Update the peer dependency versions of React to support react 17 and 18 with local development against v18
* Updates libraries to the versions that support both React 17 and 18

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.a0fbe3.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.a0fbe3.0<br/>@codecademy/gamut-kit@0.6.246-alpha.a0fbe3.0<br/>@codecademy/gamut-labs@33.9.2-alpha.a0fbe3.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.a0fbe3.0<br/>@codecademy/gamut-styles@14.2.4-alpha.a0fbe3.0<br/>@codecademy/gamut-tests@4.0.21-alpha.a0fbe3.0<br/>@codecademy/gamut@51.5.2-alpha.a0fbe3.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.a0fbe3.0<br/>@codecademy/monaco@0.6.113-alpha.a0fbe3.0<br/>@codecademy/styleguide@62.6.2-alpha.a0fbe3.0<br/>@codecademy/variance@0.20.6-alpha.a0fbe3.0<br/></pre>

**Comment by fahmij8** [comment]
Hello Jake!
I'm a frontend developer who works with the Gamut design system. I just wondering when this is going to be released? perhaps is there anything I could do to help? thank you ✨

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.2f3a19.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.2f3a19.0<br/>@codecademy/gamut-kit@0.6.253-alpha.2f3a19.0<br/>@codecademy/gamut-labs@33.11.3-alpha.2f3a19.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.2f3a19.0<br/>@codecademy/gamut-styles@14.2.4-alpha.2f3a19.0<br/>@codecademy/gamut-tests@4.0.21-alpha.2f3a19.0<br/>@codecademy/gamut@51.5.3-alpha.2f3a19.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.2f3a19.0<br/>@codecademy/monaco@0.6.114-alpha.2f3a19.0<br/>@codecademy/styleguide@62.6.10-alpha.2f3a19.0<br/>@codecademy/variance@0.20.6-alpha.2f3a19.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.801403.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.801403.0<br/>@codecademy/gamut-kit@0.6.253-alpha.801403.0<br/>@codecademy/gamut-labs@33.11.3-alpha.801403.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.801403.0<br/>@codecademy/gamut-styles@14.2.4-alpha.801403.0<br/>@codecademy/gamut-tests@4.0.21-alpha.801403.0<br/>@codecademy/gamut@51.5.3-alpha.801403.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.801403.0<br/>@codecademy/monaco@0.6.114-alpha.801403.0<br/>@codecademy/styleguide@62.6.10-alpha.801403.0<br/>@codecademy/variance@0.20.6-alpha.801403.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.7d4aaf.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.7d4aaf.0<br/>@codecademy/gamut-kit@0.6.253-alpha.7d4aaf.0<br/>@codecademy/gamut-labs@33.11.3-alpha.7d4aaf.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.7d4aaf.0<br/>@codecademy/gamut-styles@14.2.4-alpha.7d4aaf.0<br/>@codecademy/gamut-tests@4.0.21-alpha.7d4aaf.0<br/>@codecademy/gamut@51.5.3-alpha.7d4aaf.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.7d4aaf.0<br/>@codecademy/monaco@0.6.114-alpha.7d4aaf.0<br/>@codecademy/styleguide@62.6.10-alpha.7d4aaf.0<br/>@codecademy/variance@0.20.6-alpha.7d4aaf.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.646aac.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.646aac.0<br/>@codecademy/gamut-kit@0.6.253-alpha.646aac.0<br/>@codecademy/gamut-labs@33.11.3-alpha.646aac.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.646aac.0<br/>@codecademy/gamut-styles@14.2.4-alpha.646aac.0<br/>@codecademy/gamut-tests@4.0.21-alpha.646aac.0<br/>@codecademy/gamut@51.5.3-alpha.646aac.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.646aac.0<br/>@codecademy/monaco@0.6.114-alpha.646aac.0<br/>@codecademy/styleguide@62.6.10-alpha.646aac.0<br/>@codecademy/variance@0.20.6-alpha.646aac.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.6c1d55.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.6c1d55.0<br/>@codecademy/gamut-kit@0.6.253-alpha.6c1d55.0<br/>@codecademy/gamut-labs@33.11.3-alpha.6c1d55.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.6c1d55.0<br/>@codecademy/gamut-styles@14.2.4-alpha.6c1d55.0<br/>@codecademy/gamut-tests@4.0.21-alpha.6c1d55.0<br/>@codecademy/gamut@51.5.3-alpha.6c1d55.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.6c1d55.0<br/>@codecademy/monaco@0.6.114-alpha.6c1d55.0<br/>@codecademy/styleguide@62.6.10-alpha.6c1d55.0<br/>@codecademy/variance@0.20.6-alpha.6c1d55.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.3e1199.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.3e1199.0<br/>@codecademy/gamut-kit@0.6.253-alpha.3e1199.0<br/>@codecademy/gamut-labs@33.11.3-alpha.3e1199.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.3e1199.0<br/>@codecademy/gamut-styles@14.2.4-alpha.3e1199.0<br/>@codecademy/gamut-tests@4.0.21-alpha.3e1199.0<br/>@codecademy/gamut@51.5.3-alpha.3e1199.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.3e1199.0<br/>@codecademy/monaco@0.6.114-alpha.3e1199.0<br/>@codecademy/styleguide@62.6.10-alpha.3e1199.0<br/>@codecademy/variance@0.20.6-alpha.3e1199.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.b6a8d8.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.b6a8d8.0<br/>@codecademy/gamut-kit@0.6.254-alpha.b6a8d8.0<br/>@codecademy/gamut-labs@34.0.1-alpha.b6a8d8.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.b6a8d8.0<br/>@codecademy/gamut-styles@14.2.4-alpha.b6a8d8.0<br/>@codecademy/gamut-tests@4.0.21-alpha.b6a8d8.0<br/>@codecademy/gamut@51.5.3-alpha.b6a8d8.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.b6a8d8.0<br/>@codecademy/monaco@0.6.114-alpha.b6a8d8.0<br/>@codecademy/styleguide@62.6.11-alpha.b6a8d8.0<br/>@codecademy/variance@0.20.6-alpha.b6a8d8.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.86dcc7.0<br/>@codecademy/gamut-icons@7.9.6-alpha.86dcc7.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.86dcc7.0<br/>@codecademy/gamut-kit@0.6.254-alpha.86dcc7.0<br/>@codecademy/gamut-labs@34.0.1-alpha.86dcc7.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.86dcc7.0<br/>@codecademy/gamut-styles@14.2.4-alpha.86dcc7.0<br/>@codecademy/gamut-tests@4.0.21-alpha.86dcc7.0<br/>@codecademy/gamut@51.5.3-alpha.86dcc7.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.86dcc7.0<br/>@codecademy/monaco@0.6.114-alpha.86dcc7.0<br/>@codecademy/styleguide@62.6.11-alpha.86dcc7.0<br/>@codecademy/variance@0.20.6-alpha.86dcc7.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.0c5982.0<br/>@codecademy/gamut-icons@7.9.6-alpha.0c5982.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.0c5982.0<br/>@codecademy/gamut-kit@0.6.258-alpha.0c5982.0<br/>@codecademy/gamut-labs@34.0.5-alpha.0c5982.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.0c5982.0<br/>@codecademy/gamut-styles@14.2.4-alpha.0c5982.0<br/>@codecademy/gamut-tests@4.0.21-alpha.0c5982.0<br/>@codecademy/gamut@51.6.2-alpha.0c5982.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.0c5982.0<br/>@codecademy/monaco@0.6.116-alpha.0c5982.0<br/>@codecademy/styleguide@62.7.3-alpha.0c5982.0<br/>@codecademy/variance@0.20.6-alpha.0c5982.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.64be05.0<br/>@codecademy/gamut-icons@7.9.6-alpha.64be05.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.64be05.0<br/>@codecademy/gamut-kit@0.6.259-alpha.64be05.0<br/>@codecademy/gamut-labs@34.0.6-alpha.64be05.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.64be05.0<br/>@codecademy/gamut-styles@14.2.4-alpha.64be05.0<br/>@codecademy/gamut-tests@4.0.21-alpha.64be05.0<br/>@codecademy/gamut@51.6.3-alpha.64be05.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.64be05.0<br/>@codecademy/monaco@0.6.117-alpha.64be05.0<br/>@codecademy/styleguide@62.7.4-alpha.64be05.0<br/>@codecademy/variance@0.20.6-alpha.64be05.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.edcdf7.0<br/>@codecademy/gamut-icons@7.9.6-alpha.edcdf7.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.edcdf7.0<br/>@codecademy/gamut-kit@0.6.259-alpha.edcdf7.0<br/>@codecademy/gamut-labs@34.0.6-alpha.edcdf7.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.edcdf7.0<br/>@codecademy/gamut-styles@14.2.4-alpha.edcdf7.0<br/>@codecademy/gamut-tests@4.0.21-alpha.edcdf7.0<br/>@codecademy/gamut@51.6.3-alpha.edcdf7.0<br/>@codecademy/macros@3.0.3-alpha.edcdf7.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.edcdf7.0<br/>@codecademy/monaco@0.6.117-alpha.edcdf7.0<br/>@codecademy/styleguide@62.7.4-alpha.edcdf7.0<br/>@codecademy/variance@0.20.6-alpha.edcdf7.0<br/></pre>

**Comment by jakemhiller** [comment]
> Hello Jake! I'm a frontend developer who works with the Gamut design system. I just wondering when this is going to be released? perhaps is there anything I could do to help? thank you ✨

Hi @fahmij8 ! that's awesome that you're using Gamut! We're taking a step back and taking a more iterative approach to upgrading to React 18, so you'll hopefully see an update soon that adds minimal support (packages updated to versions that support both 17 & 18) with a follow up that updates the repo to actually use React 18. There are a lot of changes needed to the tests to support the newest version of `testing-library/react`.

**Pull request closed without merging**
