### PR TITLE
fix: TabNavLink not semantically a tab

### PR DESCRIPTION
**Pull request by vonbarown**
### Overview

Semantically labeling TabNavLink as a tab to fix a A11y  bug

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [EN-1749](https://codecademy.atlassian.net/browse/EN-1749)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31091)  | [Monolith Env](https://pr-31091-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2101)  | [Portal Env]( https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2101)   |
| BAM| [Another Link](https://github.com/codecademy-engineering/business-account-management/pull/651) | [Another Env](https://tayra.codecademy.com/business/account/60df4256f2c7e87fc20199b4/teams?PR_ENV=business-app-pr-651)  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.139-alpha.9f278d.0<br/>@codecademy/gamut-labs@32.0.2-alpha.9f278d.0<br/>@codecademy/gamut@48.0.1-alpha.9f278d.0<br/>@codecademy/monaco@0.6.50-alpha.9f278d.0<br/>@codecademy/styleguide@58.0.2-alpha.9f278d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62a24f875121e8042730b1a1--gamut-preview.netlify.app>https://62a24f875121e8042730b1a1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62a24f875121e8042730b1a1>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
makes sense to me and sounds great in BAM 👍

**Review by aresnik11 — APPROVED** [review]
🚀

**Pull request merged**
