### PR TITLE
feat(Popover): allow passing container ref into popover

### PR DESCRIPTION
**Pull request by jrood**
### Overview

Allow passing in a popover container ref so that the dropdown button component (in brands) will be able to use that ref to get the height of the popover contents, which is needed to determine if the popover should render above or below the target.

### PR Checklist

- [ ] ~Related to designs:~
- [x] Related to JIRA ticket: [REACH-2522]
- [x] I have run this code to verify it works
- [ ] ~This PR includes unit tests for the code change~
- [ ] ~This PR includes testing instructions tests for the code change~
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  |
| :----------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35514)  |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1784)  |

[REACH-2522]: https://codecademy.atlassian.net/browse/REACH-2522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.312-alpha.a48e3c.0<br/>@codecademy/gamut-labs@35.14.1-alpha.a48e3c.0<br/>@codecademy/gamut@53.1.3-alpha.a48e3c.0<br/>@codecademy/monaco@0.7.21-alpha.a48e3c.0<br/>@codecademy/styleguide@64.3.5-alpha.a48e3c.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
love it! i am curious why the popoverContainerRef needs to be cast but thats just for my own personal knowledge + non-blocking lol

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.313-alpha.3c8023.0<br/>@codecademy/gamut-labs@35.14.2-alpha.3c8023.0<br/>@codecademy/gamut@53.1.3-alpha.3c8023.0<br/>@codecademy/monaco@0.7.21-alpha.3c8023.0<br/>@codecademy/styleguide@64.3.6-alpha.3c8023.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://645042920cf1d227131b1a88--gamut-preview.netlify.app>https://645042920cf1d227131b1a88--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/645042920cf1d227131b1a88>Deploy Logs</a></p>

**Pull request merged**
