### PR TITLE
feat(Menu): tweak nav variant + add nav condensed example

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Changes navigation variant to new designs + adds nav condensed example

### PR Checklist

- [x] Related to designs: [biz](https://www.figma.com/file/RfVSt2smXRygdjHYSDJAMa/Navigation-Pattern-Cleanup?node-id=666%3A11436) / [gamut](https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1971%3A2430)
- [x] Related to JIRA ticket: gm-451
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.15-alpha.e2c4bc.0<br/>@codecademy/gamut-labs@28.0.10-alpha.e2c4bc.0<br/>@codecademy/gamut@40.3.2-alpha.e2c4bc.0<br/>@codecademy/monaco@0.5.12-alpha.e2c4bc.0<br/>@codecademy/styleguide@50.2.2-alpha.e2c4bc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618ead9439c997100cff0990--gamut-preview.netlify.app>https://618ead9439c997100cff0990--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618ead9439c997100cff0990>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.15-alpha.60ce4d.0<br/>@codecademy/gamut-labs@28.0.10-alpha.60ce4d.0<br/>@codecademy/gamut@40.3.2-alpha.60ce4d.0<br/>@codecademy/monaco@0.5.12-alpha.60ce4d.0<br/>@codecademy/styleguide@50.2.2-alpha.60ce4d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618ec5781eb54513e898b5d2--gamut-preview.netlify.app>https://618ec5781eb54513e898b5d2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618ec5781eb54513e898b5d2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.15-alpha.68806b.0<br/>@codecademy/gamut-labs@28.0.10-alpha.68806b.0<br/>@codecademy/gamut@40.3.2-alpha.68806b.0<br/>@codecademy/monaco@0.5.12-alpha.68806b.0<br/>@codecademy/styleguide@50.2.2-alpha.68806b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618eeacf9b5a3100a75fe477--gamut-preview.netlify.app>https://618eeacf9b5a3100a75fe477--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618eeacf9b5a3100a75fe477>Deploy Logs</a></p>

**Review by antoniablair — APPROVED** [review]
Lgtm!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.15-alpha.661ad2.0<br/>@codecademy/gamut-labs@28.0.10-alpha.661ad2.0<br/>@codecademy/gamut@40.3.2-alpha.661ad2.0<br/>@codecademy/monaco@0.5.12-alpha.661ad2.0<br/>@codecademy/styleguide@50.2.2-alpha.661ad2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6192e61b8ff0010c5667e28e--gamut-preview.netlify.app>https://6192e61b8ff0010c5667e28e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6192e61b8ff0010c5667e28e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619526238f5c562b940d7f19--gamut-preview.netlify.app>https://619526238f5c562b940d7f19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619526238f5c562b940d7f19>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.8bb3bd.0<br/>@codecademy/gamut-labs@28.0.14-alpha.8bb3bd.0<br/>@codecademy/gamut@40.3.4-alpha.8bb3bd.0<br/>@codecademy/monaco@0.5.14-alpha.8bb3bd.0<br/>@codecademy/styleguide@50.2.7-alpha.8bb3bd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619c1df04e2f5200816907de--gamut-preview.netlify.app>https://619c1df04e2f5200816907de--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619c1df04e2f5200816907de>Deploy Logs</a></p>

**Pull request merged**
