### PR TITLE
feat: update webpack-config to 6.2.0

### PR DESCRIPTION
**Pull request by jrood**
### Overview

Update to `@codecademy/webpack-config` `6.2.0` which uses other updated dependencies.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions
- `yarn build`

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6309350da1e19b0ae25bfa8d--gamut-preview.netlify.app>https://6309350da1e19b0ae25bfa8d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6309350da1e19b0ae25bfa8d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@61.5.0-alpha.f5ba56.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630d3521f6a43e2eb5be451a--gamut-preview.netlify.app>https://630d3521f6a43e2eb5be451a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630d3521f6a43e2eb5be451a>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
tested this locally + works like charm

**Pull request merged**
