### PR TITLE
feat(Toaster): Use current color mode in `Toaster`

### PR DESCRIPTION
**Pull request by melaniemohn**
### Overview

This removes the hard-coded light mode from the `Toaster` in order to show dark mode notifications in Author.

[On Slack](https://codecademy.slack.com/archives/CTVEHH2PP/p1668784079583599), we talked about potentially passing an `inverse` prop or introducing a separate higher-order component for cases where we want the `Toaster` to override the user's selected color mode (e.g. the LE?), but these approaches would have required changes to the LE in order to preserve the current light mode notifications.

Instead, I opted to pass an optional `colorMode` prop with a default value of `light`. This lets us pass the user's selected color mode in Author, without affecting the appearance of notifications elsewhere in the codebase.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [CONPLAT-2389](https://codecademy.atlassian.net/browse/CONPLAT-2389)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Visit the Author PR env linked below and make some changes to a content item. You should see success notifications on committing, or error notifications if a required field (e.g. a content item's description) is missing.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Author     | [#2430](https://github.com/codecademy-engineering/author/pull/2430)  | [PR Env](https://author-1.pr.codecademy.com/) |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.233-alpha.32e40f.0<br/>@codecademy/gamut-labs@33.8.2-alpha.32e40f.0<br/>@codecademy/gamut@51.4.3-alpha.32e40f.0<br/>@codecademy/monaco@0.6.107-alpha.32e40f.0<br/>@codecademy/styleguide@62.5.2-alpha.32e40f.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.241-alpha.326055.0<br/>@codecademy/gamut-labs@33.8.10-alpha.326055.0<br/>@codecademy/gamut@51.4.7-alpha.326055.0<br/>@codecademy/monaco@0.6.111-alpha.326055.0<br/>@codecademy/styleguide@62.5.10-alpha.326055.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6387be015c696c5db4642ccd--gamut-preview.netlify.app>https://6387be015c696c5db4642ccd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6387be015c696c5db4642ccd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.241-alpha.74c3c8.0<br/>@codecademy/gamut-labs@33.8.10-alpha.74c3c8.0<br/>@codecademy/gamut@51.4.7-alpha.74c3c8.0<br/>@codecademy/monaco@0.6.111-alpha.74c3c8.0<br/>@codecademy/styleguide@62.5.10-alpha.74c3c8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6387f5131d4acf0e8659829b--gamut-preview.netlify.app>https://6387f5131d4acf0e8659829b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6387f5131d4acf0e8659829b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.242-alpha.aa2802.0<br/>@codecademy/gamut-labs@33.8.11-alpha.aa2802.0<br/>@codecademy/gamut@51.4.7-alpha.aa2802.0<br/>@codecademy/monaco@0.6.111-alpha.aa2802.0<br/>@codecademy/styleguide@62.5.11-alpha.aa2802.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6388f75330b51931cf3da5f1--gamut-preview.netlify.app>https://6388f75330b51931cf3da5f1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6388f75330b51931cf3da5f1>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.243-alpha.0a1492.0<br/>@codecademy/gamut-labs@33.8.12-alpha.0a1492.0<br/>@codecademy/gamut@51.4.7-alpha.0a1492.0<br/>@codecademy/monaco@0.6.111-alpha.0a1492.0<br/>@codecademy/styleguide@62.5.12-alpha.0a1492.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://638a2e2d8c00a542533cbcc3--gamut-preview.netlify.app>https://638a2e2d8c00a542533cbcc3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/638a2e2d8c00a542533cbcc3>Deploy Logs</a></p>

**Pull request merged**
