### PR TITLE
feat(DiamondIcon): add diamond icon

### PR DESCRIPTION
**Pull request by saghdaey**
### Overview

Add diamond icon to gamut-icons

### PR Checklist

- [X] Related to designs:
- [X] Related to JIRA ticket: [EGG-2730]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [X] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

To test: view the diamond icon in the [Storybook preview](https://63052ebfaa8a900069560c05--gamut-preview.netlify.app/?path=/docs/atoms-icons-regular--editable-icon)
(scroll to icons interface)

To test where the monolith consumes the new icon, [please follow instructions in the monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32180)

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32180)  | [Monolith Env](https://pr-32180-monolith.dev-eks.codecademy.com/) |

[EGG-2730]: https://codecademy.atlassian.net/browse/EGG-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63052ebfaa8a900069560c05--gamut-preview.netlify.app>https://63052ebfaa8a900069560c05--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63052ebfaa8a900069560c05>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.3-alpha.e136b3.0<br/>@codecademy/gamut-kit@0.6.184-alpha.e136b3.0<br/>@codecademy/gamut-labs@33.1.5-alpha.e136b3.0<br/>@codecademy/gamut@50.4.3-alpha.e136b3.0<br/>@codecademy/monaco@0.6.76-alpha.e136b3.0<br/>@codecademy/styleguide@61.2.3-alpha.e136b3.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]

**Review by sooinc — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.3-alpha.cc5287.0<br/>@codecademy/gamut-kit@0.6.184-alpha.cc5287.0<br/>@codecademy/gamut-labs@33.1.5-alpha.cc5287.0<br/>@codecademy/gamut@50.4.3-alpha.cc5287.0<br/>@codecademy/monaco@0.6.76-alpha.cc5287.0<br/>@codecademy/styleguide@61.2.3-alpha.cc5287.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63053557e8bb87041b9dcc06--gamut-preview.netlify.app>https://63053557e8bb87041b9dcc06--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63053557e8bb87041b9dcc06>Deploy Logs</a></p>

**Pull request merged**
