### PR TITLE
chore!: Support React 18 [WEB-2055]

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

This PR adds support for React 18 WITHOUT actually using React 18 locally for tests or storybook. We will be updating those to React 18 as a follow up. This should allow clients to update to React 18.

Add support for React 18
This is a breaking change for `gamut-styles` because we have removed `react-helmet` from the `AssetProvider` component. You'll need to wrap `AssetProvider` in an instance of `react-helmet` in your app.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket:[WEB-2055](https://codecademy.atlassian.net/browse/WEB-2055)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34239)  | [Monolith Env](https://pr-34239-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/mono/pull/1036)  | [Portal Env]( https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1036)   |

[WEB-2055]: https://codecademy.atlassian.net/browse/WEB-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.6-alpha.7eddc2.0<br/>@codecademy/gamut-illustrations@0.32.8-alpha.7eddc2.0<br/>@codecademy/gamut-kit@0.6.260-alpha.7eddc2.0<br/>@codecademy/gamut-labs@34.0.7-alpha.7eddc2.0<br/>@codecademy/gamut-patterns@0.8.21-alpha.7eddc2.0<br/>@codecademy/gamut-styles@14.2.4-alpha.7eddc2.0<br/>@codecademy/gamut-tests@4.0.21-alpha.7eddc2.0<br/>@codecademy/gamut@51.7.1-alpha.7eddc2.0<br/>@codecademy/markdown-overrides@0.9.18-alpha.7eddc2.0<br/>@codecademy/monaco@0.6.118-alpha.7eddc2.0<br/>@codecademy/styleguide@62.8.1-alpha.7eddc2.0<br/>@codecademy/variance@0.20.6-alpha.7eddc2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.7-alpha.72cf52.0<br/>@codecademy/gamut-illustrations@0.32.9-alpha.72cf52.0<br/>@codecademy/gamut-kit@0.6.262-alpha.72cf52.0<br/>@codecademy/gamut-labs@34.0.9-alpha.72cf52.0<br/>@codecademy/gamut-patterns@0.8.22-alpha.72cf52.0<br/>@codecademy/gamut-styles@14.2.5-alpha.72cf52.0<br/>@codecademy/gamut-tests@4.0.22-alpha.72cf52.0<br/>@codecademy/gamut@51.7.2-alpha.72cf52.0<br/>@codecademy/markdown-overrides@0.9.19-alpha.72cf52.0<br/>@codecademy/monaco@0.6.119-alpha.72cf52.0<br/>@codecademy/styleguide@62.8.3-alpha.72cf52.0<br/>@codecademy/variance@0.20.6-alpha.72cf52.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.7-alpha.186a97.0<br/>@codecademy/gamut-illustrations@0.32.9-alpha.186a97.0<br/>@codecademy/gamut-kit@0.6.262-alpha.186a97.0<br/>@codecademy/gamut-labs@34.0.9-alpha.186a97.0<br/>@codecademy/gamut-patterns@0.8.22-alpha.186a97.0<br/>@codecademy/gamut-styles@14.2.5-alpha.186a97.0<br/>@codecademy/gamut-tests@4.0.22-alpha.186a97.0<br/>@codecademy/gamut@51.7.2-alpha.186a97.0<br/>@codecademy/markdown-overrides@0.9.19-alpha.186a97.0<br/>@codecademy/monaco@0.6.119-alpha.186a97.0<br/>@codecademy/styleguide@62.8.3-alpha.186a97.0<br/>@codecademy/variance@0.20.6-alpha.186a97.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.87ed94.0<br/>@codecademy/gamut-icons@7.9.7-alpha.87ed94.0<br/>@codecademy/gamut-illustrations@0.32.9-alpha.87ed94.0<br/>@codecademy/gamut-kit@0.6.263-alpha.87ed94.0<br/>@codecademy/gamut-labs@34.0.10-alpha.87ed94.0<br/>@codecademy/gamut-patterns@0.8.22-alpha.87ed94.0<br/>@codecademy/gamut-styles@14.2.5-alpha.87ed94.0<br/>@codecademy/gamut-tests@4.0.22-alpha.87ed94.0<br/>@codecademy/gamut@51.7.2-alpha.87ed94.0<br/>@codecademy/markdown-overrides@0.9.19-alpha.87ed94.0<br/>@codecademy/monaco@0.6.119-alpha.87ed94.0<br/>@codecademy/styleguide@62.8.4-alpha.87ed94.0<br/>@codecademy/variance@0.20.6-alpha.87ed94.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.90c336.0<br/>@codecademy/gamut-icons@7.9.7-alpha.90c336.0<br/>@codecademy/gamut-illustrations@0.32.9-alpha.90c336.0<br/>@codecademy/gamut-kit@0.6.263-alpha.90c336.0<br/>@codecademy/gamut-labs@34.0.10-alpha.90c336.0<br/>@codecademy/gamut-patterns@0.8.22-alpha.90c336.0<br/>@codecademy/gamut-styles@14.2.5-alpha.90c336.0<br/>@codecademy/gamut-tests@4.0.22-alpha.90c336.0<br/>@codecademy/gamut@51.7.2-alpha.90c336.0<br/>@codecademy/markdown-overrides@0.9.19-alpha.90c336.0<br/>@codecademy/monaco@0.6.119-alpha.90c336.0<br/>@codecademy/styleguide@62.8.4-alpha.90c336.0<br/>@codecademy/variance@0.20.6-alpha.90c336.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.0.3-alpha.17d685.0<br/>@codecademy/gamut-icons@7.9.7-alpha.17d685.0<br/>@codecademy/gamut-illustrations@0.32.9-alpha.17d685.0<br/>@codecademy/gamut-kit@0.6.264-alpha.17d685.0<br/>@codecademy/gamut-labs@34.0.11-alpha.17d685.0<br/>@codecademy/gamut-patterns@0.8.22-alpha.17d685.0<br/>@codecademy/gamut-styles@14.2.5-alpha.17d685.0<br/>@codecademy/gamut-tests@4.0.22-alpha.17d685.0<br/>@codecademy/gamut@51.7.3-alpha.17d685.0<br/>@codecademy/markdown-overrides@0.9.19-alpha.17d685.0<br/>@codecademy/monaco@0.6.120-alpha.17d685.0<br/>@codecademy/styleguide@62.8.5-alpha.17d685.0<br/>@codecademy/variance@0.20.6-alpha.17d685.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.a01756.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.a01756.0<br/>@codecademy/gamut-kit@0.6.265-alpha.a01756.0<br/>@codecademy/gamut-labs@34.0.12-alpha.a01756.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.a01756.0<br/>@codecademy/gamut-styles@14.2.6-alpha.a01756.0<br/>@codecademy/gamut-tests@4.0.23-alpha.a01756.0<br/>@codecademy/gamut@51.7.4-alpha.a01756.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.a01756.0<br/>@codecademy/monaco@0.6.121-alpha.a01756.0<br/>@codecademy/styleguide@62.8.6-alpha.a01756.0<br/>@codecademy/variance@0.20.6-alpha.a01756.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.9fa786.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.9fa786.0<br/>@codecademy/gamut-kit@0.6.265-alpha.9fa786.0<br/>@codecademy/gamut-labs@34.0.12-alpha.9fa786.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.9fa786.0<br/>@codecademy/gamut-styles@14.2.6-alpha.9fa786.0<br/>@codecademy/gamut-tests@4.0.23-alpha.9fa786.0<br/>@codecademy/gamut@51.7.4-alpha.9fa786.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.9fa786.0<br/>@codecademy/monaco@0.6.121-alpha.9fa786.0<br/>@codecademy/styleguide@62.8.6-alpha.9fa786.0<br/>@codecademy/variance@0.20.6-alpha.9fa786.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.9b50db.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.9b50db.0<br/>@codecademy/gamut-kit@0.6.265-alpha.9b50db.0<br/>@codecademy/gamut-labs@34.0.12-alpha.9b50db.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.9b50db.0<br/>@codecademy/gamut-styles@14.2.6-alpha.9b50db.0<br/>@codecademy/gamut-tests@4.0.23-alpha.9b50db.0<br/>@codecademy/gamut@51.7.4-alpha.9b50db.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.9b50db.0<br/>@codecademy/monaco@0.6.121-alpha.9b50db.0<br/>@codecademy/styleguide@62.8.6-alpha.9b50db.0<br/>@codecademy/variance@0.20.6-alpha.9b50db.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.2a06db.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.2a06db.0<br/>@codecademy/gamut-kit@0.6.265-alpha.2a06db.0<br/>@codecademy/gamut-labs@34.0.12-alpha.2a06db.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.2a06db.0<br/>@codecademy/gamut-styles@14.2.6-alpha.2a06db.0<br/>@codecademy/gamut-tests@4.0.23-alpha.2a06db.0<br/>@codecademy/gamut@51.7.4-alpha.2a06db.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.2a06db.0<br/>@codecademy/monaco@0.6.121-alpha.2a06db.0<br/>@codecademy/styleguide@62.8.6-alpha.2a06db.0<br/>@codecademy/variance@0.20.6-alpha.2a06db.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.3e81a0.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.3e81a0.0<br/>@codecademy/gamut-kit@0.6.265-alpha.3e81a0.0<br/>@codecademy/gamut-labs@34.0.12-alpha.3e81a0.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.3e81a0.0<br/>@codecademy/gamut-styles@14.2.6-alpha.3e81a0.0<br/>@codecademy/gamut-tests@4.0.23-alpha.3e81a0.0<br/>@codecademy/gamut@51.7.4-alpha.3e81a0.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.3e81a0.0<br/>@codecademy/monaco@0.6.121-alpha.3e81a0.0<br/>@codecademy/styleguide@62.8.6-alpha.3e81a0.0<br/>@codecademy/variance@0.20.6-alpha.3e81a0.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.407697.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.407697.0<br/>@codecademy/gamut-kit@0.6.265-alpha.407697.0<br/>@codecademy/gamut-labs@34.0.12-alpha.407697.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.407697.0<br/>@codecademy/gamut-styles@14.2.6-alpha.407697.0<br/>@codecademy/gamut-tests@4.0.23-alpha.407697.0<br/>@codecademy/gamut@51.7.4-alpha.407697.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.407697.0<br/>@codecademy/monaco@0.6.121-alpha.407697.0<br/>@codecademy/styleguide@62.8.6-alpha.407697.0<br/>@codecademy/variance@0.20.6-alpha.407697.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.7f6942.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.7f6942.0<br/>@codecademy/gamut-kit@0.6.265-alpha.7f6942.0<br/>@codecademy/gamut-labs@34.0.12-alpha.7f6942.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.7f6942.0<br/>@codecademy/gamut-styles@14.2.6-alpha.7f6942.0<br/>@codecademy/gamut-tests@4.0.23-alpha.7f6942.0<br/>@codecademy/gamut@51.7.4-alpha.7f6942.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.7f6942.0<br/>@codecademy/monaco@0.6.121-alpha.7f6942.0<br/>@codecademy/styleguide@62.8.6-alpha.7f6942.0<br/>@codecademy/variance@0.20.6-alpha.7f6942.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.a73ccb.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.a73ccb.0<br/>@codecademy/gamut-kit@0.6.265-alpha.a73ccb.0<br/>@codecademy/gamut-labs@34.0.12-alpha.a73ccb.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.a73ccb.0<br/>@codecademy/gamut-styles@14.2.6-alpha.a73ccb.0<br/>@codecademy/gamut-tests@4.0.23-alpha.a73ccb.0<br/>@codecademy/gamut@51.7.4-alpha.a73ccb.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.a73ccb.0<br/>@codecademy/monaco@0.6.121-alpha.a73ccb.0<br/>@codecademy/styleguide@62.8.6-alpha.a73ccb.0<br/>@codecademy/variance@0.20.6-alpha.a73ccb.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.2d69f5.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.2d69f5.0<br/>@codecademy/gamut-kit@0.6.265-alpha.2d69f5.0<br/>@codecademy/gamut-labs@34.0.12-alpha.2d69f5.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.2d69f5.0<br/>@codecademy/gamut-styles@14.2.6-alpha.2d69f5.0<br/>@codecademy/gamut-tests@4.0.23-alpha.2d69f5.0<br/>@codecademy/gamut@51.7.4-alpha.2d69f5.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.2d69f5.0<br/>@codecademy/monaco@0.6.121-alpha.2d69f5.0<br/>@codecademy/styleguide@62.8.6-alpha.2d69f5.0<br/>@codecademy/variance@0.20.6-alpha.2d69f5.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.73e740.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.73e740.0<br/>@codecademy/gamut-kit@0.6.265-alpha.73e740.0<br/>@codecademy/gamut-labs@34.0.12-alpha.73e740.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.73e740.0<br/>@codecademy/gamut-styles@14.2.6-alpha.73e740.0<br/>@codecademy/gamut-tests@4.0.23-alpha.73e740.0<br/>@codecademy/gamut@51.7.4-alpha.73e740.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.73e740.0<br/>@codecademy/monaco@0.6.121-alpha.73e740.0<br/>@codecademy/styleguide@62.8.6-alpha.73e740.0<br/>@codecademy/variance@0.20.6-alpha.73e740.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.ae778b.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.ae778b.0<br/>@codecademy/gamut-kit@0.6.265-alpha.ae778b.0<br/>@codecademy/gamut-labs@34.0.12-alpha.ae778b.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.ae778b.0<br/>@codecademy/gamut-styles@14.2.6-alpha.ae778b.0<br/>@codecademy/gamut-tests@4.0.23-alpha.ae778b.0<br/>@codecademy/gamut@51.7.4-alpha.ae778b.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.ae778b.0<br/>@codecademy/monaco@0.6.121-alpha.ae778b.0<br/>@codecademy/styleguide@62.8.6-alpha.ae778b.0<br/>@codecademy/variance@0.20.6-alpha.ae778b.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.d1ac8d.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.d1ac8d.0<br/>@codecademy/gamut-kit@0.6.265-alpha.d1ac8d.0<br/>@codecademy/gamut-labs@34.0.12-alpha.d1ac8d.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.d1ac8d.0<br/>@codecademy/gamut-styles@14.2.6-alpha.d1ac8d.0<br/>@codecademy/gamut-tests@4.0.23-alpha.d1ac8d.0<br/>@codecademy/gamut@51.7.4-alpha.d1ac8d.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.d1ac8d.0<br/>@codecademy/monaco@0.6.121-alpha.d1ac8d.0<br/>@codecademy/styleguide@62.8.6-alpha.d1ac8d.0<br/>@codecademy/variance@0.20.6-alpha.d1ac8d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63c06a7e9fd38922619acf0e--gamut-preview.netlify.app>https://63c06a7e9fd38922619acf0e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63c06a7e9fd38922619acf0e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.85968e.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.85968e.0<br/>@codecademy/gamut-kit@0.6.265-alpha.85968e.0<br/>@codecademy/gamut-labs@34.0.12-alpha.85968e.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.85968e.0<br/>@codecademy/gamut-styles@14.2.6-alpha.85968e.0<br/>@codecademy/gamut-tests@4.0.23-alpha.85968e.0<br/>@codecademy/gamut@51.7.4-alpha.85968e.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.85968e.0<br/>@codecademy/monaco@0.6.121-alpha.85968e.0<br/>@codecademy/styleguide@62.8.6-alpha.85968e.0<br/>@codecademy/variance@0.20.6-alpha.85968e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63c6f7d7f97b1a10202485d5--gamut-preview.netlify.app>https://63c6f7d7f97b1a10202485d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63c6f7d7f97b1a10202485d5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63c6fde07bc13e16f6e42557--gamut-preview.netlify.app>https://63c6fde07bc13e16f6e42557--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63c6fde07bc13e16f6e42557>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.5531c4.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.5531c4.0<br/>@codecademy/gamut-kit@0.6.265-alpha.5531c4.0<br/>@codecademy/gamut-labs@34.0.12-alpha.5531c4.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.5531c4.0<br/>@codecademy/gamut-styles@14.2.6-alpha.5531c4.0<br/>@codecademy/gamut-tests@4.0.23-alpha.5531c4.0<br/>@codecademy/gamut@51.7.4-alpha.5531c4.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.5531c4.0<br/>@codecademy/monaco@0.6.121-alpha.5531c4.0<br/>@codecademy/styleguide@62.8.6-alpha.5531c4.0<br/>@codecademy/variance@0.20.6-alpha.5531c4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63c84d4bc69c410a4c055284--gamut-preview.netlify.app>https://63c84d4bc69c410a4c055284--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63c84d4bc69c410a4c055284>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.8-alpha.9461f1.0<br/>@codecademy/gamut-illustrations@0.32.10-alpha.9461f1.0<br/>@codecademy/gamut-kit@0.6.266-alpha.9461f1.0<br/>@codecademy/gamut-labs@34.1.1-alpha.9461f1.0<br/>@codecademy/gamut-patterns@0.8.23-alpha.9461f1.0<br/>@codecademy/gamut-styles@14.2.6-alpha.9461f1.0<br/>@codecademy/gamut-tests@4.0.23-alpha.9461f1.0<br/>@codecademy/gamut@51.7.4-alpha.9461f1.0<br/>@codecademy/markdown-overrides@0.9.20-alpha.9461f1.0<br/>@codecademy/monaco@0.6.121-alpha.9461f1.0<br/>@codecademy/styleguide@62.8.7-alpha.9461f1.0<br/>@codecademy/variance@0.20.6-alpha.9461f1.0<br/></pre>

**Review by aresnik11 — APPROVED** [review]
Changes make sense and confirmed monolith and portal look good in their corresponding PRs!

**Pull request merged**
