### PR TITLE
feat(icons): add levels icon

### PR DESCRIPTION
**Pull request by aionate0812**
### Overview

Adds `LevelIcon` to `gamut-icons`

Stroke of 1.5 was too much, got confirmation from our designer to reduce it to 1
Setting the viewBox to 0 0 24 24 caused the icon to be too small, using the default viewBox numbers from streamline

### PR Checklist

- [x] Related to designs:https://www.figma.com/file/XSeoAT1Q97FBZc1uju2Cgx/Course-Landing-Page-v1?node-id=1109%3A149863
- [x] I have run this code to verify it works

#### Testing Instructions
Confirm the icon shows up in storybook

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6346d804b970b61cacd4d2a6--gamut-preview.netlify.app>https://6346d804b970b61cacd4d2a6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6346d804b970b61cacd4d2a6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.3a85a0.0<br/>@codecademy/gamut-kit@0.6.213-alpha.3a85a0.0<br/>@codecademy/gamut-labs@33.6.4-alpha.3a85a0.0<br/>@codecademy/gamut@50.8.2-alpha.3a85a0.0<br/>@codecademy/monaco@0.6.93-alpha.3a85a0.0<br/>@codecademy/styleguide@61.7.3-alpha.3a85a0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://634704364ed2b70bde9dd3b9--gamut-preview.netlify.app>https://634704364ed2b70bde9dd3b9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/634704364ed2b70bde9dd3b9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.bc78d9.0<br/>@codecademy/gamut-kit@0.6.217-alpha.bc78d9.0<br/>@codecademy/gamut-labs@33.6.8-alpha.bc78d9.0<br/>@codecademy/gamut@51.0.1-alpha.bc78d9.0<br/>@codecademy/monaco@0.6.96-alpha.bc78d9.0<br/>@codecademy/styleguide@62.0.1-alpha.bc78d9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63516b3957dd540aa928797e--gamut-preview.netlify.app>https://63516b3957dd540aa928797e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63516b3957dd540aa928797e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.19d7c2.0<br/>@codecademy/gamut-kit@0.6.217-alpha.19d7c2.0<br/>@codecademy/gamut-labs@33.6.8-alpha.19d7c2.0<br/>@codecademy/gamut@51.0.1-alpha.19d7c2.0<br/>@codecademy/monaco@0.6.96-alpha.19d7c2.0<br/>@codecademy/styleguide@62.0.1-alpha.19d7c2.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.3da6ec.0<br/>@codecademy/gamut-kit@0.6.217-alpha.3da6ec.0<br/>@codecademy/gamut-labs@33.6.8-alpha.3da6ec.0<br/>@codecademy/gamut@51.0.1-alpha.3da6ec.0<br/>@codecademy/monaco@0.6.96-alpha.3da6ec.0<br/>@codecademy/styleguide@62.0.1-alpha.3da6ec.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://635174d45f31235fa36e5fde--gamut-preview.netlify.app>https://635174d45f31235fa36e5fde--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/635174d45f31235fa36e5fde>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.8d01a9.0<br/>@codecademy/gamut-kit@0.6.217-alpha.8d01a9.0<br/>@codecademy/gamut-labs@33.6.8-alpha.8d01a9.0<br/>@codecademy/gamut@51.0.1-alpha.8d01a9.0<br/>@codecademy/monaco@0.6.96-alpha.8d01a9.0<br/>@codecademy/styleguide@62.0.1-alpha.8d01a9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://635180971339086d146400e4--gamut-preview.netlify.app>https://635180971339086d146400e4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/635180971339086d146400e4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.3c3d94.0<br/>@codecademy/gamut-kit@0.6.217-alpha.3c3d94.0<br/>@codecademy/gamut-labs@33.6.8-alpha.3c3d94.0<br/>@codecademy/gamut@51.0.1-alpha.3c3d94.0<br/>@codecademy/monaco@0.6.96-alpha.3c3d94.0<br/>@codecademy/styleguide@62.0.1-alpha.3c3d94.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6351b37f78bc3f14e71d07db--gamut-preview.netlify.app>https://6351b37f78bc3f14e71d07db--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6351b37f78bc3f14e71d07db>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.14c1f5.0<br/>@codecademy/gamut-kit@0.6.217-alpha.14c1f5.0<br/>@codecademy/gamut-labs@33.6.8-alpha.14c1f5.0<br/>@codecademy/gamut@51.0.1-alpha.14c1f5.0<br/>@codecademy/monaco@0.6.96-alpha.14c1f5.0<br/>@codecademy/styleguide@62.0.1-alpha.14c1f5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6351be4b9588ca1d319047fa--gamut-preview.netlify.app>https://6351be4b9588ca1d319047fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6351be4b9588ca1d319047fa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.f87dea.0<br/>@codecademy/gamut-kit@0.6.217-alpha.f87dea.0<br/>@codecademy/gamut-labs@33.6.8-alpha.f87dea.0<br/>@codecademy/gamut@51.0.1-alpha.f87dea.0<br/>@codecademy/monaco@0.6.96-alpha.f87dea.0<br/>@codecademy/styleguide@62.0.1-alpha.f87dea.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6352bd13b5978e22eba252c1--gamut-preview.netlify.app>https://6352bd13b5978e22eba252c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6352bd13b5978e22eba252c1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.4da868.0<br/>@codecademy/gamut-kit@0.6.217-alpha.4da868.0<br/>@codecademy/gamut-labs@33.6.8-alpha.4da868.0<br/>@codecademy/gamut@51.0.1-alpha.4da868.0<br/>@codecademy/monaco@0.6.96-alpha.4da868.0<br/>@codecademy/styleguide@62.0.1-alpha.4da868.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://635702b69df4032e836f1506--gamut-preview.netlify.app>https://635702b69df4032e836f1506--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/635702b69df4032e836f1506>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.adbbc0.0<br/>@codecademy/gamut-kit@0.6.217-alpha.adbbc0.0<br/>@codecademy/gamut-labs@33.6.8-alpha.adbbc0.0<br/>@codecademy/gamut@51.0.1-alpha.adbbc0.0<br/>@codecademy/monaco@0.6.96-alpha.adbbc0.0<br/>@codecademy/styleguide@62.0.1-alpha.adbbc0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63571008a2b9933ddc0ea249--gamut-preview.netlify.app>https://63571008a2b9933ddc0ea249--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63571008a2b9933ddc0ea249>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.f1dea6.0<br/>@codecademy/gamut-kit@0.6.217-alpha.f1dea6.0<br/>@codecademy/gamut-labs@33.6.8-alpha.f1dea6.0<br/>@codecademy/gamut@51.0.1-alpha.f1dea6.0<br/>@codecademy/monaco@0.6.96-alpha.f1dea6.0<br/>@codecademy/styleguide@62.0.1-alpha.f1dea6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6357f9739df4037e3d6f1851--gamut-preview.netlify.app>https://6357f9739df4037e3d6f1851--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6357f9739df4037e3d6f1851>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6357fc8dbdaf4002ae7a2786--gamut-preview.netlify.app>https://6357fc8dbdaf4002ae7a2786--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6357fc8dbdaf4002ae7a2786>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.2a9857.0<br/>@codecademy/gamut-kit@0.6.217-alpha.2a9857.0<br/>@codecademy/gamut-labs@33.6.8-alpha.2a9857.0<br/>@codecademy/gamut@51.0.1-alpha.2a9857.0<br/>@codecademy/monaco@0.6.96-alpha.2a9857.0<br/>@codecademy/styleguide@62.0.1-alpha.2a9857.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63582d23f150f11759f33c11--gamut-preview.netlify.app>https://63582d23f150f11759f33c11--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63582d23f150f11759f33c11>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.8.3-alpha.74a2ca.0<br/>@codecademy/gamut-kit@0.6.218-alpha.74a2ca.0<br/>@codecademy/gamut-labs@33.6.9-alpha.74a2ca.0<br/>@codecademy/gamut@51.0.1-alpha.74a2ca.0<br/>@codecademy/monaco@0.6.96-alpha.74a2ca.0<br/>@codecademy/styleguide@62.0.3-alpha.74a2ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://635834acf150f120f1f33a7f--gamut-preview.netlify.app>https://635834acf150f120f1f33a7f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/635834acf150f120f1f33a7f>Deploy Logs</a></p>

**Pull request merged**
