### PR TITLE
fix(AccordionRow, ListRow): remove incorrect aria-expanded

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Fixes e2e failures on monorepo e2e tests re: [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#rows) 

Remove aria-expanded from div

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.198-alpha.0bd9d7.0<br/>@codecademy/gamut-labs@33.3.2-alpha.0bd9d7.0<br/>@codecademy/gamut@50.6.3-alpha.0bd9d7.0<br/>@codecademy/monaco@0.6.85-alpha.0bd9d7.0<br/>@codecademy/styleguide@61.5.4-alpha.0bd9d7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63176e2725bcb000ae1cd3dc--gamut-preview.netlify.app>https://63176e2725bcb000ae1cd3dc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63176e2725bcb000ae1cd3dc>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.199-alpha.3bc299.0<br/>@codecademy/gamut-labs@33.3.3-alpha.3bc299.0<br/>@codecademy/gamut@50.6.3-alpha.3bc299.0<br/>@codecademy/monaco@0.6.85-alpha.3bc299.0<br/>@codecademy/styleguide@61.5.5-alpha.3bc299.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318e6cb35d6fa19ba26b6a0--gamut-preview.netlify.app>https://6318e6cb35d6fa19ba26b6a0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318e6cb35d6fa19ba26b6a0>Deploy Logs</a></p>

**Review by BandanaKM — APPROVED** [review]
🔥

**Comment by BandanaKM** [comment]
wait, is this still a draft?

**Comment by dreamwasp** [comment]
> wait, is this still a draft?

oops, not anymore!

**Review by aresnik11 — COMMENTED** [review]
Don't we also need it on the List Row thing?

**Comment by dreamwasp** [comment]
> Don't we also need it on the List Row thing? (and by need it i mean remove it)

definitely, great call!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.199-alpha.52632f.0<br/>@codecademy/gamut-labs@33.3.3-alpha.52632f.0<br/>@codecademy/gamut@50.6.3-alpha.52632f.0<br/>@codecademy/monaco@0.6.85-alpha.52632f.0<br/>@codecademy/styleguide@61.5.6-alpha.52632f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://631a4b80f669ea0563c897d9--gamut-preview.netlify.app>https://631a4b80f669ea0563c897d9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/631a4b80f669ea0563c897d9>Deploy Logs</a></p>

**Pull request merged**
