### PR TITLE
chore: fix top padding on tab buttons

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Fixes vertical centering text on `<TabButton/>` component

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [WEBREQ-26]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.36-alpha.058fba.0<br/>@codecademy/gamut-labs@28.5.1-alpha.058fba.0<br/>@codecademy/gamut@42.2.1-alpha.058fba.0<br/>@codecademy/monaco@0.5.27-alpha.058fba.0<br/>@codecademy/styleguide@52.3.1-alpha.058fba.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c0e94b2bf45d5490e15abb--gamut-preview.netlify.app>https://61c0e94b2bf45d5490e15abb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c0e94b2bf45d5490e15abb>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.f82334.0<br/>@codecademy/gamut-labs@28.6.1-alpha.f82334.0<br/>@codecademy/gamut@42.2.2-alpha.f82334.0<br/>@codecademy/monaco@0.5.28-alpha.f82334.0<br/>@codecademy/styleguide@52.4.1-alpha.f82334.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d46bbd0b05d23b33eb95ac--gamut-preview.netlify.app>https://61d46bbd0b05d23b33eb95ac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d46bbd0b05d23b33eb95ac>Deploy Logs</a></p>

**Pull request merged**
