### PR TITLE
feat(GlobalHeader): Update business logic for BAM profile menu

### PR DESCRIPTION
**Pull request by jenesh**
### Overview

This PR adds logic to check `hideBusinessAccount` which is a feature flag to show/hide the BAM for skillsoft users.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Check the monolith and pull down the branch to test it locally with the instructions in the monolith PR.

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32255)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2503)  | [Portal Env](http://www.google.fr/ 'Named link title')

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.198-alpha.76cc34.0<br/>@codecademy/gamut-labs@33.3.2-alpha.76cc34.0<br/>@codecademy/styleguide@61.5.4-alpha.76cc34.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318a959330fdf00a735ced2--gamut-preview.netlify.app>https://6318a959330fdf00a735ced2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318a959330fdf00a735ced2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.198-alpha.83b160.0<br/>@codecademy/gamut-labs@33.3.2-alpha.83b160.0<br/>@codecademy/styleguide@61.5.4-alpha.83b160.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318add30bdea10ec4567ba8--gamut-preview.netlify.app>https://6318add30bdea10ec4567ba8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318add30bdea10ec4567ba8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.198-alpha.9d9cd9.0<br/>@codecademy/gamut-labs@33.3.2-alpha.9d9cd9.0<br/>@codecademy/styleguide@61.5.4-alpha.9d9cd9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318b252c15f3219eb2245e3--gamut-preview.netlify.app>https://6318b252c15f3219eb2245e3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318b252c15f3219eb2245e3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318bc37330fdf13753663c5--gamut-preview.netlify.app>https://6318bc37330fdf13753663c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318bc37330fdf13753663c5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.198-alpha.3a470d.0<br/>@codecademy/gamut-labs@33.3.2-alpha.3a470d.0<br/>@codecademy/styleguide@61.5.4-alpha.3a470d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318c02a9df4b228a6b7fc2b--gamut-preview.netlify.app>https://6318c02a9df4b228a6b7fc2b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318c02a9df4b228a6b7fc2b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.199-alpha.11ca7e.0<br/>@codecademy/gamut-labs@33.3.3-alpha.11ca7e.0<br/>@codecademy/styleguide@61.5.5-alpha.11ca7e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6318fc34fe855428c9d0f7bb--gamut-preview.netlify.app>https://6318fc34fe855428c9d0f7bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6318fc34fe855428c9d0f7bb>Deploy Logs</a></p>

**Review by antoniablair — APPROVED** [review]
🚀

**Review by dreamwasp — APPROVED** [review]

**Review by vonbarown — APPROVED** [review]

**Pull request merged**
