### PR TITLE
chore: used GitHub Actions for simpler CI push jobs

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Uses GitHub Actions instead of CircleCI for some simpler push jobs.

### PR Checklist

- ~[ ] Related to designs:~
- ~[ ] Related to JIRA ticket: ABC-123~ _(there were a few heh)_
- ~[ ] I have run this code to verify it works~
- ~[ ] This PR includes unit tests for the code change~

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6184136b7cbd8e27a0281c90--gamut-preview.netlify.app>https://6184136b7cbd8e27a0281c90--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6184136b7cbd8e27a0281c90>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
yess

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618aa960f277481252401016--gamut-preview.netlify.app>https://618aa960f277481252401016--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618aa960f277481252401016>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618ab3d79443d51da8573ed7--gamut-preview.netlify.app>https://618ab3d79443d51da8573ed7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618ab3d79443d51da8573ed7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618ab777dd41f92277069252--gamut-preview.netlify.app>https://618ab777dd41f92277069252--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618ab777dd41f92277069252>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618aba56c37f4c2e1996e350--gamut-preview.netlify.app>https://618aba56c37f4c2e1996e350--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618aba56c37f4c2e1996e350>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.12-alpha.d9f077.0<br/>@codecademy/gamut-labs@28.0.7-alpha.d9f077.0<br/>@codecademy/styleguide@50.1.9-alpha.d9f077.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618abc8489752b28f3f15753--gamut-preview.netlify.app>https://618abc8489752b28f3f15753--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618abc8489752b28f3f15753>Deploy Logs</a></p>

**Pull request merged**
