### PR TITLE
fix(InfoTip): background hover

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Realized while auditing the FloatingTip issue that InfoTip was missing its hover background

### PR Checklist

- [x] Related to designs: Gamut Figma
- [x] Related to JIRA ticket: [tooltip-123]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* Head to the InfoTip stories
* InfoTip will now have a background color on hover

#### PR Links and Envs

tbd

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.2-alpha.cd8886.0<br/>@codecademy/gamut-kit@0.6.446-alpha.cd8886.0<br/>@codecademy/styleguide@68.1.2-alpha.cd8886.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6700349505f37792abf5cda3--gamut-preview.netlify.app>https://6700349505f37792abf5cda3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6700349505f37792abf5cda3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.2-alpha.db7009.0<br/>@codecademy/gamut-kit@0.6.446-alpha.db7009.0<br/>@codecademy/styleguide@68.1.2-alpha.db7009.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67004d8020b63c1768f0a473--gamut-preview.netlify.app>https://67004d8020b63c1768f0a473--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67004d8020b63c1768f0a473>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
🚢

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.2-alpha.5f2b6e.0<br/>@codecademy/gamut-kit@0.6.446-alpha.5f2b6e.0<br/>@codecademy/styleguide@68.1.2-alpha.5f2b6e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://670051e8f42be51d68e02ebb--gamut-preview.netlify.app>https://670051e8f42be51d68e02ebb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/670051e8f42be51d68e02ebb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.3.2-alpha.3cb39c.0<br/>@codecademy/gamut-kit@0.6.446-alpha.3cb39c.0<br/>@codecademy/styleguide@68.1.2-alpha.3cb39c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6703ef7d5a44d51b35abd534--gamut-preview.netlify.app>https://6703ef7d5a44d51b35abd534--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6703ef7d5a44d51b35abd534>Deploy Logs</a></p>

**Pull request merged**
