### PR TITLE
feat(gamut-icons): add HalloweenBroomIcon

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
### Overview

Adds a spooky scary icon.

Screenshot of the broom and sparkles icon

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/uJOivyBHkXRqXg3afkU4NF/Magic-Cleanup?node-id=0%3A1
- [x] Related to JIRA ticket: WEB-1725
- [x] I have run this code to verify it works
- ~[] This PR includes unit tests for the code change~

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.16d52c.0<br/>@codecademy/gamut-kit@0.6.38-alpha.16d52c.0<br/>@codecademy/gamut-labs@28.6.1-alpha.16d52c.0<br/>@codecademy/gamut@42.2.2-alpha.16d52c.0<br/>@codecademy/monaco@0.5.28-alpha.16d52c.0<br/>@codecademy/styleguide@52.4.1-alpha.16d52c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61c356ab37534549230bd198--gamut-preview.netlify.app>https://61c356ab37534549230bd198--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61c356ab37534549230bd198>Deploy Logs</a></p>

**Review by thedoomshine — APPROVED** [review]
🧹 ✨ 🔥

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.a10d3d.0<br/>@codecademy/gamut-kit@0.6.38-alpha.a10d3d.0<br/>@codecademy/gamut-labs@28.6.1-alpha.a10d3d.0<br/>@codecademy/gamut@42.3.0-alpha.a10d3d.0<br/>@codecademy/monaco@0.5.28-alpha.a10d3d.0<br/>@codecademy/styleguide@52.4.1-alpha.a10d3d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d4a601c4da3813698562fb--gamut-preview.netlify.app>https://61d4a601c4da3813698562fb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d4a601c4da3813698562fb>Deploy Logs</a></p>

**Pull request merged**
