### PR TITLE
chore: change enzyme tests to rtl in gamut-labs

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Changes all enzyme tests in gamut labs over to use react testing library via gamut-tests

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2150]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Make sure all the tests pass

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[WEB-2150]: https://codecademy.atlassian.net/browse/WEB-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.42ba1e.0<br/>@codecademy/gamut-labs@33.6.17-alpha.42ba1e.0<br/>@codecademy/gamut-tests@4.0.18-alpha.42ba1e.0<br/>@codecademy/gamut@51.3.2-alpha.42ba1e.0<br/>@codecademy/monaco@0.6.104-alpha.42ba1e.0<br/>@codecademy/styleguide@62.2.2-alpha.42ba1e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63657bef322d9d06e3fc615f--gamut-preview.netlify.app>https://63657bef322d9d06e3fc615f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63657bef322d9d06e3fc615f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.264c75.0<br/>@codecademy/gamut-labs@33.6.17-alpha.264c75.0<br/>@codecademy/gamut-tests@4.0.18-alpha.264c75.0<br/>@codecademy/gamut@51.3.2-alpha.264c75.0<br/>@codecademy/monaco@0.6.104-alpha.264c75.0<br/>@codecademy/styleguide@62.2.2-alpha.264c75.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63658371f985fa1150d5607d--gamut-preview.netlify.app>https://63658371f985fa1150d5607d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63658371f985fa1150d5607d>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
there is a conflict but other than that LGTM!

(we could have the screen vs view conversation but we should prob just pick one later)

**Review by dreamwasp — APPROVED** [review]
🔥

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.236-alpha.fbfeeb.0<br/>@codecademy/gamut-labs@33.8.5-alpha.fbfeeb.0<br/>@codecademy/gamut-tests@4.0.18-alpha.fbfeeb.0<br/>@codecademy/gamut@51.4.4-alpha.fbfeeb.0<br/>@codecademy/monaco@0.6.108-alpha.fbfeeb.0<br/>@codecademy/styleguide@62.5.5-alpha.fbfeeb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://637bc2c1fae3de0574e6e81d--gamut-preview.netlify.app>https://637bc2c1fae3de0574e6e81d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/637bc2c1fae3de0574e6e81d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.236-alpha.131bca.0<br/>@codecademy/gamut-labs@33.8.5-alpha.131bca.0<br/>@codecademy/gamut-tests@4.0.18-alpha.131bca.0<br/>@codecademy/gamut@51.4.4-alpha.131bca.0<br/>@codecademy/monaco@0.6.108-alpha.131bca.0<br/>@codecademy/styleguide@62.5.5-alpha.131bca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://637cf8ae8cf6e046744aee86--gamut-preview.netlify.app>https://637cf8ae8cf6e046744aee86--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/637cf8ae8cf6e046744aee86>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.236-alpha.a52197.0<br/>@codecademy/gamut-labs@33.8.5-alpha.a52197.0<br/>@codecademy/gamut-tests@4.0.18-alpha.a52197.0<br/>@codecademy/gamut@51.4.4-alpha.a52197.0<br/>@codecademy/monaco@0.6.108-alpha.a52197.0<br/>@codecademy/styleguide@62.5.5-alpha.a52197.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://637d0a1fdd5e0e06d283920e--gamut-preview.netlify.app>https://637d0a1fdd5e0e06d283920e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/637d0a1fdd5e0e06d283920e>Deploy Logs</a></p>

**Pull request merged**
