### PR TITLE
feat(Illustration): adds CustomProject illustration

### PR DESCRIPTION
**Pull request by jatinparab**
### Overview

Adds CustomProject illustration

### PR Checklist

- [x] Related to designs: [Figma](https://www.figma.com/design/v48M0bU0OTh9BcdxK6D5l3/%F0%9F%93%A6-AI-generated-projects?node-id=211-7020&node-type=instance&m=dev)
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions
- Open up the Portal Env preview link from the table below
- Navigate to dashboard
- You should see this card with the illustration
Screenshot 2024-10-21 at 4 47 41 PM

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/8217)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-8217)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.4.3-alpha.2e2459.0<br/>@codecademy/gamut-illustrations@0.49.0-alpha.2e2459.0<br/>@codecademy/gamut-kit@0.6.451-alpha.2e2459.0<br/>@codecademy/styleguide@68.2.3-alpha.2e2459.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6716254ce4d93e2d179d0fa7--gamut-preview.netlify.app>https://6716254ce4d93e2d179d0fa7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6716254ce4d93e2d179d0fa7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.4.3-alpha.9e1092.0<br/>@codecademy/gamut-illustrations@0.49.0-alpha.9e1092.0<br/>@codecademy/gamut-kit@0.6.451-alpha.9e1092.0<br/>@codecademy/styleguide@68.2.3-alpha.9e1092.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67162d2ca207c83cb129310f--gamut-preview.netlify.app>https://67162d2ca207c83cb129310f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67162d2ca207c83cb129310f>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://671672ef3ddfed622c4a0ebd--gamut-preview.netlify.app>https://671672ef3ddfed622c4a0ebd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/671672ef3ddfed622c4a0ebd>Deploy Logs</a></p>

**Pull request merged**
