### PR TITLE
feat(Illustration): add Events illustration

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

add Events illustration

Screenshot 2024-04-09 at 4 43 11 PM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.2-alpha.28ac6c.0<br/>@codecademy/gamut-illustrations@0.42.1-alpha.28ac6c.0<br/>@codecademy/gamut-kit@0.6.383-alpha.28ac6c.0<br/>@codecademy/styleguide@66.12.1-alpha.28ac6c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6615aa7bd9897b389963528a--gamut-preview.netlify.app>https://6615aa7bd9897b389963528a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6615aa7bd9897b389963528a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661d5c0024faf50b3a2cfdf5--gamut-preview.netlify.app>https://661d5c0024faf50b3a2cfdf5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661d5c0024faf50b3a2cfdf5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.2-alpha.6d5e71.0<br/>@codecademy/gamut-illustrations@0.43.1-alpha.6d5e71.0<br/>@codecademy/gamut-kit@0.6.399-alpha.6d5e71.0<br/>@codecademy/styleguide@66.17.3-alpha.6d5e71.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661d68591c148e133f24fff8--gamut-preview.netlify.app>https://661d68591c148e133f24fff8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661d68591c148e133f24fff8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.2-alpha.e185c8.0<br/>@codecademy/gamut-illustrations@0.43.1-alpha.e185c8.0<br/>@codecademy/gamut-kit@0.6.399-alpha.e185c8.0<br/>@codecademy/styleguide@66.17.3-alpha.e185c8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661d6b92653e780bc5fcab90--gamut-preview.netlify.app>https://661d6b92653e780bc5fcab90--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661d6b92653e780bc5fcab90>Deploy Logs</a></p>

**Review by LinKCoding — APPROVED** [review]
lgtm!

**Pull request merged**
