### PR TITLE
fix(GridFormSubmit): delete `fill` GridFormSubmit + fix `stretch` GridForm submit

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

I was being silly when I initially added this new variant without realizing the stretch variant had just been broken at some point.

 This fixes the `stretch` variant and deletes the ill-begotten `fill` variant.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [web-2269]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* Check out the GridForm story
* `stretch` version of GridFormSubmit should take up the entire width of the form

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34380)  | [Monolith Env](https://pr-34380-monolith.dev-eks.codecademy.com/catalog?PR_ENV=pr-34380-portal) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1105)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1105)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.274-alpha.654f35.0<br/>@codecademy/gamut-labs@35.4.1-alpha.654f35.0<br/>@codecademy/gamut@52.0.1-alpha.654f35.0<br/>@codecademy/monaco@0.7.1-alpha.654f35.0<br/>@codecademy/styleguide@63.3.1-alpha.654f35.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63dad929798b482f0bcc06cf--gamut-preview.netlify.app>https://63dad929798b482f0bcc06cf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63dad929798b482f0bcc06cf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.274-alpha.df924b.0<br/>@codecademy/gamut-labs@35.5.0-alpha.df924b.0<br/>@codecademy/gamut@52.0.1-alpha.df924b.0<br/>@codecademy/monaco@0.7.1-alpha.df924b.0<br/>@codecademy/styleguide@63.4.0-alpha.df924b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63dc28e1cc09c140f3b24cb6--gamut-preview.netlify.app>https://63dc28e1cc09c140f3b24cb6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63dc28e1cc09c140f3b24cb6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.275-alpha.0d89cf.0<br/>@codecademy/gamut-labs@35.5.1-alpha.0d89cf.0<br/>@codecademy/gamut@52.0.1-alpha.0d89cf.0<br/>@codecademy/monaco@0.7.1-alpha.0d89cf.0<br/>@codecademy/styleguide@63.4.1-alpha.0d89cf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63dd14132dd3cd058e9295df--gamut-preview.netlify.app>https://63dd14132dd3cd058e9295df--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63dd14132dd3cd058e9295df>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
👍

**Pull request merged**
