### PR TITLE
fix(MenuItem): fixes focus outlines and onClick support

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Adds focus-visible outlines to all variants on `MenuItem` and creates a `button` when there is an `onClick` instead of just an `li` so `onClick` will work with keyboard navigation.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2127]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Visit https://6359c2ebafcc21039a4bc4ac--gamut-preview.netlify.app//?path=/docs/brand-labs-molecules-dropdownbutton--dropdown-button
2. Navigate via keyboard to open the dropdown button menu
3. Tab through the menu items and confirm you see the focus outline for all 3 items
4. Click on each item with your mouse - the first item should redirect the page and add #, the second should console log "hi", and the third should do both
5. Navigate via keyboard and hit enter on each item - the first item should redirect the page and add #, the second should console log "hi", and the third should do both
6. Visit https://6359c2ebafcc21039a4bc4ac--gamut-preview.netlify.app//?path=/docs/molecules-menu--menu#variants
7. Navigate via keyboard through the 3 different variants and confirm you see focus visible outlines

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33212)  | [Monolith Env](https://pr-33212-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/463)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-463)   |

[WEB-2127]: https://codecademy.atlassian.net/browse/WEB-2127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.214-alpha.d79ddb.0<br/>@codecademy/gamut-labs@33.6.5-alpha.d79ddb.0<br/>@codecademy/gamut@50.9.1-alpha.d79ddb.0<br/>@codecademy/monaco@0.6.94-alpha.d79ddb.0<br/>@codecademy/styleguide@61.7.4-alpha.d79ddb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6356e7683bbf741565c7fd6f--gamut-preview.netlify.app>https://6356e7683bbf741565c7fd6f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6356e7683bbf741565c7fd6f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.214-alpha.2b1afc.0<br/>@codecademy/gamut-labs@33.6.5-alpha.2b1afc.0<br/>@codecademy/gamut@50.9.1-alpha.2b1afc.0<br/>@codecademy/monaco@0.6.94-alpha.2b1afc.0<br/>@codecademy/styleguide@61.7.4-alpha.2b1afc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6356eb529df40318d56f16e0--gamut-preview.netlify.app>https://6356eb529df40318d56f16e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6356eb529df40318d56f16e0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63582753ee42610a89848fbb--gamut-preview.netlify.app>https://63582753ee42610a89848fbb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63582753ee42610a89848fbb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.218-alpha.22dd30.0<br/>@codecademy/gamut-labs@33.6.9-alpha.22dd30.0<br/>@codecademy/gamut@51.0.1-alpha.22dd30.0<br/>@codecademy/monaco@0.6.96-alpha.22dd30.0<br/>@codecademy/styleguide@62.0.3-alpha.22dd30.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63583419b5911d193bf864c0--gamut-preview.netlify.app>https://63583419b5911d193bf864c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63583419b5911d193bf864c0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.219-alpha.76a398.0<br/>@codecademy/gamut-labs@33.6.10-alpha.76a398.0<br/>@codecademy/gamut@51.0.2-alpha.76a398.0<br/>@codecademy/monaco@0.6.97-alpha.76a398.0<br/>@codecademy/styleguide@62.0.4-alpha.76a398.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6358581b0c15680294834517--gamut-preview.netlify.app>https://6358581b0c15680294834517--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6358581b0c15680294834517>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.220-alpha.76bd77.0<br/>@codecademy/gamut-labs@33.6.11-alpha.76bd77.0<br/>@codecademy/gamut@51.1.1-alpha.76bd77.0<br/>@codecademy/monaco@0.6.98-alpha.76bd77.0<br/>@codecademy/styleguide@62.0.5-alpha.76bd77.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6359c2ebafcc21039a4bc4ac--gamut-preview.netlify.app>https://6359c2ebafcc21039a4bc4ac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6359c2ebafcc21039a4bc4ac>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
works like a charm

**Review by BandanaKM — APPROVED** [review]
this is awesome, amy!

**Pull request merged**
