### PR TITLE
docs(misc): updating component statuses in SB

### PR DESCRIPTION
**Pull request by LinKCoding**
### PR Checklist

- [ ] Related to JIRA ticket: [GM-754](https://skillsoftdev.atlassian.net/browse/GM-754)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Look over the JIRA ticket
2. Go to the respective pages
3. Check that the statuses match
4. ...
5. Profit!

[GM-754]: https://codecademy.atlassian.net/browse/GM-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@66.29.1-alpha.aed383.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667f1d40c6a6497c2b57cbb9--gamut-preview.netlify.app>https://667f1d40c6a6497c2b57cbb9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667f1d40c6a6497c2b57cbb9>Deploy Logs</a></p>

**Comment by LinKCoding** [comment]
Personally checked over twice as noted in JIRA ticket -- feel free to double check work :) thanks!

**Review by jakemhiller — APPROVED** [review]
👍

**Review by aresnik11 — APPROVED** [review]
LGTM! Only thing is I see `Anchor ⇒ updating` on the list but that's not updated here

**Comment by LinKCoding** [comment]
> LGTM! Only thing is I see `Anchor ⇒ updating` on the list but that's not updated here

Thanks Amy, I updated Anchor recently (adding in icons) and that seemed to be the only ticket associated with Anchor -- but I'll double check with Cass before merging :)

**Comment by LinKCoding** [comment]
Checked with Cass and it's good to go!

**Pull request merged**
