### PR TITLE
feat(DataTable): prop comments

### PR DESCRIPTION
**Pull request by MattSchiller**
### Overview

Just adding a few comments to help future devs figure out things that were not immediately clear from the component API.

Added in-line comments for data table components to help future us's.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: INT-76
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.3f27b2.0<br/>@codecademy/gamut-labs@28.6.1-alpha.3f27b2.0<br/>@codecademy/gamut@42.2.2-alpha.3f27b2.0<br/>@codecademy/monaco@0.5.28-alpha.3f27b2.0<br/>@codecademy/styleguide@52.4.1-alpha.3f27b2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d371162bc6cb57de4e4954--gamut-preview.netlify.app>https://61d371162bc6cb57de4e4954--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d371162bc6cb57de4e4954>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
love it

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d4727655e41242c5932f74--gamut-preview.netlify.app>https://61d4727655e41242c5932f74--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d4727655e41242c5932f74>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.38-alpha.aa951c.0<br/>@codecademy/gamut-labs@28.6.1-alpha.aa951c.0<br/>@codecademy/gamut@42.2.2-alpha.aa951c.0<br/>@codecademy/monaco@0.5.28-alpha.aa951c.0<br/>@codecademy/styleguide@52.4.1-alpha.aa951c.0<br/></pre>

**Pull request merged**
