### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by dreamwasp**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6285061909de1825fc748e21--gamut-preview.netlify.app>https://6285061909de1825fc748e21--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6285061909de1825fc748e21>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
It might be configured to ignore markdown changes...

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.3.2-alpha.421e58.0<br/>@codecademy/gamut-illustrations@0.27.2-alpha.421e58.0<br/>@codecademy/gamut-kit@0.6.128-alpha.421e58.0<br/>@codecademy/gamut-labs@31.12.3-alpha.421e58.0<br/>@codecademy/gamut-patterns@0.8.6-alpha.421e58.0<br/>@codecademy/gamut-styles@13.1.2-alpha.421e58.0<br/>@codecademy/gamut-tests@4.0.5-alpha.421e58.0<br/>@codecademy/gamut@47.3.3-alpha.421e58.0<br/>@codecademy/markdown-overrides@0.9.3-alpha.421e58.0<br/>@codecademy/monaco@0.6.46-alpha.421e58.0<br/>@codecademy/styleguide@57.4.2-alpha.421e58.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62850bf0042af424a80a9acf--gamut-preview.netlify.app>https://62850bf0042af424a80a9acf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62850bf0042af424a80a9acf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62850f80cbbe3a2bb816954e--gamut-preview.netlify.app>https://62850f80cbbe3a2bb816954e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62850f80cbbe3a2bb816954e>Deploy Logs</a></p>

**Pull request closed without merging**
