### PR TITLE
fix: add webpack as a dev dependency

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Resolves yarn + webpack issues

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions
* Storybook should run locally

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://653686ca1c4bb62752923f9f--gamut-preview.netlify.app>https://653686ca1c4bb62752923f9f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/653686ca1c4bb62752923f9f>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
Very very sorry for dropping the ball on this! But yes 💯 this fixes things on my M1 Max Mac Mini! `yarn`, `yarn build`, and `yarn start` all work as expected now. The localhost Storybook preview looks exactly as I (fondly) remember it. Thanks!

**Review by jakemhiller — APPROVED** [review]
huh, fun!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65a8295a241cb406d446ebc4--gamut-preview.netlify.app>https://65a8295a241cb406d446ebc4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65a8295a241cb406d446ebc4>Deploy Logs</a></p>

**Pull request merged**
