### PR TITLE
feat(GlobalHeader): Rename Chat to Discord

### PR DESCRIPTION
**Pull request by borisonr**
### Overview

renames chat nav link to "discord", adds discord link to footer, adds spacing between footer sections

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [DISC-574](https://codecademy.atlassian.net/browse/DISC-574) and [DISC-641](https://codecademy.atlassian.net/browse/DISC-641)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/30818)  | [Monolith Env](https://pr-30818-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/portal-app/pull/1993)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1993)   |

Screen Shot 2022-05-19 at 1 08 59 PM

Screen Shot 2022-05-19 at 11 49 59 AM

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.128-alpha.dbb424.0<br/>@codecademy/gamut-labs@31.12.3-alpha.dbb424.0<br/>@codecademy/styleguide@57.4.2-alpha.dbb424.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.128-alpha.c7ac63.0<br/>@codecademy/gamut-labs@31.12.3-alpha.c7ac63.0<br/>@codecademy/styleguide@57.4.2-alpha.c7ac63.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62867474143516006c9a85c0--gamut-preview.netlify.app>https://62867474143516006c9a85c0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62867474143516006c9a85c0>Deploy Logs</a></p>

**Comment by borisonr** [comment]
got some more spacing requests from tamar, so will put this back to draft while i add them

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.130-alpha.8bfe66.0<br/>@codecademy/gamut-labs@31.13.2-alpha.8bfe66.0<br/>@codecademy/styleguide@57.5.2-alpha.8bfe66.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6287aa9ae5974d0d4e97488a--gamut-preview.netlify.app>https://6287aa9ae5974d0d4e97488a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6287aa9ae5974d0d4e97488a>Deploy Logs</a></p>

**Review by j10sanders — APPROVED** [review]
lgtm!

**Review by dreamwasp — APPROVED** [review]
nice!

**Pull request merged**
