### PR TITLE
feat(Badges)!: color + size variants

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Adds accent state + size variant to Badges 

### PR Checklist

- [x] Related to designs: [here](https://www.figma.com/file/YKo1KmtLMm2iZjfV4dcBsX/Post-RAD---Video-MVP-v1?node-id=239%3A15937)
- [x] Related to JIRA ticket: gm-352
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.18-alpha.03ebf7.0<br/>@codecademy/gamut-labs@28.0.13-alpha.03ebf7.0<br/>@codecademy/gamut@40.3.4-alpha.03ebf7.0<br/>@codecademy/monaco@0.5.14-alpha.03ebf7.0<br/>@codecademy/styleguide@50.2.5-alpha.03ebf7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619587b3d09b6826e612d4ef--gamut-preview.netlify.app>https://619587b3d09b6826e612d4ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619587b3d09b6826e612d4ef>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.bdee74.0<br/>@codecademy/gamut-labs@28.0.14-alpha.bdee74.0<br/>@codecademy/gamut@40.3.4-alpha.bdee74.0<br/>@codecademy/monaco@0.5.14-alpha.bdee74.0<br/>@codecademy/styleguide@50.2.6-alpha.bdee74.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.e51a07.0<br/>@codecademy/gamut-labs@28.0.14-alpha.e51a07.0<br/>@codecademy/gamut@40.3.4-alpha.e51a07.0<br/>@codecademy/monaco@0.5.14-alpha.e51a07.0<br/>@codecademy/styleguide@50.2.6-alpha.e51a07.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6196aacab1490400cc9a5053--gamut-preview.netlify.app>https://6196aacab1490400cc9a5053--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6196aacab1490400cc9a5053>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.c6c152.0<br/>@codecademy/gamut-labs@28.0.14-alpha.c6c152.0<br/>@codecademy/gamut@40.3.4-alpha.c6c152.0<br/>@codecademy/monaco@0.5.14-alpha.c6c152.0<br/>@codecademy/styleguide@50.2.6-alpha.c6c152.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6196c4ede4e3b30cfc5ac526--gamut-preview.netlify.app>https://6196c4ede4e3b30cfc5ac526--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6196c4ede4e3b30cfc5ac526>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.362542.0<br/>@codecademy/gamut-labs@28.0.14-alpha.362542.0<br/>@codecademy/gamut@40.3.4-alpha.362542.0<br/>@codecademy/monaco@0.5.14-alpha.362542.0<br/>@codecademy/styleguide@50.2.6-alpha.362542.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619bc9515be1173c8d1f7190--gamut-preview.netlify.app>https://619bc9515be1173c8d1f7190--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619bc9515be1173c8d1f7190>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.56e947.0<br/>@codecademy/gamut-labs@28.0.14-alpha.56e947.0<br/>@codecademy/gamut@40.3.4-alpha.56e947.0<br/>@codecademy/monaco@0.5.14-alpha.56e947.0<br/>@codecademy/styleguide@50.2.7-alpha.56e947.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619c1d62a65ebf00c7fd1ccd--gamut-preview.netlify.app>https://619c1d62a65ebf00c7fd1ccd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619c1d62a65ebf00c7fd1ccd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.20-alpha.5d0667.0<br/>@codecademy/gamut-labs@28.0.15-alpha.5d0667.0<br/>@codecademy/gamut@40.4.1-alpha.5d0667.0<br/>@codecademy/monaco@0.5.15-alpha.5d0667.0<br/>@codecademy/styleguide@50.3.2-alpha.5d0667.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619cfb5c7fd04b16b2e7de4e--gamut-preview.netlify.app>https://619cfb5c7fd04b16b2e7de4e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619cfb5c7fd04b16b2e7de4e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.20-alpha.07bece.0<br/>@codecademy/gamut-labs@28.0.15-alpha.07bece.0<br/>@codecademy/gamut@40.4.1-alpha.07bece.0<br/>@codecademy/monaco@0.5.15-alpha.07bece.0<br/>@codecademy/styleguide@50.3.2-alpha.07bece.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a5120e076a764cc928e1c5--gamut-preview.netlify.app>https://61a5120e076a764cc928e1c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a5120e076a764cc928e1c5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a51877632f7050a1386e07--gamut-preview.netlify.app>https://61a51877632f7050a1386e07--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a51877632f7050a1386e07>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.20-alpha.49b616.0<br/>@codecademy/gamut-labs@28.0.15-alpha.49b616.0<br/>@codecademy/gamut@40.4.1-alpha.49b616.0<br/>@codecademy/monaco@0.5.15-alpha.49b616.0<br/>@codecademy/styleguide@50.3.2-alpha.49b616.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.20-alpha.87caaf.0<br/>@codecademy/gamut-labs@28.0.15-alpha.87caaf.0<br/>@codecademy/gamut@40.4.1-alpha.87caaf.0<br/>@codecademy/monaco@0.5.15-alpha.87caaf.0<br/>@codecademy/styleguide@50.3.2-alpha.87caaf.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a528e3076a76627c28e5b3--gamut-preview.netlify.app>https://61a528e3076a76627c28e5b3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a528e3076a76627c28e5b3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.22-alpha.0142f5.0<br/>@codecademy/gamut-labs@28.1.2-alpha.0142f5.0<br/>@codecademy/gamut@40.5.1-alpha.0142f5.0<br/>@codecademy/monaco@0.5.17-alpha.0142f5.0<br/>@codecademy/styleguide@50.4.2-alpha.0142f5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a64235e1850a2d9285fe47--gamut-preview.netlify.app>https://61a64235e1850a2d9285fe47--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a64235e1850a2d9285fe47>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.537aef.0<br/>@codecademy/gamut-labs@28.1.4-alpha.537aef.0<br/>@codecademy/gamut@40.5.3-alpha.537aef.0<br/>@codecademy/monaco@0.5.19-alpha.537aef.0<br/>@codecademy/styleguide@50.4.4-alpha.537aef.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6a579a4d94b2defd0d38c--gamut-preview.netlify.app>https://61a6a579a4d94b2defd0d38c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6a579a4d94b2defd0d38c>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
👍

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.41db3c.0<br/>@codecademy/gamut-labs@28.2.1-alpha.41db3c.0<br/>@codecademy/gamut@40.5.3-alpha.41db3c.0<br/>@codecademy/monaco@0.5.19-alpha.41db3c.0<br/>@codecademy/styleguide@50.4.5-alpha.41db3c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a8ee420dbaed334133d67f--gamut-preview.netlify.app>https://61a8ee420dbaed334133d67f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a8ee420dbaed334133d67f>Deploy Logs</a></p>

**Review by aionate0812 — APPROVED** [review]
Amazing 🙌

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.511c2e.0<br/>@codecademy/gamut-labs@28.2.1-alpha.511c2e.0<br/>@codecademy/gamut@40.5.3-alpha.511c2e.0<br/>@codecademy/monaco@0.5.19-alpha.511c2e.0<br/>@codecademy/styleguide@50.4.5-alpha.511c2e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61afb186a18bce41dbf504b0--gamut-preview.netlify.app>https://61afb186a18bce41dbf504b0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61afb186a18bce41dbf504b0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.572f02.0<br/>@codecademy/gamut-labs@28.2.1-alpha.572f02.0<br/>@codecademy/gamut@40.5.3-alpha.572f02.0<br/>@codecademy/monaco@0.5.19-alpha.572f02.0<br/>@codecademy/styleguide@50.4.5-alpha.572f02.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61afcccd4562c80b4c73ef0c--gamut-preview.netlify.app>https://61afcccd4562c80b4c73ef0c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61afcccd4562c80b4c73ef0c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.26-alpha.e7a0ac.0<br/>@codecademy/gamut-labs@28.2.2-alpha.e7a0ac.0<br/>@codecademy/gamut@40.5.4-alpha.e7a0ac.0<br/>@codecademy/monaco@0.5.20-alpha.e7a0ac.0<br/>@codecademy/styleguide@50.4.6-alpha.e7a0ac.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.26-alpha.cda8bb.0<br/>@codecademy/gamut-labs@28.2.2-alpha.cda8bb.0<br/>@codecademy/gamut@40.5.4-alpha.cda8bb.0<br/>@codecademy/monaco@0.5.20-alpha.cda8bb.0<br/>@codecademy/styleguide@50.4.6-alpha.cda8bb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61afd514d9c8dc097402adfa--gamut-preview.netlify.app>https://61afd514d9c8dc097402adfa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61afd514d9c8dc097402adfa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.26-alpha.bef8ca.0<br/>@codecademy/gamut-labs@28.2.2-alpha.bef8ca.0<br/>@codecademy/gamut@40.5.4-alpha.bef8ca.0<br/>@codecademy/monaco@0.5.20-alpha.bef8ca.0<br/>@codecademy/styleguide@50.4.6-alpha.bef8ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61afdf6a3c942f00687ca5eb--gamut-preview.netlify.app>https://61afdf6a3c942f00687ca5eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61afdf6a3c942f00687ca5eb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.27-alpha.de5f37.0<br/>@codecademy/gamut-labs@28.3.1-alpha.de5f37.0<br/>@codecademy/gamut@40.5.4-alpha.de5f37.0<br/>@codecademy/monaco@0.5.20-alpha.de5f37.0<br/>@codecademy/styleguide@50.5.1-alpha.de5f37.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b10111dc5ac82d37725799--gamut-preview.netlify.app>https://61b10111dc5ac82d37725799--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b10111dc5ac82d37725799>Deploy Logs</a></p>

**Pull request merged**
