### PR TITLE
feat(Icons): Add ArrowDashRightIcon, ArrowChevronRightBoldIcon, and RankingWinnerIcon

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Adds ArrowDashRightIcon, ArrowChevronRightBoldIcon, and RankingWinnerIcon.

ArrowDashRightIcon:
Screenshot 2024-11-18 at 11 48 20 AM

ArrowChevronRightBoldIcon:
Screenshot 2024-11-18 at 11 49 33 AM

RankingWinnerIcon:
Screenshot 2024-11-18 at 11 48 39 AM

### PR Checklist

- [x] Related to designs: https://www.figma.com/design/vSeLumA7bCKTyWSDl4O3pY/Weekly-Syllabus?node-id=0-1
- [x] Related to JIRA ticket: [LEGO-4182](https://skillsoftdev.atlassian.net/browse/LEGO-4182)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Impersonate katie+testuser__2024-11-19_02-52-10pm@codecademy.com on tengu
2. Visit https://tengu.codecademy.com/career-journey/back-end-engineer?PR_ENV=portal-app-pr-8480

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/8480)  | [Portal Env](https://tengu.codecademy.com/career-journey/back-end-engineer?PR_ENV=portal-app-pr-8480) |

[LEGO-4182]: https://skillsoftdev.atlassian.net/browse/LEGO-4182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.5.1-alpha.025ed2.0<br/>@codecademy/gamut-icons@9.33.1-alpha.025ed2.0<br/>@codecademy/gamut-kit@0.6.454-alpha.025ed2.0<br/>@codecademy/styleguide@68.2.6-alpha.025ed2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://673b90ad68ac8b07c890314b--gamut-preview.netlify.app>https://673b90ad68ac8b07c890314b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/673b90ad68ac8b07c890314b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.5.1-alpha.359a78.0<br/>@codecademy/gamut-icons@9.33.1-alpha.359a78.0<br/>@codecademy/gamut-kit@0.6.454-alpha.359a78.0<br/>@codecademy/styleguide@68.2.6-alpha.359a78.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://673b99547963d808930fdc41--gamut-preview.netlify.app>https://673b99547963d808930fdc41--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/673b99547963d808930fdc41>Deploy Logs</a></p>

**Comment by katiezutter** [comment]
Hi @Codecademy/gamut! Seeing an error in the verify step: https://github.com/Codecademy/gamut/actions/runs/11899779051/job/33159397012?pr=2976 - anybody seen this before?

Screenshot 2024-11-18 at 11 54 20 AM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.5.1-alpha.359a78.0<br/>@codecademy/gamut-icons@9.33.1-alpha.359a78.0<br/>@codecademy/gamut-kit@0.6.454-alpha.359a78.0<br/>@codecademy/styleguide@68.2.6-alpha.359a78.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://673ce14f8bbc943bd5519540--gamut-preview.netlify.app>https://673ce14f8bbc943bd5519540--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/673ce14f8bbc943bd5519540>Deploy Logs</a></p>

**Review by LinKCoding — APPROVED** [review]
Icons look good to me :) 
checked on storybook for light + dark mode

impersonated on tengu and saw the arrow-dash-right and rank-winner-icon (but not the chevron, which is fine since it loads and displays via storybook). 

Jake + Cass looked into the cache failure, and that should be working now, thanks for flagging! 
And re: build failures - also looking into this, but if all other tests are passing (which they look like they are) you're good to merge!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.5.1-alpha.359a78.0<br/>@codecademy/gamut-icons@9.33.1-alpha.359a78.0<br/>@codecademy/gamut-kit@0.6.454-alpha.359a78.0<br/>@codecademy/styleguide@68.2.6-alpha.359a78.0<br/></pre>

**Comment by katiezutter** [comment]
@LinKCoding thanks a million!! You should be able to see the chevron in the modal that pops up after clicking 'Change week' in the syllabus header - my bad, should have been more clear about that instruction!

And thank you so much @jakemhiller and @dreamwasp for fixing the cache and build failures :)

**Pull request merged**
