### PR TITLE
feat(CurriculumCard): added optional description

### PR DESCRIPTION
**Pull request by cstatro**
### Overview

This PR adds an optional description prop to our Curriculum Card component. 

image

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: DISC-357
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.c623ce.0<br/>@codecademy/gamut-labs@28.1.4-alpha.c623ce.0<br/>@codecademy/styleguide@50.4.4-alpha.c623ce.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6b0b86651c533bdc79768--gamut-preview.netlify.app>https://61a6b0b86651c533bdc79768--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6b0b86651c533bdc79768>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.e94250.0<br/>@codecademy/gamut-labs@28.1.4-alpha.e94250.0<br/>@codecademy/styleguide@50.4.4-alpha.e94250.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6b9fb1e82334ebe2fe07e--gamut-preview.netlify.app>https://61a6b9fb1e82334ebe2fe07e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6b9fb1e82334ebe2fe07e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.0dc716.0<br/>@codecademy/gamut-labs@28.1.4-alpha.0dc716.0<br/>@codecademy/styleguide@50.4.4-alpha.0dc716.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6bd1d62502d5026da1b61--gamut-preview.netlify.app>https://61a6bd1d62502d5026da1b61--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6bd1d62502d5026da1b61>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.54af82.0<br/>@codecademy/gamut-labs@28.1.4-alpha.54af82.0<br/>@codecademy/styleguide@50.4.4-alpha.54af82.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a79752be585733c5c4c7c6--gamut-preview.netlify.app>https://61a79752be585733c5c4c7c6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a79752be585733c5c4c7c6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.2bb583.0<br/>@codecademy/gamut-labs@28.1.4-alpha.2bb583.0<br/>@codecademy/styleguide@50.4.4-alpha.2bb583.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a799b95e12393493193cd4--gamut-preview.netlify.app>https://61a799b95e12393493193cd4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a799b95e12393493193cd4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.287415.0<br/>@codecademy/gamut-labs@28.1.4-alpha.287415.0<br/>@codecademy/styleguide@50.4.4-alpha.287415.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a7dc4c1c348f9889a55213--gamut-preview.netlify.app>https://61a7dc4c1c348f9889a55213--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a7dc4c1c348f9889a55213>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.237c18.0<br/>@codecademy/gamut-labs@28.2.1-alpha.237c18.0<br/>@codecademy/styleguide@50.4.5-alpha.237c18.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a92f4557e2a1006362769b--gamut-preview.netlify.app>https://61a92f4557e2a1006362769b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a92f4557e2a1006362769b>Deploy Logs</a></p>

**Review by zippyzow — COMMENTED** [review]
The design has the description under the title and the difficulty, etc below that. Also the description font size looks to be 16 in the storybook but is 14 in the design. 

Is the design  out of date?
Screen Shot 2021-12-03 at 2 53 17 PM

**Comment by cstatro** [comment]
@zippyzow  nope , changed size

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.595fdc.0<br/>@codecademy/gamut-labs@28.2.1-alpha.595fdc.0<br/>@codecademy/styleguide@50.4.5-alpha.595fdc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61ae82ff5113e03534940bb2--gamut-preview.netlify.app>https://61ae82ff5113e03534940bb2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61ae82ff5113e03534940bb2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.fe3ed4.0<br/>@codecademy/gamut-labs@28.2.1-alpha.fe3ed4.0<br/>@codecademy/styleguide@50.4.5-alpha.fe3ed4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61af97c1a699ec2b6e466ced--gamut-preview.netlify.app>https://61af97c1a699ec2b6e466ced--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61af97c1a699ec2b6e466ced>Deploy Logs</a></p>

**Review by zippyzow — APPROVED** [review]
Looks good to me as long as Tamar is on board as well!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.26-alpha.61b8af.0<br/>@codecademy/gamut-labs@28.2.2-alpha.61b8af.0<br/>@codecademy/styleguide@50.4.6-alpha.61b8af.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b0d507438c893a8f9bc2ba--gamut-preview.netlify.app>https://61b0d507438c893a8f9bc2ba--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b0d507438c893a8f9bc2ba>Deploy Logs</a></p>

**Pull request merged**
