### PR TITLE
feat: add listStyle props to Box and Column

### PR DESCRIPTION
**Pull request by christian-dinh**
### Overview

add listStyle, listStyleType, listStyleImage, and listStylePosition props to `Box` and `Column`

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-3045](https://codecademy.atlassian.net/browse/REACH-3045)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

- add `listStyle`, `listStyleType`, `listStyleImage`, and `listStylePosition` props to `Column`, `Box`, `FlexBox`, and `GridBox` components
- ensure code passes type checker
- ensure prop values are rendered as styles for the component

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/3657)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-3657)   |

[REACH-3045]: https://codecademy.atlassian.net/browse/REACH-3045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.5.1-alpha.e41bcc.0<br/>@codecademy/gamut-icons@9.4.3-alpha.e41bcc.0<br/>@codecademy/gamut-illustrations@0.39.3-alpha.e41bcc.0<br/>@codecademy/gamut-kit@0.6.346-alpha.e41bcc.0<br/>@codecademy/gamut-patterns@0.9.10-alpha.e41bcc.0<br/>@codecademy/gamut-styles@16.1.5-alpha.e41bcc.0<br/>@codecademy/gamut-tests@5.0.9-alpha.e41bcc.0<br/>@codecademy/styleguide@66.3.1-alpha.e41bcc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6511cab252bcec04334d32b2--gamut-preview.netlify.app>https://6511cab252bcec04334d32b2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6511cab252bcec04334d32b2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65133c106ede2a0cfb61e353--gamut-preview.netlify.app>https://65133c106ede2a0cfb61e353--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65133c106ede2a0cfb61e353>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.6.2-alpha.5b3002.0<br/>@codecademy/gamut-icons@9.4.3-alpha.5b3002.0<br/>@codecademy/gamut-illustrations@0.40.1-alpha.5b3002.0<br/>@codecademy/gamut-kit@0.6.348-alpha.5b3002.0<br/>@codecademy/gamut-patterns@0.9.10-alpha.5b3002.0<br/>@codecademy/gamut-styles@16.1.5-alpha.5b3002.0<br/>@codecademy/gamut-tests@5.0.9-alpha.5b3002.0<br/>@codecademy/styleguide@66.4.2-alpha.5b3002.0<br/></pre>

**Review by dreamwasp — COMMENTED** [review]
i love this so much!!!!! 

pending regression testing, my only ask is that you add a section in the CSS Props documentation ([here](https://65133c106ede2a0cfb61e353--gamut-preview.netlify.app/?path=/docs/foundations-system-props--layout))

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65149f429640e90b89907a5c--gamut-preview.netlify.app>https://65149f429640e90b89907a5c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65149f429640e90b89907a5c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.7.2-alpha.907198.0<br/>@codecademy/gamut-icons@9.4.3-alpha.907198.0<br/>@codecademy/gamut-illustrations@0.40.1-alpha.907198.0<br/>@codecademy/gamut-kit@0.6.351-alpha.907198.0<br/>@codecademy/gamut-patterns@0.9.10-alpha.907198.0<br/>@codecademy/gamut-styles@16.1.5-alpha.907198.0<br/>@codecademy/gamut-tests@5.0.9-alpha.907198.0<br/>@codecademy/styleguide@66.5.2-alpha.907198.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.1-alpha.f47198.0<br/>@codecademy/gamut-icons@9.4.4-alpha.f47198.0<br/>@codecademy/gamut-illustrations@0.40.1-alpha.f47198.0<br/>@codecademy/gamut-kit@0.6.356-alpha.f47198.0<br/>@codecademy/gamut-patterns@0.9.11-alpha.f47198.0<br/>@codecademy/gamut-styles@16.1.5-alpha.f47198.0<br/>@codecademy/gamut-tests@5.0.9-alpha.f47198.0<br/>@codecademy/styleguide@66.5.8-alpha.f47198.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65285c3211e7240e6cc4a903--gamut-preview.netlify.app>https://65285c3211e7240e6cc4a903--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65285c3211e7240e6cc4a903>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.2-alpha.fa77c3.0<br/>@codecademy/gamut-icons@9.4.4-alpha.fa77c3.0<br/>@codecademy/gamut-illustrations@0.41.1-alpha.fa77c3.0<br/>@codecademy/gamut-kit@0.6.357-alpha.fa77c3.0<br/>@codecademy/gamut-patterns@0.9.11-alpha.fa77c3.0<br/>@codecademy/gamut-styles@16.1.5-alpha.fa77c3.0<br/>@codecademy/gamut-tests@5.0.9-alpha.fa77c3.0<br/>@codecademy/styleguide@66.5.9-alpha.fa77c3.0<br/></pre>

**Review by dreamwasp — COMMENTED** [review]
looks great to me and works like a charm, wonderful addition to our design system!! could you add test PR to the monolith? i just want to triple-check now weird type things happen there before you 🚢

**Comment by christian-dinh** [comment]
Sorry for the delay, monolith PR is up!

https://github.com/codecademy-engineering/Codecademy/pull/36642

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.3-alpha.a6b2e4.0<br/>@codecademy/gamut-icons@9.4.4-alpha.a6b2e4.0<br/>@codecademy/gamut-illustrations@0.41.1-alpha.a6b2e4.0<br/>@codecademy/gamut-kit@0.6.358-alpha.a6b2e4.0<br/>@codecademy/gamut-patterns@0.9.11-alpha.a6b2e4.0<br/>@codecademy/gamut-styles@16.1.5-alpha.a6b2e4.0<br/>@codecademy/gamut-tests@5.0.9-alpha.a6b2e4.0<br/>@codecademy/styleguide@66.5.10-alpha.a6b2e4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6538038f410ad329a36efbdd--gamut-preview.netlify.app>https://6538038f410ad329a36efbdd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6538038f410ad329a36efbdd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.3-alpha.28232c.0<br/>@codecademy/gamut-icons@9.5.0-alpha.28232c.0<br/>@codecademy/gamut-illustrations@0.41.1-alpha.28232c.0<br/>@codecademy/gamut-kit@0.6.358-alpha.28232c.0<br/>@codecademy/gamut-patterns@0.9.11-alpha.28232c.0<br/>@codecademy/gamut-styles@16.1.5-alpha.28232c.0<br/>@codecademy/gamut-tests@5.0.9-alpha.28232c.0<br/>@codecademy/styleguide@66.5.10-alpha.28232c.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
thanks for the awesome work + for being so tenacious with this pr ✨ excited for this to get shipped 😤

**Review by dreamwasp — APPROVED** [review]
thanks for the awesome work + for being so tenacious with this pr ✨ excited for this to get shipped 😤

**Pull request merged**
