### PR TITLE
feat(Icon): Add OneTimeIcon

### PR DESCRIPTION
**Pull request by JahazielGuzman**
### Overview
This is needed for the incorrect questions intro interstitial [introduced here](https://github.com/codecademy-engineering/Codecademy/pull/34841)

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [LEGO-3210](https://codecademy.atlassian.net/browse/LEGO-3210)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[LEGO-3204]: https://codecademy.atlassian.net/browse/LEGO-3204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LEGO-3210]: https://codecademy.atlassian.net/browse/LEGO-3210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@8.0.2-alpha.367a8c.0<br/>@codecademy/gamut-kit@0.6.288-alpha.367a8c.0<br/>@codecademy/gamut-labs@35.6.3-alpha.367a8c.0<br/>@codecademy/gamut@52.0.7-alpha.367a8c.0<br/>@codecademy/monaco@0.7.7-alpha.367a8c.0<br/>@codecademy/styleguide@63.5.13-alpha.367a8c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63ffc9f7bc30e020290b86bb--gamut-preview.netlify.app>https://63ffc9f7bc30e020290b86bb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63ffc9f7bc30e020290b86bb>Deploy Logs</a></p>

**Review by katiezutter — COMMENTED** [review]
Looks like the icon is white in the storybook:
Screenshot 2023-03-02 at 4 12 31 PM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@8.0.2-alpha.2d7974.0<br/>@codecademy/gamut-kit@0.6.288-alpha.2d7974.0<br/>@codecademy/gamut-labs@35.6.3-alpha.2d7974.0<br/>@codecademy/gamut@52.0.7-alpha.2d7974.0<br/>@codecademy/monaco@0.7.7-alpha.2d7974.0<br/>@codecademy/styleguide@63.5.13-alpha.2d7974.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64012f5d825f5648b16c0012--gamut-preview.netlify.app>https://64012f5d825f5648b16c0012--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64012f5d825f5648b16c0012>Deploy Logs</a></p>

**Comment by JahazielGuzman** [comment]
> Looks like the icon is white in the storybook: Screenshot 2023-03-02 at 4 12 31 PM

Fixed!!

**Review by katiezutter — APPROVED** [review]
lgtm!

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://640237e40dfed00057d8f0ee--gamut-preview.netlify.app>https://640237e40dfed00057d8f0ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/640237e40dfed00057d8f0ee>Deploy Logs</a></p>

**Pull request merged**
