### PR TITLE
fix:  Docs: remove console.log from getKinds

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

I left this in while debugging this code with stephen, oops.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@53.0.1-alpha.747ccc.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e0997588d11b16659f886e--gamut-preview.netlify.app>https://61e0997588d11b16659f886e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e0997588d11b16659f886e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@53.0.2-alpha.92653e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e83c8b1fe03b445dcade81--gamut-preview.netlify.app>https://61e83c8b1fe03b445dcade81--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e83c8b1fe03b445dcade81>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
