### PR TITLE
fix(SelectDropdown): fixed isSearchable prop

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

isSearchable prop was getting wiped out - SelectDropdown's default state is now back to not being searchable

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.40-alpha.2a1dd2.0<br/>@codecademy/gamut-labs@28.6.3-alpha.2a1dd2.0<br/>@codecademy/gamut@42.3.1-alpha.2a1dd2.0<br/>@codecademy/monaco@0.5.29-alpha.2a1dd2.0<br/>@codecademy/styleguide@52.5.2-alpha.2a1dd2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61df5024ce642e54e4a30117--gamut-preview.netlify.app>https://61df5024ce642e54e4a30117--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61df5024ce642e54e4a30117>Deploy Logs</a></p>

**Review by MattSchiller — APPROVED** [review]
So this was definitely me, though why is the default value not falsy?

**Comment by dreamwasp** [comment]
> So this was definitely me, though why is the default value not falsy?

i suppose, at the time of its inception, i simply forgot 🥲

**Comment by MattSchiller** [comment]
Lol, no no, I mean why is `ReactSelect` not respecting an `undefined` value as falsy. That's so weird.

Either way, good spot!

**Comment by dreamwasp** [comment]
> So this was definitely me, though why is the default value not falsy?

i'm not 100% sure - i do know that explicitly defining `false` as the default fixes the problem + may be helpful for future devs to be aware that `isSearchable` being false by default is v intended behavior

**Review by mstykmshy — APPROVED** [review]
Lookin goood, thanks for getting this fixed so quickly! 🎉

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.41-alpha.07e6e2.0<br/>@codecademy/gamut-labs@28.6.4-alpha.07e6e2.0<br/>@codecademy/gamut@43.0.1-alpha.07e6e2.0<br/>@codecademy/monaco@0.5.30-alpha.07e6e2.0<br/>@codecademy/styleguide@53.0.1-alpha.07e6e2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e193aa5be3441b5ceaf805--gamut-preview.netlify.app>https://61e193aa5be3441b5ceaf805--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e193aa5be3441b5ceaf805>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61e7389d6f1c3b450e848606--gamut-preview.netlify.app>https://61e7389d6f1c3b450e848606--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61e7389d6f1c3b450e848606>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61eacb192f6377196c4e6cf1--gamut-preview.netlify.app>https://61eacb192f6377196c4e6cf1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61eacb192f6377196c4e6cf1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.44-alpha.668f7e.0<br/>@codecademy/gamut-labs@28.7.1-alpha.668f7e.0<br/>@codecademy/gamut@43.1.2-alpha.668f7e.0<br/>@codecademy/monaco@0.5.32-alpha.668f7e.0<br/>@codecademy/styleguide@53.1.1-alpha.668f7e.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.49-alpha.1a3c9b.0<br/>@codecademy/gamut-labs@29.1.2-alpha.1a3c9b.0<br/>@codecademy/gamut@44.1.1-alpha.1a3c9b.0<br/>@codecademy/monaco@0.6.3-alpha.1a3c9b.0<br/>@codecademy/styleguide@54.0.4-alpha.1a3c9b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f40245d5267fee5a4f1405--gamut-preview.netlify.app>https://61f40245d5267fee5a4f1405--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f40245d5267fee5a4f1405>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.50-alpha.dcd1a2.0<br/>@codecademy/gamut-labs@29.2.1-alpha.dcd1a2.0<br/>@codecademy/gamut@44.2.0-alpha.dcd1a2.0<br/>@codecademy/monaco@0.6.3-alpha.dcd1a2.0<br/>@codecademy/styleguide@54.0.5-alpha.dcd1a2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f423ad77de0708dc95cf14--gamut-preview.netlify.app>https://61f423ad77de0708dc95cf14--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f423ad77de0708dc95cf14>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.51-alpha.f37454.0<br/>@codecademy/gamut-labs@29.2.2-alpha.f37454.0<br/>@codecademy/gamut@44.2.1-alpha.f37454.0<br/>@codecademy/monaco@0.6.4-alpha.f37454.0<br/>@codecademy/styleguide@54.0.6-alpha.f37454.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f4434502f65449a9c0b126--gamut-preview.netlify.app>https://61f4434502f65449a9c0b126--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f4434502f65449a9c0b126>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.52-alpha.911263.0<br/>@codecademy/gamut-labs@29.2.3-alpha.911263.0<br/>@codecademy/gamut@44.2.2-alpha.911263.0<br/>@codecademy/monaco@0.6.5-alpha.911263.0<br/>@codecademy/styleguide@54.0.7-alpha.911263.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f811706cf221f7ea567772--gamut-preview.netlify.app>https://61f811706cf221f7ea567772--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f811706cf221f7ea567772>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.53-alpha.948c1a.0<br/>@codecademy/gamut-labs@29.2.4-alpha.948c1a.0<br/>@codecademy/gamut@44.2.3-alpha.948c1a.0<br/>@codecademy/monaco@0.6.6-alpha.948c1a.0<br/>@codecademy/styleguide@54.0.8-alpha.948c1a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fa94cb8530f0260f317cd0--gamut-preview.netlify.app>https://61fa94cb8530f0260f317cd0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fa94cb8530f0260f317cd0>Deploy Logs</a></p>

**Pull request merged**
