### PR TITLE
fix: Markdown details element styles

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

* Added details element styles and component override

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [WEB-1877]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

To Test: go to https://6202a30837f74d29bdb39364--gamut-preview.netlify.app/iframe.html?id=atoms-markdown--full-example&viewMode=docs#details

go down to the "details" section, try out the opening/closing details element

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.59-alpha.f39389.0<br/>@codecademy/gamut-labs@29.2.10-alpha.f39389.0<br/>@codecademy/gamut@44.5.1-alpha.f39389.0<br/>@codecademy/monaco@0.6.12-alpha.f39389.0<br/>@codecademy/styleguide@54.2.2-alpha.f39389.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.59-alpha.3fe76e.0<br/>@codecademy/gamut-labs@29.2.10-alpha.3fe76e.0<br/>@codecademy/gamut@44.5.1-alpha.3fe76e.0<br/>@codecademy/monaco@0.6.12-alpha.3fe76e.0<br/>@codecademy/styleguide@54.2.2-alpha.3fe76e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6202b3217a26da43276f0662--gamut-preview.netlify.app>https://6202b3217a26da43276f0662--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6202b3217a26da43276f0662>Deploy Logs</a></p>

**Review by reedlaverack — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.0-alpha.ac33c0.0<br/>@codecademy/gamut-kit@0.6.59-alpha.ac33c0.0<br/>@codecademy/gamut-labs@29.3.0-alpha.ac33c0.0<br/>@codecademy/gamut@44.5.1-alpha.ac33c0.0<br/>@codecademy/monaco@0.6.12-alpha.ac33c0.0<br/>@codecademy/styleguide@54.3.0-alpha.ac33c0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6202b5af47ce1e3c94ce39d6--gamut-preview.netlify.app>https://6202b5af47ce1e3c94ce39d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6202b5af47ce1e3c94ce39d6>Deploy Logs</a></p>

**Pull request merged**
