### PR TITLE
fix(Alert): padding issue when no dismiss button

### PR DESCRIPTION
**Pull request by LinKCoding**
### Overview
Added responsive right padding for Alerts where there is no close button. 
Smaller fixes for other files for consistency. 

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?type=design&node-id=30186-40358&mode=dev 
    - [x] maybe more specific to spacing: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=45965%3A32582
- [x] Related to JIRA ticket: [GM-608]
- [x] I have run this code to verify it works

#### Testing Instructions

1. Boot up the server locally
2.  go to `packages/gamut/src/Alert/Alert.tsx` 
  3. when checking the spacing for no close button, you'll need to go to `packages/styleguide/stories/Molecules/Alert/index.stories.mdx` and inside an `args` set `onClose: false` 

E.g. 
```
<Meta
  title={title}
  component={Alert}
  parameters={{
    subtitle:
      'An alert displays an important, succinct message, and provides actions for users to address (or dismiss the alert). It requires a user action to be dismissed.',
    status: 'current',
    source: 'gamut',
    design: {
      type: 'figma',
      url: 'https://www.figma.com/file/TemYhRWOavsERWprDzRJCx',
    },
    padded: true,
  }}
  args={{
    type: 'general',
    placement: 'floating',
    cta: {
      children: 'Learn More',
    },
    children:
      'You have been logged out due to inactivity. Click the button to log in again.',
   // ADDED ONCLOSE HERE
    onClose: false,
  }}
/>
```
^ you can also go to `.constants` and change `onClose` there too. 
4. Inspect the element(s) and check that the spacing(padding + column-gap) on the right-hand side is applied and that elements match the design's specs for all breakpoints
  5.  you may note that for the smallest breakpoint it's set to 4 (`{_:4 ...}` that's because the column-gap is 12 when there's no buttons, so both padding and column will add up to 16. 
6 ...
7. Done! 

#### PR Links and Envs
(None, just Gamut)

[GM-608]: https://codecademy.atlassian.net/browse/GM-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.15.1-alpha.ba6fb3.0<br/>@codecademy/gamut-kit@0.6.395-alpha.ba6fb3.0<br/>@codecademy/styleguide@66.15.1-alpha.ba6fb3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://660eef62a09f563730730f53--gamut-preview.netlify.app>https://660eef62a09f563730730f53--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/660eef62a09f563730730f53>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.15.1-alpha.6e1e5f.0<br/>@codecademy/gamut-kit@0.6.395-alpha.6e1e5f.0<br/>@codecademy/styleguide@66.15.1-alpha.6e1e5f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://660ef4a09a35f53ba975f3ff--gamut-preview.netlify.app>https://660ef4a09a35f53ba975f3ff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/660ef4a09a35f53ba975f3ff>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.1-alpha.9884d4.0<br/>@codecademy/gamut-kit@0.6.396-alpha.9884d4.0<br/>@codecademy/styleguide@66.16.1-alpha.9884d4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://660ffc0636ff3a1d2a839902--gamut-preview.netlify.app>https://660ffc0636ff3a1d2a839902--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/660ffc0636ff3a1d2a839902>Deploy Logs</a></p>

**Review by dreamwasp — CHANGES_REQUESTED** [review]
have some comments to clean up but otherwise looking great!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.1-alpha.3a7c58.0<br/>@codecademy/gamut-kit@0.6.396-alpha.3a7c58.0<br/>@codecademy/styleguide@66.16.1-alpha.3a7c58.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661040e943da5c2c2f09739b--gamut-preview.netlify.app>https://661040e943da5c2c2f09739b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661040e943da5c2c2f09739b>Deploy Logs</a></p>

**Comment by LinKCoding** [comment]
> have some comments to clean up but otherwise looking great!

@dreamwasp should be fixed now, sorry about that!

**Review by dreamwasp — APPROVED** [review]
✨

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.1-alpha.d465ac.0<br/>@codecademy/gamut-kit@0.6.396-alpha.d465ac.0<br/>@codecademy/styleguide@66.16.1-alpha.d465ac.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661410a05e6bf704cd5e9736--gamut-preview.netlify.app>https://661410a05e6bf704cd5e9736--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661410a05e6bf704cd5e9736>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.1-alpha.075b75.0<br/>@codecademy/gamut-kit@0.6.396-alpha.075b75.0<br/>@codecademy/styleguide@66.16.1-alpha.075b75.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661416e6e949a20fee5029b3--gamut-preview.netlify.app>https://661416e6e949a20fee5029b3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661416e6e949a20fee5029b3>Deploy Logs</a></p>

**Pull request merged**
