### PR TITLE
feat(Header): added configurable initial visibility for search

### PR DESCRIPTION
**Pull request by cstatro**
### PR Checklist
This PR gives our header the ability to have the search be initially expanded. We are experimenting with this as part of an onboarding flow. 

 in action:
https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1035&onboard_search=true

related PRs

- experiment PR https://github.com/codecademy-engineering/Codecademy/pull/28356
- portal app implementation of alpha build  https://github.com/codecademy-engineering/portal-app/pull/1035

- [x] Related to JIRA ticket: Disc-313
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.a1edde.0<br/>@codecademy/gamut-labs@28.0.14-alpha.a1edde.0<br/>@codecademy/styleguide@50.2.7-alpha.a1edde.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619c0156ee447f7c16a7409c--gamut-preview.netlify.app>https://619c0156ee447f7c16a7409c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619c0156ee447f7c16a7409c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.d657d2.0<br/>@codecademy/gamut-labs@28.0.14-alpha.d657d2.0<br/>@codecademy/styleguide@50.2.7-alpha.d657d2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619d2bd492bb754b70fcf1a8--gamut-preview.netlify.app>https://619d2bd492bb754b70fcf1a8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619d2bd492bb754b70fcf1a8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.f0fdba.0<br/>@codecademy/gamut-labs@28.0.14-alpha.f0fdba.0<br/>@codecademy/styleguide@50.2.7-alpha.f0fdba.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619eacb6f14e93ce81ac7cda--gamut-preview.netlify.app>https://619eacb6f14e93ce81ac7cda--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619eacb6f14e93ce81ac7cda>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
this all looks good to me, but tagging @thedoomshine as she's been working on header things recently!

**Review by borisonr — APPROVED** [review]
looks good to me, but defer to @thedoomshine !

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.cea45e.0<br/>@codecademy/gamut-labs@28.1.4-alpha.cea45e.0<br/>@codecademy/styleguide@50.4.4-alpha.cea45e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a66dae0a0dd46311164357--gamut-preview.netlify.app>https://61a66dae0a0dd46311164357--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a66dae0a0dd46311164357>Deploy Logs</a></p>

**Review by BandanaKM — COMMENTED** [review]
all else looks sound!

**Review by BandanaKM — APPROVED** [review]

**Review by dougyd92 — APPROVED** [review]
Looks good! The only issue I saw is that there is a brief moment when the page first renders where the search bar isn't visible, then it pops in. Not sure if it's possible to do anything about that though.

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.481810.0<br/>@codecademy/gamut-labs@28.1.4-alpha.481810.0<br/>@codecademy/styleguide@50.4.4-alpha.481810.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a7df37f10ac59662ef13b2--gamut-preview.netlify.app>https://61a7df37f10ac59662ef13b2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a7df37f10ac59662ef13b2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.650279.0<br/>@codecademy/gamut-labs@28.1.4-alpha.650279.0<br/>@codecademy/styleguide@50.4.4-alpha.650279.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a8e711ec25b9287c92a0ec--gamut-preview.netlify.app>https://61a8e711ec25b9287c92a0ec--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a8e711ec25b9287c92a0ec>Deploy Logs</a></p>

**Pull request merged**
