### PR TITLE
feat(List): add overflow prop

### PR DESCRIPTION
**Pull request by smithgajjar09**
### Overview
Adds an overflow prop to List Component

### PR Checklist

- [x] ~Related to designs:~
- [x] Related to JIRA ticket: [[GM-636](https://codecademy.atlassian.net/browse/GM-636)]
- [x] I have run this code to verify it works
- [x] ~This PR includes unit tests for the code change~
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. visit `courses/introduction-to-javascript/quizzes/learn-javascript-control-flow-control-flow-quiz` 
2. tab through the quiz MCQ options, focus-rings should be visible.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| LE (le-shared)      | [Mono](https://github.com/codecademy-engineering/mono/pull/5458)  | [LE Env](https://tayra.codecademy.com/courses/introduction-to-javascript/quizzes/learn-javascript-control-flow-control-flow-quiz)   |
| Portal App      | [Mono](https://github.com/codecademy-engineering/mono/pull/5458)  | [LE Env](https://tengu.codecademy.com/courses/introduction-to-javascript/quizzes/learn-javascript-control-flow-control-flow-quiz)   |

[GM-636]: https://codecademy.atlassian.net/browse/GM-636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.1-alpha.a63339.0<br/>@codecademy/gamut-kit@0.6.389-alpha.a63339.0<br/>@codecademy/styleguide@66.14.1-alpha.a63339.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f88cd2b369cb104474eed8--gamut-preview.netlify.app>https://65f88cd2b369cb104474eed8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f88cd2b369cb104474eed8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.1-alpha.d63920.0<br/>@codecademy/gamut-kit@0.6.389-alpha.d63920.0<br/>@codecademy/styleguide@66.14.1-alpha.d63920.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f89475ee073b0beeda660c--gamut-preview.netlify.app>https://65f89475ee073b0beeda660c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f89475ee073b0beeda660c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.1-alpha.ff541e.0<br/>@codecademy/gamut-kit@0.6.389-alpha.ff541e.0<br/>@codecademy/styleguide@66.14.1-alpha.ff541e.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
really wonderful change, i love how intuitive this + great docs changes as well! really matches the spirit of Gamut 🔥

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.3-alpha.026bb6.0<br/>@codecademy/gamut-kit@0.6.391-alpha.026bb6.0<br/>@codecademy/styleguide@66.14.4-alpha.026bb6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6602fa8dcaaa4d607e6b827b--gamut-preview.netlify.app>https://6602fa8dcaaa4d607e6b827b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6602fa8dcaaa4d607e6b827b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.3-alpha.1c7b24.0<br/>@codecademy/gamut-kit@0.6.391-alpha.1c7b24.0<br/>@codecademy/styleguide@66.14.4-alpha.1c7b24.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://660554e8388f5a1873b3278c--gamut-preview.netlify.app>https://660554e8388f5a1873b3278c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/660554e8388f5a1873b3278c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.14.6-alpha.f04bc4.0<br/>@codecademy/gamut-kit@0.6.394-alpha.f04bc4.0<br/>@codecademy/styleguide@66.14.7-alpha.f04bc4.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://660ecb3c153a6216114e5c68--gamut-preview.netlify.app>https://660ecb3c153a6216114e5c68--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/660ecb3c153a6216114e5c68>Deploy Logs</a></p>

**Pull request merged**
