### PR TITLE
refactor(ContentGroupBaseCard): CourseDifficulty export and description truncation 

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

- Fixed exporting for the types in ContentGroupBaseCard
- Changed description truncation to 3 per design feedback 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Check out the mono env and see existing cards are the same aside from those with longer descriptions should now be 3 lines not 4. In addition, all tests should pass despite new export fix. No visible changes on monolith yet. 

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34642)
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1260)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1260)

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e41abbb97c933019a0c004--gamut-preview.netlify.app>https://63e41abbb97c933019a0c004--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e41abbb97c933019a0c004>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.22a1cf.0<br/>@codecademy/gamut-labs@35.5.4-alpha.22a1cf.0<br/>@codecademy/styleguide@63.5.2-alpha.22a1cf.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.278-alpha.9bfba0.0<br/>@codecademy/gamut-labs@35.5.4-alpha.9bfba0.0<br/>@codecademy/styleguide@63.5.2-alpha.9bfba0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e5133fe442000050c6ac8c--gamut-preview.netlify.app>https://63e5133fe442000050c6ac8c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e5133fe442000050c6ac8c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.279-alpha.a083ab.0<br/>@codecademy/gamut-labs@35.5.5-alpha.a083ab.0<br/>@codecademy/styleguide@63.5.3-alpha.a083ab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e5172658fa1800a24fd0b5--gamut-preview.netlify.app>https://63e5172658fa1800a24fd0b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e5172658fa1800a24fd0b5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.280-alpha.d4a823.0<br/>@codecademy/gamut-labs@35.5.6-alpha.d4a823.0<br/>@codecademy/styleguide@63.5.4-alpha.d4a823.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e5392e4263d2133f872629--gamut-preview.netlify.app>https://63e5392e4263d2133f872629--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e5392e4263d2133f872629>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.06d9cd.0<br/>@codecademy/gamut-labs@35.5.8-alpha.06d9cd.0<br/>@codecademy/styleguide@63.5.6-alpha.06d9cd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e651d8a0421400b809c1f5--gamut-preview.netlify.app>https://63e651d8a0421400b809c1f5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e651d8a0421400b809c1f5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.7a9ef3.0<br/>@codecademy/gamut-labs@35.5.8-alpha.7a9ef3.0<br/>@codecademy/styleguide@63.5.6-alpha.7a9ef3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e699823d8d350829e7f13f--gamut-preview.netlify.app>https://63e699823d8d350829e7f13f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e699823d8d350829e7f13f>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.df1622.0<br/>@codecademy/gamut-labs@35.5.8-alpha.df1622.0<br/>@codecademy/styleguide@63.5.6-alpha.df1622.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e942fc16ba54420fe6644b--gamut-preview.netlify.app>https://63e942fc16ba54420fe6644b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e942fc16ba54420fe6644b>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.42f475.0<br/>@codecademy/gamut-labs@35.5.8-alpha.42f475.0<br/>@codecademy/styleguide@63.5.6-alpha.42f475.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e94ad8c36db7456ac14e8d--gamut-preview.netlify.app>https://63e94ad8c36db7456ac14e8d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e94ad8c36db7456ac14e8d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.16e478.0<br/>@codecademy/gamut-labs@35.5.8-alpha.16e478.0<br/>@codecademy/styleguide@63.5.6-alpha.16e478.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e950823d8d354799e7f1ae--gamut-preview.netlify.app>https://63e950823d8d354799e7f1ae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e950823d8d354799e7f1ae>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.fd44db.0<br/>@codecademy/gamut-labs@35.5.8-alpha.fd44db.0<br/>@codecademy/styleguide@63.5.6-alpha.fd44db.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e95aeac29eb259a91b8d7d--gamut-preview.netlify.app>https://63e95aeac29eb259a91b8d7d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e95aeac29eb259a91b8d7d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.282-alpha.790003.0<br/>@codecademy/gamut-labs@35.5.8-alpha.790003.0<br/>@codecademy/styleguide@63.5.6-alpha.790003.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63e9626ffb18ad5ccb5c4bfc--gamut-preview.netlify.app>https://63e9626ffb18ad5ccb5c4bfc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63e9626ffb18ad5ccb5c4bfc>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
✨

**Review by cstatro — APPROVED** [review]

**Pull request merged**
