### PR TITLE
feat(DataTable): Sort header click target + hover styles

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

* entire header as sort target 
* correct sort control hover state

### PR Checklist

- [x] Related to designs: [here](https://www.figma.com/file/jFEYJnf0MxgT0G4bPFAZe5/Reporting-2.0%3A-Phase-1-(Copy)?node-id=1089%3A32281)
- [x] Related to JIRA ticket: gm-445 + gm-446
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.10-alpha.0d2566.0<br/>@codecademy/gamut-labs@28.0.5-alpha.0d2566.0<br/>@codecademy/gamut@40.1.2-alpha.0d2566.0<br/>@codecademy/monaco@0.5.8-alpha.0d2566.0<br/>@codecademy/styleguide@50.1.7-alpha.0d2566.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.10-alpha.586f56.0<br/>@codecademy/gamut-labs@28.0.5-alpha.586f56.0<br/>@codecademy/gamut@40.1.2-alpha.586f56.0<br/>@codecademy/monaco@0.5.8-alpha.586f56.0<br/>@codecademy/styleguide@50.1.7-alpha.586f56.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6185b23341845a0c28ca1f09--gamut-preview.netlify.app>https://6185b23341845a0c28ca1f09--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6185b23341845a0c28ca1f09>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.10-alpha.9cb1ed.0<br/>@codecademy/gamut-labs@28.0.5-alpha.9cb1ed.0<br/>@codecademy/gamut@40.1.2-alpha.9cb1ed.0<br/>@codecademy/monaco@0.5.8-alpha.9cb1ed.0<br/>@codecademy/styleguide@50.1.7-alpha.9cb1ed.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6185b3c9bada370c5b9b932f--gamut-preview.netlify.app>https://6185b3c9bada370c5b9b932f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6185b3c9bada370c5b9b932f>Deploy Logs</a></p>

**Review by CharlieBliss — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.11-alpha.cfba6b.0<br/>@codecademy/gamut-labs@28.0.6-alpha.cfba6b.0<br/>@codecademy/gamut@40.1.3-alpha.cfba6b.0<br/>@codecademy/monaco@0.5.9-alpha.cfba6b.0<br/>@codecademy/styleguide@50.1.8-alpha.cfba6b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://618982d31afe23370d4caea4--gamut-preview.netlify.app>https://618982d31afe23370d4caea4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/618982d31afe23370d4caea4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.11-alpha.4e59db.0<br/>@codecademy/gamut-labs@28.0.6-alpha.4e59db.0<br/>@codecademy/gamut@40.1.3-alpha.4e59db.0<br/>@codecademy/monaco@0.5.9-alpha.4e59db.0<br/>@codecademy/styleguide@50.1.8-alpha.4e59db.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6189909f03d1844a8ae67be0--gamut-preview.netlify.app>https://6189909f03d1844a8ae67be0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6189909f03d1844a8ae67be0>Deploy Logs</a></p>

**Review by thedoomshine — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.11-alpha.0b3d10.0<br/>@codecademy/gamut-labs@28.0.6-alpha.0b3d10.0<br/>@codecademy/gamut@40.1.3-alpha.0b3d10.0<br/>@codecademy/monaco@0.5.9-alpha.0b3d10.0<br/>@codecademy/styleguide@50.1.8-alpha.0b3d10.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61899b5814a45b53e303d92a--gamut-preview.netlify.app>https://61899b5814a45b53e303d92a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61899b5814a45b53e303d92a>Deploy Logs</a></p>

**Pull request merged**
