### PR TITLE
style(Colors): update color-editor-red

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

update $color-editor-red

as part of this [hackathon project](https://github.com/codecademy-engineering/Codecademy/pull/30492) to add line highlighting in markdown code blocks, we want to make $color-editor-red slightly lighter so that it maintains a 4.5:1 contrast ratio to the background of the highlighted lines

Screen Shot 2022-08-17 at 2 22 53 PM

so the new contrast ratio is [4.52:1](https://webaim.org/resources/contrastchecker/?fcolor=EA6C8B&bcolor=2B2D40)

got the 👌  from stephen on this!

an example code block with the new red text color and highlighted lines:
Screen Shot 2022-08-17 at 2 16 11 PM

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/30492)  | [Monolith Env](https://pr-30492-monolith.dev-eks.codecademy.com/) |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.2-alpha.53d723.0<br/>@codecademy/gamut-illustrations@0.29.1-alpha.53d723.0<br/>@codecademy/gamut-kit@0.6.180-alpha.53d723.0<br/>@codecademy/gamut-labs@33.1.1-alpha.53d723.0<br/>@codecademy/gamut-patterns@0.8.13-alpha.53d723.0<br/>@codecademy/gamut-styles@14.0.4-alpha.53d723.0<br/>@codecademy/gamut-tests@4.0.12-alpha.53d723.0<br/>@codecademy/gamut@50.3.1-alpha.53d723.0<br/>@codecademy/markdown-overrides@0.9.10-alpha.53d723.0<br/>@codecademy/monaco@0.6.73-alpha.53d723.0<br/>@codecademy/styleguide@61.1.10-alpha.53d723.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62fd339c49a3c0007d6d64b9--gamut-preview.netlify.app>https://62fd339c49a3c0007d6d64b9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62fd339c49a3c0007d6d64b9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.2-alpha.54e099.0<br/>@codecademy/gamut-illustrations@0.29.1-alpha.54e099.0<br/>@codecademy/gamut-kit@0.6.180-alpha.54e099.0<br/>@codecademy/gamut-labs@33.1.1-alpha.54e099.0<br/>@codecademy/gamut-patterns@0.8.13-alpha.54e099.0<br/>@codecademy/gamut-styles@14.0.4-alpha.54e099.0<br/>@codecademy/gamut-tests@4.0.12-alpha.54e099.0<br/>@codecademy/gamut@50.3.1-alpha.54e099.0<br/>@codecademy/markdown-overrides@0.9.10-alpha.54e099.0<br/>@codecademy/monaco@0.6.73-alpha.54e099.0<br/>@codecademy/styleguide@61.1.10-alpha.54e099.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62fd374c730e38041643632c--gamut-preview.netlify.app>https://62fd374c730e38041643632c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62fd374c730e38041643632c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.2-alpha.4d4830.0<br/>@codecademy/gamut-illustrations@0.29.1-alpha.4d4830.0<br/>@codecademy/gamut-kit@0.6.181-alpha.4d4830.0<br/>@codecademy/gamut-labs@33.1.2-alpha.4d4830.0<br/>@codecademy/gamut-patterns@0.8.13-alpha.4d4830.0<br/>@codecademy/gamut-styles@14.0.4-alpha.4d4830.0<br/>@codecademy/gamut-tests@4.0.12-alpha.4d4830.0<br/>@codecademy/gamut@50.3.1-alpha.4d4830.0<br/>@codecademy/markdown-overrides@0.9.10-alpha.4d4830.0<br/>@codecademy/monaco@0.6.73-alpha.4d4830.0<br/>@codecademy/styleguide@61.1.11-alpha.4d4830.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62fe5739366eca009b64538c--gamut-preview.netlify.app>https://62fe5739366eca009b64538c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62fe5739366eca009b64538c>Deploy Logs</a></p>

**Review by katiezutter — APPROVED** [review]

**Review by jakemhiller — APPROVED** [review]
👍

**Review by reedlaverack — APPROVED** [review]

**Pull request merged**
