### PR TITLE
feat(StopSignIcon): added StopSignIcon

### PR DESCRIPTION
**Pull request by AbdlRahmnn**
### Overview

Adds StopSignIcon to the icon library, Used in Payment Checkout Pop-Up blocker banner

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [IN-546]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Go to the Storybook icon preview (/docs/atoms-icons-regular--editable-icon)
2. Search for StopSignIcon

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |

[IN-546]: https://codecademy.atlassian.net/browse/IN-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.6-alpha.e73946.0<br/>@codecademy/gamut-icons@9.8.0-alpha.e73946.0<br/>@codecademy/gamut-kit@0.6.361-alpha.e73946.0<br/>@codecademy/styleguide@66.6.1-alpha.e73946.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://654934d755af6e2cfc4f489a--gamut-preview.netlify.app>https://654934d755af6e2cfc4f489a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/654934d755af6e2cfc4f489a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.9.2-alpha.a1073b.0<br/>@codecademy/gamut-icons@9.8.0-alpha.a1073b.0<br/>@codecademy/gamut-kit@0.6.363-alpha.a1073b.0<br/>@codecademy/styleguide@66.8.0-alpha.a1073b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6549a732ca4b0e334db74141--gamut-preview.netlify.app>https://6549a732ca4b0e334db74141--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6549a732ca4b0e334db74141>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
nice!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.9.2-alpha.09b464.0<br/>@codecademy/gamut-icons@9.8.0-alpha.09b464.0<br/>@codecademy/gamut-kit@0.6.363-alpha.09b464.0<br/>@codecademy/styleguide@66.7.3-alpha.09b464.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://654a5f0b14942a0f149e7498--gamut-preview.netlify.app>https://654a5f0b14942a0f149e7498--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/654a5f0b14942a0f149e7498>Deploy Logs</a></p>

**Pull request merged**
