### PR TITLE
feat(adminTheme): Update dark mode green in admin theme

### PR DESCRIPTION
**Pull request by melaniemohn**
### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [CONPLAT-2207](https://codecademy.atlassian.net/browse/CONPLAT-2207)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Author | [#2410](https://github.com/codecademy-engineering/author/pull/2410) | [PR env](https://author-2.pr.codecademy.com/)  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.1-alpha.a341c3.0<br/>@codecademy/gamut-illustrations@0.32.3-alpha.a341c3.0<br/>@codecademy/gamut-kit@0.6.220-alpha.a341c3.0<br/>@codecademy/gamut-labs@33.6.11-alpha.a341c3.0<br/>@codecademy/gamut-patterns@0.8.16-alpha.a341c3.0<br/>@codecademy/gamut-styles@14.1.2-alpha.a341c3.0<br/>@codecademy/gamut-tests@4.0.15-alpha.a341c3.0<br/>@codecademy/gamut@51.1.1-alpha.a341c3.0<br/>@codecademy/markdown-overrides@0.9.13-alpha.a341c3.0<br/>@codecademy/monaco@0.6.98-alpha.a341c3.0<br/>@codecademy/styleguide@62.0.5-alpha.a341c3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://635ae1359fd73509d8ce3449--gamut-preview.netlify.app>https://635ae1359fd73509d8ce3449--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/635ae1359fd73509d8ce3449>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.9.1-alpha.7039ca.0<br/>@codecademy/gamut-illustrations@0.32.3-alpha.7039ca.0<br/>@codecademy/gamut-kit@0.6.220-alpha.7039ca.0<br/>@codecademy/gamut-labs@33.6.11-alpha.7039ca.0<br/>@codecademy/gamut-patterns@0.8.16-alpha.7039ca.0<br/>@codecademy/gamut-styles@14.1.2-alpha.7039ca.0<br/>@codecademy/gamut-tests@4.0.15-alpha.7039ca.0<br/>@codecademy/gamut@51.1.1-alpha.7039ca.0<br/>@codecademy/markdown-overrides@0.9.13-alpha.7039ca.0<br/>@codecademy/monaco@0.6.98-alpha.7039ca.0<br/>@codecademy/styleguide@62.0.5-alpha.7039ca.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://635af1976f5c65005bb30db4--gamut-preview.netlify.app>https://635af1976f5c65005bb30db4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/635af1976f5c65005bb30db4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63612894d17e5d4192f58083--gamut-preview.netlify.app>https://63612894d17e5d4192f58083--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63612894d17e5d4192f58083>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
