### PR TITLE
feat: Storybook 8 Feature Branch

### PR DESCRIPTION
**Pull request by dreamwasp**
### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.ca64cb.0<br/>@codecademy/gamut@57.3.4-alpha.ca64cb.0<br/>@codecademy/gamut-icons@9.32.1-alpha.ca64cb.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.ca64cb.0<br/>@codecademy/gamut-kit@0.6.448-alpha.ca64cb.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.ca64cb.0<br/>@codecademy/gamut-styles@17.1.1-alpha.ca64cb.0<br/>@codecademy/gamut-tests@5.1.3-alpha.ca64cb.0<br/>@codecademy/macros@3.0.5-alpha.ca64cb.0<br/>@codecademy/variance@0.21.4-alpha.ca64cb.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.07f770.0<br/>@codecademy/gamut@57.3.4-alpha.07f770.0<br/>@codecademy/gamut-icons@9.32.1-alpha.07f770.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.07f770.0<br/>@codecademy/gamut-kit@0.6.448-alpha.07f770.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.07f770.0<br/>@codecademy/gamut-styles@17.1.1-alpha.07f770.0<br/>@codecademy/gamut-tests@5.1.3-alpha.07f770.0<br/>@codecademy/macros@3.0.5-alpha.07f770.0<br/>@codecademy/variance@0.21.4-alpha.07f770.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.4fe51b.0<br/>@codecademy/gamut@57.3.4-alpha.4fe51b.0<br/>@codecademy/gamut-icons@9.32.1-alpha.4fe51b.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.4fe51b.0<br/>@codecademy/gamut-kit@0.6.448-alpha.4fe51b.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.4fe51b.0<br/>@codecademy/gamut-styles@17.1.1-alpha.4fe51b.0<br/>@codecademy/gamut-tests@5.1.3-alpha.4fe51b.0<br/>@codecademy/macros@3.0.5-alpha.4fe51b.0<br/>@codecademy/variance@0.21.4-alpha.4fe51b.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.96b8fd.0<br/>@codecademy/gamut@57.4.2-alpha.96b8fd.0<br/>@codecademy/gamut-icons@9.32.1-alpha.96b8fd.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.96b8fd.0<br/>@codecademy/gamut-kit@0.6.450-alpha.96b8fd.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.96b8fd.0<br/>@codecademy/gamut-styles@17.1.1-alpha.96b8fd.0<br/>@codecademy/gamut-tests@5.1.3-alpha.96b8fd.0<br/>@codecademy/macros@3.0.5-alpha.96b8fd.0<br/>@codecademy/variance@0.21.4-alpha.96b8fd.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.41a529.0<br/>@codecademy/gamut@57.4.2-alpha.41a529.0<br/>@codecademy/gamut-icons@9.32.1-alpha.41a529.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.41a529.0<br/>@codecademy/gamut-kit@0.6.450-alpha.41a529.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.41a529.0<br/>@codecademy/gamut-styles@17.1.1-alpha.41a529.0<br/>@codecademy/gamut-tests@5.1.3-alpha.41a529.0<br/>@codecademy/macros@3.0.5-alpha.41a529.0<br/>@codecademy/variance@0.21.4-alpha.41a529.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.84e57e.0<br/>@codecademy/gamut@57.4.2-alpha.84e57e.0<br/>@codecademy/gamut-icons@9.32.1-alpha.84e57e.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.84e57e.0<br/>@codecademy/gamut-kit@0.6.450-alpha.84e57e.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.84e57e.0<br/>@codecademy/gamut-styles@17.1.1-alpha.84e57e.0<br/>@codecademy/gamut-tests@5.1.3-alpha.84e57e.0<br/>@codecademy/macros@3.0.5-alpha.84e57e.0<br/>@codecademy/variance@0.21.4-alpha.84e57e.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.c19dff.0<br/>@codecademy/gamut@57.4.2-alpha.c19dff.0<br/>@codecademy/gamut-icons@9.32.1-alpha.c19dff.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.c19dff.0<br/>@codecademy/gamut-kit@0.6.450-alpha.c19dff.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.c19dff.0<br/>@codecademy/gamut-styles@17.1.1-alpha.c19dff.0<br/>@codecademy/gamut-tests@5.1.3-alpha.c19dff.0<br/>@codecademy/macros@3.0.5-alpha.c19dff.0<br/>@codecademy/variance@0.21.4-alpha.c19dff.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.b3a29a.0<br/>@codecademy/gamut@57.4.2-alpha.b3a29a.0<br/>@codecademy/gamut-icons@9.32.1-alpha.b3a29a.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.b3a29a.0<br/>@codecademy/gamut-kit@0.6.450-alpha.b3a29a.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.b3a29a.0<br/>@codecademy/gamut-styles@17.1.1-alpha.b3a29a.0<br/>@codecademy/gamut-tests@5.1.3-alpha.b3a29a.0<br/>@codecademy/macros@3.0.5-alpha.b3a29a.0<br/>@codecademy/variance@0.21.4-alpha.b3a29a.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.bc8c54.0<br/>@codecademy/gamut@57.4.2-alpha.bc8c54.0<br/>@codecademy/gamut-icons@9.32.1-alpha.bc8c54.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.bc8c54.0<br/>@codecademy/gamut-kit@0.6.450-alpha.bc8c54.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.bc8c54.0<br/>@codecademy/gamut-styles@17.1.1-alpha.bc8c54.0<br/>@codecademy/gamut-tests@5.1.3-alpha.bc8c54.0<br/>@codecademy/macros@3.0.5-alpha.bc8c54.0<br/>@codecademy/variance@0.21.4-alpha.bc8c54.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.0483fd.0<br/>@codecademy/gamut@57.4.2-alpha.0483fd.0<br/>@codecademy/gamut-icons@9.32.1-alpha.0483fd.0<br/>@codecademy/gamut-illustrations@0.48.2-alpha.0483fd.0<br/>@codecademy/gamut-kit@0.6.450-alpha.0483fd.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.0483fd.0<br/>@codecademy/gamut-styles@17.1.1-alpha.0483fd.0<br/>@codecademy/gamut-tests@5.1.3-alpha.0483fd.0<br/>@codecademy/macros@3.0.5-alpha.0483fd.0<br/>@codecademy/variance@0.21.4-alpha.0483fd.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.17a12a.0<br/>@codecademy/gamut@57.4.4-alpha.17a12a.0<br/>@codecademy/gamut-icons@9.32.1-alpha.17a12a.0<br/>@codecademy/gamut-illustrations@0.49.1-alpha.17a12a.0<br/>@codecademy/gamut-kit@0.6.452-alpha.17a12a.0<br/>@codecademy/gamut-patterns@0.9.16-alpha.17a12a.0<br/>@codecademy/gamut-styles@17.1.1-alpha.17a12a.0<br/>@codecademy/gamut-tests@5.1.3-alpha.17a12a.0<br/>@codecademy/macros@3.0.5-alpha.17a12a.0<br/>@codecademy/variance@0.21.4-alpha.17a12a.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.f7ecde.0<br/>@codecademy/gamut@57.4.5-alpha.f7ecde.0<br/>@codecademy/gamut-icons@9.32.2-alpha.f7ecde.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.f7ecde.0<br/>@codecademy/gamut-kit@0.6.453-alpha.f7ecde.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.f7ecde.0<br/>@codecademy/gamut-styles@17.1.2-alpha.f7ecde.0<br/>@codecademy/gamut-tests@5.1.4-alpha.f7ecde.0<br/>@codecademy/macros@3.0.5-alpha.f7ecde.0<br/>@codecademy/variance@0.21.5-alpha.f7ecde.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.e17690.0<br/>@codecademy/gamut@57.4.5-alpha.e17690.0<br/>@codecademy/gamut-icons@9.32.2-alpha.e17690.0<br/>@codecademy/gamut-illustrations@0.49.2-alpha.e17690.0<br/>@codecademy/gamut-kit@0.6.453-alpha.e17690.0<br/>@codecademy/gamut-patterns@0.9.17-alpha.e17690.0<br/>@codecademy/gamut-styles@17.1.2-alpha.e17690.0<br/>@codecademy/gamut-tests@5.1.4-alpha.e17690.0<br/>@codecademy/macros@3.0.5-alpha.e17690.0<br/>@codecademy/variance@0.21.5-alpha.e17690.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.c3121d.0<br/>@codecademy/gamut@57.5.3-alpha.c3121d.0<br/>@codecademy/gamut-icons@9.34.2-alpha.c3121d.0<br/>@codecademy/gamut-illustrations@0.49.3-alpha.c3121d.0<br/>@codecademy/gamut-kit@0.6.456-alpha.c3121d.0<br/>@codecademy/gamut-patterns@0.9.18-alpha.c3121d.0<br/>@codecademy/gamut-styles@17.1.3-alpha.c3121d.0<br/>@codecademy/gamut-tests@5.1.5-alpha.c3121d.0<br/>@codecademy/macros@3.0.5-alpha.c3121d.0<br/>@codecademy/variance@0.21.5-alpha.c3121d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://67576944be27292aa883b195--gamut-preview.netlify.app>https://67576944be27292aa883b195--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/67576944be27292aa883b195>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.3e3f48.0<br/>@codecademy/gamut@57.5.3-alpha.3e3f48.0<br/>@codecademy/gamut-icons@9.34.2-alpha.3e3f48.0<br/>@codecademy/gamut-illustrations@0.49.3-alpha.3e3f48.0<br/>@codecademy/gamut-kit@0.6.456-alpha.3e3f48.0<br/>@codecademy/gamut-patterns@0.9.18-alpha.3e3f48.0<br/>@codecademy/gamut-styles@17.1.3-alpha.3e3f48.0<br/>@codecademy/gamut-tests@5.1.5-alpha.3e3f48.0<br/>@codecademy/macros@3.0.5-alpha.3e3f48.0<br/>@codecademy/styleguide@68.1.4-alpha.3e3f48.0<br/>@codecademy/variance@0.21.5-alpha.3e3f48.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6759bc93f0100a0a33237df9--gamut-preview.netlify.app>https://6759bc93f0100a0a33237df9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6759bc93f0100a0a33237df9>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.44e7b7.0<br/>@codecademy/gamut@57.5.3-alpha.44e7b7.0<br/>@codecademy/gamut-icons@9.34.2-alpha.44e7b7.0<br/>@codecademy/gamut-illustrations@0.49.3-alpha.44e7b7.0<br/>@codecademy/gamut-kit@0.6.456-alpha.44e7b7.0<br/>@codecademy/gamut-patterns@0.9.18-alpha.44e7b7.0<br/>@codecademy/gamut-styles@17.1.3-alpha.44e7b7.0<br/>@codecademy/gamut-tests@5.1.5-alpha.44e7b7.0<br/>@codecademy/macros@3.0.5-alpha.44e7b7.0<br/>@codecademy/styleguide@68.1.4-alpha.44e7b7.0<br/>@codecademy/variance@0.21.5-alpha.44e7b7.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
everything looks good to me!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>eslint-plugin-gamut@2.2.1-alpha.db3d4f.0<br/>@codecademy/gamut@57.5.3-alpha.db3d4f.0<br/>@codecademy/gamut-icons@9.34.2-alpha.db3d4f.0<br/>@codecademy/gamut-illustrations@0.49.3-alpha.db3d4f.0<br/>@codecademy/gamut-kit@0.6.456-alpha.db3d4f.0<br/>@codecademy/gamut-patterns@0.9.18-alpha.db3d4f.0<br/>@codecademy/gamut-styles@17.1.3-alpha.db3d4f.0<br/>@codecademy/gamut-tests@5.1.5-alpha.db3d4f.0<br/>@codecademy/macros@3.0.5-alpha.db3d4f.0<br/>@codecademy/styleguide@68.1.4-alpha.db3d4f.0<br/>@codecademy/variance@0.21.5-alpha.db3d4f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://675c47d628119a0a787714ef--gamut-preview.netlify.app>https://675c47d628119a0a787714ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/675c47d628119a0a787714ef>Deploy Logs</a></p>

**Pull request merged**
