### PR TITLE
docs(FormGroup): Use correct required prop in FormGroup storybook examples

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Updates the `FormGroup` examples to accurately mark form inputs as required to match their label

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [GM-850]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Visit the storybook preview
2. Under FormGroup states see that the inputs are marked as required with an asterisks (which matches the label text)

[GM-850]: https://skillsoftdev.atlassian.net/browse/GM-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@67.2.2-alpha.9c4c54.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66c6594bd7e7ad899a719e70--gamut-preview.netlify.app>https://66c6594bd7e7ad899a719e70--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66c6594bd7e7ad899a719e70>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
ltgm! the yarn verify check that' failing can be fixed by running `yarn format --fix` and committing the result (prettier doesn't always play nice with mdx 🤷 )

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@67.2.2-alpha.9e3d65.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66c74280616fe42ff23c84dd--gamut-preview.netlify.app>https://66c74280616fe42ff23c84dd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66c74280616fe42ff23c84dd>Deploy Logs</a></p>

**Pull request merged**
