### PR TITLE
feat(AppHeaderLogo): Show minified CC logo at specific breakpoint

### PR DESCRIPTION
**Pull request by bndiep**
### PR Checklist

- [x] Related to designs: https://www.figma.com/file/5rkfS3uWZsFNTsx2GmlDYA/Save-Feature-MVP?node-id=462%3A31401
- [x] Related to JIRA ticket: REACH-1941
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.49dda6.0<br/>@codecademy/gamut-labs@33.0.6-alpha.49dda6.0<br/>@codecademy/styleguide@60.1.2-alpha.49dda6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e936bce7f6bd1183a9e2ab--gamut-preview.netlify.app>https://62e936bce7f6bd1183a9e2ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e936bce7f6bd1183a9e2ab>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.ba42b1.0<br/>@codecademy/gamut-labs@33.0.6-alpha.ba42b1.0<br/>@codecademy/styleguide@60.1.2-alpha.ba42b1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e9593cfb438333854df465--gamut-preview.netlify.app>https://62e9593cfb438333854df465--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e9593cfb438333854df465>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.d08589.0<br/>@codecademy/gamut-labs@33.0.6-alpha.d08589.0<br/>@codecademy/styleguide@60.1.2-alpha.d08589.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e95b6d71b2d22ee9d82add--gamut-preview.netlify.app>https://62e95b6d71b2d22ee9d82add--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e95b6d71b2d22ee9d82add>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.00ff6d.0<br/>@codecademy/gamut-labs@33.0.6-alpha.00ff6d.0<br/>@codecademy/styleguide@60.1.2-alpha.00ff6d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e95f60945d133941e1d758--gamut-preview.netlify.app>https://62e95f60945d133941e1d758--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e95f60945d133941e1d758>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.791f91.0<br/>@codecademy/gamut-labs@33.0.6-alpha.791f91.0<br/>@codecademy/styleguide@60.1.2-alpha.791f91.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.d0944b.0<br/>@codecademy/gamut-labs@33.0.6-alpha.d0944b.0<br/>@codecademy/styleguide@60.1.2-alpha.d0944b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e9a9d5cfcf26197a29e572--gamut-preview.netlify.app>https://62e9a9d5cfcf26197a29e572--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e9a9d5cfcf26197a29e572>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.170-alpha.9da3f0.0<br/>@codecademy/gamut-labs@33.0.6-alpha.9da3f0.0<br/>@codecademy/styleguide@60.1.2-alpha.9da3f0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62e9afd7cfcf261d4829e499--gamut-preview.netlify.app>https://62e9afd7cfcf261d4829e499--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62e9afd7cfcf261d4829e499>Deploy Logs</a></p>

**Comment by bndiep** [comment]
I'll be closing this draft since this work got folded in elsewhere: https://github.com/Codecademy/gamut/pull/2486

**Pull request closed without merging**
