### PR TITLE
refactor(header): add new flag to videos in header resources

### PR DESCRIPTION
**Pull request by bndiep**
### Overview

Add 'New' badge to videos in the header resources list.

 Related to the gamut feature to add the 'New' label: https://github.com/Codecademy/gamut/pull/2181

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/YKo1KmtLMm2iZjfV4dcBsX/Video-Library-MVP-v1?node-id=239%3A15937
- [x] Related to JIRA ticket: [Reach-1423](https://codecademy.atlassian.net/browse/REACH-1261)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Review by njradford — APPROVED** [review]
Changes make sense to me!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.33-alpha.1536a1.0<br/>@codecademy/gamut-labs@28.4.2-alpha.1536a1.0<br/>@codecademy/styleguide@52.2.2-alpha.1536a1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b8e21353778f0b2f2a1fd3--gamut-preview.netlify.app>https://61b8e21353778f0b2f2a1fd3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b8e21353778f0b2f2a1fd3>Deploy Logs</a></p>

**Review by awgraves — APPROVED** [review]

**Review by dreamwasp — APPROVED** [review]
nice!!

**Pull request merged**
