### PR TITLE
fix(TabButton): fixes focus outline on tabs

### PR DESCRIPTION
**Pull request by bndiep**
### Overview

Fixes focus outline that was missing from Tabs when using keyboard navigation

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-2521](https://codecademy.atlassian.net/browse/REACH-2521)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

https://user-images.githubusercontent.com/29311886/224438891-c851cc6f-26e7-43ab-9888-4b549437cde2.mov

1. Visit https://640bb0101c16eb0c81e322e1--gamut-preview.netlify.app/?path=/docs/molecules-tabs--tabs
2. Using `tab` key, navigate to the Tabs example.
3. Using the arrow keys to navigate between tabs. Confirm that the focus outline appears around the tabs.
4. Enter the `tab` key. Confirm that the tab panel has the focus outline.

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith       | [Monolith Link](https://github.com/codecademy-engineering/Codecademy/pull/34966)  | [Monolith Env]()   |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1447)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1447)   |

[REACH-2521]: https://codecademy.atlassian.net/browse/REACH-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://640a6365649aad0314229089--gamut-preview.netlify.app>https://640a6365649aad0314229089--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/640a6365649aad0314229089>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://640a710d143ac8065d6674ca--gamut-preview.netlify.app>https://640a710d143ac8065d6674ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/640a710d143ac8065d6674ca>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.291-alpha.812276.0<br/>@codecademy/gamut-labs@35.7.1-alpha.812276.0<br/>@codecademy/gamut@52.1.1-alpha.812276.0<br/>@codecademy/monaco@0.7.10-alpha.812276.0<br/>@codecademy/styleguide@63.6.1-alpha.812276.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.291-alpha.ee2c5f.0<br/>@codecademy/gamut-labs@35.7.1-alpha.ee2c5f.0<br/>@codecademy/gamut@52.1.1-alpha.ee2c5f.0<br/>@codecademy/monaco@0.7.10-alpha.ee2c5f.0<br/>@codecademy/styleguide@63.6.1-alpha.ee2c5f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://640bb0101c16eb0c81e322e1--gamut-preview.netlify.app>https://640bb0101c16eb0c81e322e1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/640bb0101c16eb0c81e322e1>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
picture perfect, nice work!

**Pull request merged**
