### PR TITLE
feat(GlobalHeader): add newSkuSubscription prop to show regular logo …

### PR DESCRIPTION
**Pull request by natalieweesh**
…for pro silver users

### Overview

add newSkuSubscription prop to GlobalHeader to show regular logo for pro-silver and pro-gold users

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: EGG-2390
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Review by dreamwasp — COMMENTED** [review]
maybe this should be nested under `user` ?

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.132-alpha.d5e48c.0<br/>@codecademy/gamut-labs@31.15.0-alpha.d5e48c.0<br/>@codecademy/styleguide@57.7.0-alpha.d5e48c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://628e6aabb2a618186f12b5da--gamut-preview.netlify.app>https://628e6aabb2a618186f12b5da--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/628e6aabb2a618186f12b5da>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.132-alpha.419be7.0<br/>@codecademy/gamut-labs@31.15.0-alpha.419be7.0<br/>@codecademy/styleguide@57.7.0-alpha.419be7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://628e711d91f3251eb397b152--gamut-preview.netlify.app>https://628e711d91f3251eb397b152--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/628e711d91f3251eb397b152>Deploy Logs</a></p>

**Review by dreamwasp — COMMENTED** [review]
this looks great! would you mind also adding the alpha to a portal PR? wanna make sure this is playing nicely with everything. 

it also looks like this is causing a compile error on the monolith branch its been added to - once those problems are resolved i'll  ✅

**Comment by natalieweesh** [comment]
@dreamwasp here's the alpha added to a portal-app pr: https://github.com/codecademy-engineering/portal-app/pull/2035
and for the [monolith pr](https://github.com/codecademy-engineering/Codecademy/pull/30887), it's still showing the compile error on circleCI but it is compiling fine locally so not sure if there's something off with circleCI?
Screen Shot 2022-05-31 at 12 04 11 PM

**Comment by dreamwasp** [comment]
> @dreamwasp here's the alpha added to a portal-app pr: [codecademy-engineering/portal-app#2035](https://github.com/codecademy-engineering/portal-app/pull/2035) and for the [monolith pr](https://github.com/codecademy-engineering/Codecademy/pull/30887), it's still showing the compile error on circleCI but it is compiling fine locally so not sure if there's something off with circleCI? Screen Shot 2022-05-31 at 12 04 11 PM

seems weird - i would try updating both the gamut + monolith branch to develop, may be an older breaking change in there!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6297a70752f0ba009b03ee76--gamut-preview.netlify.app>https://6297a70752f0ba009b03ee76--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6297a70752f0ba009b03ee76>Deploy Logs</a></p>

**Pull request merged**
