### PR TITLE
feat(CubeIcon): add cube icon

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

add CubeIcon

Screen Shot 2022-08-03 at 5 58 30 PM

for this pr: https://github.com/codecademy-engineering/Codecademy/pull/31883

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31913)  | [Monolith Env](https://pr-31913-monolith.dev-eks.codecademy.com/) |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.0-alpha.c5c1d9.0<br/>@codecademy/gamut-kit@0.6.171-alpha.c5c1d9.0<br/>@codecademy/gamut-labs@33.0.7-alpha.c5c1d9.0<br/>@codecademy/gamut@50.0.1-alpha.c5c1d9.0<br/>@codecademy/monaco@0.6.66-alpha.c5c1d9.0<br/>@codecademy/styleguide@61.0.1-alpha.c5c1d9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62eaf17196ddd0005b823915--gamut-preview.netlify.app>https://62eaf17196ddd0005b823915--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62eaf17196ddd0005b823915>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.6.0-alpha.2facf3.0<br/>@codecademy/gamut-kit@0.6.171-alpha.2facf3.0<br/>@codecademy/gamut-labs@33.0.7-alpha.2facf3.0<br/>@codecademy/gamut@50.0.1-alpha.2facf3.0<br/>@codecademy/monaco@0.6.66-alpha.2facf3.0<br/>@codecademy/styleguide@61.0.1-alpha.2facf3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62eaf701c81b9201d1aaa1d8--gamut-preview.netlify.app>https://62eaf701c81b9201d1aaa1d8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62eaf701c81b9201d1aaa1d8>Deploy Logs</a></p>

**Review by BandanaKM — APPROVED** [review]
🧊 nifty!

**Pull request merged**
