### PR TITLE
feat(Icons): add ProfessionalCertificateIcon

### PR DESCRIPTION
**Pull request by bndiep**
### Overview

Add ProfessionalCertificateIcon under LE section to be used on container landing pages

### PR Checklist

- [x] Related to designs: [Figma node](https://figma.com/design/TQ3lr66cVWpcOAYRxApWZV/Ready-for-dev---Product-Feature-Marketing?node-id=62-13083&m=dev)
- [x] Related to JIRA ticket: [DOT-309](https://codecademy.atlassian.net/browse/DOT-309)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6561)  | [Portal Env](https://tengu.codecademy.com/learn/paths/machine-learning-engineer?PR_ENV=portal-app-pr-6561)   |

[DOT-309]: https://codecademy.atlassian.net/browse/DOT-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.3-alpha.4b3db7.0<br/>@codecademy/gamut-icons@9.26.1-alpha.4b3db7.0<br/>@codecademy/gamut-kit@0.6.412-alpha.4b3db7.0<br/>@codecademy/styleguide@66.22.1-alpha.4b3db7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://666327690e25e01103c815e7--gamut-preview.netlify.app>https://666327690e25e01103c815e7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/666327690e25e01103c815e7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.1-alpha.531565.0<br/>@codecademy/gamut-icons@9.26.1-alpha.531565.0<br/>@codecademy/gamut-kit@0.6.413-alpha.531565.0<br/>@codecademy/styleguide@66.23.1-alpha.531565.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66636c8082cd6c29f5c4ebb7--gamut-preview.netlify.app>https://66636c8082cd6c29f5c4ebb7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66636c8082cd6c29f5c4ebb7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.2-alpha.82c873.0<br/>@codecademy/gamut-icons@9.27.1-alpha.82c873.0<br/>@codecademy/gamut-kit@0.6.414-alpha.82c873.0<br/>@codecademy/styleguide@66.24.1-alpha.82c873.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://666741ecce0da22273fe589f--gamut-preview.netlify.app>https://666741ecce0da22273fe589f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/666741ecce0da22273fe589f>Deploy Logs</a></p>

**Review by LinKCoding — APPROVED** [review]
LGTM! 

checked on both light and dark mode and it looks good :)

**Pull request merged**
