### PR TITLE
feat(GridForm): re-read errors on submit

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview
✨UPDATE✨

Clears previous error state onError and manually triggers validation so that the proper form errors are read by VO every time the Submit button is pressed. 

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: web-1809
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/30716)  | [Monolith Env](https://pr-30716-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/1952)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1952)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.133-alpha.81d8e3.0<br/>@codecademy/gamut-labs@31.15.1-alpha.81d8e3.0<br/>@codecademy/gamut@47.3.4-alpha.81d8e3.0<br/>@codecademy/monaco@0.6.47-alpha.81d8e3.0<br/>@codecademy/styleguide@57.7.1-alpha.81d8e3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6298f8475fd65e02fe239ddf--gamut-preview.netlify.app>https://6298f8475fd65e02fe239ddf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6298f8475fd65e02fe239ddf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6299040dee74cd08c16fbeaf--gamut-preview.netlify.app>https://6299040dee74cd08c16fbeaf--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6299040dee74cd08c16fbeaf>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.133-alpha.807984.0<br/>@codecademy/gamut-labs@31.15.1-alpha.807984.0<br/>@codecademy/gamut@47.3.4-alpha.807984.0<br/>@codecademy/monaco@0.6.47-alpha.807984.0<br/>@codecademy/styleguide@57.7.1-alpha.807984.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.135-alpha.89278e.0<br/>@codecademy/gamut-labs@31.15.3-alpha.89278e.0<br/>@codecademy/gamut@47.3.4-alpha.89278e.0<br/>@codecademy/monaco@0.6.47-alpha.89278e.0<br/>@codecademy/styleguide@57.7.3-alpha.89278e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629e1c797ea5354c9a69c87f--gamut-preview.netlify.app>https://629e1c797ea5354c9a69c87f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629e1c797ea5354c9a69c87f>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
Confirmed this works as expected on the corresponding monolith and portal app PRs!

Is this something we could add a unit test for?

**Review by thedoomshine — APPROVED** [review]

**Comment by dreamwasp** [comment]
> Confirmed this works as expected on the corresponding monolith and portal app PRs!
> 
> Is this something we could add a unit test for?

i've spent some time tryna figure out a way to mock clearErrors(), will spend some more time trying to figure it out!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.135-alpha.9ed211.0<br/>@codecademy/gamut-labs@31.15.3-alpha.9ed211.0<br/>@codecademy/gamut@47.3.4-alpha.9ed211.0<br/>@codecademy/monaco@0.6.47-alpha.9ed211.0<br/>@codecademy/styleguide@57.7.3-alpha.9ed211.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629e85fe43e3160c170a2192--gamut-preview.netlify.app>https://629e85fe43e3160c170a2192--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629e85fe43e3160c170a2192>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.136-alpha.0b011b.0<br/>@codecademy/gamut-labs@31.15.4-alpha.0b011b.0<br/>@codecademy/gamut@47.3.5-alpha.0b011b.0<br/>@codecademy/monaco@0.6.48-alpha.0b011b.0<br/>@codecademy/styleguide@57.7.4-alpha.0b011b.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629ecdc6158e1319a5f79ba8--gamut-preview.netlify.app>https://629ecdc6158e1319a5f79ba8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629ecdc6158e1319a5f79ba8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.136-alpha.b53e84.0<br/>@codecademy/gamut-labs@31.15.4-alpha.b53e84.0<br/>@codecademy/gamut@47.3.5-alpha.b53e84.0<br/>@codecademy/monaco@0.6.48-alpha.b53e84.0<br/>@codecademy/styleguide@57.7.4-alpha.b53e84.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://629ecf79524b221aa2ed7f24--gamut-preview.netlify.app>https://629ecf79524b221aa2ed7f24--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/629ecf79524b221aa2ed7f24>Deploy Logs</a></p>

**Pull request merged**
