### PR TITLE
feat(ProgressBar)!: add border to yellow variant and use color mode

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Adds a border to yellow variant for accessibility color contrast and consolidates light and dark variants into one default variant using color mode.

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=18448-19639&t=18akf6WOs6uZmL4B-0
- [x] Related to JIRA ticket: [WEB-2310]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

View https://6452b42fd441bc14765a4d3a--gamut-preview.netlify.app/?path=/docs/atoms-progressbar--progress-bar and confirm all progress bars have an outline

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35568)  | [Monolith Env](https://pr-35568-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1868)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

[WEB-2310]: https://codecademy.atlassian.net/browse/WEB-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://645133f264b4cb0ad6e348d1--gamut-preview.netlify.app>https://645133f264b4cb0ad6e348d1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/645133f264b4cb0ad6e348d1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.311-alpha.14b5e6.0<br/>@codecademy/gamut-labs@35.13.2-alpha.14b5e6.0<br/>@codecademy/gamut@53.1.3-alpha.14b5e6.0<br/>@codecademy/monaco@0.7.21-alpha.14b5e6.0<br/>@codecademy/styleguide@64.3.4-alpha.14b5e6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64516cf10b285e0c00ec7afa--gamut-preview.netlify.app>https://64516cf10b285e0c00ec7afa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64516cf10b285e0c00ec7afa>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.311-alpha.05b232.0<br/>@codecademy/gamut-labs@35.13.2-alpha.05b232.0<br/>@codecademy/gamut@53.1.3-alpha.05b232.0<br/>@codecademy/monaco@0.7.21-alpha.05b232.0<br/>@codecademy/styleguide@64.3.4-alpha.05b232.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6452b42fd441bc14765a4d3a--gamut-preview.netlify.app>https://6452b42fd441bc14765a4d3a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6452b42fd441bc14765a4d3a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.314-alpha.2eb2e0.0<br/>@codecademy/gamut-labs@35.14.3-alpha.2eb2e0.0<br/>@codecademy/gamut@53.2.1-alpha.2eb2e0.0<br/>@codecademy/monaco@0.7.22-alpha.2eb2e0.0<br/>@codecademy/styleguide@64.3.7-alpha.2eb2e0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://645aa11aa65b9f2cdeae1a3b--gamut-preview.netlify.app>https://645aa11aa65b9f2cdeae1a3b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/645aa11aa65b9f2cdeae1a3b>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🔥  lgtm!!!!

**Pull request merged**
