### PR TITLE
fix: HorizontalScrollMenu - Add tabIndex to scrollable element

### PR DESCRIPTION
**Pull request by j10sanders**
### Overview

We were getting periodic axe failures in portal app e2e tests - https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/
 This fixes that!

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: DISC-637
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/1986)

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.128-alpha.d763dd.0<br/>@codecademy/gamut-labs@31.12.3-alpha.d763dd.0<br/>@codecademy/styleguide@57.4.2-alpha.d763dd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62854b554c63b92bda615bd7--gamut-preview.netlify.app>https://62854b554c63b92bda615bd7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62854b554c63b92bda615bd7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.128-alpha.42d462.0<br/>@codecademy/gamut-labs@31.12.3-alpha.42d462.0<br/>@codecademy/styleguide@57.4.2-alpha.42d462.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6285517ae8cccb31ce338e8d--gamut-preview.netlify.app>https://6285517ae8cccb31ce338e8d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6285517ae8cccb31ce338e8d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62855a8de1db0d3a6804cabd--gamut-preview.netlify.app>https://62855a8de1db0d3a6804cabd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62855a8de1db0d3a6804cabd>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.128-alpha.5f9962.0<br/>@codecademy/gamut-labs@31.12.3-alpha.5f9962.0<br/>@codecademy/styleguide@57.4.2-alpha.5f9962.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://628576a75b44ae11e2c2e84b--gamut-preview.netlify.app>https://628576a75b44ae11e2c2e84b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/628576a75b44ae11e2c2e84b>Deploy Logs</a></p>

**Review by borisonr — APPROVED** [review]
still confused why this is flaky and not just always failing (is it actually the banner that was causing it??)... but this seems to definitely help!

**Comment by j10sanders** [comment]
> still confused why this is flaky and not just always failing (is it actually the banner that was causing it??)... but this seems to definitely help!

I wasn't able to reproduce now that the banner isn't displayed, but I was able to get the same error repeatedly with iphoneSE in cypress 🤷

**Comment by borisonr** [comment]
we can set up a staging banner in contentful... just to be super sure?

**Comment by j10sanders** [comment]
Can I get a quick review @jakemhiller or @reedlaverack ?  Thanks!

**Review by jakemhiller — APPROVED** [review]
lgtm

**Pull request merged**
