### PR TITLE
feat(Illustration): Add OfficeAnnouncement Illustration

### PR DESCRIPTION
**Pull request by katiezutter**
### Overview

Adds the OfficeAnnouncement illustration.

Screenshot 2024-04-12 at 5 06 42 PM

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/7Oe7eNRzW9J0KbShrfbiPy/Events?type=design&node-id=2288-19913&mode=design&t=B3O8IQiHEQUlS87t-4
- [x] Related to JIRA ticket: [LEGO-3797](https://codecademy.atlassian.net/browse/LEGO-3797)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Check the new illustration in the Storybook preview: https://6619bc47a254bc105779210a--gamut-preview.netlify.app/?path=/docs/atoms-illustrations--editable-illustration

Check the new illustration in the portal-app preview environment: https://tengu.codecademy.com/learn?page=communityEvents

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/5773)  | [Portal Env](https://tengu.codecademy.com/learn?PR_ENV=portal-app-pr-5773)   |

[LEGO-3797]: https://codecademy.atlassian.net/browse/LEGO-3797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.1-alpha.ef97f5.0<br/>@codecademy/gamut-illustrations@0.42.1-alpha.ef97f5.0<br/>@codecademy/gamut-kit@0.6.398-alpha.ef97f5.0<br/>@codecademy/styleguide@66.17.2-alpha.ef97f5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6619bc47a254bc105779210a--gamut-preview.netlify.app>https://6619bc47a254bc105779210a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6619bc47a254bc105779210a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.17.1-alpha.7b8445.0<br/>@codecademy/gamut-illustrations@0.42.1-alpha.7b8445.0<br/>@codecademy/gamut-kit@0.6.398-alpha.7b8445.0<br/>@codecademy/styleguide@66.17.2-alpha.7b8445.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661d5c0cd872f70652e85cbb--gamut-preview.netlify.app>https://661d5c0cd872f70652e85cbb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661d5c0cd872f70652e85cbb>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]

**Pull request merged**
