### PR TITLE
fix(AppHeader): clean up search bar from experiment

### PR DESCRIPTION
**Pull request by borisonr**
### Overview

We ran an experiment to default the search bar to open on the catalog page after new users went through onboarding flow. We decided to go with the variant where the search bar is not defaulted to open so we can clean up this logic in the header.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [DISC-425](https://codecademy.atlassian.net/browse/DISC-425)
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.88-alpha.db87bb.0<br/>@codecademy/gamut-labs@30.6.2-alpha.db87bb.0<br/>@codecademy/styleguide@55.4.3-alpha.db87bb.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]
thanks for the clean up!

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623dd280f629a1068f1deef8--gamut-preview.netlify.app>https://623dd280f629a1068f1deef8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623dd280f629a1068f1deef8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6241bb96e214c11d2f6f936e--gamut-preview.netlify.app>https://6241bb96e214c11d2f6f936e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6241bb96e214c11d2f6f936e>Deploy Logs</a></p>

**Pull request merged**
