### PR TITLE
feat(SkillPathCard): New skill path card

### PR DESCRIPTION
**Pull request by zippyzow**
### Overview

This PR adds the existing [SkillPathCard](https://github.com/codecademy-engineering/mono/blob/develop/apps/portal-app/src/components/CatalogPage/SkillPathCard.tsx) component into gamut-labs. 

Related gamut PRs for context 
https://github.com/Codecademy/gamut/pull/2653
https://github.com/Codecademy/gamut/pull/2656

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/q0bRIpoO92YfCpy4nCiQGI/What's-your-goal---iteration?node-id=702%3A3308&t=GjAsG8u5UGR3D1jO-0
- [x] Related to JIRA ticket: [DISC-1042]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Open the latest Styleguide deploy preview below and search for SkillPathCard
2. Review this page and make sure everything is captured for this new skill path card 
3. Open the monorepo PR env link and see that the skill path cards on catalog, hubs, and full catalog page look the same as production. 

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34458) 
| Monorepo       | [Portal PR](https://github.com/codecademy-engineering/mono/pull/1136)  | [Monorepo Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1136)   

[DISC-1042]: https://codecademy.atlassian.net/browse/DISC-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.45d5f6.0<br/>@codecademy/gamut-labs@35.2.1-alpha.45d5f6.0<br/>@codecademy/styleguide@63.1.1-alpha.45d5f6.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.4aff3d.0<br/>@codecademy/gamut-labs@35.2.1-alpha.4aff3d.0<br/>@codecademy/styleguide@63.1.1-alpha.4aff3d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63d848127b984105d0033a65--gamut-preview.netlify.app>https://63d848127b984105d0033a65--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63d848127b984105d0033a65>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.ccfc89.0<br/>@codecademy/gamut-labs@35.2.1-alpha.ccfc89.0<br/>@codecademy/styleguide@63.1.1-alpha.ccfc89.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63d8552ce5dcdb004efb7c59--gamut-preview.netlify.app>https://63d8552ce5dcdb004efb7c59--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63d8552ce5dcdb004efb7c59>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.84900e.0<br/>@codecademy/gamut-labs@35.2.1-alpha.84900e.0<br/>@codecademy/styleguide@63.1.1-alpha.84900e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63d94d8be7b883009e957e8c--gamut-preview.netlify.app>https://63d94d8be7b883009e957e8c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63d94d8be7b883009e957e8c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.5c5c76.0<br/>@codecademy/gamut-labs@35.2.1-alpha.5c5c76.0<br/>@codecademy/styleguide@63.1.1-alpha.5c5c76.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63d969260fe8651d7f167317--gamut-preview.netlify.app>https://63d969260fe8651d7f167317--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63d969260fe8651d7f167317>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.bd1c56.0<br/>@codecademy/gamut-labs@35.2.1-alpha.bd1c56.0<br/>@codecademy/styleguide@63.1.1-alpha.bd1c56.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63d96d663476f2209f42f976--gamut-preview.netlify.app>https://63d96d663476f2209f42f976--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63d96d663476f2209f42f976>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.271-alpha.5073ea.0<br/>@codecademy/gamut-labs@35.2.1-alpha.5073ea.0<br/>@codecademy/styleguide@63.1.1-alpha.5073ea.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63d98911a1c21d005edfed05--gamut-preview.netlify.app>https://63d98911a1c21d005edfed05--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63d98911a1c21d005edfed05>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.273-alpha.7fa2e3.0<br/>@codecademy/gamut-labs@35.3.2-alpha.7fa2e3.0<br/>@codecademy/styleguide@63.2.2-alpha.7fa2e3.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63da8dd859a8fb005cb4df9c--gamut-preview.netlify.app>https://63da8dd859a8fb005cb4df9c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63da8dd859a8fb005cb4df9c>Deploy Logs</a></p>

**Review by saghdaey — APPROVED** [review]

**Review by medhatnar — APPROVED** [review]
looks good!

**Pull request merged**
