### PR TITLE
feat(Icons): Add DiscordIcon and GaugeDashboardIcon

### PR DESCRIPTION
**Pull request by sooinc**
### Overview

- add regular DiscordIcon in the vender section
- add regular GaugeDashboardIcon 

### PR Checklist

- [x] Related to designs: https://www.figma.com/file/kUthvk7lekAv5tk2BDDtLZ/%F0%9F%8D%8E-Dashboard-updates?node-id=391%3A3489&mode=dev
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. check GaugeDashboardIcon in the regular section: https://661596f67c08950933ce6e9a--gamut-preview.netlify.app/?path=/docs/atoms-icons-regular--editable-icon
2. check DiscordIcon in the vendor section: https://661596f67c08950933ce6e9a--gamut-preview.netlify.app/?path=/docs/atoms-icons-regular--editable-icon

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/5737)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-5737)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.2-alpha.70657c.0<br/>@codecademy/gamut-icons@9.20.1-alpha.70657c.0<br/>@codecademy/gamut-kit@0.6.397-alpha.70657c.0<br/>@codecademy/styleguide@66.16.2-alpha.70657c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66146b93d1f3391eb33b5e93--gamut-preview.netlify.app>https://66146b93d1f3391eb33b5e93--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66146b93d1f3391eb33b5e93>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.2-alpha.e342e2.0<br/>@codecademy/gamut-icons@9.20.1-alpha.e342e2.0<br/>@codecademy/gamut-kit@0.6.397-alpha.e342e2.0<br/>@codecademy/styleguide@66.16.2-alpha.e342e2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://661596f67c08950933ce6e9a--gamut-preview.netlify.app>https://661596f67c08950933ce6e9a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/661596f67c08950933ce6e9a>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]

**Comment by LinKCoding** [comment]
@sooinc would you also need to explore the dashboard icon? I only see the discord icon exported

**Comment by sooinc** [comment]
> @sooinc would you also need to export the dashboard icon in stories? I only see the discord icon exported

i dont think so - happens automagically. you can see the `gaugeDashboardIcon` added in storybook without having to export it separately. for the discord icon, we have to specify in the const so that it shows up in the "vendor" section.
Screenshot 2024-04-10 at 5 34 52 PM

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.16.2-alpha.0f4378.0<br/>@codecademy/gamut-icons@9.20.1-alpha.0f4378.0<br/>@codecademy/gamut-kit@0.6.397-alpha.0f4378.0<br/>@codecademy/styleguide@66.16.2-alpha.0f4378.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66170ba6d990b65b2fb9382e--gamut-preview.netlify.app>https://66170ba6d990b65b2fb9382e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66170ba6d990b65b2fb9382e>Deploy Logs</a></p>

**Pull request merged**
