### PR TITLE
fix(DataGrid/DataTable): text align bug

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

fixes justify prop for row text

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.1d62ab.0<br/>@codecademy/gamut-labs@28.1.1-alpha.1d62ab.0<br/>@codecademy/gamut@40.4.2-alpha.1d62ab.0<br/>@codecademy/monaco@0.5.16-alpha.1d62ab.0<br/>@codecademy/styleguide@50.4.1-alpha.1d62ab.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a559a16607cb28cc77df0e--gamut-preview.netlify.app>https://61a559a16607cb28cc77df0e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a559a16607cb28cc77df0e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.02e625.0<br/>@codecademy/gamut-labs@28.1.1-alpha.02e625.0<br/>@codecademy/gamut@40.4.2-alpha.02e625.0<br/>@codecademy/monaco@0.5.16-alpha.02e625.0<br/>@codecademy/styleguide@50.4.1-alpha.02e625.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a55d12450f292030cc2cfa--gamut-preview.netlify.app>https://61a55d12450f292030cc2cfa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a55d12450f292030cc2cfa>Deploy Logs</a></p>

**Review by JoshuaKGoldberg — APPROVED** [review]
ty! 🙌

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.22-alpha.1d7af7.0<br/>@codecademy/gamut-labs@28.1.2-alpha.1d7af7.0<br/>@codecademy/gamut@40.5.1-alpha.1d7af7.0<br/>@codecademy/monaco@0.5.17-alpha.1d7af7.0<br/>@codecademy/styleguide@50.4.2-alpha.1d7af7.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6420b419e9429e661e594--gamut-preview.netlify.app>https://61a6420b419e9429e661e594--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6420b419e9429e661e594>Deploy Logs</a></p>

**Pull request merged**
