### PR TITLE
chore(Badge): update colors

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Updates Badges to new colors

### PR Checklist

- [x] Related to designs: [here](https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?type=design&node-id=29959-39721&mode=design&t=aiZ3RL3h0uLBGJ9Q-0)
- [x] Related to JIRA ticket: [web-2485]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Go to the Storybook preview + check out the new colors on secondary + tertiary variants 

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | https://github.com/codecademy-engineering/Codecademy/pull/36683 | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Mono       | https://github.com/codecademy-engineering/mono/pull/4058  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.6-alpha.6a87cb.0<br/>@codecademy/gamut-kit@0.6.361-alpha.6a87cb.0<br/>@codecademy/styleguide@66.6.1-alpha.6a87cb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6542b4fcb5e6962309dafd9c--gamut-preview.netlify.app>https://6542b4fcb5e6962309dafd9c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6542b4fcb5e6962309dafd9c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.6-alpha.2d1693.0<br/>@codecademy/gamut-kit@0.6.361-alpha.2d1693.0<br/>@codecademy/styleguide@66.6.1-alpha.2d1693.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6543cab6daa3b30c5e426d54--gamut-preview.netlify.app>https://6543cab6daa3b30c5e426d54--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6543cab6daa3b30c5e426d54>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.6-alpha.d22efb.0<br/>@codecademy/gamut-kit@0.6.361-alpha.d22efb.0<br/>@codecademy/styleguide@66.6.1-alpha.d22efb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6545025be3a06c46c305e7d6--gamut-preview.netlify.app>https://6545025be3a06c46c305e7d6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6545025be3a06c46c305e7d6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.9.1-alpha.5ba510.0<br/>@codecademy/gamut-kit@0.6.362-alpha.5ba510.0<br/>@codecademy/styleguide@66.7.1-alpha.5ba510.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65450815b697ca59d0c867e9--gamut-preview.netlify.app>https://65450815b697ca59d0c867e9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65450815b697ca59d0c867e9>Deploy Logs</a></p>

**Review by aresnik11 — APPROVED** [review]
✨

**Pull request merged**
