### PR TITLE
feat(Icons): add AssessmentsIcon

### PR DESCRIPTION
**Pull request by bndiep**
### Overview

Adds AssessmentsIcon

### PR Checklist

- [x] Related to designs: https://www.figma.com/design/qPfZPHAiZqUOb5aKau4PSG/Execution---SKS-Aspire-Journeys-on-.com?node-id=312-8900&node-type=instance&m=dev
- [ ] Related to JIRA ticket: [ABC-123]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/7732)  | [Portal Env](https://tengu.codecademy.com/learn/ext-paths/hello?PR_ENV=portal-app-pr-7732)   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.1-alpha.b398c8.0<br/>@codecademy/gamut-icons@9.30.2-alpha.b398c8.0<br/>@codecademy/gamut-kit@0.6.442-alpha.b398c8.0<br/>@codecademy/styleguide@68.0.3-alpha.b398c8.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66e9aee58b1f933547bc67b5--gamut-preview.netlify.app>https://66e9aee58b1f933547bc67b5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66e9aee58b1f933547bc67b5>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.2.1-alpha.bfa662.0<br/>@codecademy/gamut-icons@9.30.2-alpha.bfa662.0<br/>@codecademy/gamut-kit@0.6.442-alpha.bfa662.0<br/>@codecademy/styleguide@68.0.3-alpha.bfa662.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66e9e88ace9b6574f4157bbc--gamut-preview.netlify.app>https://66e9e88ace9b6574f4157bbc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66e9e88ace9b6574f4157bbc>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
lgtm

**Pull request merged**
