### PR TITLE
feat: Rename accordion to deprecated

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Renamed `Accordion`, `AccordionArea`, and `AccordionButton` to `AccordionDeprecated`, `AccordionAreaDeprecated`, and `AccordionButtonDeprecated` to support our NEW accordion that will be coming in a follow up PR.

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2437]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Visit https://64e77a589bd1711f953f88c8--gamut-preview.netlify.app/ and confirm accordion story is renamed as deprecated

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36383)  | [Monolith Env](https://pr-36383-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/3321)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-3321)   |

[WEB-1767]: https://codecademy.atlassian.net/browse/WEB-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2437]: https://codecademy.atlassian.net/browse/WEB-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dreamwasp — APPROVED** [review]
jake 🔪  gamut-labs since this PR so you can remove those changes but other than that everything looks ✨

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64ff5ce2ecfe833c965869b8--gamut-preview.netlify.app>https://64ff5ce2ecfe833c965869b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64ff5ce2ecfe833c965869b8>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.4.3-alpha.9b6a5d.0<br/>@codecademy/gamut-kit@0.6.345-alpha.9b6a5d.0<br/>@codecademy/styleguide@66.2.4-alpha.9b6a5d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://650c9936d59178206abca331--gamut-preview.netlify.app>https://650c9936d59178206abca331--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/650c9936d59178206abca331>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.4.3-alpha.50473e.0<br/>@codecademy/gamut-kit@0.6.345-alpha.50473e.0<br/>@codecademy/styleguide@66.2.4-alpha.50473e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://650c9c6e23a836330f02b465--gamut-preview.netlify.app>https://650c9c6e23a836330f02b465--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/650c9c6e23a836330f02b465>Deploy Logs</a></p>

**Pull request merged**
