### PR TITLE
feat(GlobalHeader): remove referrals from navbar

### PR DESCRIPTION
**Pull request by borisonr**
### Overview

remove the referrals link from navbar

our contract with saasquatch ended so we want to remove the navbar link to it. 
there's plenty of code cleanup in the monolith that will need to happen, but that will be the responsibility of the team that owns the new referrals implementation (possibly growth?)

integration pr to test: https://github.com/codecademy-engineering/Codecademy/pull/29134

(we didnt have a storybook that showed the referrals link beforehand)

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [DISC-466](https://codecademy.atlassian.net/browse/DISC-466)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.52-alpha.472dfa.0<br/>@codecademy/gamut-labs@29.2.3-alpha.472dfa.0<br/>@codecademy/styleguide@54.0.7-alpha.472dfa.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f84b7d6754ef00905af9f7--gamut-preview.netlify.app>https://61f84b7d6754ef00905af9f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f84b7d6754ef00905af9f7>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.52-alpha.0473fd.0<br/>@codecademy/gamut-labs@29.2.3-alpha.0473fd.0<br/>@codecademy/styleguide@54.0.7-alpha.0473fd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f84f7041a22f04e896e853--gamut-preview.netlify.app>https://61f84f7041a22f04e896e853--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f84f7041a22f04e896e853>Deploy Logs</a></p>

**Comment by borisonr** [comment]
tagging @sylvanasantos @ahmed-abdallah and @xendke for knowledge share and in case you get tasked with setting up the new referral program you can just revert these changes

**Comment by dougyd92** [comment]
I see in https://codecademy.atlassian.net/browse/DISC-466 that we will likely add a new referral partner soon so we will leave some of the code in place. Should we just change the logic for `showReferrals` in the monolith to always be false? Then, we wouldn't have to delete and later re-add the navbar UI.

**Comment by borisonr** [comment]
> I see in https://codecademy.atlassian.net/browse/DISC-466 that we will likely add a new referral partner soon so we will leave some of the code in place. Should we just change the logic for `showReferrals` in the monolith to always be false? Then, we wouldn't have to delete and later re-add the navbar UI.

that's a good callout. given that we haven't prioritized the new referrals work yet, i wonder if leaving this in could slow down future navigation work since that's more likely to happen beforehand. i think either solution could be fine, so if you have a strong preference for the monolith change, happy to do that. (also means i dont have to update gamut version which is nice)

**Comment by dougyd92** [comment]
No strong preference here. I'm fine with either approach.

**Comment by borisonr** [comment]
going to close this pr in favor of the monolith approach since this was never set up in portal app anyway 🙃

**Pull request closed without merging**
