### PR TITLE
feat(IconButton): aria-describedby override

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Add override to have IconButton tip optionally not be split into aria-label and described-by (non-breaking)

### PR Checklist

- [x] Related to designs:
- [x] Related to JIRA ticket: [[gm-788](https://skillsoftdev.atlassian.net/browse/GM-788)]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

* Go to ToolTip page and see new example.
* On VO new and old examples should correctly announce their tip text.

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/37945)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6846)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.24.0-alpha.1ac6a1.0<br/>@codecademy/gamut-kit@0.6.420-alpha.1ac6a1.0<br/>@codecademy/styleguide@66.28.0-alpha.1ac6a1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c216476cc4b573eb9919e--gamut-preview.netlify.app>https://667c216476cc4b573eb9919e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c216476cc4b573eb9919e>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.24.0-alpha.64bf51.0<br/>@codecademy/gamut-kit@0.6.420-alpha.64bf51.0<br/>@codecademy/styleguide@66.28.0-alpha.64bf51.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c250c05f2365bc5b7a50a--gamut-preview.netlify.app>https://667c250c05f2365bc5b7a50a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c250c05f2365bc5b7a50a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.24.0-alpha.5c3410.0<br/>@codecademy/gamut-kit@0.6.420-alpha.5c3410.0<br/>@codecademy/styleguide@66.28.0-alpha.5c3410.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c2ddd312e1d2c27bf1b47--gamut-preview.netlify.app>https://667c2ddd312e1d2c27bf1b47--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c2ddd312e1d2c27bf1b47>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.24.0-alpha.d3f275.0<br/>@codecademy/gamut-kit@0.6.420-alpha.d3f275.0<br/>@codecademy/styleguide@66.28.0-alpha.d3f275.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c577cf55779934f58ced6--gamut-preview.netlify.app>https://667c577cf55779934f58ced6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c577cf55779934f58ced6>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.24.0-alpha.7080b9.0<br/>@codecademy/gamut-kit@0.6.420-alpha.7080b9.0<br/>@codecademy/styleguide@66.28.0-alpha.7080b9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c608ebdee9e309b3477d3--gamut-preview.netlify.app>https://667c608ebdee9e309b3477d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c608ebdee9e309b3477d3>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.24.0-alpha.750f2d.0<br/>@codecademy/gamut-kit@0.6.420-alpha.750f2d.0<br/>@codecademy/styleguide@66.28.0-alpha.750f2d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c644963c90ea3f2b34644--gamut-preview.netlify.app>https://667c644963c90ea3f2b34644--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c644963c90ea3f2b34644>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.25.0-alpha.e87098.0<br/>@codecademy/gamut-kit@0.6.421-alpha.e87098.0<br/>@codecademy/styleguide@66.29.0-alpha.e87098.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667c683b655c302ac2976e9f--gamut-preview.netlify.app>https://667c683b655c302ac2976e9f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667c683b655c302ac2976e9f>Deploy Logs</a></p>

**Review by LinKCoding — APPROVED** [review]
works well!

**Pull request merged**
