### PR TITLE
feat(SelectDropdown): Add search icon to SelectDropdown based on isSearchable

### PR DESCRIPTION
**Pull request by jenesh**
### Overview

This PR update `SelectDropdown` component to look like a search component when the prop `isSearchable` is passed by updating the **icon** to a search icon.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [EN-2089]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33191)  | [Monolith Env](https://bantam.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2612)  | [Portal Env](https://tayra.codecademy.com/)   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### Screenshot of the update

Screen Shot 2022-10-24 at 3 53 48 PM

Screen Shot 2022-10-24 at 3 54 20 PM

PR for alpha change on monolith: https://github.com/codecademy-engineering/Codecademy/pull/33191

[EN-2089]: https://codecademy.atlassian.net/browse/EN-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.218-alpha.613778.0<br/>@codecademy/gamut-labs@33.6.9-alpha.613778.0<br/>@codecademy/gamut@51.0.1-alpha.613778.0<br/>@codecademy/monaco@0.6.96-alpha.613778.0<br/>@codecademy/styleguide@62.0.3-alpha.613778.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6356d6c27886da069d8f6ac7--gamut-preview.netlify.app>https://6356d6c27886da069d8f6ac7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6356d6c27886da069d8f6ac7>Deploy Logs</a></p>

**Comment by dreamwasp** [comment]
@jenesh can you add the alpha packages to the monolith + monorepo so i can test this change there? thank you!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.219-alpha.658ef9.0<br/>@codecademy/gamut-labs@33.6.10-alpha.658ef9.0<br/>@codecademy/gamut@51.0.2-alpha.658ef9.0<br/>@codecademy/monaco@0.6.97-alpha.658ef9.0<br/>@codecademy/styleguide@62.0.4-alpha.658ef9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63594525fff808092de757c5--gamut-preview.netlify.app>https://63594525fff808092de757c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63594525fff808092de757c5>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
lgtm

**Pull request merged**
