### PR TITLE
update production deploy

### PR DESCRIPTION
**Pull request by dreamwasp**
### Overview

Updates the prod release command + updates a couple of failing compile runs from mono/monolith

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [gm-916]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

I really don't know how to test this, I'm gonna ask @jakemhiller lol. i do have test packages up here - 

* https://github.com/codecademy-engineering/mono/pull/8629
* https://github.com/codecademy-engineering/Codecademy/pull/38880

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://674df14d57d00f2429780706--gamut-preview.netlify.app>https://674df14d57d00f2429780706--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/674df14d57d00f2429780706>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://674e0376ba00cf2be231f13a--gamut-preview.netlify.app>https://674e0376ba00cf2be231f13a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/674e0376ba00cf2be231f13a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://674e082970e42a209f832505--gamut-preview.netlify.app>https://674e082970e42a209f832505--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/674e082970e42a209f832505>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]
lgtm!

**Pull request merged**
