### PR TITLE
feat(DropdownButton): Auto position for dropdown button popover

### PR DESCRIPTION
**Pull request by jrood**
### Overview

Use 'above' position for popover with dropdown button when close to viewport bottom

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [REACH-2522]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

- View the button dropdown on the preview env [here](https://643054042836db7811b7b4eb--gamut-preview.netlify.app/?path=/docs/brand-labs-molecules-dropdownbutton--dropdown-button).
- Make your browser window short enough that the `click me` button is near the bottom of the window.
- Click it and verify that the popover renders above the button rather than below.
- Scroll while the popover is open to verify that it only renders above when there is not enough room for it to render below.

#### PR Links and Envs

| Repository   | PR Link                                                  |
| :----------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35449)  |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1714)  |

[REACH-2522]: https://codecademy.atlassian.net/browse/REACH-2522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.296-alpha.8be9f6.0<br/>@codecademy/gamut-labs@35.8.3-alpha.8be9f6.0<br/>@codecademy/styleguide@64.0.1-alpha.8be9f6.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6419bc558e71410fcda24f10--gamut-preview.netlify.app>https://6419bc558e71410fcda24f10--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6419bc558e71410fcda24f10>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.296-alpha.81c98a.0<br/>@codecademy/gamut-labs@35.8.3-alpha.81c98a.0<br/>@codecademy/gamut@53.0.1-alpha.81c98a.0<br/>@codecademy/monaco@0.7.15-alpha.81c98a.0<br/>@codecademy/styleguide@64.0.1-alpha.81c98a.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.304-alpha.8a448d.0<br/>@codecademy/gamut-labs@35.11.2-alpha.8a448d.0<br/>@codecademy/gamut@53.0.3-alpha.8a448d.0<br/>@codecademy/monaco@0.7.17-alpha.8a448d.0<br/>@codecademy/styleguide@64.2.1-alpha.8a448d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://643054042836db7811b7b4eb--gamut-preview.netlify.app>https://643054042836db7811b7b4eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/643054042836db7811b7b4eb>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.310-alpha.e0b88c.0<br/>@codecademy/gamut-labs@35.13.1-alpha.e0b88c.0<br/>@codecademy/gamut@53.1.3-alpha.e0b88c.0<br/>@codecademy/monaco@0.7.21-alpha.e0b88c.0<br/>@codecademy/styleguide@64.3.3-alpha.e0b88c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://644300be3a9b3802f5442e89--gamut-preview.netlify.app>https://644300be3a9b3802f5442e89--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/644300be3a9b3802f5442e89>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.310-alpha.2809e2.0<br/>@codecademy/gamut-labs@35.13.1-alpha.2809e2.0<br/>@codecademy/gamut@53.1.3-alpha.2809e2.0<br/>@codecademy/monaco@0.7.21-alpha.2809e2.0<br/>@codecademy/styleguide@64.3.3-alpha.2809e2.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6446a032e82a08520862439d--gamut-preview.netlify.app>https://6446a032e82a08520862439d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6446a032e82a08520862439d>Deploy Logs</a></p>

**Review by dreamwasp — CHANGES_REQUESTED** [review]
you are going to need to split this into two PRs - i am shipping the brand library later today and can help you migrate your edits here over to there once its ready to go!

**Comment by jrood** [comment]
Thanks @dreamwasp ! I created a first Gamut PR [here](https://github.com/codecademy-engineering/Codecademy/pull/35514).

**Comment by jrood** [comment]
Closing since this was addressed [here](https://github.com/Codecademy/gamut/pull/2721) and [here](https://github.com/codecademy-engineering/mono/pull/2269)

**Pull request closed without merging**
