### PR TITLE
chore: add functioning vscode-jest launch config

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Prior to this, the latest versions of vscode-jest weren't picking up our tests. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6182f00743090a15ebe1b781--gamut-preview.netlify.app>https://6182f00743090a15ebe1b781--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6182f00743090a15ebe1b781>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a5252843ed6b5b70d75c6d--gamut-preview.netlify.app>https://61a5252843ed6b5b70d75c6d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a5252843ed6b5b70d75c6d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6482774797835c7e50a19--gamut-preview.netlify.app>https://61a6482774797835c7e50a19--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6482774797835c7e50a19>Deploy Logs</a></p>

**Review by dreamwasp — APPROVED** [review]
🙏

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b22a48ea12328824408628--gamut-preview.netlify.app>https://61b22a48ea12328824408628--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b22a48ea12328824408628>Deploy Logs</a></p>

**Pull request merged**
