### PR TITLE
chore: fix build:watch tasks

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Update build:watch tasks to work with NX

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.191-alpha.f4210c.0<br/>@codecademy/gamut-labs@33.1.12-alpha.f4210c.0<br/>@codecademy/gamut@50.5.4-alpha.f4210c.0<br/>@codecademy/monaco@0.6.81-alpha.f4210c.0<br/>@codecademy/styleguide@61.3.5-alpha.f4210c.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6307d272cfcded0432c49674--gamut-preview.netlify.app>https://6307d272cfcded0432c49674--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6307d272cfcded0432c49674>Deploy Logs</a></p>

**Review by zippyzow — APPROVED** [review]
Working for me

Screen Shot 2022-08-25 at 3 56 39 PM

**Comment by njradford** [comment]
Thank you for updating this 👍

**Pull request merged**
