### PR TITLE
chore: update tracking package

### PR DESCRIPTION
**Pull request by amabarr**
### Overview

Below I've put the PRs of the place where PR I am using this tracking update in. If that's not okay, I can open up separate PRs applying these package updates!

Updated tracking library to v 1.0.4

### PR Checklist

- [x] Related to designs: [figma](https://www.figma.com/file/tVAwfwrr5jS83lqk3GRfEA/Trial-extension?node-id=178%3A7535&viewport=919%2C67%2C0.09)
- [x] Related to JIRA ticket: [GRW-321](https://codecademy.atlassian.net/browse/GRW-321)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Go to any of the envs below and click around (you should still see tracking events happening in the network tab) or see that lint packages is passing!

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33444 '[GRW-321] Trial Feedback Page')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/678 'Tracking library update in the mono repo')   |
| Author | [Author Link](https://github.com/codecademy-engineering/author/pull/2436) |

[GRW-321]: https://codecademy.atlassian.net/browse/GRW-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.237-alpha.816fdd.0<br/>@codecademy/gamut-labs@33.8.6-alpha.816fdd.0<br/>@codecademy/styleguide@62.5.6-alpha.816fdd.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63852b90319a3971a82f2ff4--gamut-preview.netlify.app>https://63852b90319a3971a82f2ff4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63852b90319a3971a82f2ff4>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.237-alpha.0820cb.0<br/>@codecademy/gamut-labs@33.8.6-alpha.0820cb.0<br/>@codecademy/styleguide@62.5.6-alpha.0820cb.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63864ec53645c4145980fe64--gamut-preview.netlify.app>https://63864ec53645c4145980fe64--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63864ec53645c4145980fe64>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.239-alpha.5f7da9.0<br/>@codecademy/gamut-labs@33.8.8-alpha.5f7da9.0<br/>@codecademy/styleguide@62.5.8-alpha.5f7da9.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6386523e5e4051162d2f2cea--gamut-preview.netlify.app>https://6386523e5e4051162d2f2cea--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6386523e5e4051162d2f2cea>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.241-alpha.64a14a.0<br/>@codecademy/gamut-labs@33.8.10-alpha.64a14a.0<br/>@codecademy/styleguide@62.5.10-alpha.64a14a.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6387896573fe3129b47556e2--gamut-preview.netlify.app>https://6387896573fe3129b47556e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6387896573fe3129b47556e2>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://638a1c926b71d032c1660f04--gamut-preview.netlify.app>https://638a1c926b71d032c1660f04--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/638a1c926b71d032c1660f04>Deploy Logs</a></p>

**Review by BandanaKM — COMMENTED** [review]
@amabarr this looks great! it seems as of yesterday we are on version 1.0.4 so we can go ahead and make that change too.

**Review by BandanaKM — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://638a277730b519380e3da6c1--gamut-preview.netlify.app>https://638a277730b519380e3da6c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/638a277730b519380e3da6c1>Deploy Logs</a></p>

**Review by jakemhiller — APPROVED** [review]

**Pull request merged**
