### PR TITLE
fix: fix index prop forwarding for Tabs component

### PR DESCRIPTION
**Pull request by jakemhiller**
### Overview

Fixes an issue where the `index` prop, which controls whether a `Tabs` component is controlled or uncontrolled, was not being forwarded correctly.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.8fc136.0<br/>@codecademy/gamut-labs@28.4.3-alpha.8fc136.0<br/>@codecademy/gamut@42.1.2-alpha.8fc136.0<br/>@codecademy/monaco@0.5.25-alpha.8fc136.0<br/>@codecademy/styleguide@52.2.3-alpha.8fc136.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b905756d63d230c0d25000--gamut-preview.netlify.app>https://61b905756d63d230c0d25000--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b905756d63d230c0d25000>Deploy Logs</a></p>

**Review by antoniablair — APPROVED** [review]
Looks good to me! Thanks for the quick update

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.f92a28.0<br/>@codecademy/gamut-labs@28.4.3-alpha.f92a28.0<br/>@codecademy/gamut@42.1.2-alpha.f92a28.0<br/>@codecademy/monaco@0.5.25-alpha.f92a28.0<br/>@codecademy/styleguide@52.2.3-alpha.f92a28.0<br/></pre>

**Review by dreamwasp — APPROVED** [review]

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61ba2e6dbe86b952b0b7e629--gamut-preview.netlify.app>https://61ba2e6dbe86b952b0b7e629--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61ba2e6dbe86b952b0b7e629>Deploy Logs</a></p>

**Pull request merged**
