### PR TITLE
chore(AppHeader)!: Remove bookmarks and favorites

### PR DESCRIPTION
**Pull request by aresnik11**
### Overview

Removes bookmarks and favorites code from the AppHeader.

_**This PR should not be merged until the day communicated to users that these features are being sunsetted.**_

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [WEB-2171]
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

Confirm all tests and checks pass here. See further testing instructions in https://github.com/codecademy-engineering/Codecademy/pull/33335 and https://github.com/codecademy-engineering/mono/pull/525

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33335)  | [Monolith Env](https://pr-33335-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/525)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-525)   |

[WEB-2171]: https://codecademy.atlassian.net/browse/WEB-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.220-alpha.ce9210.0<br/>@codecademy/gamut-labs@33.6.11-alpha.ce9210.0<br/>@codecademy/styleguide@62.0.5-alpha.ce9210.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.220-alpha.9e7c85.0<br/>@codecademy/gamut-labs@33.6.11-alpha.9e7c85.0<br/>@codecademy/styleguide@62.0.5-alpha.9e7c85.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6363f04b49ab2100ab4a9dff--gamut-preview.netlify.app>https://6363f04b49ab2100ab4a9dff--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6363f04b49ab2100ab4a9dff>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.f089d0.0<br/>@codecademy/gamut-labs@33.6.17-alpha.f089d0.0<br/>@codecademy/styleguide@62.2.2-alpha.f089d0.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6363fdd3703920149145d882--gamut-preview.netlify.app>https://6363fdd3703920149145d882--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6363fdd3703920149145d882>Deploy Logs</a></p>

**Review by awgraves — APPROVED** [review]

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.252-alpha.b6f71d.0<br/>@codecademy/gamut-labs@33.11.2-alpha.b6f71d.0<br/>@codecademy/styleguide@62.6.9-alpha.b6f71d.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63927d878227ab26cd04dff1--gamut-preview.netlify.app>https://63927d878227ab26cd04dff1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63927d878227ab26cd04dff1>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.253-alpha.dac754.0<br/>@codecademy/gamut-labs@33.11.3-alpha.dac754.0<br/>@codecademy/styleguide@62.6.10-alpha.dac754.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6397b82b2fbcf000510ebed6--gamut-preview.netlify.app>https://6397b82b2fbcf000510ebed6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6397b82b2fbcf000510ebed6>Deploy Logs</a></p>

**Pull request merged**
