### PR TITLE
fix: Refactor Shimmer styles for SWC compatibility

### PR DESCRIPTION
**Pull request by jrood**
### Overview

Refactor Shimmer styles so that `%` is not used in strings nested within other emotion style declarations, which was causing an `illegal escape sequence` error to be thrown when SWC is enabled in portal-app.

This error appears in portal-app on the catalog when SWC is enabled by removing `babel.config.js`
Screenshot 2023-08-02 at 9 38 00 AM
It is confirmed that the error goes away when consuming the gamut alpha package from this PR. (although it does not resolve all errors related to SWC)

### PR Checklist
- [ ] ~Related to designs:~
- [ ] ~Related to JIRA ticket: [ABC-123]~
- [x] I have run this code to verify it works
- [ ] ~This PR includes unit tests for the code change~
- [x] This PR includes testing instructions tests for the code change
- [x] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

1. Run Storybook
1. Search for the shimmer
1. Verify that the shimmer animation still works properly

#### PR Links and Envs

| Repository   | PR Link                                                  |
| :----------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36217)  |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/2961)  |

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.310-alpha.7c88d5.0<br/>@codecademy/gamut-labs@35.13.1-alpha.7c88d5.0<br/>@codecademy/gamut@53.1.3-alpha.7c88d5.0<br/>@codecademy/monaco@0.7.21-alpha.7c88d5.0<br/>@codecademy/styleguide@64.3.3-alpha.7c88d5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://644306d22b6727069a1e9257--gamut-preview.netlify.app>https://644306d22b6727069a1e9257--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/644306d22b6727069a1e9257>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://644692ba0af6ff413c8e55ee--gamut-preview.netlify.app>https://644692ba0af6ff413c8e55ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/644692ba0af6ff413c8e55ee>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.311-alpha.d554bb.0<br/>@codecademy/gamut-labs@35.13.2-alpha.d554bb.0<br/>@codecademy/gamut@53.1.3-alpha.d554bb.0<br/>@codecademy/monaco@0.7.21-alpha.d554bb.0<br/>@codecademy/styleguide@64.3.4-alpha.d554bb.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.314-alpha.b6bb35.0<br/>@codecademy/gamut-labs@35.14.3-alpha.b6bb35.0<br/>@codecademy/gamut@53.2.1-alpha.b6bb35.0<br/>@codecademy/monaco@0.7.22-alpha.b6bb35.0<br/>@codecademy/styleguide@64.3.7-alpha.b6bb35.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://645933050f98f3090aa9daae--gamut-preview.netlify.app>https://645933050f98f3090aa9daae--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/645933050f98f3090aa9daae>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.317-alpha.f0810f.0<br/>@codecademy/gamut-labs@35.14.6-alpha.f0810f.0<br/>@codecademy/gamut@55.0.1-alpha.f0810f.0<br/>@codecademy/monaco@0.7.25-alpha.f0810f.0<br/>@codecademy/styleguide@66.0.1-alpha.f0810f.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6464f3ffe8ab0f051005b479--gamut-preview.netlify.app>https://6464f3ffe8ab0f051005b479--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6464f3ffe8ab0f051005b479>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64c7c8d426b60209a308eb1a--gamut-preview.netlify.app>https://64c7c8d426b60209a308eb1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64c7c8d426b60209a308eb1a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.337-alpha.010c22.0<br/>@codecademy/gamut-labs@35.15.10-alpha.010c22.0<br/>@codecademy/gamut@55.1.15-alpha.010c22.0<br/>@codecademy/styleguide@66.1.20-alpha.010c22.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.338-alpha.76a63e.0<br/>@codecademy/gamut-labs@35.15.11-alpha.76a63e.0<br/>@codecademy/gamut@55.2.1-alpha.76a63e.0<br/>@codecademy/styleguide@66.1.21-alpha.76a63e.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64ca6b9a1eb15d305af09dac--gamut-preview.netlify.app>https://64ca6b9a1eb15d305af09dac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64ca6b9a1eb15d305af09dac>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.338-alpha.7dfbe3.0<br/>@codecademy/gamut-labs@35.15.11-alpha.7dfbe3.0<br/>@codecademy/gamut@55.2.1-alpha.7dfbe3.0<br/>@codecademy/styleguide@66.1.21-alpha.7dfbe3.0<br/></pre>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.339-alpha.888931.0<br/>@codecademy/gamut-labs@35.15.12-alpha.888931.0<br/>@codecademy/gamut@55.2.2-alpha.888931.0<br/>@codecademy/styleguide@66.1.22-alpha.888931.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64caa875c2a1f3147e248a2a--gamut-preview.netlify.app>https://64caa875c2a1f3147e248a2a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64caa875c2a1f3147e248a2a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.339-alpha.85ff42.0<br/>@codecademy/gamut-labs@35.15.12-alpha.85ff42.0<br/>@codecademy/gamut@55.2.2-alpha.85ff42.0<br/>@codecademy/styleguide@66.1.23-alpha.85ff42.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64cbbed7c871070dd3cee09d--gamut-preview.netlify.app>https://64cbbed7c871070dd3cee09d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64cbbed7c871070dd3cee09d>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.339-alpha.ecca31.0<br/>@codecademy/gamut-labs@35.15.12-alpha.ecca31.0<br/>@codecademy/gamut@55.2.2-alpha.ecca31.0<br/>@codecademy/styleguide@66.1.23-alpha.ecca31.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64cbf13181312d0db782a23a--gamut-preview.netlify.app>https://64cbf13181312d0db782a23a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64cbf13181312d0db782a23a>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.339-alpha.8a0caa.0<br/>@codecademy/gamut-labs@35.15.12-alpha.8a0caa.0<br/>@codecademy/gamut@55.2.2-alpha.8a0caa.0<br/>@codecademy/styleguide@66.1.23-alpha.8a0caa.0<br/></pre>

**Review by jakemhiller — APPROVED** [review]
looks good to me!

**Pull request merged**
