### PR TITLE
feat(ScoreSummary): create ScoreSummary gamut-labs component

### PR DESCRIPTION
**Pull request by natalieweesh**
### Overview

create ScoreSummary component in gamut-labs for use on cumulative assessment summary page and path syllabi

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [EGG-2787]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions
check out the storybook page: http://localhost:6006/?path=/docs/brand-labs-organisms-scoresummary--score-summary

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33310)  | [Monolith Env](https://pr-33310-monolith.dev-eks.codecademy.com/) |

[EGG-2787]: https://codecademy.atlassian.net/browse/EGG-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.222-alpha.ed84ee.0<br/>@codecademy/gamut-labs@33.7.0-alpha.ed84ee.0<br/>@codecademy/styleguide@62.0.7-alpha.ed84ee.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63603cb01fb777341f4a17a0--gamut-preview.netlify.app>https://63603cb01fb777341f4a17a0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63603cb01fb777341f4a17a0>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.222-alpha.867ae5.0<br/>@codecademy/gamut-labs@33.7.0-alpha.867ae5.0<br/>@codecademy/styleguide@62.0.7-alpha.867ae5.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://636042ff6c01dd40d6cea72c--gamut-preview.netlify.app>https://636042ff6c01dd40d6cea72c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/636042ff6c01dd40d6cea72c>Deploy Logs</a></p>

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.222-alpha.2d56e1.0<br/>@codecademy/gamut-labs@33.7.0-alpha.2d56e1.0<br/>@codecademy/styleguide@62.0.7-alpha.2d56e1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63604f6ac7126403c512b731--gamut-preview.netlify.app>https://63604f6ac7126403c512b731--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63604f6ac7126403c512b731>Deploy Logs</a></p>

**Review by sylvanasantos — APPROVED** [review]
Looks great!

**Comment by codecademydev** [comment]
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.226-alpha.a560f1.0<br/>@codecademy/gamut-labs@33.7.0-alpha.a560f1.0<br/>@codecademy/styleguide@62.2.2-alpha.a560f1.0<br/></pre>

**Comment by codecademydev** [comment]
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6362cb0ccb253d008b4ef20b--gamut-preview.netlify.app>https://6362cb0ccb253d008b4ef20b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6362cb0ccb253d008b4ef20b>Deploy Logs</a></p>

**Review by katiezutter — APPROVED** [review]
LGTM!! 🎉

**Comment by reedlaverack** [comment]
Since this is a -labs component I'm happy with the reviews already done and I'm going to approve it

**Review by reedlaverack — APPROVED** [review]

**Pull request merged**
